### ISSUE TITLE
colon character in password

### ISSUE THREAD

**Issue by krissfr** [signal18/replication-manager#100]
Hi,

i have an issue with replication-manager RC2 when a password for the root user or replic user has a colon character in the config.toml.

ex: 
user = "root:1234#!:$abcd"

replication manager doesn't understand the password and doesn't connect to the mysql server.

**Comment by tanji** [comment]
Hi @krissfr , does that password work in command line?

**Comment by krissfr** [comment]
@tanji the connection to a mariadb server using the mariadb client with a password that contain a colon work fine.
i guess the problem is here because the colon is also the separator character between the user and the password in the config.toml.

**Comment by krissfr** [comment]
When you say "in command line", it's like that ?
replication-manager monitor --hosts=db1:3306,db2:3306,db2:3306
--user=root:pass --rpluser=repl:pass --daemon --http-server

i didn't try that

2016-11-04 13:15 GMT+01:00 Guillaume Lefranc notifications@github.com:

**Comment by tanji** [comment]
You are right the issue is because of the separator, I will fix the utility function so any subsequent parts containing colons are also included in the password.

**Comment by krissfr** [comment]
thank you :)

2016-11-04 15:57 GMT+01:00 Guillaume Lefranc notifications@github.com:
