### ISSUE TITLE
haproxy and MRM problem ?

### ISSUE THREAD

**Issue by sysdljr** [signal18/replication-manager#102]
Hi, @tanji 
     There a little problem to ask for you help in haproxy and MRM , thank.
     when we not add --haproxy parameter , MRM 0.7 could normal run.  
replication-manager monitor --gtidcheck   --user=root:xxxxxx --rpluser=rep_user:xxxxxx --hosts=172.28.14.118:3306,172.28.14.114:3306 --interactive=false 
    after add --haproxy parameter,  could not run.  
    there some error info:  

2016-11-17 16:03:12 INFO : Monitor started in automatic mode2016/11/17 16:03:14 Haproxy loading haproxy config at /usr/share/replication-manager/dashboard                                  
2016/11/17 16:03:14 Haproxy did not find an haproxy config...initializing new config                                                                                                         
2016/11/17 16:03:14 Could not render initial haproxy config, exiting...

--   haproxy config file   in /etc/haproxy/haproxy.cfg:
listen db_writes 172.28.14.91:3306
        mode tcp
        option tcp-check
        tcp-check expect string MySQL\ master
        default-server port 6033 inter 2s fall 3 rise 3 on-marked-down shutdown-sessions
        server test-118 172.28.14.118:3306 check 
        server test-114 172.28.14.114:3306 check backup 

listen db_reads 172.28.14.92:3306
        mode tcp
        balance leastconn
        option tcp-check
        tcp-check expect string is\ running.        
        default-server port 6033 inter 2s fall 3 rise 3 on-marked-down shutdown-sessions
        server test-118 172.28.14.118:3306  check
        server test-114 172.28.14.114:3306  check

besides,  our haproxy use same port  and different ip ,  how set haproxy-read-port and haproxy-write-port ?

**Comment by svaroqui** [comment]
Hi sysdljr, 

Thanks for using haproxy wrapper feature, 
I'm the dev that implement it  in replication manager, here is the setting i'm using

haproxy = true
haproxy-binary-path = "/usr/local/skysql/haproxy/sbin/haproxy"

# Read write traffic

haproxy-write-port=3306

# Read only load balance least connection traffic

haproxy-read-port=3307

I used it mainly in daemon mode , let me know if you found issues , if changing the bind interface (ip ) is needed i can implement a variable for this , just let me know ? 

Tx
/svar

**Comment by sysdljr** [comment]
@svaroqui ,thank you.
We have hundreds of old app, previous is directly connect to database (no use haporxy).
 example:  
group1:   192.168.10.110:3306  master     192.168.10.111:3306 slave
group2:   192.168.11.120:3306  master     192.168.11.121:3306 slave
......
app1,app2,ap3  write to  192.168.10.110:3306 and read to 192.168.10.111:3306
app4,app5,ap6  write to  192.168.11.120:3306 and read to 192.168.11.121:3306

Earlier this year,we use haproxy  replace to directly connection database.
 In order to  not modify application configuration, we adjust database's ip  to haproxy's  vip and assign new ip to database server.

group1 haproxy config example:
listen db_writes 192.168.10.110:3306
..... 
server  10.0.1.110:3306 check                  ##  original database ip:  192.168.10.110  
server  10.0.1.111:3306 check backup     ##  original database ip:  192.168.10.111 

listen db_reads 192.168.10.111:3306
.....
server 10.0.1.110:3306 check
server 10.0.1.111:3306 check

Whether can add or adjust parameter to below, for reference only.
haproxy-write=192.168.10.110:3306
haproxy-read=192.168.10.111:3306

**Comment by svaroqui** [comment]
re,

Ok i understand i'll fixe this by introducing 2 new parameters 
haproxy-ip-write-bind default 0.0.0.0
haproxy-ip-read-bind default 0.0.0.0

This would enable your setting let me know if i'm on the good track here

**Comment by svaroqui** [comment]
Re,
I've push the change in  https://github.com/tanji/replication-manager/commit/119f633568f384f2be67fd58a4d622da9ca8da61
Can you build from source or do you need a special binary package to test ?

**Comment by sysdljr** [comment]
Thank you for your kind support and help.
Please send to me a binary package,  thanks again.

**Comment by tanji** [comment]
[replication-manager-0.7.0-2176dae.tar.gz](https://github.com/tanji/replication-manager/files/599688/replication-manager-0.7.0-2176dae.tar.gz)

**Comment by sysdljr** [comment]
@tanji,  @svaroqui,  thank you. 
   We use replication-manager-0.7.0-2176dae to test:
replication-manager monitor --gtidcheck  --logfile=/home/tools/rpm01.log --user=root:123456 --rpluser=rep_user:123456 --hosts=172.28.14.118:3306,172.28.14.114:3306 --haproxy-ip-write-bind=172.28.14.91 --haproxy-write-port=13304 --haproxy-ip-read-bind=172.28.14.92 --haproxy-read-port=13304 --interactive=false

Why many columns are not data in result set?   Is it not correct we run command? 

  Host   Port          Status   Failures   Using GTID         Current GTID           Slave GTID             Replicat
  172.28.14.118   3306                          0  
  172.28.14.114   3306                          0                                                                            

 2016-11-19 12:33:48 ERROR: ERR00012 Could not autodetect a master  
 2016-11-19 12:33:48 ERROR: ERR00010 No slaves were detected  
 2016-11-19 12:33:46 DEBUG: New server created: 172.28.14.114:3306  
 2016-11-19 12:33:46 DEBUG: New server created: 172.28.14.118:3306  
 2016-11-19 12:33:46 INFO : Monitor started in automatic mode

occasionally, run command above have not result  and show some error,  
at that time , linux shell can not use , only after exit and re login.

 Host   Port          Status   Failures   Using GTID         Current GTID           Slave GTID             Replicat

 2016-11-19 12:31:27 INFO : Monitor started in automatic mode  
 2016-11-19 12:31:27 INFO : Starting http monitor on port 10001                                                                                                                    

```
    /home/tanj/Dev/go/src/github.com/tanji/replication-manager/display.go:123 +0x1d0
```

main.glob..func12(0xba8860, 0xc4202b46e0, 0x0, 0xa)
        /home/tanj/Dev/go/src/github.com/tanji/replication-manager/repmgr.go:260 +0x147a
github.com/tanji/replication-manager/vendor/github.com/spf13/cobra.(_Command).execute(0xba8860, 0xc4202b45a0, 0xa, 0xa, 0xba8860, 0xc4202b45a0)
        /home/tanj/Dev/go/src/github.com/tanji/replication-manager/vendor/github.com/spf13/cobra/command.go:636 +0x443
github.com/tanji/replication-manager/vendor/github.com/spf13/cobra.(_Command).ExecuteC(0xba7760, 0x0, 0xbb01a8, 0x93aa7c)
        /home/tanj/Dev/go/src/github.com/tanji/replication-manager/vendor/github.com/spf13/cobra/command.go:722 +0x367
github.com/tanji/replication-manager/vendor/github.com/spf13/cobra.(*Command).Execute(0xba7760, 0x0, 0x0)
        /home/tanj/Dev/go/src/github.com/tanji/replication-manager/vendor/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
        /home/tanj/Dev/go/src/github.com/tanji/replication-manager/main.go:87 +0x31
