### ISSUE TITLE
Reset failcount if no failures during x minutes

### ISSUE THREAD

**Issue by krissfr** [signal18/replication-manager#105]
Hello,

This is a new feature that I would like to find in a future release.

The situation :
I have 3 configuration servers, 2 mariadb and 1 MRM.
My failcount value is 5.

If a have a short network failure between MRM and the master, the failcount will begin to increment.
Suppose that when the network fails, the failcount stops at 4/5.

At the next short network failure (which can happen x hours or days later), the failcount will start to increment from 4/5, so it will fail with only 1 failure instead of 5.

If we can have a new parameter (like failcountresettime), where we can set a value in seconds, which reset the failcount counter if no fault is detected during the failcountresettime, we can solve this problem.

What do you think about that?

Regards,

Krissfr

**Comment by svaroqui** [comment]
That looks like a must have :)

**Comment by krissfr** [comment]
cool ! :)

**Comment by svaroqui** [comment]
failcount-reset-time should be based on monitoring time not on system time because can cause strange failover disable during winter time  change

**Comment by svaroqui** [comment]
Please test last commit via 
replication-manager  --config=/etc/replication-manager/mrm.cnf monitor --daemon --monitoring-ticker=8 --failcount-reset-time=40

And restart the master

**Comment by svaroqui** [comment]
default is 2 and 300

**Comment by krissfr** [comment]
Hi Stéphane,
you commit faster than Lucky Luke ! ;-)

I'm very busy this week , but i will do my best to find some time to try it. I understand the parameter failcount-reset-time, but can you please explain what is the monitoring-ticker and the impact of changing his value ?

thank you for this new feature ! :)

**Comment by svaroqui** [comment]
Hi krissfr,

monitoring-ticker is the timeout between consecutive monitoring , should not be change in most case but increasing for testing enable to stop the failure counter under 5 when restarting a node , note that we can't  increase the number of failure before failover in config , i may expose this as well   

Any parameter name  is welcome !

**Comment by krissfr** [comment]
Thank you stéphane

**Comment by krissfr** [comment]
Hi Stéphane,
i'v did some tests with the last release  build by Tanji and i seem work as expected.

But i don't understand why the failcount column display higher value than the message in logs.

exemple : 
 => in the log : "WARN : Master Failure detected! Retry 3/5"
 => in the Fail Count column : 3/27

Another issue (not related with this one), the post failover script is not executed, i have this error : 
INFO : Calling post-failover script
ERROR: fork/exec /etc/replication-manager/create_CNAME.sh: exec format error
INFO : Post-failover script complete

the script itself run fine i don't understand why i did'nt execute with MRM.

**Comment by krissfr** [comment]
Hi Stéphane,

don't worry about the post failover script. it was my bad, a blank line in the first line of my script ;-)

**Comment by svaroqui** [comment]
HI Kissfr,

failcount column is the  number failure / the heartbeat when  failure was detected, because we know about time between  2 heartbeat we can compute when it's time to reset  number of failure . it's not based on system time that could have been dangerous in cas of system time change

**Comment by krissfr** [comment]
Hi Stéphane,

Thank you for your explanation.

As we don't configure an heartbeat number but a (reset) time in second, what do you think about to display the computed time instead of the heartbeat number ?

The best would be a count down from the failcount-reset-time value to zero when no failure append. This would be more understandable for non-initiated user.
