### ISSUE TITLE
Replication-manager is froze when any host in configuration is down

### ISSUE THREAD

**Issue by ssiuhk** [signal18/replication-manager#107]
Even given connect-timeout in the config file, the replication-manager is froze when one host is not pingable anymore. No update of host status, no response to any action (failover/switch over / change failover mode etc). It works fine if just bring down the Mariadb service (e.g. host is still pinable).

**Comment by tanji** [comment]
Yes, this is a known issue that exists at low level, because the host on the other side does not send TCP ack anymore, for example if it uses a firewall. If host is physically down, the problem you describe will not happen.

**Comment by ssiuhk** [comment]
No...... in fact I bring down the network of the host (similar to physically down), and the replication-manager froze.
I try to simulate a disaster scenario when the host is down.

**Comment by tanji** [comment]
May I ask how you bring down the network?

**Comment by ssiuhk** [comment]
systemctl stop network

**Comment by tanji** [comment]
OK. I will try to simulate this, however if it's half open TCP connection problem there will be no fix for it (as it's a very low level issue)

**Comment by ssiuhk** [comment]
May I know how replication-manager detects a Mariadb is up or down? May need to implement some kind of timeout mechanism?

**Comment by tanji** [comment]
It uses protocol ping, which is as low level as it gets, and it has a timeout.
TCP connections won't time out if the socket is in an half open state. That's a known issue which is not related to MRM or Golang whatsoever.

**Comment by svaroqui** [comment]
May be can use an other way to check like a establish a connection instead of com_ping 
check-type = conn what do you think that may be used with connection-pool extra port to be sure of never be blocked by max connection ?

**Comment by ssiuhk** [comment]
I think it's related to arp cache timeout.
e.g. if arp cache on the switch refresh after 5 min, the ping result became unreachable instead of timeout after 5min.
Then the status of server is updated.
Not sure if there could be a way to do a faster detection.
Is there a way to use com ping like ping -W 3 -c 1 so it could timeout after 3 sec instead of long wait?

**Comment by tanji** [comment]
Fixed in b4699cb4c7870e015b4e5a3116b496ac4c36cce2
