### ISSUE TITLE
Alerting on slave replication failure 

### ISSUE THREAD

**Issue by ssiuhk** [signal18/replication-manager#109]
Hello,

Would it be possible to add a new feature to e-mail report/generate file report on sync status?
e.g. in case sync is broken on one of the slave due to db corrupted, conflict of id, etc.

Thanks!

**Comment by svaroqui** [comment]
Hi ssiuhk, 

Sure that looks like something to hack on during vacation :) 

I will start tomorrow looking at this feature. 

Thanks for reporting 
/svar

**Comment by tanji** [comment]
Hi @ssiuhk We already have alerting built-in so this should be easy to add.

**Comment by svaroqui** [comment]
Hi @ssiuhk ,

This feature should be included in the next build .   
Thanks for reporting!

**Comment by ssiuhk** [comment]
Great, thanks a lot for the work! 👍
