### ISSUE TITLE
Have Replication Manager contemplate the case when a shutdown Master is ahead of its semi-sync Slave(s).

### ISSUE THREAD

**Issue by claudionanni** [signal18/replication-manager#111]
I did several tests with MariaDB 10.1.18/19 in a Master/Slave semi-sync replica setup and I observed that it's possible that the Master, once shutdown with either  kill -9 or even just `shutdown` command, has between 1 and 3 transactions more than its semi-sync Slave, the setting rpl_semi_sync_master_wait_point does not make difference.

If needed to reproduce the issue, the test is easy:
* Setup semi-sync
* Open 3 terminals and run multithread mysqlslap tests
* Stop the Master with either kill -9 or `shutdown`  (The Master will *always* shutdown immediately, no timeout waited)
* Wait for the semi sync to apply all transactions

Now check the binlog on the Master (no need to start it up), it's 1 to 3 transactions ahead.

At this point Replication Manager encounters the problem on failover.

I suppose MRM should contemplate this case in any case even if in this specific case it could be fixed.

Related to:
https://jira.mariadb.org/browse/MDEV-11853
https://jira.mariadb.org/browse/MDEV-11855

**Comment by svaroqui** [comment]
There is  a difference after commit you  are sure that those extra transaction have been receive by client but they are not necessary semi-sync , after-sync get  no client commit guaranty, i think there is no way to fixe today inside replication manager: if  agent base sending the diff could work only if not real server crash, as well i don't see more reason such agent would be able to communicate with a peace of software that already report the server was dead   t agent base can at least fixe shutdown or kill -9 case), that can't wrongly give the perception that it's ok in testing

**Comment by tanji** [comment]
Hi Claudio
Thanks for a bug report, Stephane has improved failover priority on https://github.com/tanji/replication-manager/commit/d3fe005f7b99e89f657b61e307c2f8b558ba4b83
I haven't had time to set up a reproducer, will look at this as soon as I can.

**Comment by claudionanni** [comment]
When you shutdown or kill the Master you have 1-3 transactions in the Master's binary log that are not received by the semi-sync Slave.
As soon as you start the Master also the Slave will receive them, they are not rolled back.
I tested this with both AFTER_SYNC and AFTER_COMMIT, same thing.
Note, when you issue SHUTDOWN the Master does not wait at all, no timeouts involved.

So at a certain point the situation is:

1 ack by app  -  written to master binlog -- written to engine -- sent to slave
2 ack by app  -  written to master binlog -- written to engine -- sent to slave
3 ack by app  -  written to master binlog -- written to engine -- sent to slave
4 ack by app  -  written to master binlog -- written to engine -- sent to slave
5 ack by app  -  written to master binlog -- written to engine -- sent to slave
6 ack by app  -  written to master binlog -- ? I suppose so... -- NO
7 ack by app  -  written to master binlog -- ? I suppose so... -- NO

The app relies on the fact that records 6 & 7 have been applied, it does not matter that it knows that the Master crashed, for the app, records 6 & 7 should have been safely despatched.

MRM should always know the latest GTID applied from the App(The App relies on this), and continue from there even if the records are only present in the Binary Log of the crashed Master.

**Comment by svaroqui** [comment]
Yes the fixe we pushed is to be sure that we always elect the most up to date slave regarding IO GTID no more SLAVE  GTID, if this server is not the prefered master , the prefered master is ignored , and a switchover will be trigger just after the failover to try to move to prefered master , for the case of extra transaction in the master we can't avoid them unless MariaDB or MySQL can fixe , but this bring more issues and there are good reasons its done this way , in AFTER COMMIT in  a crash those extra transactions have touch the binlog but not the client , so that should be safe to discard  them by reprovisionning the save as the transaction have never been made visible to the client API , for shutdown i think that's a pure bug that could be fixed ! and probably backported depending on complexity ?

**Comment by svaroqui** [comment]
In any case making a scenario with rolling shutdown or kill -9 can only lead to the requirement of fully re provision the old master SST like :) we don't cover that feature yet in MRM . But that's doable

**Comment by svaroqui** [comment]
Fixed with flashback or dump
