### ISSUE TITLE
0.7.0-rc3-39-g05d8ee1 with http-server with auth enabled mem leak

### ISSUE THREAD

**Issue by blackluck** [signal18/replication-manager#115]
Version 0.7.0-rc3-39-g05d8ee1

With default http configs:
```
http-server = false
http-bind-address = "0.0.0.0"
http-port = "10001"
http-root = "/usr/share/replication-manager/dashboard"
http-auth = true
http-session-lifetime = 3600
http-bootstrap-button = false
```

Started in deamon mode AND connect to it's web interface (3 same browser tab, but didn't matter numbers as I saw) and left tabs open. 
Replication-manager process memory usage from around 200MB went over 1.1GB in around 2 hours.

After closed web browser and didn't touched replication manager process doesn't really grow more mem usage.

If started with http-server=false then not seen mem leak.

**Comment by tanji** [comment]
Can you try with http-server=true and http-auth=false? We could not reproduce it so far.

**Comment by blackluck** [comment]
Did those test:

- without http auth not seen mem leak
- with http auth and opened only login page no mem leak
- with http auth and logged in there is a mem leak (after login  around half or one minute)
- after logged out but leave browser tabs open mem leak stops

mem leak shows this kind of tendency after login:
```
Thu Jan 26 15:44:21 CET 2017   VmSize:    188400 kB
Thu Jan 26 15:44:31 CET 2017   VmSize:    188400 kB
Thu Jan 26 15:44:41 CET 2017   VmSize:    188400 kB
Thu Jan 26 15:44:51 CET 2017   VmSize:    189456 kB
Thu Jan 26 15:45:01 CET 2017   VmSize:    189456 kB
Thu Jan 26 15:45:11 CET 2017   VmSize:    190516 kB
Thu Jan 26 15:45:21 CET 2017   VmSize:    191572 kB
Thu Jan 26 15:45:31 CET 2017   VmSize:    192628 kB
Thu Jan 26 15:45:41 CET 2017   VmSize:    193940 kB
Thu Jan 26 15:45:51 CET 2017   VmSize:    195000 kB
```

will do longer test without http auth, but now seems that auth cause the leak.

**Comment by tanji** [comment]
Issue confirmed here with http auth.
