### ISSUE TITLE
replication-manager web manager ?

### ISSUE THREAD

**Issue by sysdljr** [signal18/replication-manager#116]
Hi, @tanji , @svaroqui 
     We have  about 30 group master-slave.
     current,  replication-manager could not  manager multi group master-slave in a web page ?
     Could you can consider to  add a manager page,  first , it could list all groupname, example:
   
groupname        host                port    status
-----------------------------------------------------
Cluster01      172.28.14.116   3306   Master
                       172.28.14.118   3306   Slave
                       172.28.14.114   3306   Slave
Cluster02      172.28.14.111   3306   Master
                       172.28.14.112   3306   Slave
                       172.28.14.113   3306   Slave
Cluster03      ..........
Cluster30      ..........

then ,after click groupname  "Cluster01",   could open current group's  detail page , show http://172.28.14.117:10001 page content( reference picture at below ),  others groupname is same too. 
<img width="878" alt="http" src="https://cloud.githubusercontent.com/assets/17877603/22362475/de2baf04-e49d-11e6-95d4-cc59b933315e.png">

Above is personal idea for reference, thanks.

**Comment by svaroqui** [comment]
Hi sysdljr,

Did  commit a first  draft of similar design in dev it works in monitoring console by switching cluster using CtrlP and Ctrl-N

I'll let you know when the full feature work in http

**Comment by sysdljr** [comment]
ok. thank you very much for your quick development and support

**Comment by svaroqui** [comment]
This will take more time to finish ,the next month we have many client engagements coming, what can be done if you need to boost delivery of some features is to make some money contribution  to MariaDB so that the days can be blocked as non recursive eng.  But we 'll do our best anyway to improve the tool

**Comment by sysdljr** [comment]
ok. time longer , it is no problem.
I have alipay account  , later will donate money to MariaDB Foundation.
Thank you passion and focus for product again,  Happy work for you.

**Comment by tanji** [comment]
Hi guys, there is some confusion here, replication manager is not a MariaDB Foundation project, it's merely a personal project from svaroqui and myself :) however feel free to donate to the foundation if you use MariaDB, it will be appreciated, Thanks

**Comment by sysdljr** [comment]
Sorry,  because your email address contain "mariadb", I simply think is a company.
Thank you for your explanation, I understand.
