### ISSUE TITLE
No errors in log if file and position is used instead of GTID 

### ISSUE THREAD

**Issue by markus456** [signal18/replication-manager#134]
When slave servers are configured with binlog file and position instead of GTID coordinates, the failover process will fail to find a candidate slave. This might be caused by the empty GTID value in `Gtid_IO_Pos` which causes the following debug log message to be printed when the master is killed.

```
Feb 15 22:27:21 maxscale replication-manager[4883]: 2017/02/15 22:27:21 DEBUG: Checking eligibility of slave server 192.168.121.105:3306 [0]
Feb 15 22:27:21 maxscale replication-manager[4883]: 2017/02/15 22:27:21 DEBUG: Got sequence(s) [] for server [0]
Feb 15 22:27:21 maxscale replication-manager[4883]: 2017/02/15 22:27:21 DEBUG: Checking eligibility of slave server 192.168.121.151:3306 [1]
Feb 15 22:27:21 maxscale replication-manager[4883]: 2017/02/15 22:27:21 DEBUG: Got sequence(s) [] for server [1]
Feb 15 22:27:21 maxscale replication-manager[4883]: 2017/02/15 22:27:21 DEBUG: Checking eligibility of slave server 192.168.121.165:3306 [2]
Feb 15 22:27:21 maxscale replication-manager[4883]: 2017/02/15 22:27:21 DEBUG: Got sequence(s) [] for server [2]
```

Some warning in the log that GTID must be used when configuring the slave would help people figure out why the failover isn't working.

**Comment by svaroqui** [comment]
Hello that's correct i would propose to fixe it instead of warning up 
We should enable file pos comparison as an aternative solution for founding the most up to date slave

**Comment by tanji** [comment]
This is not a bug because it's clearly specified in the documentation that GTID must be used. There used to be a test for this, I think. What should be possible is to suggest upgrading the replication to GTID.
