### ISSUE TITLE
The --maxscale option uses IP instead of server name for `set server` commands

### ISSUE THREAD

**Issue by markus456** [signal18/replication-manager#135]
The --maxscale option uses IP instead of server name for `set server` commands. This causes the operation to fail unless the server names are identical to the IP of the server.

With the following configuration, replication-manager will issue a `set server 192.168.121.13 master` command when promoting the server _server1_ to a master.

```
[server1]
type=server
address=192.168.121.13
port=3306
protocol=MySQLBackend
```

The correct way would be to issue a `set server server1 master` command.

**Comment by tanji** [comment]
There is a serious issue here as "server1" is an arbitrary tag and replication-manager has no inherent knowledge of that mapping. I'm not sure how to resolve this issue at the moment unless there is a way to translate the IP address to the server name as it has been defined in MaxScale.

**Comment by markus456** [comment]
The `list servers` output has the IPs and ports of all servers, it could be parsed for the mappings. This also seems to be a bug on the MaxScale side as the `show serversjson` output doesn't contain the server names.

**Comment by tanji** [comment]
Yes I am aware, however `list servers` is nothing but simple to parse - it's human-readable, not machine-readable.
On the other hand, I guess it works for me because I do not use an IP address in maxscale.cnf but a hosts record which is similar to the sectional name, e.g.
```
[db3]
type=server
address=db3
port=3306
protocol=MySQLBackend
```

**Comment by svaroqui** [comment]
Markus,
Let's suppose we create a fake slave connection from replication-manager to standalone master  would it solve the standalone  server issue of maxscale monitoring
