### ISSUE TITLE
Set slave status for MaxScale servers

### ISSUE THREAD

**Issue by markus456** [signal18/replication-manager#136]
When replication-manager is configured with the --maxscale option, it will execute a `set server <name> master` command. This will manually assign the master status to a server allowing MaxScale to be controlled by the replication manager.

To allow MaxScale to be used without a monitor, the replication-manager would need to also issue `set server <name> slave` commands for all valid slave server. This is only required if MaxScale does no monitoring of its own.

An alternative approach to solving the problem of server status conflicts between MaxScale and replication-manager would be to shut down the monitor in MaxScale when the replication topology cannot be resolved by MaxScale. In practice, this only happens when the final node of a cluster is promoted to a master. At this point, MaxScale thinks that the remaining server is a lone slave when in fact it is the current master. By stopping the monitor and forcing the state to _Master_, the replication-manager would be able to promote the last slave to a master and MaxScale would still function.

**Comment by tanji** [comment]
Depends on #135
