### ISSUE TITLE
production implementation

### ISSUE THREAD

**Issue by bhakimi** [signal18/replication-manager#139]
sorry to create a ticket here, i tried to email you but your email address got rejected, im interested in implementing this and i was wondering if we can contract you to do this for us?

please let me know if that would be possible. thank you

**Comment by tanji** [comment]
Hi @bhakimi, yes, I offer consulting on request. Please email me to guillaume@signal18.io and we can discuss this. Thanks

**Comment by svaroqui** [comment]
Tell us more about your  topology plan ? number of nodes, os , best would be 3 database cluster nodes and 2 proxies nodes

**Comment by svaroqui** [comment]
Still it's possible to build 2 nodes cluster but this less robust , and you may lose one slave that leave you only with a single master
