### ISSUE TITLE
Could not  Set ENABLE for event on new master?

### ISSUE THREAD

**Issue by sysdljr** [signal18/replication-manager#140]
Hi, @tanji 
      After MRM switchover , set  event show error, please you help again, thanks 

 2017-03-06 20:56:35 INFO : Master switch on 172.28.14.116:3306 complete                                                    
 2017-03-06 20:56:35 INFO : Switching other slaves to the new master                                                        
 2017-03-06 20:56:34 INFO : Switching old master as a slave                                                                 
 2017-03-06 20:56:34 ERROR: **Could not  Set ENABLE for event test2 ev_test2 on new master**                                    
 2017-03-06 20:56:34 INFO : Set ENABLE for event test2 ev_test2 on new master                                               
 2017-03-06 20:56:34 INFO : Enable Event Scheduler on the new master                                                        
 2017-03-06 20:56:34 INFO : Resetting slave on new master and set read/write mode on                                        
 2017-03-06 20:56:34 INFO : Stopping slave thread on new master                                                             
 2017-03-06 20:56:34 DEBUG: Server:172.28.14.116:3306 Current GTID:0-118-53192 Slave GTID:0-118-53192 Binlog Pos:0-118-53192
 2017-03-06 20:56:34 DEBUG: MASTER_POS_WAIT executed.                                                                       
 2017-03-06 20:56:34 DEBUG: Server:172.28.14.118:3306 Current GTID:0-118-53192 Slave GTID:0-116-53186 Binlog Pos:0-118-53192
 2017-03-06 20:56:34 DEBUG: Syncing on master GTID Binlog Pos [0-118-53192]                                                 
 2017-03-06 20:56:34 INFO : Waiting for candidate Master to synchronize                                                     
 2017-03-06 20:56:34 INFO : Rejecting updates on 172.28.14.118:3306 (old master)                                            
 2017-03-06 20:56:34 INFO : Terminating all threads on 172.28.14.118:3306                                                   
 2017-03-06 20:56:34 INFO : Disable Event Scheduler on old master                                                           
 2017-03-06 20:56:34 ERROR: **Could not Set DISABLE ON SLAVE for event test2 ev_test2 on old master**                           
 2017-03-06 20:56:34 INFO : Set DISABLE ON SLAVE for event test2 ev_test2 on old master                                     
 2017-03-06 20:56:34 INFO : Slave 172.28.14.116:3306 [0] has been elected as a new master                                   
 2017-03-06 20:56:34 INFO : Electing a new master                                                                           
 2017-03-06 20:56:34 INFO : Flushing tables on 172.28.14.118:3306 (master)                                                  
 2017-03-06 20:56:34 INFO : Checking long running updates on master                                                         
 2017-03-06 20:56:34 INFO : Starting master switch  

master:  172.28.14.118 
slave : 172.28.14.116
MRM on  172.28.14.117

show grants for mysqlcheck@172.28.14.117;
##Grants for mysqlcheck@172.28.14.117
GRANT RELOAD, PROCESS, SUPER, REPLICATION CLIENT, EVENT ON *.* TO 'mysqlcheck'@'172.28.14.117' IDENTIFIED BY PASSWORD '*6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9';
GRANT  SELECT ON `mysql`.`event` TO 'mysqlcheck'@'172.28.14.117';
GRANT SELECT ON `mysql`.`user` TO 'mysqlcheck'@'172.28.14.117';

after switchover,  new master is 172.28.14.116

on 172.28.14.117 execute:
mysql -umysqlcheck -p -h 172.28.14.116
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 348
Server version: 10.1.21-MariaDB MariaDB Server
MariaDB [(none)]> use test2;
MariaDB [test2]> select db,name,status from mysql.event;
+-------+----------+--------------------+
| db    | name     | status             |
+-------+----------+--------------------+
| test2 | ev_test2 | SLAVESIDE_DISABLED |
+-------+----------+--------------------+

MariaDB [test2]> select user();
+--------------------------+
| user()                   |
+--------------------------+
| mysqlcheck@172.28.14.117 |
+--------------------------+

## manual execute alter event ,  set enable is normal.   MRM  set event to enable , it  isn't  execute the statement ?
MariaDB [test2]> alter event test2.ev_test2 enable;
Query OK, 0 rows affected (0.00 sec)

MariaDB [test2]> select db,name,status from mysql.event;
+-------+----------+---------+
| db    | name     | status  |
+-------+----------+---------+
| test2 | ev_test2 | ENABLED |
+-------+----------+---------+

**Comment by tanji** [comment]
Hi! @sysdljr, I will try to reproduce this, @svaroqui author of this feature please comment if you have an idea, thanks for reporting.

**Comment by svaroqui** [comment]
Hi , can you try to investigate more on this by using the genral log and the sql error log plugin 
- Looking at the code look's like ok to me 
- Note that 
failover-event-scheduler = false
failover-event-status = false
are auto exclusive and should not be used as both yes , this is not check by the code and so error prone , what are your value for this ?

**Comment by svaroqui** [comment]
https://mariadb.com/kb/en/mariadb/sql_error_log-plugin/

**Comment by sysdljr** [comment]
Thank you reply, @tanji , @svaroqui 
I had install sql_error_log plugin,  after switchover , check sql_errors.log:
2017-03-09 21:45:54 mysqlcheck[mysqlcheck] @[172.28.14.117] ERROR 1044: Access denied for user 'mysqlcheck'@'172.28.14.117' to database 'test2' : ALTER EVENT test2.ev_test2 ENABLE

But, use mysql client execute is normal on 172.28.14.117.
mysql -umysqlcheck -p123456 -h 172.28.14.116 
MariaDB [(none)]> ALTER EVENT test2.ev_test2 ENABLE;
Query OK, 0 rows affected (0.01 sec) 

MRM's config.toml:
failover-event-scheduler = true
failover-event-status = true

test event :
CREATE DEFINER=`mysqlcheck`@`172.28.14.117` EVENT `ev_test2` ON SCHEDULE EVERY 1 HOUR STARTS '2017-03-06 17:00:00' ENDS '2017-03-13 00:00:00' ON COMPLETION PRESERVE ENABLE DO BEGIN
    INSERT INTO test02(createtime) VALUES(now());
END

**Comment by svaroqui** [comment]
Stéphane Varoqui, Senior Consultant
Phone: +33 695-926-401, skype: svaroqui
http://www.mariadb.com <http://www.mariadb.com/>




> Le 9 mars 2017 à 15:03, sysdljr <notifications@github.com> a écrit :
> 
> Thank you reply, @tanji <https://github.com/tanji> , @svaroqui <https://github.com/svaroqui>
> I had install sql_error_log plugin, after switchover , check sql_errors.log:
> 2017-03-09 21:45:54 mysqlcheck[mysqlcheck] @[172.28.14.117] ERROR 1044: Access denied for user 'mysqlcheck'@'172.28.14.117' to database 'test2' : ALTER EVENT test2.ev_test2 ENABLE
> 
> But, in mysql client execute is normal.
> mysql -umysqlcheck -p123456 -h 172.28.14.116
> MariaDB [(none)]> ALTER EVENT test2.ev_test2 ENABLE;
> Query OK, 0 rows affected (0.01 sec)
> 
> MRM's config.toml:
> failover-event-scheduler = true
> 
so this mean that event scheduler is on on the master and off on the slave and MRM do the flap 

> failover-event-status = true
> 
This is telling MRM that the event is not running on slave and running on master 

So can you test with enabling symmetric conf where event scheduler is on on both nodes 
and use 
> failover-event-scheduler = false
> 

> failover-event-status = true
> 
Please report if that help, 
my theory is that when scheduler off we can’t really with events status

**Comment by sysdljr** [comment]
set failover-event-scheduler = false and failover-event-status = true, after switchover,  event status is OK,
but event_scheduler status is error.

on new master:
 SHOW VARIABLES WHERE variable_name IN ('read_only','event_scheduler');
 Variable_name	VALUE
**event_scheduler	OFF**          ( if is ON , event can run normal else not run)
read_only	        OFF
 
SELECT NAME, STATUS  FROM mysql.event ;
NAME	    STATUS
ev_test2	ENABLED  

on new slave:
SHOW VARIABLES WHERE variable_name IN ('read_only','event_scheduler');
Variable_name	Value
**event_scheduler	ON**
read_only	ON

SELECT NAME, STATUS  FROM mysql.event ;
NAME	STATUS
ev_test2	SLAVESIDE_DISABLED

After this switchover, No matter on master or on slave,  event can not run.

Additional:
on  product server, before and after switching,  if role is master,  its event_schedule status forever is ON, this is OK

**Comment by svaroqui** [comment]
re,

You should make sure the event_scheduler is on on all nodes before starting the test , 
It is because  failover-event-scheduler = false tell MRM not to touch the event_scheduler activation. 
So the state  you are reporting may have come from previous execution when this parameter was true

tx
/stephane

Stéphane Varoqui, Senior Consultant
Phone: +33 695-926-401, skype: svaroqui
http://www.mariadb.com <http://www.mariadb.com/>

**Comment by sysdljr** [comment]
OK, I understand. 
Sorry, this is my config error.  we always set event_scheduler = off on all slaves.
when set event_scheduler = "on"  in master and slave,   and set  failover-event-scheduler = true,
failover-event-status = true on MRM,   after switchover,  both event_scheduler and event-status are normal.
Thank you very much for your rapid support and help

**Comment by svaroqui** [comment]
Pleasure thanks for using

**Comment by sysdljr** [comment]
Hi, @svaroqui 
    Recently, we had use mrm 1.0.2 on product server,  have a little problem on event failover,  please help confirm, thanks.
example: 
on test01 database:
  CREATE DEFINER=**test1_rw@localhost** EVENT `ev_test1` ON SCHEDULE EVERY 1 HOUR STARTS '2017-03-06 17:00:00' ON COMPLETION PRESERVE ENABLE DO BEGIN
  DELETE FROM test001;
 END

on test02 database:
  CREATE DEFINER=**test2_rw@localhost** EVENT `ev_test2` ON SCHEDULE EVERY 1 HOUR STARTS '2017-03-06 17:00:00' ON COMPLETION PRESERVE ENABLE DO BEGIN
   update test02 set c1 = c1 + 100;
 END

MRM's username is mysqlcheck@172.28.14.117,   after switchover,  all event's definer change to mysqlcheck@172.28.14.117, but this user not have delete privilege on test01 database , and not have update privilege on test02 database.  so, these event still can't normal run.
on test01 database:
  CREATE DEFINER=**mysqlcheck@172.28.14.117** EVENT `ev_test1` ON SCHEDULE EVERY 1 HOUR STARTS '2017-03-06 17:00:00' ON COMPLETION PRESERVE ENABLE DO BEGIN
  DELETE FROM test001;
 END

on test02 database:
  CREATE DEFINER=**mysqlcheck@172.28.14.117** EVENT `ev_test2` ON SCHEDULE EVERY 1 HOUR STARTS '2017-03-06 17:00:00' ON COMPLETION PRESERVE ENABLE DO BEGIN
   update test02 set c1 = c1 + 100;
 END

we manual modify example, for reference
alter  definer=test1_rw@localhost  ev_test1 enable;
alter  definer=test2_rw@localhost  ev_test2 enable;

**Comment by svaroqui** [comment]
Yes i can confirm now 
ALTER EVENT ev_test1 DISABLE ON SLAVE; will change the definer ! 

I need to push a fix soon 
Thanks for reporting 

Would appreciate if you can build a test case for this if you can manage go code!
Is that possible?

**Comment by svaroqui** [comment]
it's clearly documented 
When a user executes a successful ALTER EVENT statement, that user becomes the definer for the affected event. So that mean that you need to give some grants to the mysqlcheck user , 

So the fixe is to recreate the event code from scratch from the event table definition , not easy but doable

**Comment by sysdljr** [comment]
Thank you very much.
Sorry, I only understand database , and I never used go language.
if you have free time,  Could you simple teach me how build go code ?

**Comment by sysdljr** [comment]
Yes , give some privilege to mysqlcheck user can solve , but , this will permit mysqlcheck user have many database's privileges. we restriced every database only a username's access privileges, whether can keep every event's original user ? 
example:
 execute ALTER EVENT ev_test1 DISABLE ON SLAVE , change to execute ALTER definer=test1_rw@localhost  EVENT ev_test1 DISABLE ON SLAVE ?

**Comment by svaroqui** [comment]
I've push a patch to the dev branch

**Comment by sysdljr** [comment]
ok, thank you support and help again.

**Comment by svaroqui** [comment]
What package do you need ?

**Comment by sysdljr** [comment]
use tar.gz package

**Comment by svaroqui** [comment]
Can you try this binary
http://88.191.151.84:8080/share.cgi?ssid=0QxFeAw

**Comment by sysdljr** [comment]
ok, I had download binary package.
after test , reply  you.  thank you very much.

**Comment by sysdljr** [comment]
after switchover , every event's user close to normal, 
now, problem is after definer more than two characters "@%" 

SELECT NAME,STATUS,DEFINER  FROM mysql.event ;

NAME	STATUS	DEFINER
ev_test1	ENABLED	 test1_rw@localhost@%
ev_test2	ENABLED	 test2_rw@localhost@%

**Comment by svaroqui** [comment]
Ok i see what it is i will patch it back home

**Comment by svaroqui** [comment]
Re, I created this fixe please let me know if it pass this time,  http://88.191.151.84:8080/share.cgi?ssid=0WoQlRL !

**Comment by sysdljr** [comment]
Thank you for effective support and help.
replication-manage version
Replication Manager 1.0.0 for MariaDB 10.x Series
Full Version:  1.0.0-254-g7578d90
Build Time:  2017-03-21T20:33:13+0100

First , after switchover, event's username have not change.
NAME	STATUS	DEFINER
ev_testl2	ENABLED	mysqlcheck@172.28.14.117
ev_test1	ENABLED	mysqlcheck@172.28.14.117 

after restart mysql,   execute switchover, every event's username show OK
ev_testl2	ENABLED	test2_rw@localhost
ev_test1	ENABLED	test1_rw@localhost
