### ISSUE TITLE
Indirect slaves aren't recovered

### ISSUE THREAD

**Issue by markus456** [signal18/replication-manager#145]
With a three node setup consisting of one master (A) and two slaves (B, C) and the following chain of events, the slave B will never rejoin the new master C.

* Kill slave B
* Kill master A
* Slave C is promoted as the new master
* Restart B
* Restart A

There are two issues. First, the `replication-manager` doesn't seem to consider B as a possible slave for C. The slave is logically capable of rejoining the cluster as C contains all events that were executed on A and the slave B was killed before the failover occurred. 

Second issue happens when both A and B are restarted. As the slave B was configured as a slave of A, the topology converts into a relay master setup with B replicating from A which in turn replicates from C. This is not a desired configuration as it seems to prevent further failovers when C is killed. The following error message is logged when C is killed.

```
2017/03/12 12:28:19 [Default] ERROR: Can't failover,  slave skysql:skysql@tcp(node-001:3306)/?timeout=1s still see the master
```

Here _node-001_ is B which is replicating from A.

**Comment by svaroqui** [comment]
Cover by test case 

 ./replication-manager  --config-group=cluster_test_3_nodes test --run-tests=testFailoverSemisyncSlavekilledAutoRejoin --test-stop-cluster=false
