### ISSUE TITLE
Replication Manager not logging in "daemon mode"

### ISSUE THREAD

**Issue by dimon00** [signal18/replication-manager#147]
I have a replication manager started by pacemaker which is not writing anything in my log file.
The process is running as root and shows that the log file is open:

`root      4021     1  0 Feb01 ?        08:23:14 /usr/bin/replication-manager monitor `--daemon

lsof -p 4021
COMMAND    PID USER   FD      TYPE             DEVICE SIZE/OFF      NODE NAME
replicati 4021 root  cwd       DIR                8,3     4096         2 /
replicati 4021 root  rtd       DIR                8,3     4096         2 /
replicati 4021 root  txt       REG                8,3 16747320 251134118 /root/gocode/bin/replication-manager
replicati 4021 root  mem       REG                8,3  1864888 169903667 /lib/x86_64-linux-gnu/libc-2.23.so
replicati 4021 root  mem       REG                8,3   138696 169903673 /lib/x86_64-linux-gnu/libpthread-2.23.so
replicati 4021 root  mem       REG                8,3   162632 169902262 /lib/x86_64-linux-gnu/ld-2.23.so
replicati 4021 root    0r      CHR                1,3      0t0         6 /dev/null
replicati 4021 root    1u     unix 0xffff880852e08000      0t0     23956 type=STREAM
replicati 4021 root    2u     unix 0xffff880852e08000      0t0     23956 type=STREAM
replicati 4021 root    3w      REG                8,3    17023 165347563 /var/log/replication-manager.log
replicati 4021 root    4u     IPv4            1890517      0t0       TCP xxx02-vrack.xxx.com:52970->xxx01-vrack.xxx.com:mysql (ESTABLISHED)
replicati 4021 root    5u     IPv4            1892794      0t0       TCP xxx-vrack.xxx.com:51784->xxx02-vrack.xxx.com:mysql (ESTABLISHED)
replicati 4021 root    6u  a_inode               0,11        0      7041 [eventpoll]

If I start the replication manager without the parameter "daemon" than the log is written correctly.

**Comment by tanji** [comment]
Please report the version used:
`replication-manager version`

thanks in advance

**Comment by dimon00** [comment]
replication-manager version
2017/03/14 14:05:51 INFO : Using config file: /etc/replication-manager/config.toml
MariaDB Replication Manager version 0.7
Full Version:
Build Time:

**Comment by tanji** [comment]
Please upgrade to 1.0.2

https://github.com/tanji/replication-manager/releases

**Comment by dimon00** [comment]
I upgraded to 1.0.2
Now it seems to work (at least the restart is being logged).

Thanks

**Comment by tanji** [comment]
Great to know! Thanks for using Replication Manager.
