### ISSUE TITLE
No candidates found question?

### ISSUE THREAD

**Issue by sysdljr** [signal18/replication-manager#153]
Hi, @svaroqui 
    Please again you help ,thanks
   Today morning,  we switchover five groups master slave,  there are three group repeated execute switchover ,all nomal,  other two groups , first times, switchover normal,  when second times  switchover , it could not normal switch. 

before execute switchover,  data write had stopped.

replication-manager  --config=/etc/config.toml --config-group=ms228 monitor --interactive=false
--- /etc/conf.toml ----
[ms228]
## master: 10.2.10.228 slave: 10.2.10.227,  10.9.10.228
hosts = "10.2.10.228:3306,10.2.10.227:3306,10.9.10.228:3306"
user = "mysqlcheck:xxxxxx"
rpluser = "rep_user:xxxxxx"
prefmaster = "10.2.10.227:3306"
title = "ms228"
connect-timeout = 1
logfile = "/var/log/rep-manager.log"
verbose = true
autorejoin = true
readonly = true
failover-event-scheduler = true
failover-event-status = true

at below is a group sever's log info:
2017/03/22 05:00:15 INFO : Starting master switch
2017/03/22 05:00:15 INFO : Checking long running updates on master
2017/03/22 05:00:15 INFO : Flushing tables on 10.2.10.228:3306 (master)
2017/03/22 05:00:15 INFO : Electing a new master
2017/03/22 05:00:15 WARN : Slave 10.2.10.227:3306 not in sync. Skipping
2017/03/22 05:00:15 INFO : Slave 10.9.10.228:3306 [1] has been elected as a new master
2017/03/22 05:00:15 INFO : Set DISABLE ON SLAVE for event dba EV_table_rows_Day on old master
2017/03/22 05:00:15 INFO : Set DISABLE ON SLAVE for event dba EV_day_partition on old master
2017/03/22 05:00:15 INFO : Disable Event Scheduler on old master
2017/03/22 05:00:15 INFO : Terminating all threads on 10.2.10.228:3306
2017/03/22 05:00:15 INFO : Rejecting updates on 10.2.10.228:3306 (old master)
2017/03/22 05:00:15 INFO : Waiting for candidate Master to synchronize
2017/03/22 05:00:15 DEBUG: Syncing on master GTID Binlog Pos [0-239-70839085340]
2017/03/22 05:00:15 DEBUG: Server:10.2.10.228:3306 Current GTID:0-239-70839085340,1-5358-1367 Slave GTID:0-227-68873819160,1-5358-1367 Binlog Pos:0-239-70839085340
2017/03/22 05:00:15 DEBUG: MASTER_POS_WAIT executed.
2017/03/22 05:00:15 DEBUG: Server:10.9.10.228:3306 Current GTID:0-239-70839085340,1-5358-1367 Slave GTID:0-239-70839085340,1-5358-1367 Binlog Pos:0-239-70839085340
2017/03/22 05:00:15 INFO : Stopping slave thread on new master
2017/03/22 05:00:15 INFO : Resetting slave on new master and set read/write mode on
2017/03/22 05:00:15 INFO : Enable Event Scheduler on the new master
2017/03/22 05:00:15 INFO : Set ENABLE for event dba EV_table_rows_Day on new master
2017/03/22 05:00:15 INFO : Set ENABLE for event dba EV_day_partition on new master
2017/03/22 05:00:15 INFO : Switching old master as a slave
2017/03/22 05:00:17 INFO : Switching other slaves to the new master
2017/03/22 05:00:17 INFO : Waiting for slave 10.2.10.227:3306 to sync
2017/03/22 05:00:17 DEBUG: Server:10.2.10.227:3306 Current GTID:0-239-70839085340 Slave GTID:0-239-70839085340 Binlog Pos:0-239-70839085340
2017/03/22 05:00:17 INFO : Change master on slave 10.2.10.227:3306
2017/03/22 05:00:18 INFO : Master switch on 10.9.10.228:3306 complete
2017/03/22 05:01:38 INFO : Starting master switch
2017/03/22 05:01:38 INFO : Checking long running updates on master
2017/03/22 05:01:38 INFO : Flushing tables on 10.9.10.228:3306 (master)
2017/03/22 05:01:38 INFO : Electing a new master
2017/03/22 05:01:38 WARN : **Slave 10.2.10.228:3306 not in sync. Skipping**
2017/03/22 05:01:38 WARN : **Slave 10.2.10.227:3306 not in sync. Skipping**
2017/03/22 05:01:38 ERROR: **No candidates found**
2017/03/22 05:01:40 INFO : Quitting monitor

**Comment by tanji** [comment]
Hi @sysdljr , maybe increase `--maxdelay` or `--switchover-max-slave-delay` if you're using 1.1.

The default value is 0, so it won't promote any slave that has replication delay. Then, I suppose I should mention how much delay it currently has in the error message  , it would make this issue clearer.

Thanks for the report!

**Comment by svaroqui** [comment]
> Le 23 mars 2017 à 13:18, Guillaume Lefranc <notifications@github.com> a écrit :
> 
> Hi @sysdljr <https://github.com/sysdljr> , maybe increase --maxdelay or --switchover-max-slave-delay if you're using 1.1.
> 
> The default value is 0, so it won't promote any slave that has replication delay. Then, I suppose I should mention how much delay it currently has in the error message , it would make this issue clearer.
> 
> 
> 
Please also check the values for 

failover-at-sync = true

switchover-at-sync = true

Those value are true by default and protect you to switchover when not sync , but only way to know this is by using semisync replication 
Do you have it enable already ? 
If not you can use  
force-slave-semisync = true
And tell me if that helps in your case .

Tx stephane 
Stéphane Varoqui, Senior Consulant
Phone: +33 695-926-401, skype: svaroqui
http://www.mariadb.com <http://www.mariadb.com/>

**Comment by tanji** [comment]
Yep @svaroqui Is right, this error message has nothing to do with the delay. It has to see with failover-at-sync, which in my opinion should not be true by default, the default value always used to be false.

**Comment by svaroqui** [comment]
> Le 23 mars 2017 à 13:30, Guillaume Lefranc <notifications@github.com> a écrit :
> 
> Yep @svaroqui <https://github.com/svaroqui> Is right, this error message has nothing to do with the delay. It has to see with failover-at-sync, which in my opinion should not be true by default, the default value always used to be false.
> 
That a debate and i agree, what i suggest is to make 2 sample configuration files, once that enforce best practice , and one that can be use on exiting cluster without risk or enforcement  
 What are you thinking of this plan ?

**Comment by sysdljr** [comment]
Thank you reply very much.
Because the operation on product server, I use MRM 1.0.2.
at that time,  all program write service had stopped,  between master and slave no delay time.
besides,  on test server,  I occasionally met several times,   master had stop write data, and master and slave's gtid are same,  but ,   
 example:  from A switchover to B is normal,   if again switchover from B to A,  prompt Slave not in sync too.

if on new master B , manual insert a record,  again exectue switchover from B to A , it is OK

**Comment by tanji** [comment]
If you are not using semisync in 1.0.2 please disable `gtidcheck` either in CLI or Config. Thanks :+1:

**Comment by sysdljr** [comment]
we had set semisync on product server, 
rpl_semi_sync_master_enabled = ON
rpl_semi_sync_slave_enabled = ON
rpl_semi_sync_master_timeout = 10
rpl_semi_sync_master_wait_point=AFTER_COMMIT

 MRM doc have two parameter , I have not find it's explain on mariadb doc. it must add ?
**loose_rpl_semi_sync_master_enabled = ON  
loose_rpl_semi_sync_slave_enabled = ON**

**Comment by tanji** [comment]
No need, the loose_ is a prefix for parameter, if the plugin is not loaded it will just ignore this and start MariaDB instead of giving an Error.
@svaroqui any opinion?

**Comment by tanji** [comment]
Confirmed issue
