### ISSUE TITLE
Master detection fails

### ISSUE THREAD

**Issue by miklos-szel** [signal18/replication-manager#163]
Hello,

Trying to make replication-manager work on my little test environment and looking into integrating it as a potential HA solution to try out (MHA and Orchestrator are currently available):
https://github.com/mszel42/Ansible-MHA-ProxySQL-Docker

Replication manager is running in a docker container(running Ubuntu 16.04.2 LTS), the MySQL(5.6)  instances are running in docker containers, GTID replication is up and running:

The nodes are *not* accessible via ssh from the admin host.
 report_host is empty.

Trying to monitor the cluster with 
replication-manager 1.0.2(installed from .deb)
(also tried with the latest preview release with similar results)

```
replication-manager monitor --hosts=172.17.0.2:3306,172.17.0.3:3306,172.17.0.4:3306 --user=root:mysecretpass --rpluser=root:mysecretpass --interactive --log-level=3

(no configuration file is being used however I also tried to play with the sample)
```
<img width="1061" alt="screen shot 2017-06-26 at 4 05 52 pm" src="https://user-images.githubusercontent.com/6556358/27543387-5907a39c-5a8a-11e7-84c1-748339acae3b.png">

default_master_connection is a MariaDB only variable.

When  I press Ctrl+F or CTRL-s  I get the following error:

```
 2017-06-26 14:13:27 DEBUG: Server 172.17.0.2:3306 could not be refreshed: Error 1193: Unknown system variable 'default_master_connection'
 2017-06-26 14:13:27 DEBUG: Entering topology detection
 2017-06-26 14:13:27 DEBUG: Discovering topology loop     panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0x4283c4]

goroutine 1 [running]:
panic(0x920c40, 0xc420012060)
        /usr/lib/go/src/runtime/panic.go:500 +0x1a1
main.glob..func12(0xc457a0, 0xc420269a90, 0x0, 0x5)
        /home/tanj/go/src/github.com/tanji/replication-manager/repmgr.go:358 +0x11f4
github.com/tanji/replication-manager/vendor/github.com/spf13/cobra.(*Command).execute(0xc457a0, 0xc420269a40, 0x5, 0x5, 0xc457a0, 0xc420269a40)
	/home/tanj/Dev/go/src/github.com/tanji/replication-manager/vendor/github.com/spf13/cobra/command.go:636 +0x443
github.com/tanji/replication-manager/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc446a0, 0x0, 0xc4d308, 0x9ab7a1)
	/home/tanj/Dev/go/src/github.com/tanji/replication-manager/vendor/github.com/spf13/cobra/command.go:722 +0x367
github.com/tanji/replication-manager/vendor/github.com/spf13/cobra.(*Command).Execute(0xc446a0, 0x0, 0x0)
	/home/tanj/Dev/go/src/github.com/tanji/replication-manager/vendor/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
	/home/tanj/go/src/github.com/tanji/replication-manager/main.go:88 +0x31
```

MHA works properly, config file and sample output attached:
[mha.txt](https://github.com/tanji/replication-manager/files/1102453/mha.txt)

What is the proper way of setting the replication-manager up on Oracle MySQL?

**Comment by tanji** [comment]
Hi @mszel42 
`replication-manager` has been written with MariaDB support in mind. However the timing of your issue is crucial because I just released a package that is compatible with MySQL 5.7. MySQL 5.6 is also supported but I would not advise to use it, because the implementation of replication is not very good in that version, and using GTID is safer in most cases.

Feel free to download [replication-manager 1.1.0 Preview 2 Release](https://github.com/tanji/replication-manager/releases/tag/1.1.0-preview2) and test it. Let me know if you encounter any issues and I'll be happy to fix them.
