### ISSUE TITLE
What MariaDB prerequisites are needed to find a master

### ISSUE THREAD

**Issue by awakse** [signal18/replication-manager#187]
Hi,
I have a master-slave replication setup in two different docker containers, and replication-manager running in a third container.

I recently got this setup to work, but after some fiddling with the db instances/replication it stopped working. My question is what settings and setup are needed on the db instance to get replication-manager to find a master in the topology?
Replication is using GTID, and is working. Even if I could setup a new master-slave replication and get it to work again, it would be good to know what can be done if this state appears in production. And how to get by it.

The log after startup, using log-level 3 looks like this:
```
INFO[2017-10-11T15:40:33Z] replication-manager started in daemon mode    version=
INFO[2017-10-11T15:40:33Z] No existing password encryption scheme        error="Key file does not exist"
INFO[2017-10-11T15:40:33Z] New server monitored: 172.17.0.2:3306         cluster="Cluster_Test"
INFO[2017-10-11T15:40:33Z] New server monitored: 172.17.0.3:3306         cluster="Cluster_Test"
INFO[2017-10-11T15:40:33Z] Loading 0 proxies                             cluster="Cluster_Test"
INFO[2017-10-11T15:40:33Z] Failover in interactive mode                  cluster="Cluster_Test"
2017/10/11 15:40:33 INFO : Starting http monitor on port 8080
DEBU[2017-10-11T15:40:33Z] Lookup server 172.17.0.2:3306 if maxscale binlog server: 172.17.0.2:3306  cluster="Cluster_Test"
DEBU[2017-10-11T15:40:33Z] Lookup server 172.17.0.3:3306 if maxscale binlog server: 172.17.0.2:3306  cluster="Cluster_Test"
DEBU[2017-10-11T15:40:34Z] Lookup server 172.17.0.2:3306 if maxscale binlog server: 172.17.0.2:3306  cluster="Cluster_Test"
DEBU[2017-10-11T15:40:34Z] Lookup server 172.17.0.3:3306 if maxscale binlog server: 172.17.0.2:3306  cluster="Cluster_Test"
DEBU[2017-10-11T15:40:35Z] Monitoring server loop                        cluster="Cluster_Test"
DEBU[2017-10-11T15:40:35Z] Server [0]: URL: 172.17.0.2:3306 State:        PrevState:         cluster="Cluster_Test"
DEBU[2017-10-11T15:40:35Z] Server [1]: URL: 172.17.0.3:3306 State:        PrevState:         cluster="Cluster_Test"
DEBU[2017-10-11T15:40:35Z] Entering topology detection                   cluster="Cluster_Test"
DEBU[2017-10-11T15:40:35Z] Server 172.17.0.2:3306 is configured as a slave  cluster="Cluster_Test"
DEBU[2017-10-11T15:40:35Z] Privilege check on 172.17.0.2:3306            cluster="Cluster_Test"
DEBU[2017-10-11T15:40:35Z] Client connection found on server 172.17.0.2:3306 with IP 172.17.0.5 for host 172.17.0.5  cluster="Cluster_Test"
DEBU[2017-10-11T15:40:35Z] Server 172.17.0.3:3306 is configured as a slave  cluster="Cluster_Test"
DEBU[2017-10-11T15:40:35Z] Privilege check on 172.17.0.3:3306            cluster="Cluster_Test"
DEBU[2017-10-11T15:40:35Z] Client connection found on server 172.17.0.3:3306 with IP 172.17.0.5 for host 172.17.0.5  cluster="Cluster_Test"
DEBU[2017-10-11T15:40:35Z] Rejoin replication master id 2 was lookup if master replication-manager:rmpass@tcp(172.17.0.2:3306)/?timeout=1s&readTimeout=15s is that one : 1  cluster="Cluster_Test"
DEBU[2017-10-11T15:40:35Z] Rejoin replication master id 2 was lookup if master replication-manager:rmpass@tcp(172.17.0.3:3306)/?timeout=1s&readTimeout=15s is that one : 2  cluster="Cluster_Test"
DEBU[2017-10-11T15:40:35Z] Rejoin replication master id 1 was lookup if master replication-manager:rmpass@tcp(172.17.0.2:3306)/?timeout=1s&readTimeout=15s is that one : 1  cluster="Cluster_Test"
DEBU[2017-10-11T15:40:35Z] Rejoin replication master id 1 was lookup if master replication-manager:rmpass@tcp(172.17.0.2:3306)/?timeout=1s&readTimeout=15s is that one : 1  cluster="Cluster_Test"
DEBU[2017-10-11T15:40:35Z] Rejoin replication master id 2 was lookup if master replication-manager:rmpass@tcp(172.17.0.2:3306)/?timeout=1s&readTimeout=15s is that one : 1  cluster="Cluster_Test"
DEBU[2017-10-11T15:40:35Z] Rejoin replication master id 2 was lookup if master replication-manager:rmpass@tcp(172.17.0.3:3306)/?timeout=1s&readTimeout=15s is that one : 2  cluster="Cluster_Test"
WARN[2017-10-11T15:40:35Z] Undiscovered master, skipping failover check  cluster="Cluster_Test"
INFO[2017-10-11T15:40:35Z] ERR00012 Could not find a master in topology 
```

Attached is my config.toml

Thanks!

[config.txt](https://github.com/signal18/replication-manager/files/1376287/config.txt)

**Comment by svaroqui** [comment]
Hi,
i can see you  have failover-at-sync = true in the conf , do you have semisync plugins enable ? 
The main difference in new releases is that the election is done constantly to check the capability to failover, what can be done is to turn out all replication state checks via check-replication-state=false but that is more like a drastic position.  
FYI In release 2.0-osc we changed many of the parameter names  so we are advising mostly to remove all not needed variable from your configuration ,parameter interactive is gone  and replace with failover-mode https://docs.signal18.io/configuration/failover, 

Let us know if that helps .  can you send me your exact release ./replication-manager-pro version

**Comment by tanji** [comment]
Assuming your two servers are 172.17.0.3 and 172.17.0.2:

```
DEBU[2017-10-11T15:40:35Z] Server 172.17.0.3:3306 is configured as a slave  cluster="Cluster_Test"
DEBU[2017-10-11T15:40:35Z] Server 172.17.0.3:3306 is configured as a slave  cluster="Cluster_Test"
```

Both servers are configured as slaves. That's a master-master topology. You have to turn on the `replication-multi-master` option if you really want this.

**Comment by awakse** [comment]
@svaroqui settings failover-at-sync=false doesn't change anything. I'm building from source, version 1.1.2.

@tanji Correct, that's my two servers. I don't want a multimaster topology. The question is how I configure a db instance to be detected as a master and not a slave?

**Comment by svaroqui** [comment]
Ok you need to go the the one you think is a master and do a reset slave all :) as i prety sure if you do show  slave status you still get something !

**Comment by svaroqui** [comment]
Would be intrested to know what step bring you  to such state , any database release, version  you share with us to try to reproduce

**Comment by awakse** [comment]
`reset slave all` did the trick! I've only done `reset slave`on the preferred master, to no avail.

I think the steps include restoring one instance from a mysqldump, but exactly what commands I used I can't recall.

Thanks for the help!

**Comment by svaroqui** [comment]
If you plan to get docker in production our version pro is just for you, it get some advance services orchestration like kubernetes and manager the route to  your docker container , with it bootstrapping a full cluster is matter of one command . Not to say that we embedded in MySQL and MariaDB config about 14 years of best consulting practice
