### ISSUE TITLE
Graphs not working

### ISSUE THREAD

**Issue by Slash663** [signal18/replication-manager#188]
Hello,

I can't manage to make the Graphs working, the page shows only the title of the graphs (Avg QPS, Max Replication Delay, Network In&Out, Last Threads).

I don't understand what needs to be done to make it work, could you help? Do I have to install something more on the server or modify a file or should it work on its own for the default graphs?

I've stopped the firewall service to be sure it is not the blocker but does not help.

Here is the config.toml

```
# HTTP
# ----

http-server = true
http-bind-address = "0.0.0.0"
http-port = "10001"
http-root = "/usr/share/replication-manager/dashboard"
http-auth = false
http-session-lifetime = 3600
http-bootstrap-button = false

# STATS
# -----

graphite-metrics = true
graphite-carbon-host = "127.0.0.1"
graphite-carbon-port = 2003

graphite-embedded = true
graphite-carbon-api-port = 10002
graphite-carbon-server-port = 10003
graphite-carbon-link-port = 7002
graphite-carbon-pickle-port = 2004
graphite-carbon-pprof-port = 7007
```

**Comment by svaroqui** [comment]
Hello, 

Didi you change to setup the replication-manager host inside /usr/share/replication-manager/dashboard/static/graph.js ?

**Comment by Slash663** [comment]
OMG! I can't believe I've missed this setting!

Thank you for pointing it to me!

Issue can be closed.
