### ISSUE TITLE
replication-manager-osc_2.0.0-dev-399-g5a7b_amd64.deb SIGSEGV

### ISSUE THREAD

**Issue by vlada-dudr** [signal18/replication-manager#190]
Hello, after unsuccessful attempts to set up replication-manager 1.1, I tried how far I get with 2.0. Well, it crashes almost immediatly:

INFO[2017-12-04T17:47:21Z] replication-manager started in daemon mode    version=2.0.0-dev
INFO[2017-12-04T17:47:21Z] No existing password encryption scheme        error="Key file does not exist"
Resolved Host IP: 172.17.0.37
INFO[2017-12-04T17:47:21Z] Loading database TLS certificates             cluster=some-cluster
INFO[2017-12-04T17:47:21Z] Don't Have database TLS certificates          cluster=some-cluster
INFO[2017-12-04T17:47:21Z] hostlist: srv1,srv2:3303 [srv1 srv2:3303]  cluster=some-cluster
INFO[2017-12-04T17:47:21Z] Failover in automatic mode                    cluster=some-cluster
INFO[2017-12-04T17:47:21Z] Loading 1 proxies                             cluster=some-cluster
INFO[2017-12-04T17:47:21Z] Loading Maxscale...                           cluster=some-cluster
WARN[2017-12-04T17:47:21Z] File error: open /var/lib/replication-manager/some-cluster/clusterstate.json: no such file or directory
  cluster=some-cluster
ERRO[2017-12-04T17:47:21Z] Slave wants to rejoin non discovered master   cluster=some-cluster
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7410d1]

goroutine 34 [running]:
github.com/signal18/replication-manager/dbhelper.GetPrivileges(0xc42032db00, 0xc4202e96b0, 0xb, 0xc4202a4d80, 0xc, 0xc4202704e0, 0xd, 0x0, 0x0, 0x0, ...)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/dbhelper/dbhelper.go:358 +0x8b1
github.com/signal18/replication-manager/cluster.(*Cluster).TopologyDiscover(0xc420142400, 0xd71e11, 0x5)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/topology.go:190 +0x2e93
github.com/signal18/replication-manager/cluster.(*Cluster).Run(0xc420142400)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/cluster.go:191 +0x272
created by main.glob..func5
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/server.go:583 +0x747

More details: There are two mariadb 10.2 instances in master-slave mode, fresh installation. Version 1.1 was able find them and do switchover correctly. It was not able to set up maxscale correctly having two Maxscale instances (one seemed to be ok) and didn't read their data as it should. I also tried to convert config.toml to use 2.0 directives. It doesn't work. Tried also to comment out as many config options as possible, but no success. It worked only having only one db server in the list, but that is useless...

**Comment by tanji** [comment]
@vlada-dudr, my apologies but I pushed a bad commit this afternoon, the fix is already pushed, please pull the latest source. I will comment later on the other issue.

**Comment by psachin-ic** [comment]
Can you send the config across as I am able to do just switchover fine wirh replication manager but not failover

**Comment by vlada-dudr** [comment]
Thank you, it seems to be fixed.

**Comment by tanji** [comment]
@vlada-dudr I would recommend getting binaries from our CI server http://ci.signal18.io/mrm/builds/develop/ or http://ci.signal18.io/mrm/builds/1.1/ as the latest "good" versions can always be found there.

Re. MaxScale: RM 1.1 only supported one instance for sure. Multiple proxies are only supported in 2.0.
Re. conf-changes: most of the new conf would be documented at https://docs.signal18.io/configuration. The conversion is usually straightforward - I don't understand why you would have a single db. It's just a parameter name change for most of them. I can help if you send me the config.
