### ISSUE TITLE
http client questions

### ISSUE THREAD

**Issue by boris-ragulin** [signal18/replication-manager#194]
Hi!

Could you please describe how the maintenance mode is working? I did not find any related docs :(
I'm trying to send maintenance command via http client to the one of  the servers and it seems nothing happens (but I got 200 http response). The same behavior for replication-manager 2.0 osc.

Also it seems that slave status is not updated within the list of the servers when this slave is changing its status.

Currently I'm using MariaDB 10.2 and replication-manager 1.1.3.

**Comment by svaroqui** [comment]
Hi,

What proxy are you using and are they explicitly set into your config  ? 
Maintenance mode should tell the proxies not to route traffic to such node !

**Comment by svaroqui** [comment]
Hello,

Good catch only client API was working i just push a fix for HTTP 

Sorry for that...

**Comment by svaroqui** [comment]
Looking at the code if you put a master in maintenance it is performing a switchover before setting the proxies

**Comment by tanji** [comment]
Fixed in c5f47aad62261f605691119e0fc289b61d8cc343
