### ISSUE TITLE
Error "Could not set replication channel"

### ISSUE THREAD

**Issue by gabriel-a** [signal18/replication-manager#198]
Hello and thanks for all the support,

Today i deployed the first Replication manager 2.0 version to our test environment, the failover is working perfectly but I'm receiving "Could not set replication channel"

I did check the code and i see its in srv.go like 484, is there any logging level that would allow me to see more why this is happening? I did try the _--log-level=3_ but still it would not show any clue.

Any help would be appreciated and thanks for the great work.

Cheers,
Gabriel

**Comment by svaroqui** [comment]
Hello thanks for using,

What is your  MySQL or MariaDB release ?

**Comment by svaroqui** [comment]
func (server *ServerMonitor) SetReplicationChannel(source string) error {
	if server.DBVersion.IsMariaDB() {
		err := dbhelper.SetDefaultMasterConn(server.Conn, source)
		if err != nil {
			return err
		}
	}
	return nil
}

**Comment by gabriel-a** [comment]
All the servers are:

One server:
**Server version: 10.2.12-MariaDB-log MariaDB Server**

And the rest 4 servers are:
**Server version: 10.2.11-MariaDB-log MariaDB Server**

Could a minor version does the problem?

**Comment by svaroqui** [comment]
func SetDefaultMasterConn(db *sqlx.DB, dmc string) error {
	myver, _ := GetDBVersion(db)
	if myver.IsMariaDB() {
		stmt := "SET @@default_master_connection='" + dmc + "'"
		_, err := db.Exec(stmt)
		return err
	}
	// MySQL replication channels are not supported at the moment
	return nil
}

**Comment by svaroqui** [comment]
so basically SET @@default_master_connection='" + dmc + "'" is in error?  dmc is suppose to be empty string as you did not specify any custom replication channel witch is ok

**Comment by svaroqui** [comment]
Can you try in one of the db
SET @@default_master_connection='';

**Comment by svaroqui** [comment]
There is a feature request to log all sql to db , but that's probaby something i plan for  2.1 with monitoring of queries error log and backup

**Comment by gabriel-a** [comment]
I did test on all servers SET @@default_master_connection=''; everything is working fine without any error.

MariaDB [(none)]> SET @@default_master_connection='';
Query OK, 0 rows affected (0.00 sec)

also tried to set in the config.toml 
default-master-connection = "" 
or 
default-master-connection = ''

But still I'm receiving Could not set replication channel error.

**Comment by gabriel-a** [comment]
This is my config.toml 

```
# config.toml

[DEV_CLUSTER]
title = "DevCluster"
failover-mode = "manual"
db-servers-hosts = "mysql-1.dev.mysql.net:3306,mysql-2.dev.mysql.net:3306,mysql-apps-1.dev.mysql.net:3306,mysql-apps-2.dev.mysql.net:3306,mysql-int-1.dev.mysql.net:3306"
db-servers-prefered-master = "mysql-1.dev.mysql.net:3306"
db-servers-ignored-hosts = "mysql-apps-1.dev.mysql.net:3306,mysql-apps-2.dev.mysql.net:3306,mysql-int-1.dev.mysql.net:3306"
db-servers-credential = "username:password"
replication-credential = "username:password"
test = false
verbose = true

[Default]

# LOG
# ---

working-directory = "/var/lib/replication-manager"
share-directory = "/usr/share/replication-manager"

logfile = "/var/log/replication-manager.log"
verbose = true

# TOPOLOGY
# --------

multimaster = false
multi-tier-slave = false
maxscale-binlog = false

##########
## HTTP ##
##########

http-server = true
http-bind-address = "0.0.0.0"

# ALERTS
# ------

#mail-from = "mrm@localhost"
#mail-smtp-addr = "localhost:25"
#mail-to = "mrm@mariadb.com"

# FAILOVER
# --------

pre-failover-script = ""
post-failover-script = ""
rejoin-script = ""

# SYSBENCH
# --------

sysbench-binary-path = "/usr/sbin/sysbench"
sysbench-threads = 4
sysbench-time = 60


# MARIADB >= 10.2
# ---------------

mariadb-binary-path = "/usr/sbin"
```

**Comment by svaroqui** [comment]
Config looks good,

Is that appending at every monitoring event loop or during failover or switchover ?

/svar

**Comment by gabriel-a** [comment]
At every monitoring loop.

**Comment by svaroqui** [comment]
Thanks found the issue , this is indeed a bug not detected yet because we always use binlog on slaves

**Comment by svaroqui** [comment]
Re, 

Can you check last BUILD http://ci.signal18.io/mrm/builds/2.0/

/svar

**Comment by gabriel-a** [comment]
It works, Thank you Svar 👍
