### ISSUE TITLE
Public Docker image available?

### ISSUE THREAD

**Issue by pataquets** [signal18/replication-manager#199]
I'm looking for an official, already built image (don't want to ```docker build``` each time).
Checking from the Docker CLI, lots of images match 'replication-manager'. Trying to narrow the search, I switch to searching for 'signal18':
```
$ docker search signal18
NAME                           DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
signal18/proxysql              High-performance MySQL proxy with a GPL li...   0                    [OK]
signal18/shardproxy                                                            0                    
signal18/mariadb                                                               0                    
signal18/replication-manager                                                   0                    
```
Checked at Docker Hub, but I looks like it isn't even official (user squatting?).
Checked FAQ, docs, etc. and no reference to a public image on Docker Hub or another registry. Does one currently exists? If it does, it should be made more visible in the docs. If it doesn't, warn in the docs about the above mentioned images to avoid unsuspecting users to think it's official.
TIA.

**Comment by tanji** [comment]
There's a long open task to make an automated build, but I did not come to it because there was not much interest at the time. Seems it's time to do this sooner than later. Thanks for requesting it.

The account is legit btw, "official" I think only appears if the image is maintained by Docker. More on this later!

**Comment by svaroqui** [comment]
Hi Pataquets, 

Our pro release compete with  Kubernetes and Mesos it install and deploy ready to go architecture under docker for production infrastucture, may be you would like a demo of it ! 

Please request us if intrested !

**Comment by tanji** [comment]
The automated build is now available in https://hub.docker.com/r/signal18/replication-manager/ for 2.x series

**Comment by pataquets** [comment]
Awesome!!
@svaroqui : At the moment, I just want to give it a spin on my own environments to try it and see the features. Thanks for the offering, anyway.
Just a quick note: I can't still see the usage docs on the documentation on the web, but I imagine they will follow soon. Also, with the Docker Hub image page and a bit of tinkering I suppose I will be able to figure it out myself.
Thank you guys for the quick response.

**Comment by tanji** [comment]
The docker image doesn't have anything specific compared to the packages. It offers the open source version, but there aren't any features implemented other than running the binary in a docker container for convenience. If there's anything that should be added let me know.

**Comment by pataquets** [comment]
@tanji : I mean not just usage docs, but also clearly stating and linking which is the official AB in the docs pages about Docker. I seem to recall that the DH images weren't even mentioned anywhere.
Thank you.
