### ISSUE TITLE
KEY EXPIRED on Ubuntu

### ISSUE THREAD

**Issue by hobsRKM** [signal18/replication-manager#201]
I have created a repo file in ubuntu 16.04.
When i update it i get this errors in logs.
```
Ign:12 http://repo.signal18.io/deb $(lsb_release InRelease
Hit:13 http://ftp.cuhk.edu.hk/pub/Linux/ubuntu xenial-backports InRelease
Err:14 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 Release.gpg
  The following signatures were invalid: **KEYEXPIRED 1515625755**
**The repository 'http://repo.signal18.io/deb $(lsb_release Release' does not have a Release file.**
```
I tried even adding the key

> apt-key adv --recv-keys --keyserver keyserver.ubuntu.com FAE20E50

My signal18.list looks like this

> deb [arch=amd64] http://repo.signal18.io/deb $(lsb_release -sc) 2.0

**Comment by tanji** [comment]
Please replace `$(lsb-release -sc)` by `xenial`. The line in the manual cannot be copy pasted as is, it contains a shell built-in.
