### ISSUE TITLE
Cannot install on xenial

### ISSUE THREAD

**Issue by hobsRKM** [signal18/replication-manager#202]
I have added the source list and updated and hers the output for 2.1

> sudo apt-get update
Hit:1 http://repo.signal18.io/deb xenial InRelease
Reading package lists... Done

When i try to install as mentioned in docs,  it says this

> sudo apt-get install replicaton-manager
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package replicaton-manager

Also tried with version 2.0 get the same issue

> sudo apt-get update
Hit:1 http://repo.signal18.io/deb xenial InRelease
Get:2 http://repo.signal18.io/deb xenial/2.0 amd64 Packages [1,046 B]
Fetched 1,046 B in 1s (860 B/s)
Reading package lists... Done

> sudo apt-get install replicaton-manager
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package replicaton-manager

**Comment by tanji** [comment]
Hi,

it seems you've typed `replicaton-manager` instead of `replication-manager`.

Please refer to this page for instructions:

https://docs.signal18.io/installation/setup-instructions

I have updated it to make it more clear.
