### ISSUE TITLE
ERROR Get https://127.0.0.1:3000/api/clusters: dial tcp 127.0.0.1:3000: getsockopt: connection refuse

### ISSUE THREAD

**Issue by hobsRKM** [signal18/replication-manager#203]
I get this error when accesing console.How do i make it HTTP. 
ERROR Get https://127.0.0.1:3000/api/clusters: dial tcp 127.0.0.1:3000: getsockopt: connection refused 
FATA[2018-01-30T13:07:53+05:30]                                               error="Get https://127.0.0.1:3000/api/clusters: dial tcp 127.0.0.1:3000: getsockopt: connection refused"

**Comment by svaroqui** [comment]
Hello,

Thanks for reporting ! 

Do you have already something running on port 3000 ? 
What command do you use to get this error, replication-manager-cli console on same host ?

/svar

**Comment by hobsRKM** [comment]
I ran this command on the same host (localhost).And the port is not in use
I see that its trying to connect VIA HTTPS. How can i disable HTTPS and configuration in replication manager
> replication-manager-cli console
and got this
error

> ERROR Get https://127.0.0.1:3000/api/clusters: dial tcp 127.0.0.1:3000: getsockopt: connection refused
FATA[2018-01-30T13:07:53+05:30] error="Get https://127.0.0.1:3000/api/clusters: dial tcp 127.0.0.1:3000: getsockopt: connection refused"

**Comment by svaroqui** [comment]
OK i think it means that replication-manager deamon is not started !

**Comment by svaroqui** [comment]
did you make a configuration already

**Comment by svaroqui** [comment]
I have been working in 2.1 to enable startup without config but so far in 2.0 it's not yet possible

**Comment by hobsRKM** [comment]
Not recommended for beginners.Docs are not good enough to get started

**Comment by svaroqui** [comment]
Doc says to copy and adapt a config file , but agree with you ! that's why it's on 2.1 release roadmap

**Comment by hobsRKM** [comment]
Yes. It worked I had to create default config and rename existing examples to config.toml. Please update your docs to make it more simple
