### ISSUE TITLE
Could not find a slave in toplogy

### ISSUE THREAD

**Issue by hobsRKM** [signal18/replication-manager#204]
I have used a sample configuration file as mentioned in docs and it looks like this

Console screen shot https://ibb.co/jFVvTm

### > ## config.toml
> ## Example replication-manager configuration file
> 
> ## change the service file  in /etc/systemd/system/replication-manager.service to looks like :
> ## replication-manager-osc  --config=./etc/config.toml.sample  --cluster=Cluster01,Cluster_Test_2_Nodes monitor
> 
> [Cluster_Haproxy_MasterSlave]
> title = "ClusterTestMasterSlave"
> 
> db-servers-hosts = "127.0.0.1,203.129.219.198"
> db-servers-prefered-master = "127.0.0.1:3306"
> db-servers-credential = "root:casioctk230"
> db-servers-connect-timeout = 1
> 
> replication-credential = "root:test"
> 
> haproxy = true
> haproxy-write-port = 3303
> haproxy-read-port = 3302
> 
> [Default]
> # monitoring-datadir = "/var/lib/replication-manager"
> # monitoring-sharedir = "/usr/share/replication-manager"
> 
> ## Timeout in seconds between consecutive monitoring
> 
> # monitoring-ticker = 2
> 
> #########
> ## LOG ##
> #########
> 
> # log-file = "/var/log/replication-manager.log"
> verbose = true
> 
> ##############
> ## TOPOLOGY ##
> ##############
> 
> # replication-multi-master = false
> # replication-multi-tier-slave = false
> 
> ##############
> ## FAILOVER ##
> ##############
> 
> # failover-mode = "manual"
> # failover-pre-script = ""
> # failover-post-script = ""
> 
> ## Slaves will re enter with read-only
> 
> # failover-readonly-state = true
> # failover-event-scheduler = false
> # failover-event-status = false
> 
> ## Failover after N failures detection
> 
> # failover-falsepositive-ping-counter = 5
> 
> ## Cancel failover if already N failover
> ## Cancel failover if last failover was N seconds before
> ## Cancel failover in semi-sync when one slave is not in sync
> ## Cancel failover if one slave receive master heartbeat
> ## Cancel failover when replication delay is more than N seconds
> 
> # failover-limit = 0
> # failover-time-limit = 0
> # failover-at-sync = false
> # failover-max-slave-delay = 30
> # failover-restart-unsafe = false
> 
> # failover-falsepositive-heartbeat = true
> # failover-falsepositive-heartbeat-timeout = 3
> # failover-falsepositive-maxscale = false
> # failover-falsepositive-maxscale-timeout = 14
> # failover-falsepositive-external = false
> # failover-falsepositive-external-port = 80
> 
> ################
> ## SWITCHOVER ##
> ################
> 
> ## In switchover Wait N milliseconds before killing long running transactions
> ## Cancel switchover if transaction running more than N seconds
> ## Cancel switchover if write query running more than N seconds
> ## Cancel switchover if one of the slaves is not synced based on GTID equality
> 
> # switchover-wait-kill = 5000
> # switchover-wait-trx = 10
> # switchover-wait-write-query = 10
> # switchover-at-equal-gtid = false
> # switchover-at-sync = false
> # switchover-max-slave-delay = 30
> 
> ############
> ## REJOIN ##
> ############
> 
> # autorejoin = true
> # autorejoin-script = ""
> # autorejoin-semisync = true
> # autorejoin-backup-binlog = true
> # autorejoin-flashback = false
> # autorejoin-mysqldump = false
> 
> ####################
> ## CHECKS & FORCE ##
> ####################
> 
> # check-replication-filters = true
> # check-binlog-filters = true
> # check-replication-state = true
> 
> # force-slave-heartbeat= false
> # force-slave-heartbeat-retry = 5
> # force-slave-heartbeat-time = 3
> # force-slave-gtid-mode = false
> # force-slave-semisync = false
> # force-slave-failover-readonly-state = false
> # force-binlog-row = false
> # force-binlog-annotate = false
> # force-binlog-slowqueries = false
> # force-binlog-compress = false
> # force-binlog-checksum = false
> # force-inmemory-binlog-cache-size = false
> # force-disk-relaylog-size-limit = false
> # force-disk-relaylog-size-limit-size = 1000000000
> # force-sync-binlog = false
> # force-sync-innodb = false
> 
> ##############
> ## MAXSCALE ##
> ##############
> 
> ## for 2 nodes cluster maxscale can be driven by replication manager
> 
> # maxscale = false
> # maxscale-binlog = false
> # maxscale-servers = "192.168.0.201"
> # maxscale-port = 4003
> # maxscale-user = "admin"
> # maxscale-pass = "mariadb"
> 
> ## When true replication manager drive maxscale server state
> ## Not required unless multiple maxscale or release does not support detect_stale_slave
> 
> # maxscale-disable-monitor = false
> 
> ## maxinfo|maxadmin
> 
> # maxscale-get-info-method = "maxadmin"
> # maxscale-maxinfo-port = 4002
> 
> # maxscale-write-port = 4007
> # maxscale-read-port = 4008
> # maxscale-read-write-port = 4006
> # maxscale-binlog-port = 4000
> 
> #############
> ## HAPROXY ##
> #############
> 
> ## Wrapper mode unless maxscale or proxysql required to be located with replication-manager
> 
> # haproxy = false
> # haproxy-binary-path = "/usr/sbin/haproxy"
> 
> ## Read write traffic
> ## Read only load balance least connection traffic
> # haproxy-write-port = 3306
> # haproxy-read-port = 3307
> 
> ####################
> ## SHARDING PROXY ##
> ####################
> 
> # mdbshardproxy = false
> # mdbshardproxy-hosts = "127.0.0.1:3306"
> # mdbshardproxy-user = "root:mariadb"
> 
> #################
> ## ARBITRATION ##
> #################
> 
> # arbitration-external = false
> # arbitration-external-secret = "13787932529099014144"
> # arbitration-external-hosts = "88.191.151.84:80"
> # arbitration-peer-hosts ="127.0.0.1:10002"
> 
> ## Unique value on each replication-manager
> 
> # arbitration-external-unique-id = 0
> 
> ##########
> ## HTTP ##
> ##########
> 
> http-server = true
> http-bind-address = "0.0.0.0"
> # http-port = "10001"
> # http-auth = false
> # http-session-lifetime =   3600
> # http-bootstrap-button = false
> 
> #########
> ## API ##
> #########
> 
> # api-credential = "admin:repman"
> # api-port = "3000"
> 
> ############
> ## ALERTS ##
> ############
> 
> # mail-from = "replication-manager@localhost"
> # mail-smtp-addr = "localhost:25"
> # mail-to = "replication-manager@signal18.io"
> 
> ##########
> # STATS ##
> ##########
> 
> graphite-metrics = true
> # graphite-carbon-host = "127.0.0.1"
> # graphite-carbon-port = 2003
> #graphite-embedded = true
> # graphite-carbon-api-port = 10002
> # graphite-carbon-server-port = 10003
> # graphite-carbon-link-port = 7002
> # graphite-carbon-pickle-port = 2004
> # graphite-carbon-pprof-port = 7007

But even though adding as preferred master its not taking as master.

**Comment by svaroqui** [comment]
re,

First 
According to the image replication manager can not reach the database 203.129.219.198 with the user and password you gave , any firewall issue or correct password definition . 

root:casioctk230 should be the same in both node as most user as well a replicate should identical copy of the master anyway ! 

please make sure: 
db-servers-prefered-master = "127.0.0.1:3306"
can be found in 
db-servers-hosts = "127.0.0.1,203.129.219.198"

that's not the case so far 

of change db-servers-hosts to  "127.0.0.1:3306,203.129.219.198:3306"
or 
prefered-master to 127.0.0.1

also from the conf make sure 
replication-credential = "root:test" is correct looks strange to have 2 roor user with different password. I don't have a dedicated replication-user please set it the same as 
db-servers-credential = "root:casioctk230"


tx stéphane

**Comment by hobsRKM** [comment]
@svaroqui 
I corrected and now its working, But still it says no master or slave topology even though i have specified preferd master;
Screen shot: https://ibb.co/cqeGm6

Also i get error saying no replication user defined.

New config

> [Default]
title = "ClusterTest"
db-servers-hosts = "127.0.0.1:3306,203.129.219.198:3306"
db-servers-credential = "root:samepass"
replication-credential = "root:samepass"
db-servers-prefered-master="127.0.0.1:3306"
failover-mode = "manual"

**Comment by svaroqui** [comment]
Expected with no master or slave
