### ISSUE TITLE
Could not set enable for event on new master

### ISSUE THREAD

**Issue by boris-ragulin** [signal18/replication-manager#205]
Hi again,

It seems that failover-event-status is not working when event definer looks like admin@%. It works ok if definer is for example root@localhost.
I have the following config:
failover-event-scheduler = false
failover-event-status = true

Log:
```
2018/01/30 14:03:49 [cluster_maxscale_masterslave] INFO  - Set ENABLE for event table1 test_event on new master
2018/01/30 14:03:49 [cluster_maxscale_masterslave] ERROR - Could not Set ENABLE for event table1 test_event on new master
```
It seems that query has errors:
```
ALTER DEFINER=admin@% EVENT test_event enable;
```
And the following is working ok:
```
ALTER DEFINER='admin@%' EVENT test_event enable;
```

**Comment by tanji** [comment]
Could you give me the result of the following query?

`SELECT db as Db, name as Name, definer as Definer, status+0  AS Status FROM mysql.event`

Thanks in advance.

**Comment by boris-ragulin** [comment]
From the master after switchover:
```
+---------------+---------------------------------+----------+--------+
| Db            | Name                            | Definer  | Status |
+---------------+---------------------------------+----------+--------+
| actionmq_data | reap_deleted_messages_event     | sqitch@% |      3 |
| actionmq_data | update_next_timestamp_event     | sqitch@% |      3 |
| actionmq_data | aggregate_stats_log_event       | sqitch@% |      3 |
| actionmq_data | move_dead_messages_event        | sqitch@% |      3 |
| actionmq_data | expire_transient_messages_event | sqitch@% |      3 |
+---------------+---------------------------------+----------+--------+
```

**Comment by tanji** [comment]
ok, mysql is being dumb and not quoting wildcards in the table. I will make a small patch. Thanks for report!

**Comment by tanji** [comment]
Please test latest version in CI (should be available in 5 minutes or so)

**Comment by boris-ragulin** [comment]
Got the build from here - http://ci.signal18.io/mrm/builds/2.1/. It's working, thank you!

**Comment by boris-ragulin** [comment]
The event switching is working ok but there is a one small issue :)
'%@%@' is added to the definer at each switchover.
'sqitch@%' --- 1st switchover ---> 'sqitch@%@%@' --- 2nd ---> 'sqitch@%@%@%@%@%'

**Comment by tanji** [comment]
Indeed! I will look ASAP.

**Comment by tanji** [comment]
Fixed and tested, please wait for next build in a few minutes.
The issue was that actually, if you do `ALTER DEFINER='admin@%'` , it assumes that `admin@%` is the username part. user and host need to be quoted independently.
Thanks for reporting!
