### ISSUE TITLE
No master topolgy or slave defined

### ISSUE THREAD

**Issue by hobsRKM** [signal18/replication-manager#206]
Says no master or slave topology even though i have specified preferd master;
Screen shot: https://ibb.co/cqeGm6

New config

> [Default]
title = "ClusterTest"
db-servers-hosts = "127.0.0.1:3306,203.129.219.198:3306"
db-servers-credential = "root:samepass"
replication-credential = "root:samepass"
db-servers-prefered-master="127.0.0.1:3306"
failover-mode = "manual"

**Comment by svaroqui** [comment]
Hi 

That  is expected ! 

You can run replication-manager on top of an existing cluster and it should work , It's possible to bootstrap the replication using the cli . 

replication-manager-cli bootstrap

I don't like the can't found priviledges error this tell us something is wrong in user table . 
Can you send select user , host , password from mysql.user ; 

Thanks

**Comment by hobsRKM** [comment]
@svaroqui if a master goes down, then slave is switched as master.
If the failed master is up again, the master is not rejoined it still remains in failed state.
I have to restart replication manager everytime to get it work.
is there any config that i need to add so that it is rejoined and becomes master.

**Comment by svaroqui** [comment]
You need to use one or multiple proxy to alway direct traffic to the master or the old master will diverge and will need to be rejoined via  full dataset transfert ! 

You can enable mysqldump rejoin  , we plan more advance rejoining method in 2.1 and i use some ZFS sbapshot in the pro release

**Comment by svaroqui** [comment]
hobsRKM , 

You need to pick one of the supported proxy or DNS ( proxysql - maxscale for layer 7 or haproxy for layer 4 or consul DNS) , and route your database traffic to it  best practice is to use a non super privileges user for the db traffic), also for testing it's ok but it is needed to split the replication-manager and proxies from the databases boxes, or you get no ha at all  !
