### ISSUE TITLE
 Could not connect to MaxScale: Incorrect maxscale protocol negotiation

### ISSUE THREAD

**Issue by hobsRKM** [signal18/replication-manager#207]
I get this error. I Have setup maxscale.
How do i connect to maxscale?
 **Master user 'root'@'ubuntu' is not defined on replication candidate 203.129.219.198:3306**
heres the toml file

> [Default]
title = "ClusterTest"
db-servers-hosts = "127.0.0.1:3306,203.129.219.198:3306"
db-servers-credential = "root:casioctk230"
replication-credential = "root:casioctk230"
db-servers-prefered-master="203.129.219.198:3306"
failover-mode = "auto"
failover-at-sync = true
switchover-at-sync = true
autorejoin = true
autorejoin-flashback=true
maxscale = true
maxscale-monitor = true
maxscale-maxinfo-port = 3306
#maxscale-get-info-method = "maxadmin"
maxscale-servers = "203.129.219.198,127.0.0.1"
maxscale-port = 3306
maxscale-user = "root"
maxscale-pass = "pass"
maxscale-write-port = 4007
maxscale-read-port = 4008
maxscale-read-write-port = 4006
maxscale-binlog = false
maxscale-binlog-port = 3305
[arbitrator]

title = "arbitrator"
arbitrator-bind-address = "0.0.0.0:10001"
arbitrator-driver = "mysql"

**Comment by svaroqui** [comment]
re,
arbitrator as nothing to do until you  are using multiple replication-manager  , maxscale is not required to be define in replication-manager configuration  , wih  it is defined using the maxscale-xxx options that's for helping to speed up master discovery and gather some statistics from maxscale ! 

/svar

**Comment by hobsRKM** [comment]
Thanks for your clearence.  
@svaroqui
If i want my application to point to single IP for database then on failover i need to modify Ip in my application to.Is there a way where application still points to the same IP but behind proxy the data is routed? So does this mean i have to use HA proxy? is it best suited for replication manager?

**Comment by svaroqui** [comment]
Yes all the proxies we do  support are suited for that you just point the database traffic to them and they will follow to the helected master , haproxy isr the most simple to deploy but can't split write and read , you slave will just be used when  promoted as master

**Comment by hobsRKM** [comment]
@svaroqui thanks. Will try out with Ha proxy
