### ISSUE TITLE
http-auth = true url not logging in.

### ISSUE THREAD

**Issue by gabriel-a** [signal18/replication-manager#208]
Installed the latest version of replication manager:  (replication-manager-osc-2.0.0_rc1_45) with the following http config:

##########
##########

http-server = true
http-bind-address = "0.0.0.0"
http-auth = true
http-port = "80"

without http-auth=true the page logs normal with it, the page http://replication-manager/login and the login stays there stuck it does not login.

I did read here the disclaimer about the advice not to use it, but is this declaimer still applies? 

https://docs.signal18.io/usage/http 

The http dashboard is an angularjs application, it has no protected access for now use creativity to restrict access to it. Some login protection using http-auth = true can be enable and use the database password giving in the replication-manager config file but it is reported to leak memory when a browser is still connected and constantly refresh the display. We advice not to used it but to protect via a web proxying authentication instead.

Should we use the nginx or apache proxy? or this is a bug from us?

**Comment by svaroqui** [comment]
Hi Gabriel, 

Sorry for the silence here , yes that feature is deprecated until we use the JWT API to secure Auth 

Using the API is secure , using the http can't be unless you would like the password to transit into the network ! 

The plan is to go with more multi tenant  cluster grants and users roles but that's a work in progress 

Thanks for opening closing the ticket

**Comment by gabriel-a** [comment]
@svaroqui I did notice that reading in the code, now we went with the basic authentication and for the API we are using secure dmz without any functionality. 

Sorry was few days working outside the office but now I'm back to my testing habits. 

Cheers & Thanks for the great work,
Gabriel

**Comment by svaroqui** [comment]
Excellent , note that in 2.1 i have unified API and HTTP code and the web call same URL as the API so now need an angular guru to just rewrite each GET with  API PORT using JWT Token exchange, 

If you know one angular guru that can help , it would be welcome as it's not  our prefered cop off tea:)

**Comment by gabriel-a** [comment]
I can help with that, its angular 1.4 as i see so its pretty simple to add some interceptor. 

I just need to know how to run the whole application on my mac specially go... do you have any read me?

**Comment by svaroqui** [comment]
Re,

I'm on osx as well so pretty simple as we are using glide to get all dependency in one command 
https://docs.signal18.io/contribute/build
Please reach me on skype svaroqui if you need more

tx
/svar
