### ISSUE TITLE
Client code does not lookup in config.toml for api-port and may be password 

### ISSUE THREAD

**Issue by hobsRKM** [signal18/replication-manager#209]
I have installed replication manager on fresh machine using debian method OSC version
I created config.toml
Server starts fine.
Accesing console gives error
**INFO[2018-02-01T11:06:35+05:30] ERROR Get https://127.0.0.1:3000/api/clusters: EOF 
FATA[2018-02-01T11:06:35+05:30]                                               error="Get https://127.0.0.1:3000/api/clusters: EOF"**

 ```
# config.toml
# Example replication-manager configuration file

# change the service file  in /etc/systemd/system/replication-manager.service to looks like :
# replication-manager  --config=./etc/config.toml.sample  --cluster=Cluster01,Cluster_Test_2_Nodes monitor
[arbitrator]
db-servers-hosts = "203.129.219.198:3306"
db-servers-credential = "pass"
title = "arbitrator"
arbitrator-bind-address = "0.0.0.0:10001"
arbitrator-driver = "mysql"
```

Event minimal configuration doesnt work from docs
```
`[Default]
title = "ClusterTest"
db-servers-hosts = "203.129.219.198:3306,127.0.0.1:3306"
db-servers-credential = "pass"
replication-credential = "pass"
failover-mode = "manual"`
```

Does replication manager always listen to port 3000?? WHere do i change this port if i  have to??

**Comment by svaroqui** [comment]
HI hobsRKM,

Thanks for trying replication-manager, 

Most of the time when this happen it mean the server daemon is not correctly started ! 

Can you check: ps aux | grep repli 

And confirm the process is started ?  

You can start the server by hand : replication-manager-osc monitor 
 
Can you please report the log, 

yes e the port and password of the API can be changed, but i'm not sure that the client can read the new value from config to get the new port, you will have to pass it as parameter at every client command.

To see all options available  use replication-manager-osc monitor --help  !  

is "pass" in the config just a value to hide the real credential ?
Because credential should be the database user in format  "user:pass"

/stéphane

**Comment by hobsRKM** [comment]
3000 is already being used. How can i change it. Can you just give me an example. Tried help coudnt get detailed info on changing port.
```
INFO[2018-02-01T12:11:27+05:30] replication-manager started in daemon mode    version=2.0.0-rc1
INFO[2018-02-01T12:11:27+05:30] No existing password encryption scheme        error="Key file does not exist"
INFO[2018-02-01T12:11:27+05:30] Loading database TLS certificates             cluster=arbitrator
INFO[2018-02-01T12:11:27+05:30] Don't Have database TLS certificates          cluster=arbitrator
ERRO[2018-02-01T12:11:27+05:30] No replication user/pair specified            cluster=arbitrator
ERRO[2018-02-01T12:11:27+05:30] Failed to validate config: No replication user/pair specified  cluster=arbitrator
INFO[2018-02-01T12:11:27+05:30] Failover in interactive mode                  cluster=arbitrator
INFO[2018-02-01T12:11:27+05:30] Loading 0 proxies                             cluster=arbitrator
WARN[2018-02-01T12:11:27+05:30] All cluster db servers down                   cluster=arbitrator code=ERR00021 status=OPENED type=state
WARN[2018-02-01T12:11:27+05:30] Could not find a slave in topology            cluster=arbitrator code=ERR00010 status=OPENED type=state
WARN[2018-02-01T12:11:27+05:30] Could not find a master in topology           cluster=arbitrator code=ERR00012 status=OPENED type=state
ERRO[2018-02-01T12:11:27+05:30] JWT API can't start: listen tcp 0.0.0.0:3000: bind: address already in use 
INFO[2018-02-01T12:11:27+05:30] JWT API listening on 0.0.0.0:3000   
```

**Comment by svaroqui** [comment]
./replication-manager-osc  monitor --help |grep api 
      --api-bind string                                    Rest API bind ip (default "0.0.0.0")
      --api-credential string                              Rest API user:password (default "admin:repman")
      --api-port string                                    Rest API listen port (default "3000")
      --graphite-carbon-api-port int                       Graphite Carbon API port (default 10002)

**Comment by hobsRKM** [comment]
This works. But client cant read from config as u said.This is disadvantage as some users might want replication manager run on different port and have config read it.

**Comment by svaroqui** [comment]
Thanks for reporting,

i have patched the API to use port 10005 as default everywhere 
like this security policyy will range from 10001 to 10005

/svar

**Comment by hobsRKM** [comment]
How do i apply the patch?

**Comment by svaroqui** [comment]
We have to backport to 2.0 first 
CI build is taking place here http://ci.signal18.io/mrm/builds/

I'll tell you when backport is done

**Comment by svaroqui** [comment]
Last build for 2.0 should be in CI  now
