### ISSUE TITLE
Frontend not loading after upgrade.

### ISSUE THREAD

**Issue by gabriel-a** [signal18/replication-manager#210]
After upgrade to: replication-manager-osc-2.0.0_rc2_17_gdb82-1.x86_64

The website is not loading:
`jquery.ba-bbq.min.js:18 Uncaught TypeError: Cannot read property 'msie' of undefined
    at jquery.ba-bbq.min.js:18
    at jquery.ba-bbq.min.js:18
(anonymous) @ jquery.ba-bbq.min.js:18
(anonymous) @ jquery.ba-bbq.min.js:18
dashboard.js:26 Uncaught SyntaxError: Unexpected token <<
angular.min.js:6 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.10/$injector/modulerr?p0=dashboard&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.4.10%2F%24injector%2Fnomod%3Fp0%3Ddashboard%0A%20%20%20%20at%20http%3A%2F%2Fblaarkop.dev.ripe.net%2Fstatic%2Fvendor%2Fangular.min.js%3A6%3A417%0A%20%20%20%20at%20http%3A%2F%2Fblaarkop.dev.ripe.net%2Fstatic%2Fvendor%2Fangular.min.js%3A24%3A186%0A%20%20%20%20at%20b%20(http%3A%2F%2Fblaarkop.dev.ripe.net%2Fstatic%2Fvendor%2Fangular.min.js%3A23%3A252)%0A%20%20%20%20at%20http%3A%2F%2Fblaarkop.dev.ripe.net%2Fstatic%2Fvendor%2Fangular.min.js%3A23%3A495%0A%20%20%20%20at%20http%3A%2F%2Fblaarkop.dev.ripe.net%2Fstatic%2Fvendor%2Fangular.min.js%3A38%3A237%0A%20%20%20%20at%20p%20(http%3A%2F%2Fblaarkop.dev.ripe.net%2Fstatic%2Fvendor%2Fangular.min.js%3A7%3A355)%0A%20%20%20%20at%20g%20(http%3A%2F%2Fblaarkop.dev.ripe.net%2Fstatic%2Fvendor%2Fangular.min.js%3A38%3A85)%0A%20%20%20%20at%20db%20(http%3A%2F%2Fblaarkop.dev.ripe.net%2Fstatic%2Fvendor%2Fangular.min.js%3A41%3A368)%0A%20%20%20%20at%20c%20(http%3A%2F%2Fblaarkop.dev.ripe.net%2Fstatic%2Fvendor%2Fangular.min.js%3A19%3A463)%0A%20%20%20%20at%20yc%20(http%3A%2F%2Fblaarkop.dev.ripe.net%2Fstatic%2Fvendor%2Fangular.min.js%3A20%3A274)
    at angular.min.js:6
    at angular.min.js:39
    at p (angular.min.js:7)
    at g (angular.min.js:38)
    at db (angular.min.js:41)
    at c (angular.min.js:19)
    at yc (angular.min.js:20)
    at de (angular.min.js:19)
    at HTMLDocument.<anonymous> (angular.min.js:299)
    at j (jquery-2.1.1.min.js:2)
(anonymous) @ angular.min.js:6
(anonymous) @ angular.min.js:39
p @ angular.min.js:7
g @ angular.min.js:38
db @ angular.min.js:41
c @ angular.min.js:19
yc @ angular.min.js:20
de @ angular.min.js:19
(anonymous) @ angular.min.js:299
j @ jquery-2.1.1.min.js:2
fireWith @ jquery-2.1.1.min.js:2
ready @ jquery-2.1.1.min.js:2
I @ jquery-2.1.1.min.js:2`

I deleted the cache and open from different browsers but the page just loads light grey backround and thats it.

Does anyone have the same issue?

**Comment by svaroqui** [comment]
Yep are you using the rpm depot ?

**Comment by tanji** [comment]
Please upgrade to 2.0.0-rc2-23
http://ci.signal18.io/mrm/builds/2.0/

**Comment by svaroqui** [comment]
i fixed it for debian but not for redhat or centos depot, but there is an intermediare commit in 2.0.0-rc2-23 that is very verbose 

Wait i remove verbosity and will update the depot

**Comment by gabriel-a** [comment]
svar yes im using the rpm depot on centos 7.

**Comment by svaroqui** [comment]
We found intresting scenario at a at a client using many many lock tables and prefered master where failover failed and picking a late slave , i'm currently fixing that , i let you know when  i'm pushing the fix today in centos depot

**Comment by svaroqui** [comment]
Ok you should be good to go now

**Comment by gabriel-a** [comment]
The update fixed it.
