### ISSUE TITLE
Strange Failover issue 

### ISSUE THREAD

**Issue by gabriel-a** [signal18/replication-manager#211]
After upgrading to the latest version, I have master1, master2 and 3 slaves under.

Testing switchover works fine, but the moment I turn off master1 and i click on failover I receive this error:

```
2018/02/14 16:57:45	ERROR	No candidates found
2018/02/14 16:57:45	INFO	Election matrice: [ { "URL": "master2.mariadb.test:3306", "Indice": 0, "Pos": 2592, "Seq": 1220085, "Prefered": false, "Ignoredconf": false, "Ignoredrelay": false, "Ignoredmultimaster": false, "Ignoredreplication": true, "Weight": 0 }, { "URL": "slave1.mariadb.test:3306", "Indice": 1, "Pos": 2592, "Seq": 1220085, "Prefered": false, "Ignoredconf": true, "Ignoredrelay": false, "Ignoredmultimaster": false, "Ignoredreplication": false, "Weight": 0 }, { "URL": "slave2.mariadb.test:3306", "Indice": 2, "Pos": 2592, "Seq": 1220085, "Prefered": false, "Ignoredconf": true, "Ignoredrelay": false, "Ignoredmultimaster": false, "Ignoredreplication": false, "Weight": 0 }, { "URL": "slave3.mariadb.test:3306", "Indice": 3, "Pos": 2592, "Seq": 1220085, "Prefered": false, "Ignoredconf": true, "Ignoredrelay": false, "Ignoredmultimaster": false, "Ignoredreplication": false, "Weight": 0 } ]
2018/02/14 16:57:45	INFO	Electing a new master
2018/02/14 16:57:45	INFO	------------------------
2018/02/14 16:57:45	INFO	Starting master failover
2018/02/14 16:57:45	INFO	------------------------
2018/02/14 16:57:41	ALERT	Server master1.mariadb.test:3306 state changed from Suspect to Failed
2018/02/14 16:57:41	INFO	Declaring master as failed
2018/02/14 16:57:41	INFO	Master Failure detected! Retry 5/5
2018/02/14 16:57:39	INFO	Master Failure detected! Retry 4/5
2018/02/14 16:57:37	INFO	Master Failure detected! Retry 3/5
2018/02/14 16:57:35	INFO	Master Failure detected! Retry 2/5
```

The configuration is:
```
[DEV_CLUSTER]
title = "DevCluster"
failover-mode = "manual"
db-servers-hosts = "master1.mariadb.test:3306,master2.mariadb.test:3306,slave1.mariadb.test:3306,slave2.mariadb.test:3306,slave3.mariadb.test:3306"
db-servers-prefered-master = "master1.mariadb.test:3306"
db-servers-ignored-hosts = "slave1.mariadb.test:3306,slave2.mariadb.test:3306,slave3.mariadb.test:3306"
db-servers-credential = "user:pass"
replication-credential = "ruser:rpass"
test = false
verbose = true

[Default]

# LOG
# ---

working-directory = "/var/lib/replication-manager"
share-directory = "/usr/share/replication-manager"

logfile = "/var/log/replication-manager.log"
verbose = true

# TOPOLOGY
# --------

multimaster = false
multi-tier-slave = false
maxscale-binlog = false
```

Not so sure if it's a new bug?

**Comment by svaroqui** [comment]
Hi could be or not 

[
{
"URL":"master2.mariadb.test:3306",
"Indice":0,
"Pos":2592,
"Seq":1220085,
"Prefered":false,
"Ignoredconf":false,
"Ignoredrelay":false,
"Ignoredmultimaster":false,
"Ignoredreplication":true,
"Weight":0
},
{
"URL":"slave1.mariadb.test:3306",
"Indice":1,
"Pos":2592,
"Seq":1220085,
"Prefered":false,
"Ignoredconf":true,
"Ignoredrelay":false,
"Ignoredmultimaster":false,
"Ignoredreplication":false,
"Weight":0
},
{
"URL":"slave2.mariadb.test:3306",
"Indice":2,
"Pos":2592,
"Seq":1220085,
"Prefered":false,
"Ignoredconf":true,
"Ignoredrelay":false,
"Ignoredmultimaster":false,
"Ignoredreplication":false,
"Weight":0
},
{
"URL":"slave3.mariadb.test:3306",
"Indice":3,
"Pos":2592,
"Seq":1220085,
"Prefered":false,
"Ignoredconf":true,
"Ignoredrelay":false,
"Ignoredmultimaster":false,
"Ignoredreplication":false,
"Weight":0
}
]

the only possible master is "Ignoredreplication":true,

Witch means that something is blocking it regarding replication , may be late or not semi sync

You should have more hint  in the warnings tab can you send those warnings to us ? 

Rds

**Comment by svaroqui** [comment]
I see can please use last release , indeed that was a bug i fixed 20 minutes after i told you ok to go

**Comment by gabriel-a** [comment]
Is the latest release pushed on Centos repo? or should i install a special one?

**Comment by svaroqui** [comment]
Yes i hope if the build process worked !  

the bug was stupid i change it soon after with repo update
https://github.com/signal18/replication-manager/commits/2.0
You have been unlucky to get the unfixed release that stayed only 20 minutes !

**Comment by gabriel-a** [comment]
@svaroqui Thanks, the latest build fixed it.
