### ISSUE TITLE
RESOLV ERR00021 : All cluster db servers down

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#224]
OS : CentOS 7.4
192.168.30.73 : MariaDB-10.2.14 (Master)
192.168.30.74 : MariaDB-10.2.14 (Slave)
192.168.30.75 : MRM ( replication-manager-osc-2.0.0_11_gc365-1.x86_64.rpm )
MRM config.toml

### [Cluster1]
title = "Cluster1"

db-servers-hosts = "192.168.30.73:3306,192.168.30.74:3306"
db-servers-prefered-master = "192.168.30.73:3306"
db-servers-credential = "root:mariadb"
db-servers-connect-timeout = 1

replication-credential = "repl:repl"

#haproxy = true
#haproxy-write-port = 3303
#haproxy-read-port = 3302

[Default]
# monitoring-datadir = "/var/lib/replication-manager"
# monitoring-sharedir = "/usr/share/replication-manager"

## Timeout in seconds between consecutive monitoring

# monitoring-ticker = 2

#########
#########

# log-file = "/var/log/replication-manager.log"
verbose = true
log-level = 2

![20180404_122138](https://user-images.githubusercontent.com/33710188/38286936-f57c3dea-3802-11e8-961a-d1b23ffafe1c.png)

**Comment by tanji** [comment]
not a bug, from replication-manager standpoint the cluster hasn't been initialized and starts with state all down, then as you can see this state is going to RESOLV. There will be a fix not to print it in the next release though.
