### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nigel889** [signal18/replication-manager#226]
mysql5.6.32 gtid mode on
use replication-manager-pro-2.0.0_13_g373c-1.x86_64.rpm install 
/usr/bin/replication-manager-pro --version
INFO[2018-04-24T20:36:47+08:00] OpenSVC user account: replication-manager@localhost.localdomain 
INFO[2018-04-24T20:36:47+08:00] OpenSVC code application: Signal8633443116262958532 

start monitor:
/usr/bin/replication-manager-pro monitor

The output error:
1 ,ERROR: ciphertext too short
2, config: 
 hosts = "10.1.1.171:3306,10.1.1.172:3306,10.1.1.173:3306"
 user = "mrm:1c67ed32d596044189849a3d0aa0c4f489bdbc36bd6438c3a2"
rpluser = "rpl:6656d27ed0b8031de6833d901262b8da768be5b4a0c6"

  hint:
   Server [0]: URL: 10.1.1.171:3306 State: Suspect PrevState: Suspect
   Server [1]: URL: 10.1.1.172:3306 State: Suspect PrevState: Suspect
   Server [2]: URL: 10.1.1.173:3306 State: Suspect PrevState: Suspect
   State unconnected set by non-master rule on server 10.1.1.173:3306

3,last error:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa73f3e]

goroutine 15 [running]:
github.com/signal18/replication-manager/cluster.(*Cluster).electFailoverCandidate(0xc420400880, 0xc420075f30, 0x2, 0x2, 0xc420252800, 0x13)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/failover.go:827 +0x5ee
github.com/signal18/replication-manager/cluster.(*Cluster).isFoundCandidateMaster(0xc420400880, 0x0)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/cluster_chk.go:262 +0x55
github.com/signal18/replication-manager/cluster.(*Cluster).CheckFailed(0xc420400880)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/cluster_chk.go:35 +0x63
github.com/signal18/replication-manager/cluster.(*Cluster).Run(0xc420400880)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/cluster.go:205 +0x263
created by main.glob..func5
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/server.go:627 +0x834

**Comment by tanji** [comment]
Please upgrade to `2.0.0_15`, that contains a fix for this issue
