### ISSUE TITLE
panic: runtime error: index out of range with HAProxy and replication manager

### ISSUE THREAD

**Issue by Simon7352** [signal18/replication-manager#228]
Hi,
I have problems with HAProxy in local mode, mrm failed after a few seconds running but HAProxy still running.
Also mrm is ok when i don't use HAProxy.

here my conf and the config.toml

server with mrm and haproxy :
Ubuntu 16.04.2
HA-Proxy version 1.6.3
mrm version 2.0

servers with MariaDB master-slave:
Debian GNU/Linux 8.10 (jessie)
10.2.14-MariaDB

config.toml:

[Cluster_Haproxy_MasterSlave]
title = "ClusterTestMasterSlave"

db-servers-hosts = "#ip_master#,#ip_slave#"
db-servers-prefered-master = "#ip_master#"
db-servers-credential = "root:test"
db-servers-connect-timeout = 1

replication-credential = "test:test"

haproxy = true
haproxy-write-port = 3303
haproxy-read-port = 3302

[Default]

log-file = "/var/log/replication-manager/replication-manager.log"
verbose = true

http-server = true
http-bind-address = "0.0.0.0"

graphite-metrics = true

when starting :
 replication-manager-osc monitor --config=/etc/replication-manager/config.toml --verbose
INFO[2018-04-26T10:33:35+02:00] replication-manager started in daemon mode    version=2.0.0
INFO[2018-04-26T10:33:35+02:00] No existing password encryption scheme        error="Key file does not exist"
INFO[2018-04-26T10:33:35+02:00] Loading database TLS certificates             cluster=cluster_haproxy_masterslave
INFO[2018-04-26T10:33:35+02:00] Don't Have database TLS certificates          cluster=cluster_haproxy_masterslave
INFO[2018-04-26T10:33:35+02:00] New server monitored: #ip_master#               cluster=cluster_haproxy_masterslave
INFO[2018-04-26T10:33:35+02:00] New server monitored: #ip_slave#              cluster=cluster_haproxy_masterslave
INFO[2018-04-26T10:33:35+02:00] Failover in interactive mode                  cluster=cluster_haproxy_masterslave
INFO[2018-04-26T10:33:35+02:00] Loading 1 proxies                             cluster=cluster_haproxy_masterslave
INFO[2018-04-26T10:33:35+02:00] Loading HaProxy...                            cluster=cluster_haproxy_masterslave
INFO[2018-04-26T10:33:35+02:00] Starting http monitor on port 10001
INFO[2018-04-26T10:33:35+02:00] Set stateSlave from rejoin slave #ip_slave#   cluster=cluster_haproxy_masterslave
INFO[2018-04-26T10:33:35+02:00] Init Proxy Type: haproxy Host: 127.0.0.1 Port: 1988  cluster=cluster_haproxy_masterslave
INFO[2018-04-26T10:33:35+02:00] Haproxy loading haproxy config at /var/lib/replication-manager  cluster=cluster_haproxy_masterslave
INFO[2018-04-26T10:33:35+02:00] Haproxy did not find an haproxy config...initializing new config  cluster=cluster_haproxy_masterslave
WARN[2018-04-26T10:33:35+02:00] Haproxy pidfile exists at /var/lib/replication-manager/cluster_haproxy_masterslave-haproxy-private.pid, proceeding with reload config...  cluster=cluster_haproxy_masterslave
2018/04/26 10:33:35 Haproxy reloading /usr/sbin/haproxy -f /var/lib/replication-manager/cluster_haproxy_masterslave-haproxy.cfg -p /var/lib/replication-manager/cluster_haproxy_masterslave-haproxy-private.pid -D -sf 125347
WARN[2018-04-26T10:33:35+02:00] No GTID strict mode on slave #ip_slave#       cluster=cluster_haproxy_masterslave code=WARN0058 status=OPENED type=state
WARN[2018-04-26T10:33:35+02:00] No InnoDB durability on master #ip_master#      cluster=cluster_haproxy_masterslave code=WARN0064 status=OPENED type=state
WARN[2018-04-26T10:33:35+02:00] No compression of binlog on slave #ip_master#   cluster=cluster_haproxy_masterslave code=WARN0068 status=OPENED type=state
WARN[2018-04-26T10:33:35+02:00] No log-slave-updates on master #ip_master#      cluster=cluster_haproxy_masterslave code=WARN0069 status=OPENED type=state
WARN[2018-04-26T10:33:35+02:00] No semisync settings on slave #ip_slave#      cluster=cluster_haproxy_masterslave code=WARN0048 status=OPENED type=state
WARN[2018-04-26T10:33:35+02:00] No GTID replication on slave #ip_slave#       cluster=cluster_haproxy_masterslave code=WARN0051 status=OPENED type=state
WARN[2018-04-26T10:33:35+02:00] No compression of binlog on slave #ip_slave#  cluster=cluster_haproxy_masterslave code=WARN0056 status=OPENED type=state
WARN[2018-04-26T10:33:35+02:00] No Heartbeat <= 1s on master #ip_master#        cluster=cluster_haproxy_masterslave code=WARN0062 status=OPENED type=state
WARN[2018-04-26T10:33:35+02:00] No GTID strict mode on master #ip_master#       cluster=cluster_haproxy_masterslave code=WARN0070 status=OPENED type=state
WARN[2018-04-26T10:33:35+02:00] All cluster db servers down                   cluster=cluster_haproxy_masterslave code=ERR00021 status=OPENED type=state
WARN[2018-04-26T10:33:35+02:00] No log-slave-updates on slave #ip_slave#      cluster=cluster_haproxy_masterslave code=WARN0057 status=OPENED type=state
WARN[2018-04-26T10:33:35+02:00] No semisync settings on master #ip_master#      cluster=cluster_haproxy_masterslave code=WARN0060 status=OPENED type=state
panic: runtime error: index out of range

goroutine 28 [running]:
github.com/signal18/replication-manager/cluster.(*Cluster).refreshHaproxy(0xc420440000, 0xc4202c62a0, 0x0, 0x0)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/prx_haproxy.go:173 +0xffc
github.com/signal18/replication-manager/cluster.(*Cluster).refreshProxies(0xc420440000)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/prx.go:352 +0x276
github.com/signal18/replication-manager/cluster.(*Cluster).Run(0xc420440000)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/cluster.go:199 +0x3db
created by main.glob..func5
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/server.go:627 +0x834

Any idea ?

Thanks

**Comment by svaroqui** [comment]
Oups my bad , 

	} else if error != nil {
			cluster.LogPrintf(LvlErr, "Could not read csv from haproxy response")
		}
		if strings.Contains(strings.ToLower(line[0]), "write") {
			srv := cluster.GetServerFromURL(line[73])
			if srv != nil {

The code crash here 
srv := cluster.GetServerFromURL(line[73])

That is in the process of reading haproxy stats and reporting 
i may have to exit the function if previous read failed 
 
I 'll send you a patch

**Comment by svaroqui** [comment]
Did you notice you have strange server names or ip #ip_master#

**Comment by Simon7352** [comment]
Thanks svaroqui for the answer and the patch !

> Did you notice you have strange server names or ip #ip_master#

Yes, just changing them for publication, they are good in the original one.

**Comment by svaroqui** [comment]
Did you experimented with remote setup and external checks, i think is better method to manage haproxy  and the one we use in most cases : 

https://docs.signal18.io/configuration/routing-traffic/haproxy see remote instead

**Comment by svaroqui** [comment]
Can you paste me the result of url := "http://" + proxy.Host + ":" + proxy.Port + "/stats;csv" where host port is the haproxy

**Comment by Simon7352** [comment]
the result of url : 
# pxname,svname,qcur,qmax,scur,smax,slim,stot,bin,bout,dreq,dresp,ereq,econ,eresp,wretr,wredis,status,weight,act,bck,chkfail,chkdown,lastchg,downtime,qlimit,pid,iid,sid,throttle,lbtot,tracked,type,rate,rate_lim,rate_max,check_status,check_code,check_duration,hrsp_1xx,hrsp_2xx,hrsp_3xx,hrsp_4xx,hrsp_5xx,hrsp_other,hanafail,req_rate,req_rate_max,req_tot,cli_abrt,srv_abrt,comp_in,comp_out,comp_byp,comp_rsp,lastsess,last_chk,last_agt,qtime,ctime,rtime,ttime,
stats,FRONTEND,,,1,1,500000,6,72597,1510179,0,0,1,,,,,OPEN,,,,,,,,,1,2,0,,,,0,0,0,1,,,,0,174,0,1,0,0,,1,3,176,,,0,0,0,0,,,,,,,,
stats,BACKEND,0,0,0,0,50000,0,72597,1510179,0,0,,0,0,0,0,UP,0,0,0,,0,1576,0,,1,2,0,,0,,1,0,,0,,,,0,0,0,0,0,0,,,,,0,0,0,0,0,0,0,,,11844,0,1,599,
my_write_frontend,FRONTEND,,,0,0,500000,0,0,0,0,0,0,,,,,OPEN,,,,,,,,,1,3,0,,,,0,0,0,0,,,,,,,,,,,0,0,0,,,0,0,0,0,,,,,,,,
my_read_frontend,FRONTEND,,,0,0,500000,0,0,0,0,0,0,,,,,OPEN,,,,,,,,,1,4,0,,,,0,0,0,0,,,,,,,,,,,0,0,0,,,0,0,0,0,,,,,,,,
service_write,leader,0,0,0,0,2000,0,0,0,,0,,0,0,0,0,UP,100,1,0,0,0,1576,0,,1,5,1,,0,,2,0,,0,L4OK,,0,,,,,,,0,,,,0,0,,,,,-1,,,0,0,0,0,
service_write,BACKEND,0,0,0,0,50000,0,0,0,0,0,,0,0,0,0,UP,100,1,0,,0,1576,0,,1,5,0,,0,,1,0,,0,,,,,,,,,,,,,,0,0,0,0,0,0,-1,,,0,0,0,0,
service_read,2440140912896384478,0,0,0,0,2000,0,0,0,,0,,0,0,0,0,UP,100,1,0,0,0,1576,0,,1,6,1,,0,,2,0,,0,L4OK,,0,,,,,,,0,,,,0,0,,,,,-1,,,0,0,0,0,
service_read,18071757885279488880,0,0,0,0,2000,0,0,0,,0,,0,0,0,0,UP,100,1,0,0,0,1576,0,,1,6,2,,0,,2,0,,0,L4OK,,0,,,,,,,0,,,,0,0,,,,,-1,,,0,0,0,0,
service_read,BACKEND,0,0,0,0,50000,0,0,0,0,0,,0,0,0,0,UP,200,2,0,,0,1576,0,,1,6,0,,0,,1,0,,0,,,,,,,,,,,,,,0,0,0,0,0,0,-1,,,0,0,0,0,

**Comment by svaroqui** [comment]
Intresting you seems to have less fields than me reported in statistics, i use HA-Proxy version 1.7.2 or latest  in docker

**Comment by Simon7352** [comment]
I upgraded to HAProxy 1.7.10 it seems to work fine.

**Comment by svaroqui** [comment]
Thanks for reporting i push a fix anyway
