### ISSUE TITLE
Positional replication failed to rejoin a stop slave when master did not change

### ISSUE THREAD

**Issue by nigel889** [signal18/replication-manager#229]
used replication-manager-pro-2.0.0_16_g9ad9-1.x86_64.rpm installed 
percona5.6.32 gtid mode = off
 1master  --> 2 slave 
 master: 10.1.1.173
 slave1: 10.1.1.171
 slave2: 10.1.1.172
when I stop one of slaves mysql-server , logs output:
Server [0]: URL: 10.1.1.171:3306 State: Failed PrevState: Failed
then , I start this slave mysql-server, but  no start repliction (Slave_IO_Running: No, Slave_SQL_Running: No),
at this moment, outpup logs :
  2018/04/27 13:03:41 [test] INFO  - Found slave to rejoin 10.1.1.171:3306 slave was previously in state Failed replication io thread  {No %!s(bool=true)}, pointing currently to 10.1.1.173:3306
2018/04/27 13:03:41 [test] INFO  - Doing Positional switch of slave 10.1.1.171:3306
AND replication-m die , MRM service stop.

**Comment by svaroqui** [comment]
Thanks for using and reporting i will try to reproduce the issue and let you know !

**Comment by svaroqui** [comment]
OK i have reproduce and push a fixe can you try the last depot code or use http://ci.signal18.io/mrm/builds/

Alos we strongly advice usage of GTID or at least pseudo GTID !

**Comment by nigel889** [comment]
thx
