### ISSUE TITLE
how to called external script parameter?

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#233]
Using external script
--failover-pre-script = "/usr/local/bin/vip-down.sh"
--failover-post-script = "/usr/local/bin/vip-up.sh"

how to called Parameter Info in Script file.
oldMaster.Host, electedMaster.Host, oldMaster.Port, cluster.master.Port

vip-down.sh 
vip-up.sh

I don't know. how  to print Parameter?

**Comment by nigel889** [comment]
@nyxneuf how to called Parameter Info in Script file.
 oldMaster.Host, electedMaster.Host, oldMaster.Port, cluster.master.Port order 
bash shell example : $1 ,$2,$3 ,$4

**Comment by nyxneuf** [comment]
Thanks @nigel889  :)

**Comment by svaroqui** [comment]
Thanks @nigel889 :)
