### ISSUE TITLE
mysql read-only syntax error

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#240]
MRM Version : replication-manager-osc-2.0.1_1_gaea9-1.x86_64.rpm
DBMS : MySQL-5.7.22

Master/Slave MRM switch & fail over log message.

 2018/06/22 11:25:44 [cluster2] INFO  - --------------------------
2018/06/22 11:25:44 [cluster2] INFO  - Starting master switchover
2018/06/22 11:25:44 [cluster2] INFO  - --------------------------
2018/06/22 11:25:44 [cluster2] INFO  - Checking long running updates on master 10
2018/06/22 11:25:44 [cluster2] INFO  - Flushing tables on master 192.168.30.90:3306
2018/06/22 11:25:44 [cluster2] INFO  - Electing a new master
2018/06/22 11:25:44 [cluster2] INFO  - Slave 192.168.30.91:3306 has been elected as a new master
2018/06/22 11:25:44 [cluster2] INFO  - Set DISABLE ON SLAVE for event test e1 on old master
2018/06/22 11:25:44 [cluster2] INFO  - Disable Event Scheduler on old master
2018/06/22 11:25:44 [cluster2] INFO  - Could not set 192.168.30.90:3306 as read-only: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-read-only=1' at line 1
2018/06/22 11:25:44 [cluster2] INFO  - Rejecting updates on 192.168.30.90:3306 (old master)
2018/06/22 11:25:44 [cluster2] INFO  - Waiting for candidate master to apply relay log
2018/06/22 11:25:44 [cluster2] INFO  - Reading all relay logs on 192.168.30.91:3306
2018/06/22 11:25:44 [cluster2] DEBUG - Save replication status before electing
2018/06/22 11:25:44 [cluster2] DEBUG - master_log_file=mysql-bin.000006
2018/06/22 11:25:44 [cluster2] DEBUG - master_log_pos=12622
2018/06/22 11:25:44 [cluster2] DEBUG - Candidate was in sync=true
2018/06/22 11:25:44 [cluster2] INFO  - Stopping slave thread on new master
2018/06/22 11:25:44 [cluster2] INFO  - Resetting slave on new master and set read/write mode on
2018/06/22 11:25:44 [cluster2] ERROR - Could not set new master as read-write
2018/06/22 11:25:44 [cluster2] INFO  - Enable Event Scheduler on the new master
2018/06/22 11:25:44 [cluster2] INFO  - Set ENABLE for event test e1 on new master
2018/06/22 11:25:44 [cluster2] INFO  - Inject fake transaction on new master 192.168.30.91:3306
2018/06/22 11:25:44 [cluster2] INFO  - Switching old master as a slave
2018/06/22 11:25:44 [cluster2] INFO  - Doing MySQL GTID switch of the old master
2018/06/22 11:25:44 [cluster2] INFO  - Switching other slaves to the new master
2018/06/22 11:25:44 [cluster2] INFO  - Master switch on 192.168.30.91:3306 complete
2018/06/22 11:25:44 [cluster2] DEBUG - Purging crashes, all databses nodes up

PS. MariaDB-10.2 is No problem

**Comment by svaroqui** [comment]
Hi,

Replication-manger is trying to set super read only 

SET GLOBAL super-read-only=1 

Can you see if this command is working for your mysql release? 

Tx
Stéphane

**Comment by nyxneuf** [comment]
mysql-5.7.22 
 
SLAVE Command

mysql> show variables like '%read_only';
+-----------------------+-------+
| Variable_name         | Value |
+-----------------------+-------+
| innodb_read_only      | OFF   |
| read_only             | ON    |
| super_read_only       | OFF   |
| transaction_read_only | OFF   |
| tx_read_only          | OFF   |
+-----------------------+-------+
5 rows in set (0.00 sec)

mysql> set global super_read_only=1;
Query OK, 0 rows affected (0.00 sec)

mysql> show variables like '%read_only';
+-----------------------+-------+
| Variable_name         | Value |
+-----------------------+-------+
| innodb_read_only      | OFF   |
| read_only             | ON    |
| super_read_only       | ON    |
| transaction_read_only | OFF   |
| tx_read_only          | OFF   |
+-----------------------+-------+
5 rows in set (0.01 sec)

**Comment by svaroqui** [comment]
Re, Na Yum

Are you using same user that connect with replication-manger ?
Could possibly be a grant issue for that user 
/stéphane

**Comment by nyxneuf** [comment]
MRM config.toml
db-servers-credential = "mrm:mrm"

mysql -umrm -p

mysql> select * from mysql.user where user='mrm'\G
*************************** 1. row ***************************
                  Host: 192.168.30.%
                  User: mrm
           Select_priv: Y
           Insert_priv: Y
           Update_priv: Y
           Delete_priv: Y
           Create_priv: Y
             Drop_priv: Y
           Reload_priv: Y
         Shutdown_priv: Y
          Process_priv: Y
             File_priv: Y
            Grant_priv: N
       References_priv: Y
            Index_priv: Y
            Alter_priv: Y
          Show_db_priv: Y
            Super_priv: Y
 Create_tmp_table_priv: Y
      Lock_tables_priv: Y
          Execute_priv: Y
       Repl_slave_priv: Y
      Repl_client_priv: Y
      Create_view_priv: Y
        Show_view_priv: Y
   Create_routine_priv: Y
    Alter_routine_priv: Y
      Create_user_priv: Y
            Event_priv: Y
          Trigger_priv: Y
Create_tablespace_priv: Y
              ssl_type: 
            ssl_cipher: 
           x509_issuer: 
          x509_subject: 
         max_questions: 0
           max_updates: 0
       max_connections: 0
  max_user_connections: 0
                plugin: mysql_native_password
 authentication_string: *99CDDEA04A32EC0AE9F6DB59415E3F4CF7758458
      password_expired: N
 password_last_changed: 2018-02-13 13:46:48
     password_lifetime: NULL
        account_locked: N
1 row in set (0.00 sec)

mysql> show variables like '%read_only';
+-----------------------+-------+
| Variable_name         | Value |
+-----------------------+-------+
| innodb_read_only      | OFF   |
| read_only             | ON    |
| super_read_only       | OFF   |
| transaction_read_only | OFF   |
| tx_read_only          | OFF   |
+-----------------------+-------+
5 rows in set (0.01 sec)

mysql> set global super_read_only=1;
Query OK, 0 rows affected (0.00 sec)

mysql> show variables like '%read_only';
+-----------------------+-------+
| Variable_name         | Value |
+-----------------------+-------+
| innodb_read_only      | OFF   |
| read_only             | ON    |
| super_read_only       | ON    |
| transaction_read_only | OFF   |
| tx_read_only          | OFF   |
+-----------------------+-------+
5 rows in set (0.00 sec)

mysql>

**Comment by svaroqui** [comment]
Thanks for founding this i think i understand and we will push a fix in next commit !

**Comment by nyxneuf** [comment]
Thanks! :-)

**Comment by JeremyYu2018** [comment]
> Thanks for founding this i think i understand and we will push a fix in next commit !

<pre>
mysql> SET GLOBAL super-read-only=1;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-read-only=1' at line 1
mysql> 
mysql> 
mysql> \s
--------------
/opt/mysql/base/5.7.21/bin/mysql  Ver 14.14 Distrib 5.7.21, for linux-glibc2.12 (x86_64) using  EditLine wrapper

Connection id:          37234
Current database:
Current user:           root@localhost
SSL:                    Not in use
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server version:         5.7.21-log MySQL Community Server (GPL)
Protocol version:       10
Connection:             Localhost via UNIX socket
Server characterset:    utf8mb4
Db     characterset:    utf8mb4
Client characterset:    utf8
Conn.  characterset:    utf8
UNIX socket:            /opt/mysql/data/3306/mysqld.sock
Uptime:                 1 day 8 hours 16 min 43 sec

Threads: 4  Questions: 2251858  Slow queries: 8  Opens: 1110062  Flush tables: 17  Open tables: 21  Queries per second avg: 19.378
--------------

mysql> 
</pre>

I get the same error log when I manual failover  through web interface.
<pre>

2018/12/07 21:39:53	STATE	RESOLV ERR00039 : Skip slave in election db3:3306 repl not electable	
2018/12/07 21:39:53	STATE	RESOLV ERR00041 : Skip slave in election db3:3306 has more than 30 seconds of replication delay (116003)	
2018/12/07 21:39:51	STATE	OPENED ERR00039 : Skip slave in election db3:3306 repl not electable	
2018/12/07 21:39:51	STATE	OPENED ERR00041 : Skip slave in election db3:3306 has more than 30 seconds of replication delay (116003)	
2018/12/07 21:39:48	INFO	Master switch on db1:3306 complete	
2018/12/07 21:39:48	ERROR	Could not set slave db3:3306 as read-only, Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-read-only=1' at line 1	
2018/12/07 21:39:48	INFO	Change master on slave db3:3306	
2018/12/07 21:39:48	INFO	Waiting for slave db3:3306 to sync	
2018/12/07 21:39:48	INFO	Switching other slaves to the new master	
2018/12/07 21:39:48	INFO	Doing MySQL GTID switch of the old master	
2018/12/07 21:39:48	INFO	Switching old master as a slave	
2018/12/07 21:39:48	INFO	Inject fake transaction on new master db1:3306	
2018/12/07 21:39:48	ERROR	Could not set new master as read-write	
2018/12/07 21:39:48	INFO	Resetting slave on new master and set read/write mode on	
2018/12/07 21:39:48	INFO	Stopping slave thread on new master	
2018/12/07 21:39:48	INFO	Reading all relay logs on db1:3306	
2018/12/07 21:39:48	INFO	Waiting for candidate master to apply relay log	
2018/12/07 21:39:48	INFO	Rejecting updates on db2:3306 (old master)	
2018/12/07 21:39:48	INFO	Terminating all threads on db2:3306	
2018/12/07 21:39:48	INFO	Slave db1:3306 has been elected as a new master	
2018/12/07 21:39:48	INFO	Electing a new master	
2018/12/07 21:39:48	INFO	Flushing tables on master db2:3306	
2018/12/07 21:39:48	INFO	Checking long running updates on master 10	
2018/12/07 21:39:48	INFO	--------------------------	
2018/12/07 21:39:48	INFO	Starting master switchover	
2018/12/07 21:39:48	INFO	--------------------------	
2018/12/07 21:39:48	INFO	Signaling Switchover...	
2018/12/07 21:39:47	INFO	Rest API receive Switchover request	
</pre>
mysqld version is Oracle MySQL,  SO the 'read-only' issues has not been patched?  when it can be fixed? thanks so much,  I guess the way to solve this is to only change super-read-only  to super_read_only.  and  and  read_only variable works right.
