### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#243]
MRM : replication-manager-osc-2.0.1_2_gf6c1-1
MySQL-5.6.40 
Master : 192.168.30.90 / Slave : 192.168.30.91
OS : CentOS 7.5

1. Master MySQL STOP
2. Slave Fail-Over OK ( 192.168.30.91 - Master )
3. 192.168.30.90 MySQL START
4. replication-manager-osc Process Down

[system error] 

 Jul 04 11:12:31 mha3 replication-manager-osc[2866]: time="2018-07-04T11:12:31+09:00" level=debug msg="Failure detection handling for server 192.168.30.90:3307
Jul 04 11:12:31 mha3 replication-manager-osc[2866]: time="2018-07-04T11:12:31+09:00" level=debug msg="Failure detection of no master FailCount 7 MaxFail 5" cl
Jul 04 11:12:33 mha3 replication-manager-osc[2866]: time="2018-07-04T11:12:33+09:00" level=debug msg="Failure detection handling for server 192.168.30.90:3307
Jul 04 11:12:33 mha3 replication-manager-osc[2866]: time="2018-07-04T11:12:33+09:00" level=debug msg="Failure detection of no master FailCount 8 MaxFail 5" cl
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: time="2018-07-04T11:12:35+09:00" level=debug msg="State comparison reinitialized failed server 192.168.30.
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: time="2018-07-04T11:12:35+09:00" level=info msg="Setting Read Only on unconnected server 192.168.30.90:330
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: time="2018-07-04T11:12:35+09:00" level=info msg="Trying to rejoin restarted server 192.168.30.90:3307" clu
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: time="2018-07-04T11:12:35+09:00" level=info msg="Rejoining server 192.168.30.90:3307 to master 192.168.30.
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: time="2018-07-04T11:12:35+09:00" level=info msg="Backup ahead binlog events of previously failed server 19
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: time="2018-07-04T11:12:35+09:00" level=info msg="Backup /usr/share/replication-manager/amd64/linux/mysqlbi
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: time="2018-07-04T11:12:35+09:00" level=info msg="Rejoin master incremental 192.168.30.90:3307" cluster=clu
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: time="2018-07-04T11:12:35+09:00" level=info msg="Crash info &{192.168.30.90:3307 mysql-bin.000014 231 mysq
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: time="2018-07-04T11:12:35+09:00" level=info msg="Setting Read Only on rejoin incremental on server 192.168
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xab02f0]
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: goroutine 1857 [running]:
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: github.com/signal18/replication-manager/cluster.(*ServerMonitor).rejoinMasterSync(0xc420148600, 0xc4204f89
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/srv_rejoin.go:122 +0xa7
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: github.com/signal18/replication-manager/cluster.(*ServerMonitor).rejoinMasterIncremental(0xc420148600, 0xc
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/srv_rejoin.go:274 +0x21
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: github.com/signal18/replication-manager/cluster.(*ServerMonitor).RejoinMaster(0xc420148600, 0x0, 0x0)
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/srv_rejoin.go:59 +0x2b2
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: github.com/signal18/replication-manager/cluster.(*ServerMonitor).Ping(0xc420148600, 0xc42046cea0)
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/srv.go:324 +0x15a6
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: created by github.com/signal18/replication-manager/cluster.(*Cluster).TopologyDiscover
Jul 04 11:12:35 mha3 replication-manager-osc[2866]: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/topology.go:117 +0x1b1
Jul 04 11:12:35 mha3 systemd[1]: replication-manager.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 04 11:12:35 mha3 systemd[1]: Unit replication-manager.service entered failed state.
Jul 04 11:12:35 mha3 systemd[1]: replication-manager.service failed.

**Comment by svaroqui** [comment]
Hi nyxneuf,
 
Can you use the last release on ci http://ci.signal18.io/mrm/builds/2.0/ and tell me if that fix that issue!

Rds
/svar

**Comment by nyxneuf** [comment]
Apply the patch version ( replication-manager-osc-2.0.1_4_gf0b6-1 )

The same issue!  replication-manager-osc Process Down.

[Error]

Jul 06 10:23:40 mha3 replication-manager-osc[2219]: time="2018-07-06T10:23:40+09:00" level=debug msg="Failure detection handling for server 192.168.30.90:3307
Jul 06 10:23:40 mha3 replication-manager-osc[2219]: time="2018-07-06T10:23:40+09:00" level=debug msg="Failure detection of no master FailCount 12 MaxFail 5" c
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: time="2018-07-06T10:23:42+09:00" level=debug msg="State comparison reinitialized failed server 192.168.30.
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: time="2018-07-06T10:23:42+09:00" level=info msg="Setting Read Only on unconnected server 192.168.30.90:330
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: time="2018-07-06T10:23:42+09:00" level=info msg="Trying to rejoin restarted server 192.168.30.90:3307" clu
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: time="2018-07-06T10:23:42+09:00" level=info msg="Rejoining server 192.168.30.90:3307 to master 192.168.30.
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: time="2018-07-06T10:23:42+09:00" level=info msg="Backup ahead binlog events of previously failed server 19
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: time="2018-07-06T10:23:42+09:00" level=info msg="Backup /usr/share/replication-manager/amd64/linux/mysqlbi
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: time="2018-07-06T10:23:42+09:00" level=info msg="Rejoin master incremental 192.168.30.90:3307" cluster=clu
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: time="2018-07-06T10:23:42+09:00" level=info msg="Crash info &{192.168.30.90:3307 mysql-bin.000022 354 mysq
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: time="2018-07-06T10:23:42+09:00" level=info msg="Setting Read Only on rejoin incremental on server 192.168
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xab07f0]
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: goroutine 1506 [running]:
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: github.com/signal18/replication-manager/cluster.(*ServerMonitor).rejoinMasterSync(0xc420148600, 0xc4204e03
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/srv_rejoin.go:122 +0xa7
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: github.com/signal18/replication-manager/cluster.(*ServerMonitor).rejoinMasterIncremental(0xc420148600, 0xc
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/srv_rejoin.go:274 +0x21
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: github.com/signal18/replication-manager/cluster.(*ServerMonitor).RejoinMaster(0xc420148600, 0x0, 0x0)
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/srv_rejoin.go:59 +0x2b2
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: github.com/signal18/replication-manager/cluster.(*ServerMonitor).Ping(0xc420148600, 0xc420450290)
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/srv.go:324 +0x15a6
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: created by github.com/signal18/replication-manager/cluster.(*Cluster).TopologyDiscover
Jul 06 10:23:42 mha3 replication-manager-osc[2219]: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/topology.go:117 +0x1b1
Jul 06 10:23:42 mha3 systemd[1]: replication-manager.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 06 10:23:42 mha3 systemd[1]: Unit replication-manager.service entered failed state.
Jul 06 10:23:42 mha3 systemd[1]: replication-manager.service failed.

**Comment by nyxneuf** [comment]
And MySQL-5.7 and MariaDB-10.2.
The same scenario. No problem!
