### ISSUE TITLE
Slave state not accounted in consul dns in 2.0

### ISSUE THREAD

**Issue by tangweichun** [signal18/replication-manager#250]
Hi,this is my mysql replication topology:
master:
    192.168.56.11(node1)
slave:
    192.168.56.12(node2)
    192.168.56.13(node3)

When i excute "stop slave;" or "reset salve all;" on 192.168.56.13,it still can resolvethe wrong slave node though consul dns just like below:

[root]# nslookup read_mysql57.service.consul
Server:		192.168.56.100
Address:	192.168.56.100#53

Name:	read_mysql57.service.consul
Address: 192.168.56.12
Name:	read_mysql57.service.consul
Address: 192.168.56.13

[root]# while true;do mysql -h read_mysql57.service.consul -P 3307 -urepl -pmysql -e "select @@hostname,sleep(1);";done
Warning: Using a password on the command line interface can be insecure.
+--------------+----------+
| @@hostname   | sleep(1) |
+--------------+----------+
| node2 |        0 |
+--------------+----------+
Warning: Using a password on the command line interface can be insecure.
+--------------+----------+
| @@hostname   | sleep(1) |
+--------------+----------+
| node3 |        0 |
+--------------+----------+

I think when a slave node is stopped or out of replication topology,it should be kick out of consul dns

**Comment by scrambledb** [comment]
Hi, 

Thanks for testing , it should not,  can you provide me the log and version of replication-manager , i was looking at the code and found no evidence of the issue in the last code , i'd like to reproduce this !

**Comment by tangweichun** [comment]
Sorry, I didn't keep the log of replication-manager.

[root]# replication-manager-osc version
Replication Manager 2.0.1 for MariaDB 10.x and MySQL 5.7 Series
Full Version:  2.0.1-6-g0ff0d711
Build Time:  2018-07-26T10:02:38+0000

It's easy to reproduce:
step 1: "stop slave;" or "reset slave all;" on any of your slaves
step 2: nslookup read_xxx.service.consul'

then you'll see what i meet!

**Comment by svaroqui** [comment]
Ok it's fixed in 2.1 , i'll backport the fix in 2.0 thanks for reporting

**Comment by svaroqui** [comment]
Please reopen if not fixed
