### ISSUE TITLE
Documentation typo in External Scripts section

### ISSUE THREAD

**Issue by koleo** [signal18/replication-manager#255]
I noticed a documentation typo in _External Scripts_ section of replication-manager documentation:

https://docs.signal18.io/configuration/routing-traffic/external

The following option names are misspelled (no trailing "s"):

failover-post-scripts => failover-post-script
failover-pre-scripts => failover-pre-script

**Comment by tanji** [comment]
Hi thanks for the report, we will fix it in documentation repo
