### ISSUE TITLE
prevent a slave to be master

### ISSUE THREAD

**Issue by Slash663** [signal18/replication-manager#256]
Hello,

I have a configuration with 1 master and 2 slaves. 
One of the 2 slaves must remain slave, no matter what happens.

Is there any possibilities to prevent replication-manager to promote this slave as master?

Thank you

**Comment by nyxneuf** [comment]
https://docs.signal18.io/configuration/databases

db-servers-ignored-hosts

**Comment by svaroqui** [comment]
Hello for switchover yes there is a parameter but for failover it's impossible .
replication-manager have to pick the most up to date slave, but you can organise this slave delay via using delayed replication or by having the other slaves and master using semi sync and not using it on the one you wan't to ignore

**Comment by Slash663** [comment]
Thank you both for your answers!
