### ISSUE TITLE
启动报错，replication-manager ，Master not discovered, skipping failover check

### ISSUE THREAD

**Issue by deep-cds** [signal18/replication-manager#260]
hi，下面是报错信息 和日志
![image](https://user-images.githubusercontent.com/44251514/48976671-f0901c80-f0c5-11e8-8a04-4fe4b303a582.png)
[replication-manager.log](https://github.com/signal18/replication-manager/files/2612901/replication-manager.log)
![image](https://user-images.githubusercontent.com/44251514/48976695-4bc20f00-f0c6-11e8-969e-90eebdce3198.png)

下面是配置文件
[config.txt](https://github.com/signal18/replication-manager/files/2612904/config.txt)

请研发的同学帮忙解决一下，谢谢

**Comment by tanji** [comment]
嗨，看起来`replication-manager`无法连接到服务器。 是否有可以远程连接的root用户？

**Comment by deep-cds** [comment]
hi，有可以远程连接的mysql root用户
拓扑如下：
192.168.20.20   master
192.168.20.30  slave
192.168.20.40  slave
三个mysql 都是正常的，而且是可以正常连接的

**Comment by deep-cds** [comment]
请问有replication-manager搭建过程吗？ 可以分享一下参考吗？

**Comment by deep-cds** [comment]
报错日志描述：没有发现mysql  master 
![image](https://user-images.githubusercontent.com/44251514/48977137-867c7500-f0cf-11e8-8420-7ec02dd5ac4e.png)

**Comment by tanji** [comment]
You need to get `golang-1.10` at least, then you can build replication-manager with `make`:

```
git clone https://github.com/signal18/replication-manager.git ~/go/src/github.com/replication-manager
cd ~/go/src/github.com/replication-manager
make bin
```

I am not sure what causes your problem. It is the first time I see that; maybe my colleague will have an idea.

**Comment by tanji** [comment]
Yes, it seems like replication-manager cannot reach your master. The slaves are correctly detected, though. Which version of replication-manager are you using?

**Comment by deep-cds** [comment]
hi ，我是yum源安装replication-manager
![image](https://user-images.githubusercontent.com/44251514/48977273-479bee80-f0d2-11e8-93ea-e884eaa798d6.png)

**Comment by svaroqui** [comment]
Hi, created a regression in my last commit , i've push a fix it will be available soon sorry for the issue , but such change should make repman stronger in case of network glinch at the end !

**Comment by svaroqui** [comment]
Ok packages are in depot now

**Comment by deep-cds** [comment]
hi，日志报错： 说  No GTID strict mode on slave 192.168.20.30:3306  是什么意思，每一个mysql我都开启了gtid 功能了
![image](https://user-images.githubusercontent.com/44251514/48977657-79fd1a00-f0d9-11e8-8087-e27d76dbf09d.png)

![image](https://user-images.githubusercontent.com/44251514/48977675-cb0d0e00-f0d9-11e8-8892-cd43c0f1c11f.png)


请研发同学帮忙解决一下，谢谢

**Comment by svaroqui** [comment]
can yo please confirm 2.0.1-16-gd9ab879  is the version you are running now ?

**Comment by deep-cds** [comment]
![image](https://user-images.githubusercontent.com/44251514/48977738-428f6d00-f0db-11e8-891b-cd0da8cbaf61.png)
是的，我yum 安装的时候是安装这个版本的

**Comment by svaroqui** [comment]
I mean did you make sure it was restarted , install new package do not auto restart

**Comment by deep-cds** [comment]
我已经重新启动好多次了，还是这个报错，我安装最新的版本试试看。尝试安装 2.0.1.17版本试试。

**Comment by servomac** [comment]
I have same problem with 2.0 (today's build, using the docker image, 2.0.1-27-g7abda7ee), but with 2.1 works like charm.

I have uploaded an example scenario to reproduce the error to a simple repo https://github.com/servomac/replication-tests; If in the docker-compose you change the 2.1 tag by 2.0 and reproduce again the steps, you will be able to reproduce the error.
