### ISSUE TITLE
replication-manager软件自身是否具有高可用能力？

### ISSUE THREAD

**Issue by JeremyYu2018** [signal18/replication-manager#262]
### replication-manager软件自身是否具有高可用能力？ 
比如部署replication-manager多节点，多节之间使用Raft或者Paxos协议操持数据一致性，以实现软件自身的高可用。

**Comment by tanji** [comment]
Hi!
High Availability is obtained in active-passive mode through the `arbitrator` function. It uses a heartbeat mechanism to determine which node is primary and which node is standby.
I realize this function is not really well documented, I will check with my colleague and update this issue later.

**Comment by JeremyYu2018** [comment]
> Hi!
> High Availability is obtained in active-passive mode through the `arbitrator` function. It uses a heartbeat mechanism to determine which node is primary and which node is standby.
> I realize this function is not really well documented, I will check with my colleague and update this issue later.

tx
