### ISSUE TITLE
MySQL Replication Positional vs GTID Test Issue

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#265]
https://github.com/signal18/replication-manager/issues/254

I tested it more on the link above.

OS : CentOS 7.5
MySQL-5.7.24
MRM : replication-manager-osc-2.0.1_18_gb4ffd-1.x86_64
Topology : Master / Slave

Positional Replication AND autocommit=off 
No problem with position replication!!

GTID Replication AND autocommit=off
Problems Occur When Using GTID!!

**Comment by nyxneuf** [comment]
I Fonud it!!
It was a mysql bug.

https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-25.html#mysqld-5-7-25-bug
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-14.html#mysqld-8-0-14-bug

Replication: If autocommit was set to 0 for a replication slave or Group Replication group member where GTIDs were in use and super_read_only=ON was set, server shutdown was prevented by a transaction that did not complete. The transaction was attempting to save GTIDs to the mysql.gtid_executed table, but the update failed because super_read_only=ON was set. (With autocommit set to 1, the transaction would complete in this situation, and the mysql.gtid_executed table would instead be updated at server startup.) Now, the check for the super_read_only setting is skipped for this task, so the transaction is able to save the GTIDs to the mysql.gtid_executed table and complete regardless of the combination of super_read_only and autocommit settings. (Bug #28183718)

No problem after patching!! :)

**Comment by svaroqui** [comment]
Thanks , good catch i'll update the doc with the info
