### ISSUE TITLE
MariaDB set gtid_domain_id !=0, replication-manager 2.0 switchover question ?

### ISSUE THREAD

**Issue by sysdljr** [signal18/replication-manager#266]
Hi, @tanji @svaroqui 
     Long time no see,  we have some question , please help confirm, thanks.
    Today , we test replication-manager switchover in a master and a slave,  first, switchover is OK.
    after 3~4 times swithover,  occur some switch question,  there many info in log file: 
2019/01/13 18:33:01 [db_test] INFO  - Status IO_Pos:3-330803-4,2901-102182901-5, Slave_Pos:3-330803-3,2901-102182901-5
 ....

replication-manager-osc version
Replication Manager 2.0.1 for MariaDB 10.x and MySQL 5.7 Series
Full Version:  2.0.1-18-gb4ffd27f
Build Time:  2018-11-25T09:57:35+0000

MariaDB version:  10.2.18 server

master : 172.16.16.29  ( gtid_domain_id = 29)
slave:  172.16.16.3 (gtid_domain_id = 3)

if  modify gtid_domain_id = 0 (default) ,  all switchover execute normal, 
but after slave server , we use multi source replication, so we set gtid_domain_id !=0 ,  after set gtid_domain_id,   execute switchover , found some question above.

**Comment by tanji** [comment]
Hello @sysdljr Not sure if I understood your problem - is there any error with the switchover, other than the INFO message above?
Thanks in advance

**Comment by sysdljr** [comment]
Thank you reply
This my switchover test at below, please help confirm.

master: 172.16.16.29    gtid_domain_id = 0
slave:    172.16.16.3      gtid_domain_id  =3 

at slave 172.16.16.3 execute 
change master to master_host='172.16.16.29', master_port=3308, 
master_user='repl', master_password='123456', master_log_file= 'master-bin.000001' ,master_log_position=329;

stop slave; change master to master_use_gtid= slave_pos;  start slave;

master 172.16.16.29 execute 
insert into tb02 values(1,133);

 mrm web console:
![image](https://user-images.githubusercontent.com/17877603/51822852-7cb5fe80-2318-11e9-85b5-367559496b96.png)

First,  after click "switchover",   it is OK
![image](https://user-images.githubusercontent.com/17877603/51822970-dc140e80-2318-11e9-97c8-7a92c44ea297.png)

Then , at new master, exectue
insert into tb02 values(2,200);

![image](https://user-images.githubusercontent.com/17877603/51823105-5a70b080-2319-11e9-9b4f-d977f988ab19.png)

Second, after click "swithover", it is OK too.
![image](https://user-images.githubusercontent.com/17877603/51823192-a7548700-2319-11e9-9b13-2f2adf501f16.png)

Then ,  it not execute write on master, 
Third, forth,   after click "swithover",  all is OK.

Fifth,  again click "switchover",   it could not normal swithover. mrm web console show:
![image](https://user-images.githubusercontent.com/17877603/51823555-bbe54f00-231a-11e9-968d-1c8ebfce217f.png)

in error log:
2019/01/28 16:31:11 [db_test] INFO  - Rest API receive Switchover request
2019/01/28 16:31:13 [db_test] INFO  - Signaling Switchover...
2019/01/28 16:31:13 [db_test] INFO  - --------------------------
2019/01/28 16:31:13 [db_test] INFO  - Starting master switchover
2019/01/28 16:31:13 [db_test] INFO  - --------------------------
2019/01/28 16:31:13 [db_test] INFO  - Checking long running updates on master 10
2019/01/28 16:31:13 [db_test] INFO  - Flushing tables on master 172.16.16.29:3308
2019/01/28 16:31:13 [db_test] INFO  - Electing a new master
2019/01/28 16:31:13 [db_test] INFO  - Slave 172.16.16.3:3308 has been elected as a new master
2019/01/28 16:31:13 [db_test] INFO  - Terminating all threads on 172.16.16.29:3308
2019/01/28 16:31:13 [db_test] INFO  - Rejecting updates on 172.16.16.29:3308 (old master)
2019/01/28 16:31:13 [db_test] INFO  - Waiting for candidate master to apply relay log
2019/01/28 16:31:13 [db_test] INFO  - Reading all relay logs on 172.16.16.3:3308
2019/01/28 16:31:13 [db_test] INFO  - Status IO_Pos:29-102182901-1,0-102182901-2,3-330803-3, Slave_Pos:0-102182901-2,29-102182901-1
2019/01/28 16:31:14 [db_test] INFO  - Status IO_Pos:29-102182901-1,0-102182901-2,3-330803-3, Slave_Pos:0-102182901-2,29-102182901-1
2019/01/28 16:31:14 [db_test] INFO  - Status IO_Pos:29-102182901-1,0-102182901-2,3-330803-3, Slave_Pos:0-102182901-2,29-102182901-1
2019/01/28 16:31:15 [db_test] INFO  - Status IO_Pos:29-102182901-1,0-102182901-2,3-330803-3, Slave_Pos:0-102182901-2,29-102182901-1
2019/01/28 16:31:15 [db_test] INFO  - Status IO_Pos:29-102182901-1,0-102182901-2,3-330803-3, Slave_Pos:0-102182901-2,29-102182901-1
2019/01/28 16:31:16 [db_test] INFO  - Status IO_Pos:29-102182901-1,0-102182901-2,3-330803-3, Slave_Pos:0-102182901-2,29-102182901-1
2019/01/28 16:31:16 [db_test] INFO  - Status IO_Pos:29-102182901-1,0-102182901-2,3-330803-3, Slave_Pos:0-102182901-2,29-102182901-1
2019/01/28 16:31:17 [db_test] INFO  - Status IO_Pos:29-102182901-1,0-102182901-2,3-330803-3, Slave_Pos:0-102182901-2,29-102182901-1
2019/01/28 16:31:17 [db_test] INFO  - Status IO_Pos:29-102182901-1,0-102182901-2,3-330803-3, Slave_Pos:0-102182901-2,29-102182901-1
2019/01/28 16:31:18 [db_test] INFO  - Status IO_Pos:29-102182901-1,0-102182901-2,3-330803-3, Slave_Pos:0-102182901-2,29-102182901-1
2019/01/28 16:31:18 [db_test] INFO  - Status IO_Pos:29-102182901-1,0-102182901-2,3-330803-3, Slave_Pos:0-102182901-2,29-102182901-1
2019/01/28 16:31:19 [db_test] INFO  - Status IO_Pos:29-102182901-1,0-102182901-2,3-330803-3, Slave_Pos:0-102182901-2,29-102182901-1
2019/01/28 16:31:19 [db_test] INFO  - Status IO_Pos:29-102182901-1,0-102182901-2,3-330803-3, Slave_Pos:0-102182901-2,29-102182901-1
2019/01/28 16:31:20 [db_test] INFO  - Status IO_Pos:29-102182901-1,0-102182901-2,3-330803-3, Slave_Pos:0-102182901-2,29-102182901-1


#172.16.16.3 exectue 
MariaDB [dbtest]> show global variables like '%gtid%';   
+------------------------+-----------------------------------------+
| Variable_name          | Value                                   |
+------------------------+-----------------------------------------+
| gtid_binlog_pos        | 0-102182901-2,3-330803-3,29-102182901-1 |
| gtid_binlog_state      | 0-102182901-2,3-330803-3,29-102182901-1 |
**| gtid_current_pos       | 0-102182901-2,3-330803-3,29-102182901-1 |**
| gtid_domain_id         | 3                                       |
| gtid_ignore_duplicates | OFF                                     |
**| gtid_slave_pos         | 0-102182901-2,29-102182901-1            |**
| gtid_strict_mode       | OFF                                     |
| wsrep_gtid_domain_id   | 0                                       |
| wsrep_gtid_mode        | OFF                                     |


MariaDB [dbtest]> show all slaves status \G 
                  Master_Host: 172.16.16.29
                   ........
                   Using_Gtid:      Current_Pos
                  **Gtid_IO_Pos:     29-102182901-1,0-102182901-2,3-330803-3**
                  ..........
                  **Gtid_Slave_Pos: 0-102182901-2,3-330803-3,29-102182901-1**


 both master and slave,  if set gtid_domain_id = 0 ,  every switchover is OK .

if set gtid_domain_id !=0 ,  when execute swithover,  it always occur failed.

**Comment by tanji** [comment]
Pardon my question, but why do you use a different GTID Domain on the Master and the Slave? Is there any use to that?

**Comment by sysdljr** [comment]
@tanji Thank you reply.
Because we use multi soure replication and GTID,   172.16.16.29 and 172.16.16.3 only a group master/slave,   in fact,   it have six groups master and slave replicaiton to a group multi soure replication.   on multi source GTID replication ,  it must set different GTID Domain.
 
reference: https://mariadb.com/kb/en/library/gtid/#use-with-multi-source-replication-and-other-multi-master-setups

It show multi-domains Support Status is Alpha  in replication-manager's document ?
https://docs.signal18.io/architecture/topologies/multi-domains

**Comment by svaroqui** [comment]
replication-manger can monitor a single source and failover on it , i plan to implement child cluster to link multiple cluster via multi source but that's  a plan for 2.2
