### ISSUE TITLE
What is mean message

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#268]
OS : CentOS 7.5
DB : MySQL 5.7.25 
Master/Slave
replication-manager-osc-2.0.1_18_gb4ffd-1.x86_64

[replication-manager.log]
 
2019/02/19 20:05:43 [cluster3] ERROR - Preferred master is not included in the hosts option
2019/02/19 20:05:43 [cluster3] ERROR - Failed to validate config: Prefmaster option takes exactly one argument
2019/02/19 20:05:43 [cluster3] INFO  - Failover in interactive mode
2019/02/19 20:05:43 [cluster3] INFO  - Loading 0 proxies
2019/02/19 20:05:43 [cluster3] DEBUG - Master not discovered, skipping failover check
2019/02/19 20:05:43 [cluster3] STATE - OPENED ERR00021 : All cluster db servers down
2019/02/19 20:05:43 [cluster3] STATE - OPENED ERR00010 : Could not find a slave in topology
2019/02/19 20:05:43 [cluster3] STATE - OPENED ERR00012 : Could not find a master in topology
2019/02/19 20:05:45 [cluster3] DEBUG - Master not discovered, skipping failover check
2019/02/19 20:05:47 [cluster3] DEBUG - Master not discovered, skipping failover check
2019/02/19 20:05:49 [cluster3] DEBUG - Master not discovered, skipping failover check
2019/02/19 20:05:51 [cluster3] DEBUG - Master not discovered, skipping failover check
2019/02/19 20:05:53 [cluster3] DEBUG - Master not discovered, skipping failover check
2019/02/19 20:05:55 [cluster3] DEBUG - Master not discovered, skipping failover check
2019/02/19 20:05:57 [cluster3] DEBUG - Master not discovered, skipping failover check
2019/02/19 20:05:59 [cluster3] DEBUG - Master not discovered, skipping failover check
2019/02/19 20:06:01 [cluster3] DEBUG - Master not discovered, skipping failover check
2019/02/19 20:06:03 [cluster3] DEBUG - Master not discovered, skipping failover check
2019/02/19 20:06:05 [cluster3] DEBUG - Master not discovered, skipping failover check

**Comment by svaroqui** [comment]
Hi,
Preferered master can only take one server , the rest of the log says that no slaves point to any master so replication-manager have lost the cluster topology !

**Comment by nyxneuf** [comment]
Thanks! I understood. :)
