### ISSUE TITLE
use db port 10005 and replication-manager-cli console problem 

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#269]
We use DB Port 10005.
DB Server and relication-manager are the same server.

replication-manager-cli Command Problem!!

[root@db3 etc]# systemctl status replication-manager.service -l
● replication-manager.service - replication-manager open source
   Loaded: loaded (/etc/systemd/system/replication-manager.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-02-20 10:10:54 KST; 19min ago
 Main PID: 5436 (replication-man)
    Tasks: 10
   CGroup: /system.slice/replication-manager.service
           └─5436 /usr/bin/replication-manager-osc monitor

Feb 20 10:10:55 db03 replication-manager-osc[5436]: time="2019-02-20T10:10:55+09:00" level=info msg="New server monitored: 192.168.30.72:10005" cluster=cluster11
Feb 20 10:10:55 db03 replication-manager-osc[5436]: time="2019-02-20T10:10:55+09:00" level=info msg="Failover in interactive mode" cluster=cluster11
Feb 20 10:10:55 db03 replication-manager-osc[5436]: time="2019-02-20T10:10:55+09:00" level=info msg="Loading 0 proxies" cluster=cluster11
Feb 20 10:10:55 db03 replication-manager-osc[5436]: time="2019-02-20T10:10:55+09:00" level=info msg="Starting http monitor on port 10001"
Feb 20 10:10:55 db03 replication-manager-osc[5436]: time="2019-02-20T10:10:55+09:00" level=error msg="No master found from replication" cluster=cluster11
Feb 20 10:10:55 db03 replication-manager-osc[5436]: time="2019-02-20T10:10:55+09:00" level=debug msg="State unconnected set by non-master rule on server 192.168.30.71:10005" cluster=cluster11
Feb 20 10:10:55 db03 replication-manager-osc[5436]: time="2019-02-20T10:10:55+09:00" level=warning msg="All cluster db servers down" cluster=cluster11 code=ERR00021 status=OPENED type=state
Feb 20 10:10:55 db03 replication-manager-osc[5436]: time="2019-02-20T10:10:55+09:00" level=warning msg="No GTID replication on slave 192.168.30.72:10005" cluster=cluster11 code=WARN0051 status=OPENED type=state
Feb 20 10:10:55 db03 replication-manager-osc[5436]: time="2019-02-20T10:10:55+09:00" level=warning msg="No GTID strict mode on master 192.168.30.71:10005" cluster=cluster11 code=WARN0070 status=OPENED type=state
Feb 20 10:10:57 db03 replication-manager-osc[5436]: time="2019-02-20T10:10:57+09:00" level=info msg="All cluster db servers down" cluster=cluster11 code=ERR00021 status=RESOLV type=state
[root@db03 etc]# 
[root@db03 etc]# 
[root@db03 etc]# replication-manager-cli show
INFO[2019-02-20T10:30:59+09:00] ERROR Get https://127.0.0.1:10005/api/clusters: tls: first record does not look like a TLS handshake 
FATA[2019-02-20T10:30:59+09:00]                                               error="Get https://127.0.0.1:10005/api/clusters: tls: first record does not look like a TLS handshake"
[root@db03 etc]# replication-manager-cli console
INFO[2019-02-20T10:31:03+09:00] ERROR Get https://127.0.0.1:10005/api/clusters: tls: first record does not look like a TLS handshake 
FATA[2019-02-20T10:31:03+09:00]                                               error="Get https://127.0.0.1:10005/api/clusters: tls: first record does not look like a TLS handshake"

**Comment by tanji** [comment]
Please post your config. Replication-manager is trying to find a DB on port 10005, which is usually the replication-manager port. IMHO you've got those ports wrong in the config.

**Comment by nyxneuf** [comment]
Sorry! My mistake. I solved the problem.

# api-credential = "admin:repman"
api-port = "3000"

api-port enable. 

#replication-manager-cli console --port=3000

Thanks!!
