### ISSUE TITLE
replication-manager-osc password command issue!

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#270]
Hi~
Create encrypted passwords using!
Problems using special characters!

[test result]

[root@test etc]# replication-manager-osc password 1234
Encrypted password hash: 0d991eff85fea2b2f0e1b89e7dde98726e9b4046
[root@test etc]# 
[root@test etc]# replication-manager-osc password 12!34
-bash: !34: event not found
[root@test etc]# 
[root@test etc]# replication-manager-osc password 1234!
Encrypted password hash: c3fcb3633961b55b1e21590bcc546b0d0802096a6f
[root@test etc]# 
[root@test etc]# replication-manager-osc password !1234
-bash: !1234: event not found
[root@test etc]# 
[root@test etc]# replication-manager-osc password 1234&
[1] 2333
[root@test etc]# Encrypted password hash: fb2d2c9d8065b7f9f0c0b2431b20f706f94cbeed

[1]+  Done                    replication-manager-osc password 1234
[root@test etc]# replication-manager-osc password 12&34
[1] 2339
bash: 34: command not found...
[root@test etc]# Encrypted password hash: 411dd862db46d0cc0a4e6c6c77e95ae72ef6

[1]+  Done                    replication-manager-osc password 12
[root@test etc]# 
[root@test etc]# replication-manager-osc password 1234(
-bash: syntax error near unexpected token `('
[root@test etc]# 
[root@test etc]# replication-manager-osc password 1234)
-bash: syntax error near unexpected token `)'
[root@test etc]# 
[root@test etc]# replication-manager-osc password 12(34
-bash: syntax error near unexpected token `('
[root@test etc]# 
[root@test etc]# 
[root@test etc]# replication-manager-osc password "1234"
Encrypted password hash: 08fe89a2a10a94a900169d4f0925f7791ab169e1
[root@test etc]# 
[root@test etc]# replication-manager-osc password "1234
> 
> 
> ^C
[root@test etc]#

**Comment by tanji** [comment]
This is a shell (bash) issue, not replication-manager.
Read http://tldp.org/LDP/abs/html/special-chars.html
Use single quotes or escape your chars.
