### ISSUE TITLE
using Multi tier slave. db-servers-ignored-hosts warn message

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#271]
CentOS 7.3 / MySQL 5.7 
replication-manager-osc-2.0.1_18_gb4ffd-1.x86_64.rpm

[config.toml]

title = "cluster1"

db-servers-hosts = "192.168.30.70:3306,192.168.30.71:3306,192.168.30.72:3306"
db-servers-prefered-master = "192.168.30.70:3306"
db-servers-credential = "mrm:mrm"
db-servers-connect-timeout = 1

db-servers-ignored-hosts = "192.168.30.72:3306"

replication-credential = "repl:repl"

[Default]
monitoring-datadir = "/var/lib/replication-manager"
monitoring-sharedir = "/usr/share/replication-manager"

monitoring-write-heartbeat = 2

## Timeout in seconds between consecutive monitoring
monitoring-ticker = 2

#########
#########

log-file = "/var/log/replication-manager.log"
verbose = true
log-level = 2

##############
##############

replication-multi-master = false
replication-multi-tier-slave = true

----------------------------------------------------------------
replication-manager.log

%!(EXTRA string=192.168.30.72:3306)2019/02/28 17:24:38 [cluster1] WARN  - Slave is in ignored list
%!(EXTRA string=192.168.30.72:3306)2019/02/28 17:24:40 [cluster1] WARN  - Slave is in ignored list
%!(EXTRA string=192.168.30.72:3306)2019/02/28 17:24:42 [cluster1] WARN  - Slave is in ignored list
%!(EXTRA string=192.168.30.72:3306)2019/02/28 17:24:44 [cluster1] WARN  - Slave is in ignored list
%!(EXTRA string=192.168.30.72:3306)2019/02/28 17:24:46 [cluster1] WARN  - Slave is in ignored list
%!(EXTRA string=192.168.30.72:3306)2019/02/28 17:24:49 [cluster1] WARN  - Slave is in ignored list
%!(EXTRA string=192.168.30.72:3306)2019/02/28 17:24:51 [cluster1] WARN  - Slave is in ignored list
%!(EXTRA string=192.168.30.72:3306)2019/02/28 17:24:53 [cluster1] WARN  - Slave is in ignored list
%!(EXTRA string=192.168.30.72:3306)2019/02/28 17:24:55 [cluster1] WARN  - Slave is in ignored list

![20190228_172717](https://user-images.githubusercontent.com/33710188/53552386-91d3b680-3b7e-11e9-833b-7453bfaf66de.png)

**Comment by tanji** [comment]
Please set your `log-level` to 1, you are at `log-level` 2 which is debug mode and therefore can see a lot of unnecessary messages.
