### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by narcisbcn** [signal18/replication-manager#272]
When we provide a large host and ignore_servers variableon the configuration file (/etc/replication-manager/config.toml), we get a  _len out of range runtime error_

`panic: runtime error: makeslice: len out of range
goroutine 1 [running]:
github.com/signal18/replication-manager/termlog.NewTermLog(...)
	/home/tanj/go/src/github.com/signal18/replication-manager/termlog/termlog.go:30
main.glob..func15(0x139cdc0, 0xc42000d600, 0x0, 0x2)
	/home/tanj/go/src/github.com/signal18/replication-manager/repmgr.go:315 +0x18e
github.com/signal18/replication-manager/vendor/github.com/spf13/cobra.(*Command).execute(0x139cdc0, 0xc42000d460, 0x2, 0x2, 0x139cdc0, 0xc42000d460)
	/home/tanj/go/src/github.com/signal18/replication-manager/vendor/github.com/spf13/cobra/command.go:648 +0x237
github.com/signal18/replication-manager/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x139baa0, 0x11, 0xc4201d5f70, 0x40f5b4)
	/home/tanj/go/src/github.com/signal18/replication-manager/vendor/github.com/spf13/cobra/command.go:734 +0x2fe
github.com/signal18/replication-manager/vendor/github.com/spf13/cobra.(*Command).Execute(0x139baa0, 0xc4201d5f70, 0xb2b15d)
	/home/tanj/go/src/github.com/signal18/replication-manager/vendor/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
	/home/tanj/go/src/github.com/signal18/replication-manager/main.go:166 +0x31`

**Version:**
replication-manager-1.1.3-d51731e1.x86_64
OS: _Amazon Linux AMI release 2018.03_

**Comment by tanji** [comment]
Hello @narcisbcn! 
It is hard for us to recommend using 1.1.3 anymore, but it is certainly fixable.
Can you send me your config by email?
Thanks
