### ISSUE TITLE
ERROR - Could not set max_connections to 0 on demoted leader

### ISSUE THREAD

**Issue by lusor** [signal18/replication-manager#274]
Hi,

I justed tested replication manager on a simple master-slave setup with MariaDB 10.3 and switchovers are working fine.
However, there is always one error:

> ERROR - Could not set max_connections to 0 on demoted leader

According to the documention of [MariaDB](https://mariadb.com/kb/en/library/server-system-variables/#max_connections) and [MySQL](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_connections) the range of valid values for max_connections is 1 or 10 (in newest MariaDB versions).

In [cluster/srv.go](https://github.com/signal18/replication-manager/blob/e710cdfa1a0c4e6a3201de628979034d754a2f5a/cluster/srv.go#L610), however, it is tried to set it to 0.

A second issue seems to exist when [resetting max_connections](https://github.com/signal18/replication-manager/blob/2.0/cluster/failover.go#L473) after the switch, as maxConn doesn't seem to be defined there. However, I don't know go, so I could be mistaken and it's taken from [srv.go](https://github.com/signal18/replication-manager/blob/2.0/cluster/srv.go#L606).

Cheers

**Comment by svaroqui** [comment]
Many thanks for this report , the maxConn was indeed global to all servers but was store from server.freeze so it should only be saved once for the old master, so logic looks correct , i  patch the code in 2.1 to store this information in each server structure, what release of repman and MariaDB have such issue because i'm only getting a warning could it be special sql_mode that process warning as errors? 
  
```
Server version: 10.3.9-MariaDB-1:10.3.9+maria~bionic-log mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> set global max_connections=0; 
Query OK, 0 rows affected, 1 warning (0.000 sec)

MariaDB [(none)]> show warnings;
+---------+------+------------------------------------------------+
| Level   | Code | Message                                        |
+---------+------+------------------------------------------------+
| Warning | 1292 | Truncated incorrect max_connections value: '0' |
+---------+------+------------------------------------------------+
1 row in set (0.000 sec)

```
MariaDB [(none)]> show variables like 'max_connections'; 
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 10    |
+-----------------+-------+
1 row in set (0.001 sec)

**Comment by svaroqui** [comment]
I have added variables in commit 2.1 to control this 
switchover-decrease-max-conn default true
switchover-decrease-max-conn-value default 10 

Found in our ci the last binaries http://ci.signal18.io/mrm/builds/2.1/

**Comment by lusor** [comment]
In my environment, I get an error trying to set max_connections:
```
Server version: 10.3.12-MariaDB-1:10.3.12+maria~jessie-log mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql ((none))> set global max_connections = 0;
ERROR 1231 (42000): Variable 'max_connections' can't be set to the value of '0'
mysql ((none))> show global variables like 'max_connections';
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 500   |
+-----------------+-------+
1 row in set (0.001 sec)

mysql ((none))> show global variables like 'sql_mode';
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                                                                                                                                               |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| sql_mode      | REAL_AS_FLOAT,PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ONLY_FULL_GROUP_BY,ANSI,STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)
```
I also tested it with MariaDB 5.5 with the same behavior. sql_mode is set by:
`sql_mode = 'ANSI,TRADITIONAL,ONLY_FULL_GROUP_BY'`

[EDIT]
I'm using Replication Manager OSC 2.0.1-18-gb4ffd
[/EDIT]

**Comment by tanji** [comment]
@lusor yes that's expected, `sql_mode='TRADITIONAL'` produces this, as documented there:

https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_traditional

Thanks for your report!

**Comment by svaroqui** [comment]
The fix has been backported and our repository is updated please update and reopen if the bug still happens

**Comment by lusor** [comment]
Thanks for the quick fix, it's working fine
