### ISSUE TITLE
Detecting synchronous delay logic will lose data

### ISSUE THREAD

**Issue by thinkdb** [signal18/replication-manager#279]
[https://github.com/signal18/replication-manager/blob/2.0/cluster/srv.go#L661](https://github.com/signal18/replication-manager/blob/2.0/cluster/srv.go#L661)
`for ss.MasterLogFile != ss.RelayMasterLogFile && ss.ReadMasterLogPos == ss.ExecMasterLogPos {
			ss, err = dbhelper.GetSlaveStatus(server.Conn)
			if err != nil {
				return err
			}
			time.Sleep(500 * time.Millisecond)
		}`
if ss.MasterLogFile == ss.RelayMasterLogFile && ss.ReadMasterLogPos != ss.ExecMasterLogPos or if ss.MasterLogFile != ss.RelayMasterLogFile && ss.ReadMasterLogPos != ss.ExecMasterLogPos, then return nil. So this logic will lose data.

**Comment by svaroqui** [comment]
Thanks for founding this shame on me !

**Comment by svaroqui** [comment]
Thanks again is tested and fixed
