### ISSUE TITLE
MariaDB slave uses wrong GTID after switchover

### ISSUE THREAD

**Issue by jordan-nicholas** [signal18/replication-manager#282]
Hi,

I'm having an issue where my new slave is starting replication from the wrong point after switchover.  It looks like the switchover code allows writing to the new master before it gets the GTID start position for the new slave.  I have noticed this problem when a switchover is run on a busy server, and I've been able to recreate it on a test server.

https://github.com/signal18/replication-manager/blob/7abda7ee3f3fe6646a1f2de8d4d1229d6b015ca5/cluster/failover.go#L298-L331

In the above code, if I'm interpreting it correctly, replication manager sets the new master to Read/Write on line 298, then gets the GTID in the Refresh() method on line 331.  I have been able to do database inserts between these two events, which makes the new slave lose data.

My checkout is on commit 7abda7ee3f3fe6646a1f2de8d4d1229d6b015ca5
I'm using MariaDB version 10.1.38-MariaDB on CentOS 7

Thanks,

Jordan

**Comment by svaroqui** [comment]
Hi Jordan,

Thanks for reaching to us, would you answer few questions to better diagnostic the issue .
 
- Where is the extra write take place on the old master or on the new master ? 
- MariaDB does not have super_read_only, user having super read only or all priviledges are discourage for writing ?
- What routing solution do you use ?

tx
/svar

**Comment by jordan-nicholas** [comment]
Hi, thanks for the quick reply.

- The writes are taking place on the new master.

- The user that is writing the extra rows is not a super user.  I can see in the query log that the read_only variable is being respected.  Only the rows after "SET GLOBAL read_only=0" on the new master are being written.  They show up on the slave after the following query is run:

SELECT UPPER(Variable_name) AS variable_name, UPPER(Variable_Value) AS value FROM information_schema.global_variables

- We are not using a router, the connections are directly to the database.

**Comment by svaroqui** [comment]
Hi Jordan ,

Pushed a fix to 2.1  and tested switchover over sysbench. 

Can you test it before i can backport the fixe to 2.0 and report back ? 

Appreciate 
/svar

**Comment by jordan-nicholas** [comment]
I've tested the fix and it all looks good.  Thank you for getting out a fix so quickly!

**Comment by svaroqui** [comment]
Jordan , 

Thanks for using and giving a proper bug report, i also have fixe later on in 2.1  a smaller bug when one new slave is not yet provision and is failed, it was no possible to switchover in that case, i advice 2.1 for better alerting as it is a lot more resilient to cluster glitch i have tested it with some  very ugly network .

Also found in osc release our new database configurator that we use  to provision full clusters on opensvc cluster or can be used by ks8
