### ISSUE TITLE
quiet change read_only

### ISSUE THREAD

**Issue by leagueofsoups** [signal18/replication-manager#283]
Hi!
I have simple MASTER-SLAVE topology for tests. All my.cnf files have parameter read_only = ON (for master & slave). Replication manager set the read_only to 0 for master, but no writing log about this. What else action replication manager not logging? Why he do it quiet?

replication-manager-osc-2.0.1_28_gf072-1.x86_64

**Comment by svaroqui** [comment]
Hi, i have complain myself about this as well , and so changed this in 2.1 would you like to try it  ?

**Comment by svaroqui** [comment]
also checking 2.1 code it looks like with log level 3 on 
if cluster.Conf.LogLevel > 2 {
					cluster.LogPrintf(LvlDbg, "Server %s was set master as last non slave", sv.URL)
				}

I 'm changing code to get  a more log info in this specific case 
A dump thread need to be found on the server and  server should not be standalone  and no master detected yet: (case of new extra server added without replication definition)

**Comment by leagueofsoups** [comment]
https://github.com/signal18/replication-manager/commit/7464ab796cab3615eb450fe89e8095d5f040fd99

Thank you a lot. I will track change on branch 2.1, and will test it. A you have release plan? When will this release become stable?

**Comment by svaroqui** [comment]
It's stable , that's the one we are using for our private cloud for a year now, but we are so bad at Web UI design that i did not wan't to release it yet

**Comment by svaroqui** [comment]
in 2.1 there are slack reporting  , capture mode, enabling secured smtp, schema & processlist monitoring, and much more, and much higher quality of unstable network false positive alerting

**Comment by leagueofsoups** [comment]
Thanks for fast replies, I will testing 2.1.
