### ISSUE TITLE
multi-tier-slave issue

### ISSUE THREAD

**Issue by emanuel7L** [signal18/replication-manager#285]
First time using the software, I have 3 mysql setups (5.7), 1 of them is the master and the other 2 are slaves. When I use the Switchover function the old master is left as relay and one of the 2 slaves is switched to the new master; however, there's 1 of the 2 slaves that is switched to Maintenance and is never hooked to the new master.
All the tests were running the mysql server without any activity at all except for Replication Manager.
I'm using version 2.0.
Regards!

**Comment by svaroqui** [comment]
Hi please have a look at demo.signal18.io, 

admin/repman

Pick cluster  tst-3x-mysql57-gtid-maxscale  (may be you need to double click sometime with low latency network we have an issue to init cluster ) 

Proceed with switchover , you can as well put traffic with the cluster menu 

So far i can't reproduce what you are reporting may be your initial setup is not correct like show slave status on the master get already something .

**Comment by emanuel7L** [comment]
Hello @svaroqui thanks for the reply! I tried switching to master-slave topology and it seems to be working fine now. If anything, I was using replication-multi-tier-slave before.
