### ISSUE TITLE
percona mysql5.6 gtid or async

### ISSUE THREAD

**Issue by fuyuntaot115** [signal18/replication-manager#288]
Replication-manager supports gtid synchronization of percona mysql5.6, or async

**Comment by fuyuntaot115** [comment]
How to achieve replication-manager high availability

**Comment by svaroqui** [comment]
Replication topology is fixed and don't change if replication-manager is down so a single replication-manager on third datacenter already  is a valid solution , other then that we also have heartbeat with arbitrator of 2 replication-manager as describe in documentation

**Comment by svaroqui** [comment]
Need feedback
