### ISSUE TITLE
Support for mysql 8.0 issues

### ISSUE THREAD

**Issue by ghost** [signal18/replication-manager#289]
cat /var/log/replication-manager.log    
DEBU[2019-09-13T08:46:39Z] Could not get variables Error 1109: Unknown table 'GLOBAL_VARIABLES' in information_schema  cluster=db3310
ERRO[2019-09-13T08:46:39Z] Could not get variables Error 1109: Unknown table 'GLOBAL_VARIABLES' in information_schema  cluster=db3310
##########
This error,I think may need to modify the file,Remove the code **&& myver.Minor> = 7**
/dbhelper/dbhelper.go

func GetVariableSource(db *sqlx.DB) string {
	myver, _ := GetDBVersion(db)
	var source string
	if !myver.IsMariaDB() && myver.Major >= 5 **&& myver.Minor >= 7** {
		source = "performance_schema"
	} else {
		source = "information_schema"
	}
	return source
}

**Comment by svaroqui** [comment]
Hello wind-linux , 
Please found a fixe in 2.1 for testing  , i did not push inside our repo yet , found the build here http://ci.signal18.io/mrm/builds/2.1/, 

Do you need backport to 2.0 ? 
Let me know if the patch works for you ?

**Comment by ghost** [comment]
I use 2.1-dev, I will tell you the result after the test.

**Comment by ghost** [comment]
Hello svaroqui ,
http://ci.signal18.io/mrm/builds/2.1/
Currently observed can be used normally.

I open https://x.x.x.x:1005
ALERTS ^1 -> ERRORS
Info: **Could not get events on server x.x.x.x:3306**
This error is because of what?

**Comment by svaroqui** [comment]
Hello 
Currently fighting to bootstrap a simple MySQL 8.0 on docker by passing many configuration regression, can you report to me why this query  SELECT db as Db, name as Name, definer as Definer, status+0  AS Status FROM mysql.event stop working in 8.0. Could you provide similar query form the information_schema

**Comment by svaroqui** [comment]
After being able to bootstrap MySQL8.0 via orchestrators on our demo cluster , i run a some  test and now looks like MySQL 8.0 is now supported , thanks for pointing out issues with monitoring. I may continue to work on the topic vi support of cloning  for  old master rejoining

**Comment by spihiker** [comment]
666

**Comment by niduyi** [comment]
> 您好wind-linux，
> 请在2.1中找到一个测试用的修复程序，我还没有放入我们的仓库，在这里找到了构建http://ci.signal18.io/mrm/builds/2.1/，
> 
> 您需要反向移植到2.0吗？
> 让我知道该补丁对您有用吗？

Login password for RPM
