### ISSUE TITLE
4 nodes galera cluster problem replication-manager-osc

### ISSUE THREAD

**Issue by asterlab** [signal18/replication-manager#292]
I can connect and work with every and each of the 4 nodes through my proxysql, and replication is working.

`2019/12/13 13:10:56 [cluster_haproxy_multimaster] INFO  - New server monitored: 10.4.0.13:3306
2019/12/13 13:10:56 [cluster_haproxy_multimaster] INFO  - New server monitored: 10.4.0.14:3306
2019/12/13 13:10:56 [cluster_haproxy_multimaster] INFO  - New server monitored: 10.4.0.15:3306
2019/12/13 13:10:56 [cluster_haproxy_multimaster] INFO  - New server monitored: 10.4.0.16:3306
2019/12/13 13:10:56 [cluster_haproxy_multimaster] INFO  - Failover in automatic mode
2019/12/13 13:10:56 [cluster_haproxy_multimaster] INFO  - Loading 1 proxies
2019/12/13 13:10:56 [cluster_haproxy_multimaster] INFO  - Loading HaProxy...
2019/12/13 13:10:56 [cluster_haproxy_multimaster] STATE - OPENED ERR00010 : Could not find a slave in topology
2019/12/13 13:10:56 [cluster_haproxy_multimaster] STATE - OPENED ERR00012 : Could not find a master in topology
2019/12/13 13:10:56 [cluster_haproxy_multimaster] STATE - OPENED ERR00021 : All cluster db servers down
2019/12/13 13:11:04 [cluster_haproxy_multimaster] INFO  - Declaring server 10.4.0.13:3306 as failed
2019/12/13 13:11:04 [cluster_haproxy_multimaster] ALERT - Server 10.4.0.13:3306 state changed from Suspect to Failed
2019/12/13 13:11:04 [cluster_haproxy_multimaster] INFO  - Declaring server 10.4.0.16:3306 as failed
2019/12/13 13:11:04 [cluster_haproxy_multimaster] ALERT - Server 10.4.0.16:3306 state changed from Suspect to Failed
2019/12/13 13:11:04 [cluster_haproxy_multimaster] INFO  - Declaring server 10.4.0.15:3306 as failed
2019/12/13 13:11:04 [cluster_haproxy_multimaster] ALERT - Server 10.4.0.15:3306 state changed from Suspect to Failed
2019/12/13 13:11:04 [cluster_haproxy_multimaster] INFO  - Declaring server 10.4.0.14:3306 as failed
2019/12/13 13:11:04 [cluster_haproxy_multimaster] ALERT - Server 10.4.0.14:3306 state changed from Suspect to Failed
`

[config.toml.txt](https://github.com/signal18/replication-manager/files/3960987/config.toml.txt)

**Comment by asterlab** [comment]
also I'd love to know which parameters should I add to switch from haproxy to proxysql

**Comment by asterlab** [comment]
figured out a couple of things, changed my config.toml but problem persists
[config.toml.txt](https://github.com/signal18/replication-manager/files/3961383/config.toml.txt)

**Comment by asterlab** [comment]
figured out a couple of things changed my config.toml a bit but the problem persists it still cannot find a master nor the slaves .....
[config.toml.txt](https://github.com/signal18/replication-manager/files/3961387/config.toml.txt)

**Comment by asterlab** [comment]
tcp        0      0 10.4.0.13:4567          10.4.0.14:48784         ESTABLISHED 1361/mysqld         
tcp        0      0 10.4.0.13:3306          10.4.70.2:54484         ESTABLISHED 1361/mysqld         
tcp        0      0 10.4.0.13:4567          10.4.0.15:34256         ESTABLISHED 1361/mysqld         
tcp        0      0 10.4.0.13:4567          10.4.0.16:39724         ESTABLISHED 1361/mysqld         
tcp        0      0 10.4.0.13:3306          10.4.70.1:50442         ESTABLISHED 1361/mysqld 

tcp        0      0 10.4.0.14:4567          10.4.0.15:54732         ESTABLISHED 1403/mysqld         
tcp        0      0 10.4.0.14:3306          10.4.70.1:48416         ESTABLISHED 1403/mysqld         
tcp        0      0 10.4.0.14:48784         10.4.0.13:4567          ESTABLISHED 1403/mysqld         
tcp        0      0 10.4.0.14:49570         10.4.0.16:4567          ESTABLISHED 1403/mysqld         
tcp        0      0 10.4.0.14:3306          10.4.70.2:42566         ESTABLISHED 1403/mysqld 

tcp        0      0 10.4.0.15:3306          10.4.70.2:49506         ESTABLISHED 1383/mysqld         
tcp        0      0 10.4.0.15:54732         10.4.0.14:4567          ESTABLISHED 1383/mysqld         
tcp        0      0 10.4.0.15:34256         10.4.0.13:4567          ESTABLISHED 1383/mysqld         
tcp        0      0 10.4.0.15:3306          10.4.70.1:45876         ESTABLISHED 1383/mysqld         
tcp        0      0 10.4.0.15:39422         10.4.0.16:4567          ESTABLISHED 1383/mysqld

tcp        0      0 10.4.0.16:4567          10.4.0.14:49570         ESTABLISHED 821/mysqld          
tcp        0      0 10.4.0.16:3306          10.4.70.1:38726         ESTABLISHED 821/mysqld          
tcp        0      0 10.4.0.16:4567          10.4.0.15:39422         ESTABLISHED 821/mysqld          
tcp        0      0 10.4.0.16:3306          10.4.70.2:34644         ESTABLISHED 821/mysqld          
tcp        0      0 10.4.0.16:39724         10.4.0.13:4567          ESTABLISHED 821/mysqld

**Comment by asterlab** [comment]
on all nodes   : 
| wsrep_ready   | ON    |
| wsrep_cluster_size | 4     |

**Comment by svaroqui** [comment]
HI thanks for testing 
Can you please use 2.1 from depot

**Comment by asterlab** [comment]
I am using the debian repositories
cat /etc/apt/sources.list.d/signal18.list 
deb [arch=amd64] http://repo.signal18.io/deb buster 2.0
I can try to change 2.0 to 2.1

**Comment by svaroqui** [comment]
Thanks , 
Let me know what flavor and version of galera cluster are you using so that i can try to reproduce in the lab

**Comment by asterlab** [comment]
latest mariadb on debian buster

**Comment by asterlab** [comment]
I have reinstalled without galera

**Comment by svaroqui** [comment]
HI Renato i have push some fixes into galera monitor recently in 2.1 but they are not yet on depot only ci builds via packages, replication-manager was at some point working for it , but propably never restested since , as 100% of our supported client are master-slave so far. If you are intrested in deploying such solution please let me know that we proceed with more testing , our lab now have some galera clusters with proxysql support , tx for the feadback
