### ISSUE TITLE
Documentation error on option failover-readonly[-state]

### ISSUE THREAD

**Issue by koleo** [signal18/replication-manager#294]
Configuration option for Managing _read_only_ state after switchover/failover is not `failover-readonly` as stated in the [repman documentation](https://docs.signal18.io/configuration/failover) but `failover-readonly-state` (in repman v2.0 and v2.1 at least, as can be seen in [source code](https://github.com/signal18/replication-manager/blob/2.0/server.go#L145))

**Comment by svaroqui** [comment]
Thanks Fixed
