### ISSUE TITLE
replication-use-ssl setting is ignored

### ISSUE THREAD

**Issue by tafkam** [signal18/replication-manager#300]
The option replication-use-ssl = "true" is ignored when bootstrapping a multi-master cluster:

```
2020-06-04  0:35:45 185 [Warning] Access denied for user 'replicator'@'10.244.3.239' (using password: YES)

show slave status \G
...
Master_SSL_Allowed: No
...
```

Reconfiguring the replication ssl option manually just works:
```
stop slave;
change master to master_ssl=1;
start slave;
show slave status \G
...
Master_SSL_Allowed: Yes
...

2020-06-04  0:35:59 198 [Note] Start binlog_dump to slave_server(100), pos(, 4)
```

**Comment by svaroqui** [comment]
Hi Tafkam,
 
Thanks fo pointing that out , i revisited the code to use similar code for every architecture, and found a bad error reporting has well , 

The binaries are in CI but not yet in repos let us know if you need a repo update for testing ?
