### ISSUE TITLE
Mail alerting TLS issue

### ISSUE THREAD

**Issue by tafkam** [signal18/replication-manager#301]
I want to send email alerts with replication manager. I have an internal smtp server configured with a self-signed certificate and optional STARTTLS command. The mail server is configured to accept unencrypted smtp connections from the network.

replication-manager is using the smtp STARTTLS command and then rejects the smtp server certificate:

> level=error msg="Could not send mail alert: x509: certificate signed by unknown authority "

It should be possible to configure either the smtp server's CA certificate, or to not use STARTTLS while sending alert mails in replication manager.

**Comment by svaroqui** [comment]
Hi Tafkam, 

I have implemented something in my last commit can you test using last binaries on our ci and repport if it works for you using mail-smtp-tls-skip-verify = true

tx 
/stéphane

**Comment by tafkam** [comment]
The latest docker image seems to work with that option, thanks.
