### ISSUE TITLE
A Replication Manager Cluster

### ISSUE THREAD

**Issue by JoyceEmanuele** [signal18/replication-manager#302]
Hello,
I have a replication manager configuration for mariaDB's failover solution, but it ends up being a point of failure in my structure, because if the machine it is installed inactive for some reason, I end up losing the Replication manager, there would be some way to cluster the replication manager or something, to maintain availability?

**Comment by svaroqui** [comment]
Hi Emanuele, 

Sure there is many ways , the simplest way is to use a clustering solution like keepalived, corosync or opensvc  cluster to failover replication-manager based on a VIP an other one can be used with adding 2 replication-manager-pro and a the replication-manager-arb that stand for arbitrator. Each one of the   replication-manager will get an active or passive status given by the heartbeat or the arbitrator if peer node does not answer. The last way may be more dangerous as it tried to managed split brain of the database as well and a passive replication-manager may put read only flag if it detect multiple db in standalone one on his side of the network split and one coming from the arbitrator 

Hope it helps 
Stephane

**Comment by JoyceEmanuele** [comment]
Got it,
Thank you very much Stephane for the answer, it helped a lot !!

**Comment by msvendsen** [comment]
Hi guys!
Sorry for re-opening this 5 year old thread, but I have an additional question and didn't know where to ask.
If you use RepMan and Keepalived, in case active node goes down, Keepalived will then acticate VIP and start RepMan on another node. So far so good :-)
But what about data? Would we need to sync the directory defined in "monitoring-datadir" too?

Thanks!!
