### ISSUE TITLE
2.0.2 release for repository?

### ISSUE THREAD

**Issue by 0x6d617474** [signal18/replication-manager#303]
Greetings, 

I noticed that version 2.0.2 was released back in Apr, but it does not appear to be available through the repositories at http://repo.signal18.io

It looks like there are quite a few bugfixes that would be good to have applied, but since we are using the repository instead of building from source we don't have access to the latest release of 2.0.x

Is there a reason for withholding the release from the repository, or could it be added to the repo?

**Comment by tanji** [comment]
@0x6d617474 Hello, the repo is now updated.
