### ISSUE TITLE
M/S external script VIP And Slave Read Only Problem

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#307]
VM / CentOS7 / MariaDB 10.2
Master : 192.168.50.11
Slave : 192.168.50.12
VIP : 192.168.50.100
SRM : replication-manager-osc-2.0.2-1.x86_64.rpm

[Test Scenario]
**- current status**
- Master(192.168.50.11) - VIP up
   Slave(192.168.50.12) 

1. Master(192.168.50.11) - VM Network Off ( OS, MariaDB Alive And VIP up )
2. Fail-Over Complete
3. Old Master(192.168.50.11) -> New Master(192.168.50.12) - VIP up
4. Old Master(192.168.50.11) - VM Network On 

**after state**
Slave(192.168.50.11) - VIP up And Read Only OFF
Master(192.168.50.12) - VIP up And Read Only OFF

In case of master server network error!
(OS,MariaDB Alive And VIP Up state )

[Log]
2020/09/11 14:23:33 [cluster_db] INFO  - Master Failure detected! Retry 1/5
2020/09/11 14:23:33 [cluster_db] ALERT - Server 192.168.50.11:3306 state changed from Master to Suspect
2020/09/11 14:23:33 [cluster_db] STATE - RESOLV WARN0068 : No compression of binlog on slave 192.168.50.11:3306
2020/09/11 14:23:33 [cluster_db] STATE - RESOLV WARN0070 : No GTID strict mode on master 192.168.50.11:3306
2020/09/11 14:23:33 [cluster_db] STATE - OPENED ERR00016 : Master is unreachable but slaves are replicating
2020/09/11 14:23:36 [cluster_db] INFO  - Master Failure detected! Retry 2/5
2020/09/11 14:23:39 [cluster_db] INFO  - Master Failure detected! Retry 3/5
2020/09/11 14:23:42 [cluster_db] INFO  - Master Failure detected! Retry 4/5
2020/09/11 14:23:45 [cluster_db] INFO  - Master Failure detected! Retry 5/5
2020/09/11 14:23:45 [cluster_db] INFO  - Declaring master as failed
2020/09/11 14:23:45 [cluster_db] ALERT - Server 192.168.50.11:3306 state changed from Suspect to Failed
2020/09/11 14:23:48 [cluster_db] INFO  - ------------------------
2020/09/11 14:23:48 [cluster_db] INFO  - Starting master failover
2020/09/11 14:23:48 [cluster_db] INFO  - ------------------------
2020/09/11 14:23:48 [cluster_db] INFO  - Electing a new master
2020/09/11 14:23:48 [cluster_db] INFO  - Election matrice: [
	{
		"URL": "192.168.50.12:3306",
		"Indice": 0,
		"Pos": 262115,
		"Seq": 236,
		"Prefered": false,
		"Ignoredconf": false,
		"Ignoredrelay": false,
		"Ignoredmultimaster": false,
		"Ignoredreplication": false,
		"Weight": 0
	}
] 
2020/09/11 14:23:48 [cluster_db] INFO  - Slave 192.168.50.12:3306 has been elected as a new master
2020/09/11 14:23:48 [cluster_db] INFO  - Calling pre-failover script
2020/09/11 14:24:20 [cluster_db] ERROR - exit status 255
2020/09/11 14:24:20 [cluster_db] INFO  - Pre-failover script complete:
%!(EXTRA string= VIP DOWN / Old Master Host : 192.168.50.11:3306
**ssh: connect to host 192.168.50.11 port 22: No route to host**
)2020/09/11 14:24:20 [cluster_db] INFO  - Waiting for candidate master to apply relay log
2020/09/11 14:24:20 [cluster_db] INFO  - Reading all relay logs on 192.168.50.12:3306
2020/09/11 14:24:20 [cluster_db] INFO  - Stopping slave thread on new master
2020/09/11 14:24:20 [cluster_db] INFO  - Calling post-failover script
2020/09/11 14:24:24 [cluster_db] INFO  - Post-failover script complete
%!(EXTRA string= VIP UP / New Master Host : 192.168.50.12:3306
)2020/09/11 14:24:24 [cluster_db] INFO  - Resetting slave on new master and set read/write mode on
2020/09/11 14:24:24 [cluster_db] INFO  - Inject fake transaction on new master 192.168.50.12:3306 
2020/09/11 14:24:24 [cluster_db] INFO  - Switching other slaves to the new master
2020/09/11 14:24:24 [cluster_db] INFO  - Master switch on 192.168.50.12:3306 complete
2020/09/11 14:24:24 [cluster_db] STATE - OPENED WARN0023 : Failover number of master pings failure has been reached
2020/09/11 14:24:26 [cluster_db] STATE - RESOLV WARN0058 : No GTID strict mode on slave 192.168.50.12:3306
2020/09/11 14:24:26 [cluster_db] STATE - RESOLV ERR00016 : Master is unreachable but slaves are replicating
2020/09/11 14:24:26 [cluster_db] STATE - RESOLV WARN0023 : Failover number of master pings failure has been reached
2020/09/11 14:24:26 [cluster_db] STATE - RESOLV WARN0052 : No InnoDB durability on slave 192.168.50.12:3306
2020/09/11 14:24:26 [cluster_db] STATE - RESOLV WARN0056 : No compression of binlog on slave 192.168.50.12:3306
2020/09/11 14:24:26 [cluster_db] STATE - OPENED ERR00010 : Could not find a slave in topology
2020/09/11 14:24:26 [cluster_db] STATE - OPENED WARN0068 : No compression of binlog on slave 192.168.50.12:3306
2020/09/11 14:24:26 [cluster_db] STATE - OPENED WARN0070 : No GTID strict mode on master 192.168.50.12:3306
2020/09/11 14:24:26 [cluster_db] STATE - OPENED ERR00032 : No candidates found in slaves list

**2020/09/11 14:25:16 [cluster_db] INFO  - Setting Read Only on unconnected server 192.168.50.11:3306 as actif monitor and other master dicovereds**
2020/09/11 14:25:16 [cluster_db] INFO  - Trying to rejoin restarted server 192.168.50.11:3306
2020/09/11 14:25:16 [cluster_db] INFO  - Rejoining server 192.168.50.11:3306 to master 192.168.50.12:3306
2020/09/11 14:25:16 [cluster_db] INFO  - Backup ahead binlog events of previously failed server 192.168.50.11:3306
2020/09/11 14:25:16 [cluster_db] INFO  - Backup /app/mrm/share/amd64/linux/mysqlbinlog [/app/mrm/share/amd64/linux/mysqlbinlog --read-from-remote-server --raw --stop-never-slave-server-id=10000 --user=repl --password=repl --host=192.168.50.11 --port=3306 --result-file=/app/mrm/data/cluster_db-server1- --start-position=2115 mariadb-bin.000026]
2020/09/11 14:25:16 [cluster_db] INFO  - Rejoin master incremental 192.168.50.11:3306
2020/09/11 14:25:16 [cluster_db] INFO  - Crash info &{192.168.50.11:3306 mariadb-bin.000026 2115 mariadb-bin.000004 2115 %!s(bool=true) %!s(*gtid.List=&[{0 1 236}]) 192.168.50.12:3306}
2020/09/11 14:25:16 [cluster_db] INFO  - Setting Read Only on rejoin incremental on server 192.168.50.11:3306
2020/09/11 14:25:16 [cluster_db] INFO  - Rejoined GTID sequence 236
2020/09/11 14:25:16 [cluster_db] INFO  - Crash Saved GTID sequence 236 for master id 1
2020/09/11 14:25:16 [cluster_db] INFO  - Found same or lower GTID 0-1-236 and new elected master was 0-1-236
2020/09/11 14:25:16 [cluster_db] INFO  - New Master 192.168.50.11:3306 was not synced before failover, unsafe flashback, lost events backing up event to /app/mrm/data/cluster_db/crash-bin-20200911142516
2020/09/11 14:25:18 [cluster_db] STATE - RESOLV ERR00010 : Could not find a slave in topology
2020/09/11 14:25:18 [cluster_db] STATE - OPENED ERR00041 : Skip slave in election 192.168.50.11:3306 has more than 30 seconds of replication delay (54)
2020/09/11 14:25:18 [cluster_db] STATE - OPENED WARN0052 : No InnoDB durability on slave 192.168.50.11:3306
2020/09/11 14:25:18 [cluster_db] STATE - OPENED WARN0056 : No compression of binlog on slave 192.168.50.11:3306
2020/09/11 14:25:18 [cluster_db] STATE - OPENED WARN0058 : No GTID strict mode on slave 192.168.50.11:3306
2020/09/11 14:25:23 [cluster_db] STATE - RESOLV ERR00041 : Skip slave in election 192.168.50.11:3306 has more than 30 seconds of replication delay (56)
2020/09/11 14:25:23 [cluster_db] STATE - RESOLV ERR00032 : No candidates found in slaves list

Is it possible to solve it?

**Comment by svaroqui** [comment]
Hi,

If i remind correctly 2.1 solved that issue

**Comment by nyxneuf** [comment]
Thanks, 
2.1 Test. Old Master(New Slave) Read Only ON. OK
but, Both are M/S VIP Up.

Do you have any plans to fix version 2.0?

**Comment by svaroqui** [comment]
Hi,  this is a classic scenario of split brain that you have to take care via the failover script using a  STONITH device to shoot the old master in the head  because the old master does not commit suicide and keep the VIP in case of network down , such script need to force VIP down somehow see https://clusterlabs.org/pacemaker/doc/en-US/Pacemaker/1.1/html/Clusters_from_Scratch/ch08.html

**Comment by svaroqui** [comment]
Thanks for reporting You can  fix this by setting force-slave-readonly=true i put this default in 2.2
and to remove the vip
--autorejoin-script string                             Path of old master rejoin script 
I would suggest to set readonly  setting in  MariaDB or MySQL config as in case of rebboot then the VIP can not write to old master supposing client application do not have SUPER privileges when both nodes are  read only replication-manager remove read only on the master by looking at the replication topology
