### ISSUE TITLE
old master rejoin big delay

### ISSUE THREAD

**Issue by donghy-coredumped** [signal18/replication-manager#310]
hi ,  I test old master rejoin in cluster , has a big delay， The phenomenon is as follows:

1.  cluster status is good:
![image](https://user-images.githubusercontent.com/5544423/96564426-ba7d6680-12f5-11eb-819d-5836a63f2f26.png)

2. shutdown master :
![image](https://user-images.githubusercontent.com/5544423/96564538-da148f00-12f5-11eb-9c51-8bc23f74f036.png)

3. restart old master , rejoin in cluster (No write to the new master
) , I see that the "change master to" statement is:
CHANGE MASTER  TO master_host='xxx', master_port=8307, master_user='root', master_password=‘xxx', master_connect_retry=5, master_heartbeat_period=3;

if you do not specify MASTER_LOG_FILE and MASTER_LOG_POS in the statement, MASTER_LOG_FILE='' and MASTER_LOG_POS=4 are silently appended to it. 

Status after joining:
![image](https://user-images.githubusercontent.com/5544423/96565806-6c696280-12f7-11eb-95b1-ab1495fc82fd.png)

so "show slave status\G" : 
![image](https://user-images.githubusercontent.com/5544423/96564978-5e671200-12f6-11eb-8b8f-93a6cc025c73.png)
from master top binlog scan.

but I use GTID mode , I think "change master to " statement should be : 
CHANGE MASTER  TO master_host='xxx', master_port=8307, master_user='root', master_password=‘xxx', master_connect_retry=5, master_heartbeat_period=3, MASTER_AUTO_POSITION=1
Automatically find the required GTID SET

**Comment by svaroqui** [comment]
Hi thanks for the feedback, 
 
Indeed the code was forgetting MySQL GTID in rejoin I've push a fix in the ci .

Can you please test the last 2.1 release in ci

**Comment by donghy-coredumped** [comment]
Thank you, I test it.

**Comment by donghy-coredumped** [comment]
I pull the latest code from git:

commit c21c0b36c355b5d4c7c7d8d9d4f06e683c442f18
Author: svaroqui <stephane@signal18.io>
Date:   Tue Oct 20 11:53:04 2020 +0200

    Use MASTER_AUTO_POSITION in old master rejoin in sync for MySQL or Percona > 5.7 GTID
 
Encountered the following problems:

![image](https://user-images.githubusercontent.com/5544423/97133133-eaa88780-1783-11eb-973e-f0ec453a6303.png)

 shutdown master:
![image](https://user-images.githubusercontent.com/5544423/97133179-07dd5600-1784-11eb-8946-bfabf05cad9b.png)

start old master:
![image](https://user-images.githubusercontent.com/5544423/97133210-26435180-1784-11eb-9a9a-ef9ebf16a91e.png)

not rejoin in cluster

error log: 
![image](https://user-images.githubusercontent.com/5544423/97133236-3b1fe500-1784-11eb-9fa5-fce05097c8bc.png)

**Comment by svaroqui** [comment]
Hi 
Can let me kwow what release you are using so that i can try to reproduce ?

**Comment by donghy-coredumped** [comment]
> Hi
> Can let me kwow what release you are using so that i can try to reproduce ?

Hi:
I use the latest code build pulled from git.
Because the version I installed with yum is:
Replication Manager v2.1.1 for MariaDB 10.x and MySQL 5.7 Series
Full Version: v2.1.1-139-g68c63d18
Build Time: 2020-09-05T11:04:40+0000
There is the first problem I mentioned.

Where can I download the 2.1 release in ci version?

**Comment by svaroqui** [comment]
Sorry i mean MySQL version ? other than that http://ci.signal18.io/mrm/builds/

**Comment by donghy-coredumped** [comment]
> Sorry i mean MySQL version ? other than that http://ci.signal18.io/mrm/builds/


Server version:         5.7.32-log MySQL Community Server (GPL)

**Comment by svaroqui** [comment]
Do you have an idea what is wrong with this syntax ?

**Comment by donghy-coredumped** [comment]
> Do you have an idea what is wrong with this syntax ?

It should be MASTER_AUTO_POSITION=1, but I don’t see "=1" in the printed statement

**Comment by svaroqui** [comment]
Yes that is the case in dbhelper 

func ChangeMaster(db *sqlx.DB, opt ChangeMasterOpt, myver *MySQLVersion) (string, error) {
	//CREATE PUBLICATION alltables FOR ALL TABLES;
	cm := ""
	if myver.IsPPostgreSQL() {
		if opt.Channel == "" {
			opt.Channel = "alltables"
		}
		cm += "CREATE SUBSCRIPTION " + opt.Channel + " CONNECTION 'dbname=" + opt.PostgressDB + " host=" + misc.Unbracket(opt.Host) + " user=" + opt.User + " port=" + opt.Port + " password=" + opt.Password + " ' PUBLICATION  " + opt.Channel + " WITH (enabled=false, copy_data=false, create_slot=true)"
	} else {

		cm += "CHANGE MASTER "
		if myver.IsMariaDB() && opt.Channel != "" {
			cm += " '" + opt.Channel + "'"
		}
		cm += " TO master_host='" + misc.Unbracket(opt.Host) + "', master_port=" + opt.Port + ", master_user='" + opt.User + "', master_password='" + opt.Password + "', master_connect_retry=" + opt.Retry + ", master_heartbeat_period=" + opt.Heartbeat
		if opt.IsDelayed {
			cm += " ,master_delay=" + opt.Delay
		}
		switch opt.Mode {
		case "SLAVE_POS":
			cm += ", MASTER_USE_GTID=SLAVE_POS"
		case "CURRENT_POS":
			cm += ", MASTER_USE_GTID=CURRENT_POS"
		case "MXS":
			cm += ", master_log_file='" + opt.Logfile + "', master_log_pos=" + opt.Logpos
		case "POSITIONAL":
			cm += ", master_log_file='" + opt.Logfile + "', master_log_pos=" + opt.Logpos
			if myver.IsMariaDB() {
				cm += ", MASTER_USE_GTID=NO"
			}
		case "MASTER_AUTO_POSITION":
			cm += ", MASTER_AUTO_POSITION = 1"
		}
		if opt.SSL {
			cm += ", MASTER_SSL=1"
			//cm +=, MASTER_SSL_CA='" + opt.SSLCa + "', MASTER_SSL_CERT='" + opt.SSLCert + "', MASTER_SSL_KEY=" + opt.SSLKey + "'"
		}
		if myver.IsMySQLOrPercona() && opt.Channel != "" {
			cm += " FOR CHANNEL '" + opt.Channel + "'"
		}
	}
	_, err := db.Exec(cm)
	cm = strings.Replace(cm, opt.Password, "XXX", -1)
	if err != nil {
		return cm, fmt.Errorf("Change master statement %s failed, reason: %s", cm, err)
	}
	return cm, nil
}

**Comment by svaroqui** [comment]
I've remove the spaces  MASTER_AUTO_POSITION = 1" to  MASTER_AUTO_POSITION=1" in my last commit just in case this can cause an issue to the parser or of MySQL or from sql driver

**Comment by svaroqui** [comment]
I guess  the query is just truncated in the log , master_connect_retry=5, master_heartbeat_period=3 could probably be the issue

**Comment by donghy-coredumped** [comment]
Sorry, it is my problem, I tested it again and there is no problem.

**Comment by svaroqui** [comment]
Hey thanks what a good news i was lacking ideas :)

**Comment by donghy-coredumped** [comment]
My local code conflicts with the git code, I closed this issue
