### ISSUE TITLE
After a failover,the old master rejoin the cluster as a slave with read_only off

### ISSUE THREAD

**Issue by MonkeyFang** [signal18/replication-manager#311]
[current version]
os:CentOS Linux release 7.8.2003 (Core)
mysql: 5.7.22 percona/postional replication
rm:Replication Manager 2.0.2 for MariaDB 10.x and MySQL 5.7 Series
Full Version:  2.0.2
Build Time:  2020-07-28T08:32:28+0000

[replication config]
[Default]
include = "/etc/replication-manager/cluster.d"

check-replication-filters = true
check-binlog-filters = true
check-replication-state = true

force-slave-heartbeat= true
force-slave-heartbeat-retry = 5
force-slave-heartbeat-time = 3
force-slave-gtid-mode = false
force-slave-semisync = true
force-slave-failover-readonly-state = true
force-binlog-row = true
force-binlog-annotate = false
force-binlog-slowqueries = false
force-binlog-compress = false
force-binlog-checksum = true
force-inmemory-binlog-cache-size = false
force-disk-relaylog-size-limit = false
force-disk-relaylog-size-limit-size = 1000000000
force-sync-binlog = true
force-sync-innodb = true

switchover-wait-kill = 5000
switchover-wait-trx = 10
switchover-wait-write-query = 10
switchover-at-equal-gtid = true
switchover-at-sync = true
switchover-max-slave-delay = 0

failover-mode = "automatic"
failover-at-sync = true
failover-max-slave-delay = 30
failover-readonly-state = true
failover-time-limit = 60
failover-limit = 5
failover-restart-unsafe = false

[before failover]
192.168.174.21 slave read_only=on
192.168.174.22 master read_only=off
192.168.174.21 slave read_only=on

[after failover/reboot the master server]
192.168.174.21 slave read_only=off
192.168.174.22 slave read_only=off
192.168.174.21 slave read_only=on

The old master rejoin the cluster as a slave with read_only off that is supposed to be read_only on.

**Comment by MonkeyFang** [comment]
This problem may be solved in v2.1

**Comment by svaroqui** [comment]
Thanks for reporting
