### ISSUE TITLE
Does replication-manager support ARM architecture?

### ISSUE THREAD

**Issue by hobsRKM** [signal18/replication-manager#312]
I am trying to install replication manager on ARM architecture on AWS mariadb instance.

How do i install it?

The doc says amd64 x86.

**Comment by svaroqui** [comment]
Hi,

Well you can probably build it from source or i could try to include it in repos with minimal modification  
What Operating System do you plan and can you let me know about ARM Architecture Version 5, 6, 7, 8 

Tx
/svar

**Comment by hobsRKM** [comment]
Hi,
its Version 8, ubuntu 18.04.
I was hoping so that i can directly  use the command as in docs and install it.
It would be great if it was in repo.

Thanks

**Comment by svaroqui** [comment]
I have create the ARM rpm and deb packages but they are not yet in repository . Let me know i can push it  if you still need ARM builds

**Comment by hobsRKM** [comment]
Thank you, i just installed it on x86.
