### ISSUE TITLE
MySQL 8.0 autorejoin-backup-binlog failed!!

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#313]
Hello!

Autorejoin-backup-binlog does not work in mysql 8.0.
No problem when using mariadb.

MySQL Version : 8.0.22
SRM Version :  replication-manager-osc-2.1.1_180_g6e8c-1.x86_64.rpm

[replication-manager.log]

time="2020-12-23 16:54:25" level=info msg="Setting Read Only on unconnected server 192.168.50.12:53306 as active monitor and other master is discovered" cluster=cluster_mysql53306
time="2020-12-23 16:54:25" level=debug msg="Trying to rejoin restarted standalone server 192.168.50.12:53306" cluster=cluster_mysql53306
time="2020-12-23 16:54:25" level=info msg="Trying to rejoin restarted standalone server 192.168.50.12:53306" cluster=cluster_mysql53306
time="2020-12-23 16:54:25" level=debug msg="Backup ahead binlog events of previously failed server 192.168.50.12:53306" cluster=cluster_mysql53306
time="2020-12-23 16:54:25" level=info msg="Backup ahead binlog events of previously failed server 192.168.50.12:53306" cluster=cluster_mysql53306
time="2020-12-23 16:54:25" level=debug msg="Backup /usr/share/replication-manager/amd64/linux/mysqlbinlog /usr/share/XXXXication-manager/amd64/linux/mysqlbinlog --read-from-remote-server --raw --stop-never-slave-server-id=10000 --user=XXXX --password=XXXX --host=192.168.50.12 --port=53306 --result-file=/var/lib/XXXXication-manager/cluster_mysql53306-server102- --start-position=453 mysql-bin.000023" cluster=cluster_mysql53306
time="2020-12-23 16:54:25" level=info msg="Backup /usr/share/replication-manager/amd64/linux/mysqlbinlog /usr/share/XXXXication-manager/amd64/linux/mysqlbinlog --read-from-remote-server --raw --stop-never-slave-server-id=10000 --user=XXXX --password=XXXX --host=192.168.50.12 --port=53306 --result-file=/var/lib/XXXXication-manager/cluster_mysql53306-server102- --start-position=453 mysql-bin.000023" cluster=cluster_mysql53306
time="2020-12-23 16:54:25" level=debug msg="Failed to backup binlogs of 192.168.50.12:53306,exit status 1" cluster=cluster_mysql53306
time="2020-12-23 16:54:25" level=error msg="Failed to backup binlogs of 192.168.50.12:53306,exit status 1" cluster=cluster_mysql53306
time="2020-12-23 16:54:25" level=debug msg="/usr/share/replication-manager/amd64/linux/mysqlbinlog [/usr/share/replication-manager/amd64/linux/mysqlbinlog --read-from-remote-server --raw --stop-never-slave-server-id=10000 --user=repl --password=repl --host=192.168.50.12 --port=53306 --result-file=/var/lib/replication-manager/cluster_mysql53306-server102- --start-position=453 mysql-bin.000023]" cluster=cluster_mysql53306
time="2020-12-23 16:54:25" level=error msg="/usr/share/replication-manager/amd64/linux/mysqlbinlog [/usr/share/replication-manager/amd64/linux/mysqlbinlog --read-from-remote-server --raw --stop-never-slave-server-id=10000 --user=repl --password=repl --host=192.168.50.12 --port=53306 --result-file=/var/lib/replication-manager/cluster_mysql53306-server102- --start-position=453 mysql-bin.000023]" cluster=cluster_mysql53306
time="2020-12-23 16:54:25" level=info msg="[cluster_mysql53306] ERROR: Could not find server version: Master reported unrecognized MySQL version '8.0.22-commercial'.\n"
time="2020-12-23 16:54:25" level=info msg="[cluster_mysql53306] "
time="2020-12-23 16:54:25" level=debug msg="Rejoin master incremental 192.168.50.12:53306" cluster=cluster_mysql53306
time="2020-12-23 16:54:25" level=info msg="Rejoin master incremental 192.168.50.12:53306" cluster=cluster_mysql53306

**Comment by svaroqui** [comment]
Hi myxneuf, sorry for that and thanks for reporting

Could not find server version: Master reported unrecognized MySQL version '8.0.22-commercial'.\n"

Humm this is because you probably have a MariaDB client for the mysqlbinlog utility it may have to be reported upstream for mysql compatibility or you may change the package to get a MySQL one. I 'm not sure that MySQL get binlog flashback feature but It stay important to get a binlog backup anyway in case of snapshot or backup flashback. that may lead to lost transactions applied to the old master .  What i can do already is to add all those command line parameters to a replication-manager variable as i did it for mysqldump options in case mysql and mariadb diverge much more giving user en entry point to fix something i did not implement

**Comment by svaroqui** [comment]
I also see /usr/share/replication-manager/amd64/linux . This path can be replace in config to your mysqlbinlog path via   --backup-mysqlbinlog-path string                       Path to mysqlbinlog binary

**Comment by nyxneuf** [comment]
Thanks for your reply! :)

MySQL server and SRM server are separate.

I copied the 8.0.22 mysqlbinlog file to /usr/share/replication-manager/amd64/linux and tested it.
Eventually it failed.

So, unzip the MySQL8.0.22 Binary installation file on the SRM server and
I modified the backup-mysqlbinlog-path path.

I tested it and it was successful.

thanks regards.
