### ISSUE TITLE
MySQL 8.0 issue

### ISSUE THREAD

**Issue by wavelet123** [signal18/replication-manager#315]
Hi,
I can see the following errors in the log for Percona MySQL 8.0.16,as GLOBAL_VARIABLES has been changed in MySQL 8.0
Could you please take a look?
 
Could not get variables Error 1109: Unknown table 'GLOBAL_VARIABLES' in information_schema

thanks

**Comment by svaroqui** [comment]
Hi wavelet123, what release are you using this changed from long time into 2.1 ?

**Comment by wavelet123** [comment]
> Hi wavelet123, what release are you using this changed from long time into 2.1 ?

We're using 2.0.2,I will try with 2.1.1.Thanks

**Comment by wavelet123** [comment]
issue resolved
