### ISSUE TITLE
Driver Error xxx:3306 1045

### ISSUE THREAD

**Issue by iwyz0** [signal18/replication-manager#316]
Hello
Master & Slave client mysql version;
mysql-server 8.0.22-1debian10 amd64 [installed]

config.toml;
`[Cluster_Haproxy_MasterSlaveSlave]

title = "ClusterTestMasterSlaveSlave"
db-servers-prefered-master = "xxx:3306"
db-servers-hosts = "xxx:3306,xxx:3306,xxx:3306"
db-servers-credential = "root:xxx"
db-servers-connect-timeout = 1
replication-credential = "root:xxx"

haproxy=true
haproxy-write-port=3308
haproxy-read-port=3309
haproxy-servers= "127.0.0.1"

proxysql = true
proxysql-port = 6033
proxysql-servers = "xxx"
proxysql-user = "xxx"
proxysql-bootstrap = true
proxysql-admin-port = 6032
proxysql-password = "xxx"
prov-proxy-tags = "pkg,masterslave,linux,noreadwritesplit"

[Default]
prov-orchestrator = "local"
db-servers-binary-path= "/usr/share/replication-manager/tests/data10.2"
haproxy-binary-path= "/usr/sbin/haproxy"
sysbench-binary-path= "/usr/local/bin/sysbench"

verbose = true
http-auth = true
http-server = true
http-bind-address = "0.0.0.0"
http-bootstrap-button = false
http-session-lifetime =   3600

backup-mydumper-path = "/usr/bin/mydumper"
backup-myloader-path = "/usr/bin/myloader"
backup-mysqlbinlog-path = "/usr/bin/mysqlbinlog"
backup-mysqldump-path = "/usr/bin/mysqldump"
`

Docker image version > v2.1.1

Error log;
`time="2020-12-29T11:00:30Z" level=error msg="Driver Error xxx:3306 1045 " cluster=cluster_haproxy_masterslaveslave
time="2020-12-29T11:00:30Z" level=error msg="Driver Error xxx:3306 1045 " cluster=cluster_haproxy_masterslaveslave
time="2020-12-29T11:00:32Z" level=error msg="Driver Error xxx:3306 1045 " cluster=cluster_haproxy_masterslaveslave
time="2020-12-29T11:00:32Z" level=error msg="Driver Error xxx:3306 1045 " cluster=cluster_haproxy_masterslaveslave
time="2020-12-29T11:00:32Z" level=error msg="Driver Error xxx:3306 1045 " cluster=cluster_haproxy_masterslaveslave
time="2020-12-29T11:00:34Z" level=error msg="Driver Error xxx:3306 1045 " cluster=cluster_haproxy_masterslaveslave
time="2020-12-29T11:00:34Z" level=error msg="Driver Error xxx:3306 1045 " cluster=cluster_haproxy_masterslaveslave
time="2020-12-29T11:00:34Z" level=error msg="Driver Error xxx:3306 1045 " cluster=cluster_haproxy_masterslaveslave
time="2020-12-29T11:00:36Z" level=error msg="Driver Error xxx:3306 1045 " cluster=cluster_haproxy_masterslaveslave
time="2020-12-29T11:00:36Z" level=error msg="Driver Error xxx:3306 1045 " cluster=cluster_haproxy_masterslaveslave
time="2020-12-29T11:00:36Z" level=error msg="Driver Error xxx:3306 1045 " cluster=cluster_haproxy_masterslaveslave
`
Thank you..

**Comment by svaroqui** [comment]
prov-orchestrator = "local" means that replication-manager will  provision from packages inside the replication-manager container for testing 

in such case a  better configuration is probably 

db-servers-hosts = "127.0.0.1:3305,127.0.0.1:3306,127.0.0.1:3307"
db-servers-prefered-master = "127.0.0.1:3306"
prov-db-binary-basedir= "/usr/bin"
prov-db-client-basedir= "/usr/bin"
backup-mysqlclient-path ="/usr/bin/mysql"
backup-mysqlbinlog-path = "/usr/bin/mysqlbinlog"
haproxy-binary-path= "/usr/sbin/haproxy"
proxysql-binary-path="/usr/bin/proxysql"
backup-restic-binary-path="/usr/bin/restic"

You are refering to mysql 8 in the docker image mariadb is the default flavor /usr/bin/mysqld --version  
/usr/bin/mysqld  Ver 10.4.15-MariaDB for Linux on x86_64 (MariaDB Server)


You may wan't to use prov-orchestrator = "onpremise" that do not offer provisioning just monitoring and failover on remote dbms & proxies already setup.

**Comment by iwyz0** [comment]
Hello
It's okay right now, thank you very much
error log is misleading when password is wrong
Driver Error > it may be correct to say the password is invalid instead
