### ISSUE TITLE
Network flood by replication manager  - Too many requests

### ISSUE THREAD

**Issue by hobsRKM** [signal18/replication-manager#317]
![image](https://user-images.githubusercontent.com/11420858/103287263-16f0b680-4a08-11eb-803b-1e1f3ce45caa.png)

Keeps on polling every 200ms causing network flood and sometimes the system gets locked out. Any fix?

Sometimes the request /proxies go into the pending state causing all the other requests in a pending state and locks out the system with a network flood.

Please fix this, or may be use even sockets?

**Comment by svaroqui** [comment]
Hi we found out that a repository build process was off since a month and that the last release as this GUI bug, we moved to auto build by tag and i was not aware of that new change in that process . A last release of 2.1.3 was now tagged that should fixe all this.
