### ISSUE TITLE
Continuous output “INFO	Add ProxySQL user root”

### ISSUE THREAD

**Issue by qiuqiuqiubo** [signal18/replication-manager#320]
hai，

10.5.8-MariaDB+ProxySQL 2.0.15+Replication Manager 2.0.2

`[root@ ~]# tail -f /var/log/replication-manager.log
2021/01/11 10:43:12 [wuxi-cluster] INFO  - Add ProxySQL user root 
2021/01/11 10:43:12 [wuxi-cluster] INFO  - Add ProxySQL user root 
2021/01/11 10:43:14 [wuxi-cluster] INFO  - Add ProxySQL user root 
2021/01/11 10:43:14 [wuxi-cluster] INFO  - Add ProxySQL user root 
2021/01/11 10:43:16 [wuxi-cluster] INFO  - Add ProxySQL user root 
2021/01/11 10:43:16 [wuxi-cluster] INFO  - Add ProxySQL user root 
2021/01/11 10:43:19 [wuxi-cluster] INFO  - Add ProxySQL user root 
2021/01/11 10:43:19 [wuxi-cluster] INFO  - Add ProxySQL user root 
2021/01/11 10:43:21 [wuxi-cluster] INFO  - Add ProxySQL user root 
2021/01/11 10:43:21 [wuxi-cluster] INFO  - Add ProxySQL user root `

mariadb
`MariaDB [(none)]> select user,host,password from mysql.user;
+-------------+-------------+-------------------------------------------+
| User        | Host        | Password                                  |
+-------------+-------------+-------------------------------------------+
| mariadb.sys | localhost   |                                           |
| root        | localhost   | invalid                                   |
| mysql       | localhost   | invalid                                   |
| monitor     | 192.168.1.% | *86A3F5CCF25BCC2B67106E4BCFADC075F7522B96 |
| repl        | 192.168.1.% | *7B147B9BA3E40F1E27FECA2C164D7FC2EB807DBE |
| root        | 192.168.1.% | *E157E2CBF227169A5C5A954333DF6CB9B8778095 |
| root        | 172.16.%.%  | *E157E2CBF227169A5C5A954333DF6CB9B8778095 |
+-------------+-------------+-------------------------------------------+`

proxysql Refresh multiple times
proxy SQL table mysql_users Field password  sometimes is “invalid” sometimes is “*E157E2CBF227169A5C5A954333DF6CB9B8778095”

`2021-01-11 10:43:02 [INFO] Received LOAD MYSQL USERS TO RUNTIME command
2021-01-11 10:43:04 [INFO] Received LOAD MYSQL USERS TO RUNTIME command
2021-01-11 10:43:06 [INFO] Received LOAD MYSQL USERS TO RUNTIME command
2021-01-11 10:43:08 [INFO] Received LOAD MYSQL USERS TO RUNTIME command
2021-01-11 10:43:10 [INFO] Received LOAD MYSQL USERS TO RUNTIME command
2021-01-11 10:43:12 [INFO] Received LOAD MYSQL USERS TO RUNTIME command
2021-01-11 10:43:14 [INFO] Received LOAD MYSQL USERS TO RUNTIME command
2021-01-11 10:43:16 [INFO] Received LOAD MYSQL USERS TO RUNTIME command
2021-01-11 10:43:19 [INFO] Received LOAD MYSQL USERS TO RUNTIME command
2021-01-11 10:43:21 [INFO] Received LOAD MYSQL USERS TO RUNTIME command`

**Comment by qiuqiuqiubo** [comment]
10.5.8-MariaDB+ProxySQL 2.0.15+Replication Manager 2.0.2

[root@ ~]# tail -f /var/log/replication-manager.log 
![image](https://user-images.githubusercontent.com/52772304/104144787-b138fd00-53ff-11eb-98cb-7b126186f27a.png)


mariadb
![image](https://user-images.githubusercontent.com/52772304/104144808-c2820980-53ff-11eb-8b8f-219b64bd2156.png)


proxysql Refresh multiple times
proxy SQL table mysql_users Field password sometimes is “invalid” sometimes is “*E157E2CBF227169A5C5A954333DF6CB9B8778095”
![image](https://user-images.githubusercontent.com/52772304/104144832-dc235100-53ff-11eb-98f0-3ddced2ae711.png)

**Comment by svaroqui** [comment]
Thanks for the details report i'll work on it and keep you posted

**Comment by svaroqui** [comment]
I 've push a fix can you check if last 2.1 release fixe your issue also a workaround is to disable proxy proxysql-bootstrap-users=false

**Comment by svaroqui** [comment]
The reason for such issue is that proxysql do not have a host information in user so replication-manager try to do si best by distinct user:password and mount this in hash table that get random order the fix is for now to ignore invalid password

**Comment by svaroqui** [comment]
Fixed need feedback
