### ISSUE TITLE
MySQL-8.0.23 Change Master To Command Deprecation and Removal

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#322]
Hi!
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-23.html#mysqld-8-0-23-deprecation-removal
https://dev.mysql.com/doc/refman/8.0/en/change-replication-source-to.html

From mysql-8.0.23, the change master to command has been discontinued and removed.
Are there any problems with SRM?

**Comment by svaroqui** [comment]
No it is just for racial raisons in US, it's no more politically correct  to use master and slave but the syntax is still supported and get changed in the logs.  I'll catch with this when it will be needed or when slavery will be gone on earth witch is far from being soon :)
