### ISSUE TITLE
mysql8 mysqlbinlog issue

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#324]
hi.

DB : mysql-8.0.23
SRM : replication-manager-osc-2.1.1_221_g5dbc-1.x86_64.rpm

mysqlbinlog problem. 

-log-

me="2021-01-29 11:01:23" level=error msg="Could not get binary log files 192.168.50.11:53306 Could not get binary logs" cluster=cluster_mysql53306 error="Could not get binary logs" module=Monitor server="192.168.50.11:53306" sql="SHOW BINARY LOGS"
time="2021-01-29 11:01:23" level=info msg="/app/mysql/mysql/bin/mysqlbinlog --read-from-remote-server --raw --server-id=10000 --user=repl --password=repl --host=192.168.50.11 --port=53306 --result-file=/app/mrm/data/backups/cluster_mysql53306/192.168.50.11_53306/ mysql-bin.000150" cluster=cluster_mysql53306
time="2021-01-29 11:01:23" level=info msg="Purging binlog file mysql-bin.000150" cluster=cluster_mysql53306

-Run directly-

#/app/mysql_53306/mysql/bin/mysqlbinlog --read-from-remote-server --raw --server-id=10000 --user=repl --password=repl --host=192.168.50.11 --port=53306 --result-file=/app/mysql_53306/ mysql-bin.000149
mysqlbinlog: [Warning] Using a password on the command line interface can be insecure.

MariaDB no problem. MySQL issue.

Is it possible to solve it?

**Comment by svaroqui** [comment]
Please reopen if not fixed
