### ISSUE TITLE
SSL certificate for https://signal18.io/ expired February 8, 2018

### ISSUE THREAD

**Issue by ghost** [signal18/replication-manager#330]
As written in the headline, the ssl cert for https://signal18.io/products expired three years ago :P

Check: https://www.ssllabs.com/ssltest/analyze.html?d=signal18.io

**Comment by ghost** [comment]
Also I'm reasonably sure that this error / debug page on the docs. site should not be there instead of the actual docs: https://docs.signal18.io/

**Comment by tanji** [comment]
Hello,

you caught us in the middle of a Sunday server migration. Please give it some time :) it should be fixed soon!
