### ISSUE TITLE
Replication Manager DB Switcover/Failover to specific Host Feature 

### ISSUE THREAD

**Issue by Manoharan-NMS** [signal18/replication-manager#337]
**Configuration Details:**
File Name: /etc/replication-manager/cluster.d/cluster1.toml

db-servers-hosts = "x.x.x.a:3306,x.x.x.b:3306,x.x.x.c:3306"
db-servers-prefered-master = "x.x.x.a:3306"

switchover-max-slave-delay = 30
failover-max-slave-delay = 30

**Execution Steps:**
Always preferred master is x.x.x.a only.  During failover, expecting to go to x.x.x.b

**Expected Result:**
During failover, switchover should happen from x.x.x.a to x.x.x.b always.

**Actual Result:**
During failover, from x.x.x.a to x.x.x.b is not going. Instead of that it switched over from x.x.x.a to x.x.x.c server most of that time.
Out of 10 times, only 1 time only switching to x.x.x.a to x.x.x.b

**Feature Requirement:**
In there any logic like **db-servers-prefered-master** variable should hold more than one host in order.

**Observations:**
From x.x.x.a has less than 30 seconds delay. But x.x.x.b has more than 30 seconds delay.

**Replication Manager Version:**
replication-manager-osc-2.1.1_178_g913c-1.x86_64

**Comment by svaroqui** [comment]
The logic is that failover always go to the most up to date slave always if it is not electable the failover is canceled but still can be forced at your own risk of re-seeding all slaves make sens has of the slave elected is for sure behind other slaves 

For switchover any slaves can be used to flavor one over the other you can simply or use --db-servers-ignored-hosts="x.x.x.c:3306" some servers or 
db-servers-prefered-master = "x.x.x.a:3306,x.x.x.b:3306"

after that  the order is the monitoring order db-servers-hosts = "x.x.x.a:3306,x.x.x.b:3306,x.x.x.c:3306"
so x.x.x.c:3306 get probably more chance to have the most up to date value as is the last in monitor loop but still refresh status happen in concurrent go routing on all nodes so the diff should really be minimal

Hope it's helps

**Comment by Manoharan-NMS** [comment]
> The logic is that failover always go to the most up to date slave always if it is not electable the failover is canceled but still can be forced at your own risk of re-seeding all slaves make sens has of the slave elected is for sure behind other slaves
> 
> For switchover any slaves can be used to flavor one over the other you can simply or use --db-servers-ignored-hosts="x.x.x.c:3306" some servers or
> db-servers-prefered-master = "x.x.x.a:3306,x.x.x.b:3306"
> 
> after that the order is the monitoring order db-servers-hosts = "x.x.x.a:3306,x.x.x.b:3306,x.x.x.c:3306"
> so x.x.x.c:3306 get probably more chance to have the most up to date value as is the last in monitor loop but still refresh status happen in concurrent go routing on all nodes so the diff should really be minimal
> 
> Hope it's helps

Thanks for your reply. Will test and provide the feedback.

**Comment by Manoharan-NMS** [comment]
> > The logic is that failover always go to the most up to date slave always if it is not electable the failover is canceled but still can be forced at your own risk of re-seeding all slaves make sens has of the slave elected is for sure behind other slaves
> > For switchover any slaves can be used to flavor one over the other you can simply or use --db-servers-ignored-hosts="x.x.x.c:3306" some servers or
> > db-servers-prefered-master = "x.x.x.a:3306,x.x.x.b:3306"
> > after that the order is the monitoring order db-servers-hosts = "x.x.x.a:3306,x.x.x.b:3306,x.x.x.c:3306"
> > so x.x.x.c:3306 get probably more chance to have the most up to date value as is the last in monitor loop but still refresh status happen in concurrent go routing on all nodes so the diff should really be minimal
> > Hope it's helps
> 
> Thanks for your reply. Will test and provide the feedback.

Old version of Replication Manager **replication-manager-osc-2.1.0_dev_795_g19a64-1.x86_64**  had following problem.

**db-servers-prefered-master = "x.x.x.a:3306,x.x.x.b:3306"**    This is not working

Will it be resolved when updating to latest  version. ?

**Comment by svaroqui** [comment]
Re, use repo or ci to get last 2.1

**Comment by Manoharan-NMS** [comment]
> Re, use repo or ci to get last 2.1

In my production environment no internet connection. So downloading RPM only. from following URL

http://ci.signal18.io/mrm/builds/2.1/

http://ci.signal18.io/mrm/builds/2.1/replication-manager-osc-2.1.1_246_g80837-1.x86_64.rpm

**Comment by Manoharan-NMS** [comment]
Related to this issue raised.
https://github.com/signal18/replication-manager/issues/345
