### ISSUE TITLE
Replication user credentials in log files

### ISSUE THREAD

**Issue by ncstate-mafields** [signal18/replication-manager#341]
While testing an upgrade to 2.1 today, I noticed that the replication user credentials appeared in plain text in the log files. 

I see no reason why this info level message should appear in the log at all, nor why it needs to have the full command arguments including the replication user credentials in plain text. 

```
time="2021-04-21 12:41:22" level=info msg="Backup master missing binlog of [REDACTED],mariadb-bin.002365" cluster=test
time="2021-04-21 12:41:22" level=info msg="/usr/share/replication-manager/amd64/linux/mysqlbinlog --read-from-remote-server --raw --server-id=10000 --user=sys_replication --password=[REDACTED] --host=[REDACTED] --port=3306 --result-file=/var/lib/replication-manager/backups/test/[REDACTED]_3306/ mariadb-bin.002365" cluster=test
```

**Comment by svaroqui** [comment]
Hi thanks for reporting , 

Fully agree and apparently i missed that one 

I'll a quick fixe as soon as possible and get you posted 
You can disable that feature backup-binlogs=false 

Tx
/stephane

**Comment by svaroqui** [comment]
re,

OK the binaries from our repository of last from ci is supposed to replace the password with  XXXX wher did you get the binaries from Git ? 

	cmdrun := exec.Command(server.ClusterGroup.GetMysqlBinlogPath(), "--read-from-remote-server", "--raw", "--server-id=10000", "--user="+server.ClusterGroup.rplUser, "--password="+server.ClusterGroup.rplPass, "--host="+misc.Unbracket(server.Host), "--port="+server.Port, "--result-file="+server.GetMyBackupDirectory(), binlogfile)
	server.ClusterGroup.LogPrintf(LvlInfo, "%s", strings.Replace(cmdrun.String(), server.ClusterGroup.dbPass, "XXXX", 1))
/svar

**Comment by ncstate-mafields** [comment]
I added the repo here: http://repo.signal18.io/centos/2.1/7/x86_64/
I installed the latest ocs package and restarted replication-manager

**Comment by svaroqui** [comment]
Thanks, let me know if that is fixing that issue, any way i plan to disable this feature by default because it may consume 4 gig of disk space that could be a issue for new users.

**Comment by ncstate-mafields** [comment]
Yes, disabling the binlog backups feature works as workaround to prevent the log file from leaking credentials (since it never executes the command). 

RPM version `1612802017:replication-manager-osc-2.1.1_246_g80837-1.x86_64` from the http://repo.signal18.io/centos/2.1/7/x86_64/ repository failed to replace the password. 

Note that in your code snippet, the password used in the command is `server.ClusterGroup.rplPass`, and the replacement password is `server.ClusterGroup.dbPass`. It seems like the `dbPass` should be `rplPass`.

**Comment by svaroqui** [comment]
Hi,
 
Nice catch i need more users like you :)

/svar
