### ISSUE TITLE
Table scanning causes massive load spikes for high table counts

### ISSUE THREAD

**Issue by ncstate-mafields** [signal18/replication-manager#342]
The 2.1 release appear to scan the information schema for tables: 

```
time="2021-04-21 12:40:47" level=error msg="Could not fetch master tables [Could not get table list]" cluster=test
```

In a database where there are over 10k tables, the query times out and replication-manager gives this error. However, it then tries again in one minute. This results in the backend server constantly attempting to dump the table information from the information schema, and spikes the load on the backend server causing degraded performance. 

Is there a way to disable the table scanning functionality?

**Comment by svaroqui** [comment]
Hi, 

please try to monitoring-schema-change=false

I know i have made some special code for table monitoring where it take tables one by one with show table status , i'll  dig the code to tell you if some more work is needed or if there is still some IS queries that indeed produce a lot of temp tables 

 Tx
/svar

**Comment by ncstate-mafields** [comment]
It looks like `monitoring-schema-change=false` worked to disable the table scans, and load on the backend servers is nominal under 2.1 with that option disabled. 

FYI, I didn't see that option documented here: https://docs.signal18.io/configuration/server

**Comment by svaroqui** [comment]
Repository release should not produce load , added doc to disable and if load still happen with monitor-schema enable please re open , at the same time monitoring was disable per default to avoid any surprise on this

**Comment by svaroqui** [comment]
Hi we found out that a repository build process was off since a month and that the last release as a GUI bug and this bug as well , we moved to auto build by tag and i was not aware  of that new change in that process . A last release of 2.1.3 was now tagged that should fixe all this.
