### ISSUE TITLE
 What does this message mean?

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#344]
my system closed network.

[Log]
time="2021-05-07 09:59:27" level=error msg="Get File https://docs.google.com/spreadsheets/d/e/2PACX-1vQClXknRapJZ4bRSId_aa5zUrbFDZmmc6GiV3n7-tPyQJispqqnSJj6lMaJxoJv5pOC9Ktj8ywWdGX6/pub?gid=0&single=true&output=csv to /var/lib/replication-manager/serviceplan.csv : Get \"https://docs.google.com/spreadsheets/d/e/2PACX-1vQClXknRapJZ4bRSId_aa5zUrbFDZmmc6GiV3n7-tPyQJispqqnSJj6lMaJxoJv5pOC9Ktj8ywWdGX6/pub?gid=0&single=true&output=csv\": dial tcp: lookup docs.google.com on [::1]:53: read udp [::1]:59691->[::1]:53: read: connection refused"
time="2021-05-07 09:59:27" level=error msg="GetServicePlans download csv  Get \"https://docs.google.com/spreadsheets/d/e/2PACX-1vQClXknRapJZ4bRSId_aa5zUrbFDZmmc6GiV3n7-tPyQJispqqnSJj6lMaJxoJv5pOC9Ktj8ywWdGX6/pub?gid=0&single=true&output=csv\": dial tcp: lookup docs.google.com on [::1]:53: read udp [::1]:59691->[::1]:53: read: connection refused"

**Comment by svaroqui** [comment]
Hi nyxneuf,  

This is a tentative to download and upgrade a service plan list in share from a google doc :) i worked on  this not long time ago,  may be i left it run in OSC release and that would be wrong what release are you running that i not supposed to happen what i already worked out is to put a shortest  timeout and i think did something if it failed to load to read a csv file in share, i'll check the code and keep you posted

**Comment by svaroqui** [comment]
id,plan,dbmemory,dbcores,dbdatasize,dbsystemsize,dbiops,dbcpufreq,prxcores,prxdatasize
1,x1.small,16384,2,700,300,300,3000,1,80
2,x1.small.compute,16384,4,700,300,300,3000,1,80
3,x1.small.perf,32768,2,700,300,600,3000,1,80
4,x1.middle,32768,4,700,300,600,3000,2,80
5,x1.middle.compute,32768,8,700,300,600,3000,2,80
6,x1.middle.perf,65536,4,700,300,800,3000,2,80
7,x1.large,65536,8,700,300,800,3000,2,80
8,x1.large.compute,65536,16,700,300,800,3000,2,80
9,x1.large.perf,131072,8,700,300,1000,3000,2,80
10,x1.huge,131072,16,700,300,1000,3000,4,80
11,x1.huge.compute,131072,32,700,300,1000,3000,4,80
12,x1.huge.perf,262144,16,700,300,2000,3000,4,80

**Comment by nyxneuf** [comment]
Hi! svaroqui,

Using replication-manager-osc-2.1.3-1.x86_64.rpm

I installed rpm and there is no serviceplan.csv.

**Comment by svaroqui** [comment]
Yes , i simply forget to commit that file i'll do it today , looking at the code setting prov-service-plan-registry = "" would disable the download , if you wan't to setup provisioning with external script this is now possible with 2.2 and then the service plan can get used to add new clusters,let me know if that's one thing you would like to explore with me. 
This is something i have in mind for some ansible deployement. 

So far the parameter pass are very limited server_host 
 server_port  , server_user, server_password , i may also add the cluster _name soon and may be cluster_conf in json
