### ISSUE TITLE
how install it on aarch

### ISSUE THREAD

**Issue by xiaomianlang** [signal18/replication-manager#356]
I want to use it on CentOS Linux release 7.9.2009 (AltArch)，how can I install it？

**Comment by tanji** [comment]
Hi @xiaomianlang right now we don't provide an AltArch version
I would recommend compiling from source, that is not too complex with the Makefile.
We'll look at providing official ARM Versions. Let me know if you need help with the compile!

**Comment by svaroqui** [comment]
Hi Xiaomianlang , there are some arm release badly named in in http://ci.signal18.io/mrm/builds/2.1/  may be you can try out those ones , and let us know if that works for you until we make repo arch enable

**Comment by xiaomianlang** [comment]
> Hi @xiaomianlang right now we don't provide an AltArch version
> I would recommend compiling from source, that is not too complex with the Makefile.
> We'll look at providing official ARM Versions. Let me know if you need help with the compile!

I have tried  to recommend compiling from source，but I got an error as "gcc:error:unrecognized command line option '-m64'",How should I deal with it? Thank you .
