### ISSUE TITLE
version 2.1.6 not available in deb repo

### ISSUE THREAD

**Issue by bmillemathias** [signal18/replication-manager#358]
Hello

the latest version cannot be found under http://repo.signal18.io/deb/pool/2.1/r/replication-manager-osc/

**Comment by svaroqui** [comment]
Thanks for the notice it should be up to date now :)

**Comment by bmillemathias** [comment]
Hi, thanks for the quick head up.
I've noticed also there is no version 2.2.x at all in the repo (under http://repo.signal18.io/deb/pool/)
