### ISSUE TITLE
Give more information (user account + host) related for a user related message

### ISSUE THREAD

**Issue by bmillemathias** [signal18/replication-manager#361]
I just got such message `[Default] STATE - OPENED ERR00007 : User must have REPLICATION SLAVE privilege`
That would be helpful to know which user is referenced and perhaps also the node, because AFAIK my replication-manager user has `ALL` privileges and the replication user has the correct permission
```
(root@localhost) [(none)]> show grants for 'repl'@'%';               
+------------------------------------------------------------------+ 
| Grants for repl@%                                                | 
+------------------------------------------------------------------+ 
| GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'repl'@'%' | 
+------------------------------------------------------------------+ 
```

so specifically for this message, that would be more than welcome to have which user is targeted by the message.

**Comment by svaroqui** [comment]
Hi, 
The processing here is very complex for the user as it get that from a list of users where many host part are lookup , % , ip , x.%.%.%. x.y.%.% x.y.z.% hostname of the replication-manager and ip of the replictaion-manager 

I can push for sure the server when it failed 

Did you check all the nodes have the replication user ?

**Comment by bmillemathias** [comment]
> Did you check all the nodes have the replication user ?

I had created it on all nodes when creating the replication yesterday but the moment I had the issue, it has disappeared (I wondered if replication-manager could have done that). I don't understand why because my mysql configuration is managed by ansible so was created the same on all nodes but that's another issue.

**Comment by svaroqui** [comment]
If it happens again  you could debug more using  log level >2  as it print the lookup with user and server at every monitor loop
