### ISSUE TITLE
ERROR 1045 (28000): ProxySQL Error: Access denied for user

### ISSUE THREAD

**Issue by zhituanchen** [signal18/replication-manager#368]
Hi
After I start replication-manager，Trying to connect MySQL by useing port 6033 get error:
[root@mysql-dev soft]# mysql -utuan -pNfjd_1234 -h10.0.0.162 -P6033  -e 'select @@port'; 
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): ProxySQL Error: Access denied for user 'tuan'@'10.0.0.162' (using password: YES)

using port 3306 is ok:
[root@mysql-dev soft]#   mysql -utuan -pNfjd_1234 -h10.0.0.162 -P3306 -e 'select @@port';
mysql: [Warning] Using a password on the command line interface can be insecure.
+--------+
| @@port |
+--------+
|   3306 |
+--------+ 

replication-manager logs:
![image](https://user-images.githubusercontent.com/71009460/126286822-88658723-6328-4c4e-8801-2014d158d564.png)
Is look like auto Received LOAD MYSQL USERS TO ProxySQL mysql_users table. I not add rows in ProxySQL mysql_users table;
Is there any error when auto Received LOAD MYSQL USERS TO ProxySQL mysql_users table data;

ProxySQL logs:
![image](https://user-images.githubusercontent.com/71009460/126286988-2b8f52db-bd7d-41e2-9d95-d3cab4607e08.png)

info
system info :CentOS Linux release 7.5
replication-manager:replication-manager-osc-2.2.2-1.x86_64
ProxySQL:proxysql-2.2.0-1-centos7.x86_64

**Comment by zhituanchen** [comment]
HI:
 I open mysql general_log and fond,the replication-manager select mysql.user table：
SELECT user, host, '****' as password, CONV(LEFT(MD5(concat(user,host)), 16), 16, 10)    FROM mysql.user;
And the password is not a correct password，Why？
![image](https://user-images.githubusercontent.com/71009460/126457939-e232e097-b230-4a97-860c-b4032d5cfbe4.png)

And can't change proxysql mysql_users tables password，the replication-manager will trigger select mysql.user data and cover it.
![image](https://user-images.githubusercontent.com/71009460/126458467-2d165402-b9d5-40f3-a71d-939756ad7630.png)
![image](https://user-images.githubusercontent.com/71009460/126458536-4591eb3d-737e-4035-b17d-b43281e21237.png)

**Comment by svaroqui** [comment]
Hi ,
You can disable that auto load users feature until we understand what is the issue 
inside your cluster config proxysql-bootstrap-users = false
--proxysql-bootstrap                                   Bootstrap ProxySQL backend servers and hostgroup
      --proxysql-bootstrap-hostgroups                        Bootstrap ProxySQL hostgroups
      --proxysql-bootstrap-query-rules                       Bootstrap Query rules into ProxySQL
      --proxysql-bootstrap-users                             Copy users from master (default true)
      --proxysql-bootstrap-variables                         Bootstrap ProxySQL backend servers and hostgroup
      --proxysql-master-is-reader                            Add the master to the reader group
      --proxysql-multiplexing                                Multiplexing
      --proxysql-password string                             ProxySQL admin password (default "admin")
      --proxysql-port string                                 ProxySQL read/write proxy port (default "3306")
      --proxysql-reader-hostgroup string                     ProxySQL reader hostgroup (default "1")
      --proxysql-save-to-disk                                Save proxysql change to sqllight
      --proxysql-servers string                              ProxySQL hosts
      --proxysql-servers-ipv6 string                         ProxySQL extra IPV6 bind for interfaces
      --proxysql-user string                                 ProxySQL admin user (default "admin")
      --proxysql-writer-hostgroup string                     ProxySQL writer hostgroup (default "0")

**Comment by zhituanchen** [comment]
Hi,
 Is works,tnanks,Now when i start the replication-manager ,it will change the ProxySQL mysql_servers table data,which variables can fix it:
is change the old data,and hostgroup_id is 666;
![image](https://user-images.githubusercontent.com/71009460/126471543-aefb928f-f4bf-441a-b6c8-164dcfb285d8.png)
![image](https://user-images.githubusercontent.com/71009460/126471598-3838707d-5ab1-4ac8-9d5d-3d941883ab5e.png)

**Comment by svaroqui** [comment]
What is the state of your cluster any valid replication running ? 666 is when replication-manager  protect the database from no master found ?

**Comment by zhituanchen** [comment]
The mysql cluster is M-S:

The ProxySQL info:
insert into mysql_replication_hostgroups ( writer_hostgroup, reader_hostgroup, comment) values (10,20,'proxy');
insert into mysql_servers(hostgroup_id,hostname,port) values (10,'10.0.0.162',3306);
insert into mysql_servers(hostgroup_id,hostname,port) values (20,'10.0.0.231',3306);

when restart the replication-manager,it change the ProxySQL mysql_servers tables data,hostgroup_id 10 change to 666;
the hostgroup_id  666  in mysql_servers, i not add it;

**Comment by svaroqui** [comment]
Re,

proxysql-bootstrap-hostgroups=false
proxysql-writer-hostgroup =10
proxysql-reader-hostgroup =20

But 666 is done  by replication-manager to disable a server so something must be wrong in your cluster

**Comment by zhituanchen** [comment]
Hi
 Thanks. I change the mechine reinstall replication-manage. It works.

**Comment by svaroqui** [comment]
Thanks feel free to reopen if more is needed
