### ISSUE TITLE
set proxysql-writer/reader-hostgroup parameter not displayed on the web page

### ISSUE THREAD

**Issue by zhituanchen** [signal18/replication-manager#369]
Hi
  I set proxysql-writer-hostgroup and proxysql-reader-hostgroup. but i not found displayed on the web page. 
proxysql is a cluster(10.0.0.231,10.0.0.162)
config.toml info:
[db3306]
title = "db3306"
db-servers-hosts = "10.0.0.231:3306,10.0.0.162:3306"
db-servers-prefered-master = "10.0.0.231:3306"
db-servers-credential = "dbadmin:Nfjd_1234"
replication-credential = "repl:Repl_2019"
failover-mode = "manual"
proxysql=true
proxysql-servers="10.0.0.231,10.0.0.162"
proxysql-port=6033
proxysql-admin-port=6032
**proxysql-writer-hostgroup="10"
proxysql-reader-hostgroup="20"**
proxysql-user="cluster1"
proxysql-password="secret1pass"
proxysql-bootstrap=false
proxysql-bootstrap-hostgroups=false
proxysql-bootstrap-users=false

message info:
![image](https://user-images.githubusercontent.com/71009460/126733453-37bdd2db-3912-4a87-9a3a-72389545d9a1.png)

**Comment by svaroqui** [comment]
Thanks for reporting i'll fix it , that is just a typo issue .

**Comment by zhituanchen** [comment]
Thanks
