### ISSUE TITLE
original master rejoining to new master failed

### ISSUE THREAD

**Issue by zhangcunhai** [signal18/replication-manager#376]
dear,I have one master and one slave on ubuntu with the replication manager vision 2.2.4.
when i shutdown the original master ,the cluster failover sucessfully,then i start the original master ,it can't rejoin to the new master.
with the rejoin logs:
time="2021-08-23 10:00:21" level=debug msg="Monitoring server loop" cluster=qiftest
time="2021-08-23 10:00:21" level=debug msg="Server [0]: URL: 172.26.1.144:3308 State: Failed PrevState: Failed" cluster=qiftest
time="2021-08-23 10:00:21" level=debug msg="Server [1]: URL: 172.26.1.152:3308 State: Master PrevState: Master" cluster=qiftest
time="2021-08-23 10:00:21" level=debug msg="Master [ ]: URL: 172.26.1.152:3308 State: Master PrevState: Master" cluster=qiftest
time="2021-08-23 10:00:21" level=debug msg="Remove cookie (cookie_waitstart) remove /data/replication-manager/qiftest/172.26.1.144_3308/@cookie_waitstart: no such file or directory" cluster=qiftest
time="2021-08-23 10:00:21" level=debug msg="Remove cookie (cookie_restart) remove /data/replication-manager/qiftest/172.26.1.144_3308/@cookie_restart: no such file or directory" cluster=qiftest
time="2021-08-23 10:00:21" level=debug msg="State comparison reinitialized failed server 172.26.1.144:3308 as unconnected" cluster=qiftest
time="2021-08-23 10:00:21" level=info msg="Setting Read Only on unconnected server 172.26.1.144:3308 as active monitor and other master is discovered" cluster=qiftest
time="2021-08-23 10:00:21" level=info msg="Trying to rejoin restarted standalone server 172.26.1.144:3308" cluster=qiftest
time="2021-08-23 10:00:21" level=info msg="Backup ahead binlog events of previously failed server 172.26.1.144:3308" cluster=qiftest
time="2021-08-23 10:00:21" level=info msg="Backup /usr/share/replication-manager/amd64/linux/mysqlbinlog /usr/share/replication-manager/amd64/linux/mysqlbinlog --read-from-remote-server --raw --stop-never-slave-server-id=10000 --user=root --password=XXXX --host=172.26.1.144 --port=3308 --result-file=/data/replication-manager/qiftest-server23- --start-position=514 3308-bin.000021" cluster=qiftest
time="2021-08-23 10:00:21" level=info msg="Rejoin master incremental 172.26.1.144:3308" cluster=qiftest
time="2021-08-23 10:00:21" level=info msg="Crash info &{172.26.1.144:3308 3308-bin.000021 514 3308-bin.000016 374 %!s(bool=true) %!s(*gtid.List=&[{0 17340952101732639850 371} {0 14386675944214502826 16}]) 172.26.1.152:3308}" cluster=qiftest
time="2021-08-23 10:00:21" level=info msg="Rejoined GTID sequence 0" cluster=qiftest
time="2021-08-23 10:00:21" level=info msg="Crash Saved GTID sequence 0 for master id 23" cluster=qiftest
time="2021-08-23 10:00:21" level=info msg="Rejoin server found a crash GTID greater than 0 " cluster=qiftest
time="2021-08-23 10:00:21" level=info msg="Cascading failover, found empty GTID, forcing full state transfer" cluster=qiftest
time="2021-08-23 10:00:21" level=info msg="Cascading failover, consider we cannot flashback" cluster=qiftest
time="2021-08-23 10:00:21" level=info msg="No flashback rejoin can flashback false, autorejoin-flashback false autorejoin-backup-binlog true" cluster=qiftest
time="2021-08-23 10:00:21" level=error msg="Failed to autojoin incremental to master 172.26.1.144:3308" cluster=qiftest
time="2021-08-23 10:00:21" level=info msg="No SST rejoin method found" cluster=qiftest
time="2021-08-23 10:00:21" level=error msg="State transfer rejoin failed" cluster=qiftest
time="2021-08-23 10:00:21" level=info msg="Rejoin old Master 172.26.1.144:3308 , backing up lost event to /data/replication-manager/qiftest/crash-bin-20210823100021" cluster=qiftest
time="2021-08-23 10:00:21" level=debug msg="Server 172.26.1.144:3308 has no slaves " cluster=qiftest
time="2021-08-23 10:00:21" level=debug msg="Server 172.26.1.152:3308 was set master as last non slave" cluster=qiftest

**Comment by zhangcunhai** [comment]
here is the config ：

db-servers-credential = "root:xxx,"
db-servers-connect-timeout = 2
replication-credential = "root:xxx"
failover-mode = "automatic"
failover-time-limit=30
failover-post-script = "/etc/replication-manager/vip_up.sh"
failover-falsepositive-heartbeat = true
failover-readonly-state = true
failover-event-scheduler = false
failover-event-status = false
failover-max-slave-delay = 30


autorejoin = true
# autorejoin-script = ""
autorejoin-semisync = true
autorejoin-backup-binlog = true

[Default]
#########
## LOG ##
#########
log-file = "/data/replication-manager/replication-manager.log"
log-heartbeat = false
log-syslog = false
monitoring-datadir = "/data/replication-manager"
log-level=1

replication-multi-master = false
replication-multi-tier-slave = false
failover-readonly-state = true
http-server = true
http-bind-address = "0.0.0.0"

**Comment by svaroqui** [comment]
hello look like you old master is ahead : Backup /usr/share/replication-manager/amd64/linux/mysqlbinlog /usr/share/replication-manager/amd64/linux/mysqlbinlog --read-from-remote-server --raw --stop-never-slave-server-id=10000 --user=root --password=XXXX --host=172.26.1.144 --port=3308 --result-file=/data/replication-manager/qiftest-server23- --start-position=514 3308-bin.000021" cluster=qiftest first you need to fix this by  installing a mariadb non started server binary and providing the path to mysqlbinlog on the replication-manager server also please take a backup of the master with replication-manager so that the cluster have 2 ways to flashback the old master , i suggest to use mydumper myloader as it's the only way not use cron jobs on each server that replication-manager need to restaure backups , i'll make a new release today as the release is little old , if want's to use mysqldump i advice to change the settings and remove --system-all parameter unless you use the very last mariadb release as some restore bugs have been fixed for system tables

**Comment by svaroqui** [comment]
Also it is advice to use semi sync replication to limit the need to flashback despite it does not limit it fully until https://jira.mariadb.org/browse/MDEV-18959 is entering the MariaDB trunk

**Comment by zhangcunhai** [comment]
> hello look like you old master is ahead : Backup /usr/share/replication-manager/amd64/linux/mysqlbinlog /usr/share/replication-manager/amd64/linux/mysqlbinlog --read-from-remote-server --raw --stop-never-slave-server-id=10000 --user=root --password=XXXX --host=172.26.1.144 --port=3308 --result-file=/data/replication-manager/qiftest-server23- --start-position=514 3308-bin.000021" cluster=qiftest first you need to fix this by installing a mariadb non started server binary and providing the path to mysqlbinlog on the replication-manager server also please take a backup of the master with replication-manager so that the cluster have 2 ways to flashback the old master , i suggest to use mydumper myloader as it's the only way not use cron jobs on each server that replication-manager need to restaure backups , i'll make a new release today as the release is little old , if want's to use mysqldump i advice to change the settings and remove --system-all parameter unless you use the very last mariadb release as some restore bugs have been fixed for system tables

Thank you very much for your reply,i will try this way latter.
