### ISSUE TITLE
a lot of 'No candidates found in slaves list' in the log

### ISSUE THREAD

**Issue by lenovore** [signal18/replication-manager#382]
**version: v2.0.2**

![QQ截图20210917091853](https://user-images.githubusercontent.com/29646774/133708637-5e5cad9d-37bd-40d5-8a86-4d74e153ea7c.png)
**configuration path**
![2](https://user-images.githubusercontent.com/29646774/133709547-5eaf1b73-2803-40a8-952a-c0fbe016afc6.png)
**configuration file**
[conf.zip](https://github.com/signal18/replication-manager/files/7181927/conf.zip)

Is there something wrong with my configuration or is it caused by other reasons?

**Comment by svaroqui** [comment]
Hi, 

Excepting a typo in config.toml -mode = "manual" that should probably be failover-mode 

2.0 is deprecated  ? Can you please try last 2.2 release ?
This message  comes on  simulation of the cluster failover capability  at every monitoring loop replication-manager order the slaves by Gtid and elect a candidate than look if it is the most up to date slave. When not it his failing. like  the second slave is ignored it is founding this one to be most up to date , i remember at some point to rig the  monitoring order for  prefered server first and than monitoring ignored server in a second loop to make sure regular monitoring without master failure stop printing such messages you are propbably not on that code base.

**Comment by svaroqui** [comment]
in new release please do not ignore node 3   but set the first 2 as prefered so that switchover always switch and switch back on them, ignored server are here for the case this server can never be a master because it does not have the capabilities to take over the traffic or does not have the full data , when it's the case and the ignored server is the most up to date than you will end up  probably electing a server behind and get data lost, if it is not ignored than the replication can produce switchover after  failover  once it get the events from the node 3 also note that semi-sync in most case until MariaDB 10.6 may also let the old master broken , on 10.6 this has been fixed as transaction in bin log not semi synced are purged on restart and this enable a failed master to reenter the cluster without any flashback

**Comment by lenovore** [comment]
Thanks Reply.

I use replication-manager just to do master-slave failover and integrate proxysql proxy.

The new version 2.2 adds too many features that I don’t need, and some documents have not been updated, such as routing. I’m not sure what configuration items are added in 2.2. I set monitoring-save-config = true and then on the web Modify the configuration dynamically to get all the configuration items.

And I also tested the 2.2 version, using proxysql and setting proxysql-bootstarp-users = false and proxysql-bootstrap = false did not work.

Incomplete documentation, too many features that I don’t need, test bugs, etc. These are the reasons why I don’t use version 2.2.

Additional 2.2 configuration
[v2.2 config.zip](https://github.com/signal18/replication-manager/files/7189053/v2.2.config.zip)

**Comment by svaroqui** [comment]
Please help us to identify what's wrong with the documentation, we are always willing to improve and help for deployment You don't need to use monitoring save confiig at all 

./replication-manager-osc --config etc/local/config.toml.osx  monitor --help

Will give you the list of all options 

What features you. do not need ?

Configurator: his is sad not ti use as both developers ex MySQL MariaDB employees follow best configurations practices 

Backup , you really get advantages to use them 
- We do use backup stage only available in MariaDB enterprise 
- We integrate best practices for valid non blocking backup for upgrade 
- We integrate mydumper as well 
- We archive backups with a policy, and can stream them to S3 

Ok multi source child  clusters may not be useful at first but may save your life in the future for sharding data when data become to big for memory or facing traffic increase 

A lot of code refactoring have been done in 2.2 
Now the best  reason to upgrade: end of life of 2.0 and all our clients are on 2.1 and 2.2 except one that is 50% still on 2.0   but have many deployments  

2.2 now default to 2.0 and every feature added as been disable by default to false 
For proxysql 

func (proxy *ProxySQLProxy) Init() {
	cluster := proxy.ClusterGroup
	if !cluster.Conf.ProxysqlBootstrap || !cluster.Conf.ProxysqlOn {
		return
       }


func (proxy *ProxySQLProxy) Refresh() error {

	// nothing should be done if no bootstrap
		if cluster.Conf.ProxysqlBootstrap {


This as been added only to 2.2 

So you can ask replication-manager to not correct a wrong proxysql configuration 

I agree that this code as change a lot during early release of 2.2 and also 2.1 but now it's stable an should not change much.

Can you please retest it and disable bootstrap if you found that it does not do the correct stuff , also this was improve for good reasons .
