### ISSUE TITLE
proxysql-bootstarp-users=false did not work

### ISSUE THREAD

**Issue by lenovore** [signal18/replication-manager#383]
**v2.2.10** 

**cluster config**

> [cluster_test]
> title = "cluster_test"
> db-servers-hosts = "172.16.20.186:3307,172.16.20.186:3308,172.16.20.186:3309,172.16.20.225:3307"
> db-servers-credential = "replmanager:replmanager"
> db-servers-connect-timeout = 2
> 
> proxysql = true
> proxysql-servers = "172.16.20.186"
> proxysql-port = "6000"
> proxysql-admin-port = "6032"
> proxysql-writer-hostgroup = "1000"
> proxysql-reader-hostgroup = "1001"
> proxysql-user = "remoteadmin"
> proxysql-password = "remoteadmin"
> proxy-servers-read-on-master = true
> proxysql-bootstrap = false
> proxysql-bootstrap-hostgroups = false
> proxysql-bootstarp-users = false
> proxysql-bootstrap-variables = false
> proxysql-bootstrap-query-rules = false
> proxysql-multiplexing = false

**log**

> time="2021-09-23 14:37:25" level=info msg="Replication-Manager started in daemon mode" version=v2.2.10
> time="2021-09-23 14:37:25" level=info msg="No existing password encryption scheme" error="Key file does not exist"
> time="2021-09-23 14:37:25" level=info msg="Failover in automatic mode" cluster=cluster_test
> time="2021-09-23 14:37:25" level=info msg="No existing password encryption scheme in LoadAPIUsers" cluster=cluster_test
> time="2021-09-23 14:37:26" level=info msg="Starting HTTPS & JWT API on 0.0.0.0:10005"
> time="2021-09-23 14:37:35" level=info msg="No database TLS certificates" cluster=cluster_test
> time="2021-09-23 14:37:35" level=info msg="No database previous TLS certificates" cluster=cluster_test
> time="2021-09-23 14:37:35" level=info msg="New proxy monitored proxysql: 172.16.20.186:6032" cluster=cluster_test
> time="2021-09-23 14:37:35" level=info msg="Loaded 1 proxies" cluster=cluster_test
> time="2021-09-23 14:37:35" level=info msg="No database TLS certificates" cluster=cluster_test
> time="2021-09-23 14:37:35" level=info msg="No database previous TLS certificates" cluster=cluster_test
> time="2021-09-23 14:37:35" level=info msg="No database TLS certificates" cluster=cluster_test
> time="2021-09-23 14:37:35" level=info msg="No database previous TLS certificates" cluster=cluster_test
> time="2021-09-23 14:37:35" level=info msg="No database TLS certificates" cluster=cluster_test
> time="2021-09-23 14:37:35" level=info msg="No database previous TLS certificates" cluster=cluster_test
> time="2021-09-23 14:37:35" level=info msg="Starting cluster scheduler" cluster=cluster_test
> time="2021-09-23 14:37:35" level=info msg="Schedule Sla rotate at: 0 0 0 1 * *" cluster=cluster_test
> time="2021-09-23 14:37:35" level=info msg="Assigning a global connection on server 172.16.20.225:3307" cluster=cluster_test
> time="2021-09-23 14:37:35" level=info msg="Assigning a global connection on server 172.16.20.186:3308" cluster=cluster_test
> time="2021-09-23 14:37:35" level=info msg="Assigning a global connection on server 172.16.20.186:3307" cluster=cluster_test
> time="2021-09-23 14:37:35" level=info msg="Assigning a global connection on server 172.16.20.186:3309" cluster=cluster_test
> time="2021-09-23 14:37:35" level=info msg="New proxy monitored: proxysql 172.16.20.186:6032" cluster=cluster_test
> time="2021-09-23 14:37:38" level=info msg="Add ProxySQL user proxysql_rw " cluster=cluster_test
> time="2021-09-23 14:37:38" level=info msg="Add ProxySQL user inception_check " cluster=cluster_test
> time="2021-09-23 14:37:38" level=info msg="Add ProxySQL user huc " cluster=cluster_test
> time="2021-09-23 14:37:38" level=info msg="Add ProxySQL user replmanager " cluster=cluster_test
> time="2021-09-23 14:37:38" level=info msg="Add ProxySQL user inception_exec " cluster=cluster_test

**web settings**

![image](https://user-images.githubusercontent.com/29646774/134465297-b66fc99c-a5af-4177-a9ba-825af507a69a.png)

**Comment by lenovore** [comment]
After startup, although proxysql-bootstarp-users=false is set in the configuration file, it is not used. This can be confirmed through web settings and logs. Other proxysql-bootstrap variables are normal.

**Comment by svaroqui** [comment]
Hey , welcome to 2.2 :) 

This is probably an effect of the old settings monioring-save-config , can you stop replication-manager go to /var/lib/replication/cluster_test and delete the content of this directory before restart and let me know if that works , the cluster config was saved here in a json file config.toml

**Comment by svaroqui** [comment]
proxysql-bootstarp-users = false 

Also there is a typo here

s/bootstarp/bootstrap/g

**Comment by lenovore** [comment]
i was not careful, it was indeed a typo!  thanks，I continue to test

**Comment by svaroqui** [comment]
Are you intrested in automatic mariadb config  ? 

2.2 can do this by ssh to to db nodes and also start the server , this enable rolling restart capabilities

**Comment by lenovore** [comment]
Whether to automatically configure all parameters or some special parameters, such as read_only

**Comment by svaroqui** [comment]
It configure all parameters based on the input you provide in the configurator or via config file  , the default is very close to the best settings and practice we learn here

**Comment by svaroqui** [comment]
I see you have multiple instances on the same node , this is not  valid for auto configure via ssh. Is this just for testing ? your next step to pick some prefered master you can set :
db-servers-prefered-master = "172.16.20.186:3307,172.16.20.186:3308"

**Comment by svaroqui** [comment]
if you don't use replication-manager configurator to bootstrap db config than make sure read_only is set in db config as a restart of one server should always bring back the db in readonly for proyysql

**Comment by lenovore** [comment]
Yes, this configuration is only for testing, but we also have applications that deploy multiple mariadb instances on the same host

Is the database replication_manager_schema created because monitoring-scheduler=true is set? In fact, I don’t need this feature, but if monitoring-scheduler=false, the following problems will occur https://github.com/signal18/replication-manager/issues/260

**Comment by svaroqui** [comment]
yes replication_manager_schema  is created for 
- trigger task to bash scripts jobs deployed and run via ssh
  (error and slow log reporting to replication-manager, backup to be restored or send to replication-manager etc...)   
- to hold pseudo-gtid heartbeat
- to hold sysbench data 
- to possibly hold futur analyses of queries and data distribution 

The tasks put in the kjob table are not replicated as set sql_log_bin=0

**Comment by lenovore** [comment]
I may not need replication_manager_schema for some database instances. As I said above, how can I not create this db without affecting the normal operation of replication-manager?

**Comment by svaroqui** [comment]
I don't know about #260 but  i think it's ok to set monitoring-scheduler=false and than if you don't use the traffic menu or traffic api call than you should not get that schema it yes please open an issue i will fix it

**Comment by lenovore** [comment]
ok,thanks! i will close this issue.

**Comment by svaroqui** [comment]
Also note that the replication_manager_schema is also used in some complex switchover scenario and some API operation like stopping all slaves on same master position, i need a database to generate a gtid in the cluster but can probably replace it by a user choice parameter this is a request upstream to mariadb and mysql to provide such SQL that is in pending mode so far

**Comment by lenovore** [comment]
Okay, thanks for the reminder, I need more testing and documentation review
