### ISSUE TITLE
replication-manager command

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#400]
Hi.
Up to replication-manager 2.2.8, Generate a new encryption key.
[keygen] and [password] commands were available.
As of replication-manager 2.2.9, there is no such command.
Check why you can't use this . 
Should I use a different method?

**Comment by svaroqui** [comment]
Thanks for reporting i'm able to do this from the 2.2 source code manual compile

**Comment by svaroqui** [comment]
```
apple@mars replication-manager % sudo ./replication-manager-osc  keygen 
Password:
apple@mars replication-manager % sudo ./replication-manager-osc password mysecret  
Encrypted password hash: 0b99f6468c5872b5e10ee3971c159fb09ee9cec47f8f0803
```
Can you let me know witch command just changed  for you ? There is a new release 2.2.14 but i don't think it has an impact on this code

**Comment by nyxneuf** [comment]
![20220221_200946](https://user-images.githubusercontent.com/33710188/155088788-8a117dbd-c332-4295-9cab-fb5a0ec6eba8.png)

Not such command. keygen and password

**Comment by nyxneuf** [comment]
Remove the top 3 lines of the password.go file and build it,
After installing, a command will appear.

[password.go](https://github.com/signal18/replication-manager/blob/v2.2.15/password.go)
1 //go:build server
2 // +build server
3
.
I do not know why!!

**Comment by svaroqui** [comment]
Nice catch nyxneuf i was scratching my head on this thanks

**Comment by svaroqui** [comment]
That's some conditional compilation may this was to remove it from the client

**Comment by nyxneuf** [comment]
Thanks~ :)

**Comment by svaroqui** [comment]
Should now be in repos as of v2.2.16
