### ISSUE TITLE
document is not available

### ISSUE THREAD

**Issue by wonderisland** [signal18/replication-manager#401]
document website： https://docs.signal18.io/
can not visit， http status code 521 
could any guys help me？

![image](https://user-images.githubusercontent.com/5255905/153818835-96de0eee-6b9a-4ce7-8fb8-110c4a65aa6d.png)

**Comment by svaroqui** [comment]
Hello wonderisland, we changed  our jenkins config this Weekend and get this bad side effect,  thanks for reporting it it should be fixed now .
