### ISSUE TITLE
Why all  CMD command prompt invalid character 'E' ”errors

### ISSUE THREAD

**Issue by tanglu86** [signal18/replication-manager#402]
When I run all  CMD command, the following prompts appear：error="invalid character 'E' looking for beginning of value"：
![1](https://user-images.githubusercontent.com/38269740/154431905-3224a0a2-5df0-47c9-9578-4a84b8802179.png)

My profile:
![2](https://user-images.githubusercontent.com/38269740/154432075-f5401149-9913-4f01-ac51-4d334de8382d.png)

**Comment by svaroqui** [comment]
Hi Tanglu this has been fixed sorry can you run he last 2.2 release

**Comment by tanglu86** [comment]
> Hi Tanglu this has been fixed sorry can you run he last 2.2 release

my replication-manager version  is 2.2.13

**Comment by svaroqui** [comment]
Yes that a broken one , please use 2.2.14  let me know if 2.2.13 is the last in the repo but it should not be

**Comment by tanglu86** [comment]
> Yes that a broken one , please use 2.2.14 let me know if 2.2.13 is the last in the repo but it should not be

![3](https://user-images.githubusercontent.com/38269740/154436221-a5a6c723-ef92-47bb-9b68-c49e88846f4a.png)
yum repo version is 2.2.13

**Comment by svaroqui** [comment]
Ok Guillaume we fix the repo today we'll let you know when it's done

**Comment by svaroqui** [comment]
Ok this should be in the repo now

**Comment by tanglu86** [comment]
thank you very much !
