### ISSUE TITLE
User must have REPLICATION SLAVE privilege

### ISSUE THREAD

**Issue by tanglu86** [signal18/replication-manager#403]
MASTER：172.20.1.190
SLAVE：172.20.1.191
Both MASTER and SLAVE  have a repl account and permission to replicate：
mysql> grant REPLICATION SLAVE,REPLICATION CLIENT on *.* to 'repl'@'172.20.'%;
When I visit  HTTP  always see errors

![企业微信截图_20220218113458](https://user-images.githubusercontent.com/38269740/154612693-e10b59a7-908c-4abb-ba1f-962c36ce98bd.png)

Can you help me ,thank you

**Comment by svaroqui** [comment]
Hi, 'repl'@'172.20.'%; should  it be to  'repl'@'172.20.%'; instead or is this a copy past issue ?

**Comment by tanglu86** [comment]
> mysql> grant REPLICATION SLAVE,REPLICATION CLIENT on _._ to 'repl'@'172.20.'%;


The command I actually run is 'mysql> grant REPLICATION SLAVE,REPLICATION CLIENT on . to 'repl'@'172.20.%';
', but this error still exists on the console

**Comment by tanglu86** [comment]
> Hi, 'repl'@'172.20.'%; should it be to 'repl'@'172.20.%'; instead or is this a copy past issue ?

Can you tell me which account has the permission problem？
Neither "replication-credential"  or "db-servers-credential"  has "replication slave,replication client" permission
thank you !
![1](https://user-images.githubusercontent.com/38269740/154652902-9ebf6698-bbfb-49e1-bed5-bd0ef55273af.png)
![2](https://user-images.githubusercontent.com/38269740/154653010-2b5ef245-f79b-4093-b9b0-7b0e4b49625b.png)

**Comment by svaroqui** [comment]
please see the issue 127.20.%  is not a valid network for replication-manager it check only for 127.20.1 .%  or 127.20.% .% or  127.%.%.%  or '%'

**Comment by svaroqui** [comment]
may be i can add those extra to fixe your case

**Comment by tanglu86** [comment]
> please see the issue 127.20.% is not a valid network for replication-manager it check only for 127.20.1 .% or 127.20.% .% or 127.%.%.% or '%'

It's work successful ! thank you!

**Comment by svaroqui** [comment]
Next release will also check for 127.20.% :) thanks for reporting
