### ISSUE TITLE
how to build replication-manager on CentOS AltArch7 (kernel 5.4.125-200.el7.aarch64)

### ISSUE THREAD

**Issue by lynn447742** [signal18/replication-manager#404]
Hi：
I need to run replication-manager on `CentOS AltArch7 (kernel 5.4.125-200.el7.aarch64)`.
I refer to #356，tried `https://ci.signal18.io/mrm/builds/2.1`, but failed.
can you provide RPM or binary on the version? 
thanks!!!

**Comment by tanji** [comment]
Hello,

you can look here: https://github.com/signal18/replication-manager/releases/tag/v2.2.15 
For latest release including aarch64

Regards
