### ISSUE TITLE
“ No log of replication queries in slow query ” question

### ISSUE THREAD

**Issue by tanglu86** [signal18/replication-manager#405]
I do not understand the meaning of "No log of replication queries in slow query", why do I need replication queries in slowlog?
How can I fix it?I hope to get your reply. Thank you very much
![企业微信截图_20220222103853](https://user-images.githubusercontent.com/38269740/155053330-15a7291a-28ad-482f-bdbb-96f913250fb9.png)

it's my profile:

[test1]
title = "test1"
db-servers-hosts = "172.20.1.190:3306,172.20.1.191:3306"
db-servers-prefered-master = "172.20.1.190:3306"
db-servers-credential = “root:123456"
db-servers-connect-timeout = 10
replication-credential = "repl:123456"

verbose = 1 
log-failed-election  = true
log-level = 7
log-rotate-max-age = 7
log-rotate-max-backup = 7
log-rotate-max-size = 5
log-sql-in-monitoring   = true
log-sst = true

replication-multi-master = false
replication-multi-tier-slave = false

monitoring-scheduler = false
scheduler-db-servers-logical-backup  = false
scheduler-db-servers-logical-backup-cron= "0 0 1 * * 6"
scheduler-db-servers-logs   =  false
scheduler-db-servers-logs-cron = "0 0 * * * *"
scheduler-db-servers-logs-table-keep = 4
scheduler-db-servers-logs-table-rotate  = false
scheduler-db-servers-logs-table-rotate-cron = "0 0 0/6 * * *"
scheduler-db-servers-optimize  = false
scheduler-db-servers-optimize-cron = "0 0 3 1 * 5"
scheduler-db-servers-physical-backup = false
scheduler-db-servers-physical-backup-cron = "0 0 0 * * *"

failover-mode = "manual"
failover-pre-script = ""
failover-post-script = ""
failover-readonly-state = true
failover-max-slave-delay = 0
failover-event-scheduler = false
failover-event-status = false
failover-falsepositive-ping-counter = 30
failover-falsepositive-heartbeat = true
failover-limit = 0
failover-time-limit = 1800
failover-at-sync = false
failover-restart-unsafe = false
switchover-wait-kill = 10000
switchover-wait-trx = 10
switchover-wait-write-query = 10
switchover-at-equal-gtid = false
switchover-at-sync = false
switchover-max-slave-delay = 30
autorejoin = true
autorejoin-script = ""
autorejoin-semisync = true
autorejoin-backup-binlog = false
autorejoin-flashback = false
autorejoin-mysqldump = false
check-replication-filters = true
check-binlog-filters = true
check-replication-state = true
force-slave-heartbeat= false
force-slave-heartbeat-retry = 5
force-slave-heartbeat-time = 3
force-slave-gtid-mode = false
force-slave-semisync = false
force-slave-failover-readonly-state = false
force-binlog-row = false
force-binlog-annotate = false
force-binlog-slowqueries = false
force-binlog-compress = false
force-binlog-checksum = false
force-inmemory-binlog-cache-size = false
force-disk-relaylog-size-limit = false
force-disk-relaylog-size-limit-size = 1000000000
force-sync-binlog = false
force-sync-innodb = false

**Comment by svaroqui** [comment]
return server.Variables["LOG_SLOW_SLAVE_STATEMENTS"] == "ON"

**Comment by tanglu86** [comment]
> 

Now it's working normally  !  thank you
