### ISSUE TITLE
develop build error

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#409]
[root@TMRM replication-manager]# ./package_linux.sh 
# Getting branch info
## develop...origin/develop
# Building for amd64
env GOOS=linux GOARCH=amd64 go build -v --tags "server" --ldflags "-extldflags '-static' -w -s -X server.Version=v2.2.16 -X server.FullVersion=v2.2.16-10-g50440a37 -X server.Build=2022-03-04T10:08:40+0900 -X server.WithProvisioning=OFF "   -o build/binaries/replication-manager-osc
github.com/signal18/replication-manager/cluster
github.com/signal18/replication-manager/regtest
github.com/signal18/replication-manager/server
github.com/signal18/replication-manager
env GOOS=linux GOARCH=amd64  go build -v --tags "server" --ldflags "-w -s -X server.Version=v2.2.16 -X server.FullVersion=v2.2.16-10-g50440a37 -X server.Build=2022-03-04T10:08:49+0900   -X server.WithDeprecate=OFF"   -o build/binaries/replication-manager-tst
env GOOS=linux GOARCH=amd64  go build -v --tags "server" --ldflags "-w -s -X server.Version=v2.2.16 -X server.FullVersion=v2.2.16-10-g50440a37 -X server.Build=2022-03-04T10:08:50+0900 -X server.WithOpenSVC=ON  "   -o build/binaries/replication-manager-pro
env CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -v --tags "server" --ldflags "-extldflags '-static' -w -s -X server.Version=v2.2.16 -X server.FullVersion=v2.2.16-10-g50440a37 -X server.Build=2022-03-04T10:08:52+0900 -X server.WithProvisioning=OFF "   -o build/binaries/replication-manager-osc-cgo
env GOOS=linux GOARCH=amd64  go build -v --tags "server"  --ldflags "-extldflags '-static' -w -s -X server.WithTarball=ON -X server.Version=v2.2.16 -X server.FullVersion=v2.2.16-10-g50440a37 -X server.Build=2022-03-04T10:08:54+0900 -X server.WithProvisioning=OFF "   -o build/binaries/replication-manager-osc-basedir
env GOOS=linux GOARCH=amd64  go build -v --tags "server"  --ldflags "-w -s -X server.WithTarball=ON -X server.Version=v2.2.16 -X server.FullVersion=v2.2.16-10-g50440a37 -X server.Build=2022-03-04T10:08:56+0900   -X server.WithDeprecate=OFF"   -o build/binaries/replication-manager-tst-basedir
env GOOS=linux GOARCH=amd64  go build -v --tags "server" --ldflags "-w -s -X server.WithTarball=ON -X server.Version=v2.2.16 -X server.FullVersion=v2.2.16-10-g50440a37 -X server.Build=2022-03-04T10:08:58+0900 -X server.WithOpenSVC=ON  "   -o build/binaries/replication-manager-pro-basedir
env CGO_ENABLED=1 GOOS=linux GOARCH=amd64  go build -v --tags "server" --ldflags "-extldflags '-static' -w -s -X server.WithTarball=ON -X server.Version=v2.2.16 -X server.FullVersion=v2.2.16-10-g50440a37 -X server.Build=2022-03-04T10:09:00+0900 -X server.WithProvisioning=OFF "   -o build/binaries/replication-manager-osc-cgo-basedir
env GOOS=linux GOARCH=amd64  go build -v --tags "clients" --ldflags "-w -s -X clients.Version=v2.2.16 -X clients.FullVersion=v2.2.16-10-g50440a37 -X clients.Build=2022-03-04T10:09:01+0900"   -o build/binaries/replication-manager-cli
github.com/signal18/replication-manager/server
github.com/signal18/replication-manager/clients
github.com/signal18/replication-manager
env GOOS=linux GOARCH=amd64  go build -v --tags "arbitrator" --ldflags "-w -s -X arbitrator.Version=v2.2.16 -X arbitrator.FullVersion=v2.2.16-10-g50440a37 -X arbitrator.Build=2022-03-04T10:09:05+0900"    -o build/binaries/replication-manager-arb
github.com/signal18/replication-manager/arbitrator
# github.com/signal18/replication-manager/arbitrator
arbitrator/arbitrator_cmd.go:56:39: undefined: cfgGroup
make: *** [Makefile:57: arb] 오류 2

arbitrator_cmd.go

56 - rootCmd.PersistentFlags().StringVar(&cfgGroup, "cluster", "", "Configuration group (default is none)")

**Comment by svaroqui** [comment]
this will be fixed in next release already in git
