### ISSUE TITLE
2.2.16 failover command issue

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#410]
SRM : 2.2.16

![1](https://user-images.githubusercontent.com/33710188/156702698-981506a6-8288-404c-a9ed-627ece4d2fcb.png)

[root@mrm /]# replication-manager-cli failover
Enter Password: | Group: cluster_mariadb |  Mode: Manual 
                 Id            Host   Port          Status   Failures   Using GTID         Current GTID           Slave GTID             Replication Health  Delay  RO
db12687750588917314080   192.168.50.11  43306          Master          0           No           0-1-821942           0-2-821941                                     0 OFF
db1341665945707207274   192.168.50.12  43306           Slave          0  Current_Pos           0-1-821942           0-1-821942                                     0  ON
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:58 [cluster_mariadb] INFO  - Master switch on 192.168.50.12:43306 complete 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:58 [cluster_mariadb] INFO  - Switching other slaves to the new master 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:58 [cluster_mariadb] INFO  - Inject fake transaction on new master 192.168.50.12:43306  
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:56 [cluster_mariadb] INFO  - Waiting 2s for unmanaged proxy to monitor route change 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:56 [cluster_mariadb] INFO  - Failover proxies 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:56 [cluster_mariadb] INFO  - Resetting slave on new master and set read/write mode on 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:56 [cluster_mariadb] INFO  - Stopping slave threads on new master 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:56 [cluster_mariadb] INFO  - Reading all relay logs on 192.168.50.12:43306 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:56 [cluster_mariadb] INFO  - Waiting for candidate master 192.168.50.12:43306 to apply relay log 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:56 [cluster_mariadb] INFO  - Slave 192.168.50.12:43306 has been elected as a new master 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:56 [cluster_mariadb] INFO  - Election matrice: [
	{
		"URL": "192.168.50.12:43306",
		"Indice": 0,
		"Pos": 175000000001897,
		"Seq": 821942,
		"Prefered": false,
		"Ignoredconf": false,
		"Ignoredrelay": false,
		"Ignoredmultimaster": false,
		"Ignoredreplication": false,
		"Weight": 0
	}
]  
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:56 [cluster_mariadb] INFO  - Electing a new master 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:56 [cluster_mariadb] INFO  - ------------------------ 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:56 [cluster_mariadb] INFO  - Starting master failover 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:56 [cluster_mariadb] INFO  - ------------------------ 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:16 [cluster_mariadb] STATE - RESOLV ERR00021 : Cluster state down 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:14 [cluster_mariadb] STATE - OPENED WARN0070 : No GTID strict mode on master 192.168.50.11:43306 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:14 [cluster_mariadb] STATE - OPENED WARN0068 : No compression of binlog on slave 192.168.50.11:43306 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:14 [cluster_mariadb] STATE - OPENED WARN0056 : No compression of binlog on slave 192.168.50.12:43306 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:14 [cluster_mariadb] STATE - OPENED WARN0058 : No GTID strict mode on slave 192.168.50.12:43306 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:14 [cluster_mariadb] STATE - RESOLV ERR00032 : No candidates found in slaves list 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:14 [cluster_mariadb] STATE - RESOLV ERR00012 : Could not find a master in topology 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:14 [cluster_mariadb] STATE - RESOLV ERR00010 : Could not find a slave in topology 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:12 [cluster_mariadb] INFO  - Election matrice: []  
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:12 [cluster_mariadb] INFO  - Assigning a global connection on server 192.168.50.12:43306 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:12 [cluster_mariadb] INFO  - Assigning a global connection on server 192.168.50.11:43306 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:12 [cluster_mariadb] INFO  - Loaded 0 proxies 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:12 [cluster_mariadb] INFO  - No database previous TLS certificates 
INFO[2022-03-04T14:01:58+09:00]  2022-03-04 14:01:12 [cluster_mariadb] INFO  - No database TLS certificates 
| Group: cluster_mariadb |  Mode: Manual 
                 Id            Host   Port          Status   Failures   Using GTID         Current GTID           Slave GTID             Replication Health  Delay  RO
db12687750588917314080   192.168.50.11  43306          Master          0           No           0-1-821942           0-2-821941                                     0 OFF
db1341665945707207274   192.168.50.12  43306          Master          0  Current_Pos           0-1-821942           0-1-821942                                     0  ON

![2](https://user-images.githubusercontent.com/33710188/156702752-c6cefdd8-cfab-4d9c-b157-d616c0207563.png)

Old Master rejoin failed!!

**Comment by svaroqui** [comment]
HI Nyxneuf thanks that's expected i never worked on this you should switchover on a valid topology as failover does not take care at the old master , but i thinks we can escalade  failover to switchover  if the topology get a valid master this may indeed prevent such case

**Comment by nyxneuf** [comment]
ok. I understand!
Then, the failover command should be executed when the master has a problem.
