### ISSUE TITLE
2.2.16 replication-manager start error

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#411]
SRM : 2.2.16
3node : M-S-S

extproxy = true

-- log --

Mar  7 10:36:00 mrm replication-manager-osc: time="2022-03-07T10:36:00+09:00" level=info msg="New proxy monitored extproxy: 192.168.50.100:53306" cluster=cluster_mysql53306
Mar  7 10:36:00 mrm replication-manager-osc: time="2022-03-07T10:36:00+09:00" level=info msg="Loaded 1 proxies" cluster=cluster_mysql53306
Mar  7 10:36:00 mrm replication-manager-osc: time="2022-03-07T10:36:00+09:00" level=info msg="Assigning a global connection on server 192.168.50.12:53306" cluster=cluster_mysql53306
Mar  7 10:36:00 mrm replication-manager-osc: time="2022-03-07T10:36:00+09:00" level=info msg="Assigning a global connection on server 192.168.50.11:53306" cluster=cluster_mysql53306
Mar  7 10:36:00 mrm replication-manager-osc: time="2022-03-07T10:36:00+09:00" level=info msg="New proxy monitored: extproxy 192.168.50.100:53306" cluster=cluster_mysql53306
Mar  7 10:36:00 mrm replication-manager-osc: panic: runtime error: invalid memory address or nil pointer dereference
Mar  7 10:36:00 mrm replication-manager-osc: [signal SIGSEGV: segmentation violation code=0x1 addr=0x180 pc=0x18e9352]
Mar  7 10:36:00 mrm replication-manager-osc: goroutine 77 [running]:
Mar  7 10:36:00 mrm replication-manager-osc: github.com/signal18/replication-manager/cluster.(*Proxy).Init(0xc000177880)
Mar  7 10:36:00 mrm replication-manager-osc: <autogenerated>:1 +0x32
Mar  7 10:36:00 mrm replication-manager-osc: github.com/signal18/replication-manager/cluster.(*Cluster).initProxies(0xc0002b8000)
Mar  7 10:36:00 mrm replication-manager-osc: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/prx.go:371 +0x22c
Mar  7 10:36:00 mrm replication-manager-osc: github.com/signal18/replication-manager/cluster.(*Cluster).Run(0xc0002b8000)
Mar  7 10:36:00 mrm replication-manager-osc: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/cluster.go:445 +0x490
Mar  7 10:36:00 mrm replication-manager-osc: created by github.com/signal18/replication-manager/server.(*ReplicationManager).StartCluster
Mar  7 10:36:00 mrm replication-manager-osc: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/server/server.go:647 +0x545
Mar  7 10:36:00 mrm systemd: replication-manager.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Mar  7 10:36:00 mrm systemd: Unit replication-manager.service entered failed state.
Mar  7 10:36:00 mrm systemd: replication-manager.service failed.
Mar  7 10:36:01 mrm systemd: replication-manager.service holdoff time over, scheduling restart.
Mar  7 10:36:01 mrm systemd: Stopped replication-manager open source.
Mar  7 10:36:01 mrm systemd: Started replication-manager open source.
Mar  7 10:36:01 mrm replication-manager-osc: time="2022-03-07T10:36:01+09:00" level=info msg="Reading default section include directory: /etc/replication-manager/cluster.d"
Mar  7 10:36:01 mrm replication-manager-osc: time="2022-03-07T10:36:01+09:00" level=warning msg="No monitoring-save-config variable in default section config change lost on restart"
Mar  7 10:36:01 mrm replication-manager-osc: time="2022-03-07T10:36:01+09:00" level=info msg="Cluster discover from config: cluster_mysql53306"
Mar  7 10:36:01 mrm replication-manager-osc: time="2022-03-07T10:36:01+09:00" level=info msg="Replication-Manager started in daemon mode" version=v2.2.16
Mar  7 10:36:01 mrm replication-manager-osc: time="2022-03-07T10:36:01+09:00" level=info msg="Failover in automatic mode" cluster=cluster_mysql53306
Mar  7 10:36:01 mrm replication-manager-osc: 2022/03/07 10:36:01 ERROR: ciphertext too short
Mar  7 10:36:01 mrm replication-manager-osc: 2022/03/07 10:36:01 ERROR: ciphertext too short
Mar  7 10:36:01 mrm replication-manager-osc: time="2022-03-07T10:36:01+09:00" level=info msg="No SSL certificate provided using insecured from /app/mrm/share/server.crt"
Mar  7 10:36:01 mrm replication-manager-osc: time="2022-03-07T10:36:01+09:00" level=info msg="Starting HTTPS & JWT API on 0.0.0.0:10005"
Mar  7 10:36:01 mrm replication-manager-osc: time="2022-03-07T10:36:01+09:00" level=info msg="starting multiplexed TLS HTTP/2.0 and HTTP/1.1 Gateway server: 0.0.0.0:10005"
Mar  7 10:36:01 mrm replication-manager-osc: 2022/03/07 10:36:01 http: TLS handshake error from 127.0.0.1:52224: remote error: tls: bad certificate
Mar  7 10:36:01 mrm replication-manager-osc: 2022/03/07 10:36:01 http: TLS handshake error from 127.0.0.1:52222: remote error: tls: bad certificate

**Comment by svaroqui** [comment]
Thanks this will be fixed in next release
