### ISSUE TITLE
2.2.17 replication-manager-cli  unknown flag

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#414]
[root@mrm mrm]# replication-manager-cli console --help
Connect to replication-manager in stateful TLS JWT mode.

Usage:
  replication-manager-cli console [flags]

Flags:
  -h, --help   help for console

=========================================

[root@mrm mrm]# replication-manager-cli topology --help
Print the replication topology by detecting master and slaves

Usage:
  replication-manager-cli topology [flags]

Flags:
  -h, --help   help for topology

==========================================

[root@mrm cluster.d]# replication-manager-cli console --cluster=cluster_mysql33307
Error: unknown flag: --cluster
Usage:
  replication-manager-cli console [flags]

Flags:
  -h, --help   help for console

unknown flag: --cluster
[root@mrm cluster.d]# replication-manager-cli topology --cluster=cluster_mysql33307
Error: unknown flag: --cluster
Usage:
  replication-manager-cli topology [flags]

Flags:
  -h, --help   help for topology

unknown flag: --cluster

=========================

[root@mrm cluster.d]# replication-manager-cli switchover --help
Performs an online master switch by promoting a slave to master
and demoting the old master to slave

Usage:
  replication-manager-cli switchover [flags]

Flags:
      --cert string                         Public certificate
      --db-servers-prefered-master string   Database preferred candidate in election,  host:[port] format
  -h, --help                                help for switchover
      --host string                         Host of replication-manager (default "127.0.0.1")
      --insecure                            Don't check certificate (default true)
      --password string                     Paswword of replication-manager (default "repman")
      --port string                         TLS port of  replication-manager (default "10005")
      --user string                         User of replication-manager (default "admin")
[root@mrm cluster.d]# 
[root@mrm cluster.d]# 
[root@mrm cluster.d]# replication-manager-cli failover --help
Trigger failover on a dead master by promoting a slave.

Usage:
  replication-manager-cli failover [flags]

Flags:
      --cert string       Public certificate
  -h, --help              help for failover
      --host string       Host of replication-manager (default "127.0.0.1")
      --insecure          Don't check certificate (default true)
      --password string   Paswword of replication-manager (default "repman")
      --port string       TLS port of  replication-manager (default "10005")
      --user string       User of replication-manager (default "admin")
=========================================================

Global Flags not found!!

Global Flags:
      --cluster string      Configuration group (default is none)
      --config string       Configuration file (default is config.toml)
      --memprofile string   Write a memory profile to a file readable by pprof (default "/tmp/repmgr.mprof")
      --verbose             Print detailed execution info

**Comment by svaroqui** [comment]
Thanks i'll look at this
