### ISSUE TITLE
Website is down....

### ISSUE THREAD

**Issue by rhurup** [signal18/replication-manager#416]
I was trying to contact you guys but i get errors all around you website.

![Skærmbillede 2022-03-24 kl  11 48 22](https://user-images.githubusercontent.com/43495471/159900776-f398aef5-1fd9-4b64-ab74-75c59cd015e8.png)
![Skærmbillede 2022-03-24 kl  11 47 41](https://user-images.githubusercontent.com/43495471/159900785-c6136e1a-fdba-4149-b4f0-20308c5723e0.png)

I'm interested in a price on a Pro subscription.

**Comment by tanji** [comment]
Hi @rhurup please write to contact at signal18.io 

Thanks for reporting the errors, we will fix them

**Comment by rhurup** [comment]
Thanks @tanji - Mail is sent :)
