### ISSUE TITLE
Race condition when fail-over chlid cluster

### ISSUE THREAD

**Issue by rdemongeot** [signal18/replication-manager#417]
Hello,

As discussed per Skype, we have found a possible race condition when fail-over a child cluster.

```
Parent-stream1 --------+
                                   +-->  child-s1 (old primary) --------> child-s2 (new primary)
Parent-stream2 --------+
```

to migrate to 

```
Parent-stream1 --------+
                                   +-->  child-s2 (new primary) --------> child-s1 (old primary)
Parent-stream2 --------+
```

During the operation, the child S1 was reconfigured with "MASTER_USE_GTID=CURRENT_POS" (expected)
but REJOIN Module reconfigure it as "MASTER_USE_GTID=SLAVE_POS" making search for a very old GTID not found into the new primary binary log.

**Comment by svaroqui** [comment]
Please reopen if not fixed
