### ISSUE TITLE
Optimization : add an option to autoload master in proxy read group when no more slaves available

### ISSUE THREAD

**Issue by rdemongeot** [signal18/replication-manager#418]
Aim : 
Be able to halt a slave without any production issue.

Setup : 
Primary/secondary cluster with proxy SQL as request routers.
One of proxy SQL is dedicated for read-only and point to only hostgroup 1. (composed from 1 server, the secondary).

If we need to have a maintenance onto the secondary server (add memory, or just reboot), we need to pass the cluster as "degraded", and so : 

1. stop Replication manager
2. add the primary as tempoary reader
3. Put the secondary as offline_soft
4. when no traffic : stop mariadb on the secondary
5. and then halt the server and take maintenance.

After that, we need to do the resume with other order.

It should be interesting to have a button who deal with actions 2 and 3 - that permit to keep Replication manager started during the work.

Regards;

**Comment by rdemongeot** [comment]
Erratum : It's possible to add flag : "readonmaster" but there is no option to delcare a server as "OFFLINE_SOFT" onto ProxySQL

**Comment by svaroqui** [comment]
I have added a flag 
`--proxy-servers-read-on-master-no-slave  (default true)`
And a cluster state as a warning 
`WARN[2022-04-13T11:34:32+02:00] No replica found for routing reads            cluster=bench code=ERR00085 status=OPENED type=state` 
Tracking this state in ProxySQL monitoring to add or remove the master according 

What disqualify a slave as possible reader are :

- No SQL thread running 
- A failed Slave
- Ignored Slave 
- Slave in Maintenance

We keep slave for reading when delayed ( this can be setup in proxysql monitor) or IO thread issues to avoid overloading the leader in case of network issue or long replication operations like alter table copy .
