### ISSUE TITLE
Could not get event status Percona 8

### ISSUE THREAD

**Issue by GarrettQi** [signal18/replication-manager#419]
If the database version is version Percona 8.0.19-10, an error is reported.

logfile:
time="2022-03-15 16:25:28" level=error msg="Could not get events status host:port Could not get event status" cluster=dbatest-003 error="Could not get event status" module=Monitor server="host:port" sql="SELECT db as Db, name as Name, definer as Definer, status+0  AS Status FROM mysql.event"

database version:
![image](https://user-images.githubusercontent.com/18721697/162415367-6d4fd2f8-4b0a-4bd9-8208-51f3f1a8d7f1.png)

replication-manager：dbhelper.go
![image](https://user-images.githubusercontent.com/18721697/162415503-a83ba1a4-c1d0-4e1b-b10e-21a2a4b4ac35.png)

**Comment by svaroqui** [comment]
Hey thanks for reporting we will sure fixed this for next minor release !

**Comment by svaroqui** [comment]
Please reopen if not fixed
