### ISSUE TITLE
build error 2.2.19

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#420]
![20220414_094046](https://user-images.githubusercontent.com/33710188/163291971-82980da1-ca2b-4aea-949d-27b446a5560f.png)

**Comment by svaroqui** [comment]
Hi nyxneuf,  what is your go version , we use go embed that was released last year

**Comment by nyxneuf** [comment]
[root@TMRM replication-manager]# go version
go version go1.16.12 linux/amd64
[root@TMRM replication-manager]# rpm -qa | grep golang
golang-bin-1.16.12-1.module+el8.5.0+720+c057d5cf.x86_64
golang-misc-1.16.12-1.module+el8.5.0+720+c057d5cf.noarch
golang-src-1.16.12-1.module+el8.5.0+720+c057d5cf.noarch
golang-race-1.16.12-1.module+el8.5.0+720+c057d5cf.x86_64
golang-1.16.12-1.module+el8.5.0+720+c057d5cf.x86_64
golang-docs-1.16.12-1.module+el8.5.0+720+c057d5cf.noarch
golang-tests-1.16.12-1.module+el8.5.0+720+c057d5cf.noarch
[root@TMRM replication-manager]# 
[root@TMRM replication-manager]# cat /etc/redhat-release 
Rocky Linux release 8.5 (Green Obsidian)
[root@TMRM replication-manager]#

**Comment by svaroqui** [comment]
Oups can you retry now i was missing a file in this release

**Comment by nyxneuf** [comment]
build success~ Thanks! :)

**Comment by svaroqui** [comment]
Great many thanks for pointing this out
