### ISSUE TITLE
make osc failed

### ISSUE THREAD

**Issue by GarrettQi** [signal18/replication-manager#421]
[root@mysql101 replication-manager]# make osc
env GOOS=linux GOARCH=amd64 go build -v --tags "server" --ldflags "-extldflags '-static' -w -s -X github.com/signal18/replication-manager/server.Version=v2.2.19 -X github.com/signal18/replication-manager/server.FullVersion=v2.2.19 -X github.com/signal18/replication-manager/server.Build=2022-04-14T12:26:03+0800 -X github.com/signal18/replication-manager/server.WithProvisioning=OFF "   -o build/binaries/replication-manager-osc
cluster/configurator/configurator.go:23:2: no required module provides package github.com/signal18/replication-manager/share; to add it:
	go get github.com/signal18/replication-manager/share
make: *** [osc] Error 1

![image](https://user-images.githubusercontent.com/18721697/163313773-4a3c7d86-0f7e-4a99-ad19-b43ac3118031.png)

**Comment by GarrettQi** [comment]
v2.2.19

**Comment by svaroqui** [comment]
Hi Garrett , did you try to upgrade you go release , embed feature is pretty new !

**Comment by GarrettQi** [comment]
I upgraded to 1.18 and still reported an error.
[root@mysql101 replication-manager]# go version
go version go1.18.1 linux/amd64
[root@mysql101 replication-manager]# make osc
env GOOS=linux GOARCH=amd64 go build -v --tags "server" --ldflags "-extldflags '-static' -w -s -X github.com/signal18/replication-manager/server.Version=v2.2.19 -X github.com/signal18/replication-manager/server.FullVersion=v2.2.19 -X github.com/signal18/replication-manager/server.Build=2022-04-14T16:22:02+0800 -X github.com/signal18/replication-manager/server.WithProvisioning=OFF "   -o build/binaries/replication-manager-osc
cluster/configurator/configurator.go:23:2: no required module provides package github.com/signal18/replication-manager/share; to add it:
	go get github.com/signal18/replication-manager/share
make: *** [osc] Error 1

**Comment by svaroqui** [comment]
Thanks Oups can you retry now i was missing a file in this release

**Comment by svaroqui** [comment]
Ok we have now retag v2.2.19

**Comment by svaroqui** [comment]
Thanks for reporting please reopen if it's not fixed

**Comment by GarrettQi** [comment]
It's OK now, thanks.
