### ISSUE TITLE
mysqldump rejoin old master for mysql failed.

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#422]
MySQL8 - M/S (GTID Mode)
SRM : 2.2.19

Master DB stop And Slave is New Master OK!
Old Master DB start And Rejoin Failed.

MariaDB is No Problem! Only MySQL Problem.

-- Log --
time="2022-04-14 17:56:36" level=info msg="Election matrice: [] " cluster=cluster_mysql33307
time="2022-04-14 17:56:38" level=info msg="Election matrice: [] " cluster=cluster_mysql33307
time="2022-04-14 17:56:51" level=info msg="Election matrice: [] " cluster=cluster_mysql33307
time="2022-04-14 17:56:59" level=info msg="Rejoin master incremental 192.168.50.12:33307" cluster=cluster_mysql33307
time="2022-04-14 17:56:59" level=info msg="Crash info &{192.168.50.12:33307 mysql-bin.000001 493 mysql-bin.000002 507 %!s(bool=true) %!s(*gtid.List=&[{0 18118878413861267065 2}]) 192.168.50.11:33307}" cluster=cluster_mysql33307
time="2022-04-14 17:56:59" level=info msg="Rejoined GTID sequence 0" cluster=cluster_mysql33307
time="2022-04-14 17:56:59" level=info msg="Crash Saved GTID sequence 0 for master id 802" cluster=cluster_mysql33307
time="2022-04-14 17:56:59" level=info msg="Rejoin server found a crash GTID greater than 0 " cluster=cluster_mysql33307
time="2022-04-14 17:56:59" level=info msg="Cascading failover, found empty GTID, forcing full state transfer" cluster=cluster_mysql33307
time="2022-04-14 17:56:59" level=info msg="Cascading failover, consider we cannot flashback" cluster=cluster_mysql33307
time="2022-04-14 17:56:59" level=info msg="No flashback rejoin can flashback false, autorejoin-flashback true autorejoin-backup-binlog true" cluster=cluster_mysql33307
time="2022-04-14 17:56:59" level=error msg="Failed to autojoin incremental to master 192.168.50.12:33307" cluster=cluster_mysql33307
time="2022-04-14 17:56:59" level=info msg="Rejoin flashback dump restore 192.168.50.12:33307" cluster=cluster_mysql33307
time="2022-04-14 17:56:59" level=info msg="CHANGE MASTER  TO master_host='192.168.50.11', master_port=33307, master_user='XXX', master_password='XXX', master_connect_retry=5, master_heartbeat_period=3, MASTER_AUTO_POSITION=1" cluster=cluster_mysql33307 module=Rejoin server="192.168.50.12:33307"
time="2022-04-14 17:56:59" level=info msg="Rejoin old Master 192.168.50.12:33307 , backing up lost event to /app/mrm/data/cluster_mysql33307/crash-bin-20220414175659" cluster=cluster_mysql33307
time="2022-04-14 17:56:59" level=info msg="Server 192.168.50.12:33307 previous state changed to: StandAlone" cluster=cluster_mysql33307
time="2022-04-14 17:56:59" level=info msg="Election matrice: [] " cluster=cluster_mysql33307
time="2022-04-14 17:56:59" level=warning msg="Rejoining standalone server 192.168.50.12:33307 to master 192.168.50.11:33307" cluster=cluster_mysql33307 code=WARN0022 status=OPENED type=state
time="2022-04-14 17:56:59" level=info msg="Rejoining from direct mysqldump from 192.168.50.11:33307" cluster=cluster_mysql33307
time="2022-04-14 17:56:59" level=info msg="Command: /app/mysql/mysql8/bin/mysqldump --hex-blob --single-transaction --verbose --all-databases --add-drop-database --apply-slave-statements --host=192.168.50.11 --port=33307 --user=XXXX --password=XXXX --master-data=1 --gtid=true --events=true " cluster=cluster_mysql33307
time="2022-04-14 17:56:59" level=error msg="Can't start mysql client:exit status 1 at /app/mrm/share/amd64/linux/mysql --host=192.168.50.12 --port=33307 --user=XXXX --password=XXXX --batch --init-command=reset master;set sql_log_bin=0;set global slow_query_log=0;set global general_log=0;" cluster=cluster_mysql33307
time="2022-04-14 17:57:01" level=info msg="Server 192.168.50.12:33307 state transition StandAlone changed to: SlaveErr" cluster=cluster_mysql33307
time="2022-04-14 17:57:01" level=info msg="Server 192.168.50.12:33307 previous state changed to: SlaveErr" cluster=cluster_mysql33307
time="2022-04-14 17:57:01" level=info msg="Election matrice: [\n\t{\n\t\t\"URL\": \"192.168.50.12:33307\",\n\t\t\"Indice\": 0,\n\t\t\"Pos\": 0,\n\t\t\"Seq\": 0,\n\t\t\"Prefered\": false,\n\t\t\"Ignoredconf\": false,\n\t\t\"Ignoredrelay\": false,\n\t\t\"Ignoredmultimaster\": false,\n\t\t\"Ignoredreplication\": true,\n\t\t\"Weight\": 0\n\t}\n] " cluster=cluster_mysql33307
time="2022-04-14 17:57:01" level=warning msg="Rejoining standalone server 192.168.50.12:33307 to master 192.168.50.11:33307" cluster=cluster_mysql33307 code=WARN0022 status=RESOLV type=state
time="2022-04-14 17:57:01" level=warning msg="Could not find a slave in topology" cluster=cluster_mysql33307 code=ERR00010 status=RESOLV type=state

----------

Rejoined GTID sequence  not found!

MySQL mysqldump and MariaDB mysqldump is different!

MySQL mysqldump is --gtid option not command.

https://github.com/signal18/replication-manager/blob/develop/cluster/srv_job.go#L1027-L1031

**Comment by svaroqui** [comment]
thanks for founding this i'll fixe this

**Comment by svaroqui** [comment]
Hi nyxneuf, if you can provide feedback about the last 2 commits so i can push in repositories
