### ISSUE TITLE
JWT API can't start

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#424]
Full Version:  v2.2.19-8-g0bc50ea7

-- log --

me="2022-04-29 10:48:02" level=info msg="Replication-Manager started in daemon mode" version=v2.2.19
time="2022-04-29 10:48:02" level=info msg="No existing password encryption scheme" error="Key file does not exist"
time="2022-04-29 10:48:02" level=info msg="Failover in automatic mode" cluster=cluster_mysql33307
time="2022-04-29 10:48:02" level=info msg="No existing password encryption scheme in LoadAPIUsers" cluster=cluster_mysql33307
time="2022-04-29 10:48:03" level=info msg="No TLS certificate provided using generated key (/tmp/key.pem2390273068) and certificate (/tmp/cert.pem3997393872)"
time="2022-04-29 10:48:03" level=info msg="Starting HTTP & JWT API on 0.0.0.0:10005"
time="2022-04-29 10:48:03" level=warning msg="Ici :0.0.0.0"
time="2022-04-29 10:48:03" level=info msg="starting multiplexed TLS HTTP/2.0 and HTTP/1.1 Gateway server: 0.0.0.0:10005"
time="2022-04-29 10:48:03" level=error msg="JWT API can't start: http2: TLSConfig.CipherSuites index 6 contains an HTTP/2-approved cipher suite (0x1302), but it comes after unapproved cipher suites. With this configuration, clients that don't support previous, approved cipher suites may be given an unapproved one and reject the connection."
time="2022-04-29 10:48:06" level=info msg="No database TLS certificates" cluster=cluster_mysql33307
time="2022-04-29 10:48:06" level=info msg="No database previous TLS certificates" cluster=cluster_mysql33307

**Comment by svaroqui** [comment]
Hi, 

tlsConfig = &tls.Config{
			Certificates: []tls.Certificate{cer},
			// declare that the listener supports http/2.0
			NextProtos:               []string{"h2"},
			ServerName:               s.v3Config.Listen.Address, // this is critical
			MinVersion:               tls.VersionTLS12,
			CurvePreferences:         []tls.CurveID{tls.CurveP521, tls.CurveP384, tls.CurveP256},
			PreferServerCipherSuites: true,
			CipherSuites: []uint16{
				tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
				tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
				tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
				tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
				tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
				tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,
				tls.TLS_AES_256_GCM_SHA384,
				tls.TLS_CHACHA20_POLY1305_SHA256,
				tls.TLS_AES_128_GCM_SHA256,
				tls.TLS_AES_256_GCM_SHA384,
				tls.TLS_CHACHA20_POLY1305_SHA256,
			},
		} 

According to https://groups.google.com/g/golang-codereviews/c/0aEs1j2ftzk this could be an order issue of the cipher suite fixed in go1.17 by reordering , we need to found with one in weaker to index 6 and move it after in the list 

Any idea is welcome ?

**Comment by svaroqui** [comment]
Re, can you let me know if  the commit [1c56aeaa](https://github.com/signal18/replication-manager/commit/1c56aeaa0ef6ecfdb33aa08174df2d53458ecda7) is fixing your issue else we will need to change go.mod to use 1.17 and you need to compile with go 1.17 as well .

**Comment by terwey** [comment]
PR #425 fixes this issue. Tested on `go version go1.16.15 linux/amd64`
