### ISSUE TITLE
Not able to start Replication Manager installed from tar ball (Failed to start replication-manager open source, replication-manager.service failed)

### ISSUE THREAD

**Issue by Manoharan-NMS** [signal18/replication-manager#428]
```
My OS: CentOS 7.9
Hardware Platform : x86_64
```
**NOTE:** Upto version 2.2.16 x86_64 RPM package available. It was worked without any problem.

Team,
Followed below steps for replication  installation from Tar ball. Not able to start the service. Kindly share the proper steps. 

Reference: https://docs.signal18.io/installation/setup-instructions

Downloaded Binary Reference: https://ci.signal18.io/mrm/builds/tags/v2.2.20/replication-manager-osc-2.2.20.tar.gz

**Steps Followed:**

```
sudo tar -zxvf replication-manager-osc-2.2.20.tar.gz -C /usr/local/
sudo ln -s /usr/local/replication-manager-osc /usr/local/replication-manager
sudo cp /usr/local/replication-manager/share/replication-manager.init /etc/init.d/replication-manager
sudo cp /usr/local/share/replication-manager.service /etc/systemd/system/replication-manager.service
```

`systemctl status replication-manager.service`
```
● replication-manager.service - replication-manager open source
   Loaded: loaded (/etc/systemd/system/replication-manager.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
```
`sudo systemctl start replication-manager.service`

`sudo systemctl status replication-manager.service`
```
● replication-manager.service - replication-manager open source
   Loaded: loaded (/etc/systemd/system/replication-manager.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Wed 2022-05-04 14:04:39 IST; 4s ago
  Process: 22022 ExecStart=/usr/local/replication-manager/bin/replication-manager-osc monitor (code=exited, status=203/EXEC)
 Main PID: 22022 (code=exited, status=203/EXEC)

May 04 14:04:39 manoharan.nmsworks.co.in systemd[1]: Unit replication-manager.service entered failed state.
May 04 14:04:39 manoharan.nmsworks.co.in systemd[1]: replication-manager.service failed.
May 04 14:04:39 manoharan.nmsworks.co.in systemd[1]: replication-manager.service holdoff time over, scheduling restart.
May 04 14:04:39 manoharan.nmsworks.co.in systemd[1]: Stopped replication-manager open source.
May 04 14:04:39 manoharan.nmsworks.co.in systemd[1]: start request repeated too quickly for replication-manager.service
May 04 14:04:39 manoharan.nmsworks.co.in systemd[1]: Failed to start replication-manager open source .
May 04 14:04:39 manoharan.nmsworks.co.in systemd[1]: Unit replication-manager.service entered failed state.
May 04 14:04:39 manoharan.nmsworks.co.in systemd[1]: replication-manager.service failed.
```

**Comment by tanji** [comment]
Do you mean to say that you don't have new packages for RPM?

**Comment by Manoharan-NMS** [comment]
> Do you mean to say that you don't have new packages for RPM?

Yes. 
Upto Version v2.2.16 RPM is available for x86_64
From Version v2.2.17 onwards RPM available for aarch64 only. RPM not available for x86_64.

Kindly suggest, aarch RPM generated by Replication Manager, will it support for x86_64 ?

**Link Reference:** 

Latest Binary:   https://ci.signal18.io/mrm/builds/tags/v2.2.20/
Old Binary: https://ci.signal18.io/mrm/builds/tags/v2.2.16/

**Comment by Manoharan-NMS** [comment]
Tried in my PC (x86_64), with aarch64 RPM. But its not happening.

sudo yum install replication-manager-osc-2.2.20-1.aarch64.rpm
[sudo] password for xxxxxxx: 
Loaded plugins: fastestmirror, langpacks
Examining replication-manager-osc-2.2.20-1.aarch64.rpm: 1651489779:replication-manager-osc-2.2.20-1.aarch64
Cannot add package replication-manager-osc-2.2.20-1.aarch64.rpm to transaction. Not a compatible architecture: aarch64
Error: Nothing to do


From version v2.2.17 on wards purposely x86_64 RPM support is removed ?

**Comment by tanji** [comment]
No, it's an error, thanks for reporting. We will restore it and keep you posted

PS: aarch64 is for ARM CPU, you cannot use it on x86 architecture ;)

**Comment by Manoharan-NMS** [comment]
> No, it's an error, thanks for reporting. We will restore it and keep you posted
> 
> PS: aarch64 is for ARM CPU, you cannot use it on x86 architecture ;)

@tanji  Thanks for your prompt response. 

Once done, please update.

**Comment by tanji** [comment]
The repositories have been updated.

**Comment by Manoharan-NMS** [comment]
> The repositories have been updated.

Thanks @tanji for your quick response & fix.

**Comment by Manoharan-NMS** [comment]
Reference Link :  https://ci.signal18.io/mrm/builds/tags/v2.2.20/replication-manager-osc-2.2.20-1.x86_64.rpm

Now able to install & able to start the replication-manager service.

`Thanks a lot !!! `
