### ISSUE TITLE
How to solve Cluster Logs STATE ERR000

### ISSUE THREAD

**Issue by zhituanchen** [signal18/replication-manager#432]
Hi
    After start replication manager.There are same STATE RESOLV ERR000XXX in cluster logs ,how to solve it.It should be ignore or same paramter can solve it.Thk.
   Cluster Logs
2022/05/16 11:24:27	STATE	RESOLV ERR00021 : Cluster state down
2022/05/16 11:24:27	INFO	Server 10.0.0.162:3306 previous state changed to: Master
2022/05/16 11:24:25	STATE	OPENED WARN0054 : No log of replication queries in slow query on slave 10.0.0.231:3306
2022/05/16 11:24:25	STATE	RESOLV ERR00085 : No replica found for routing reads
2022/05/16 11:24:25	STATE	RESOLV ERR00012 : Could not find a master in topology
2022/05/16 11:24:25	STATE	RESOLV ERR00010 : Could not find a slave in topology
2022/05/16 11:24:25	STATE	RESOLV ERR00032 : No candidates found in slaves list
2022/05/16 11:24:25	INFO	Server 10.0.0.162:3306 state transition Suspect changed to: Master
2022/05/16 11:24:25	INFO	Server 10.0.0.231:3306 previous state changed to: Slave
2022/05/16 11:24:25	INFO	Server 10.0.0.231:3306 state transition Suspect changed to: Slave
2022/05/16 11:24:23	INFO	New proxy monitored: proxysql 10.0.0.162:6032
2022/05/16 11:24:23	INFO	New proxy monitored: proxysql 10.0.0.231:6032
2022/05/16 11:24:23	INFO	Assigning a global connection on server 10.0.0.162:3306
2022/05/16 11:24:23	INFO	Assigning a global connection on server 10.0.0.231:3306
2022/05/16 11:24:23	INFO	Loaded 2 proxies
2022/05/16 11:24:23	INFO	New proxy monitored proxysql: 10.0.0.162:6032
2022/05/16 11:24:23	INFO	New proxy monitored proxysql: 10.0.0.231:6032
2022/05/16 11:24:23	INFO	Server 10.0.0.162:3306 previous state changed to: Suspect
2022/05/16 11:24:23	INFO	Server 10.0.0.162:3306 state transition changed to: Suspect
2022/05/16 11:24:23	INFO	Server 10.0.0.231:3306 previous state changed to: Suspect
2022/05/16 11:24:23	INFO	Server 10.0.0.231:3306 state transition changed to: Suspect
2022/05/16 11:24:23	INFO	No database previous TLS certificates
2022/05/16 11:24:23	INFO	No database TLS certificates
2022/05/16 11:24:12	INFO	No existing password encryption scheme in LoadAPIUsers
2022/05/16 11:24:12	INFO	Failover in interactive mode

the mysql cluster web dislpay is ok.
![image](https://user-images.githubusercontent.com/71009460/168515514-b2625798-df07-4bc8-8dbd-037b17490666.png)

replication-manager-osc  version
Replication Manager v2.2.20 for MariaDB 10.x and MySQL 5.7 Series
Full Version:  v2.2.20
Build Time:  2022-05-04T11:25:50+0000

cat config.toml
[db3306]
title = "db3306"
db-servers-hosts = "10.0.0.231:3306,10.0.0.162:3306"
db-servers-prefered-master = "10.0.0.231:3306"
db-servers-credential = "dbadmin:Nfjd_1234"
replication-credential = "repl:Repl_2019"
failover-mode = "manual"
proxysql=true
proxysql-servers="10.0.0.231,10.0.0.162"
proxysql-port=6033
proxysql-admin-port=6032
proxysql-writer-hostgroup="10"
proxysql-reader-hostgroup="20"
proxysql-user="cluster1"
proxysql-password="secret1pass"
proxysql-bootstrap=false
proxysql-bootstrap-hostgroups=false
proxysql-bootstrap-users=false

[Default]

include = "/etc/replication-manager/cluster.d"

monitoring-save-config = false
monitoring-datadir = "/var/lib/replication-manager"
#monitoring-sharedir = "/usr/share/replication-manager"
autorejoin = false

## Timeout in seconds between consecutive monitoring

monitoring-ticker = 2

log-file = "/var/log/replication-manager.log"
log-heartbeat = false
log-syslog = false
log-rotate-max-age = 1
log-rotate-max-backup = 7
log-rotate-max-size = 10
#log-sql-in-monitoring = true 

arbitration-external = false
arbitration-external-secret = "13787932529099014144"
arbitration-external-hosts = "88.191.151.84:80"
arbitration-peer-hosts ="127.0.0.1:10002"

## Unique value on each replication-manager

arbitration-external-unique-id = 0

http-server = true
http-bind-address = "0.0.0.0"
http-port = "10001"
http-auth = false
http-session-lifetime =   3600
http-bootstrap-button = false
http-refresh-interval = 4000

api-credentials = "admin:repman"
api-port = "10005"
api-https-bind = false

api-credentials-acl-allow =  "admin:cluster proxy db prov,dba:cluster proxy db,foo:"
api-credentials-acl-discard = false
api-credentials-external = "dba:repman,foo:bar"

mail-from = "replication-manager@localhost"
mail-smtp-addr = "localhost:25"
mail-to = "replication-manager@signal18.io"
mail-smtp-password=""
mail-smtp-user=""

alert-slack-channel = "#support"
alert-slack-url = ""
alert-slack-user = "svar"

graphite-metrics = false
graphite-carbon-host = "127.0.0.1"
graphite-carbon-port = 2003
graphite-embedded = false
graphite-carbon-api-port = 10002
graphite-carbon-server-port = 10003
graphite-carbon-link-port = 7002
graphite-carbon-pickle-port = 2004
graphite-carbon-pprof-port = 7007

backup-logical-type = "mydumper"
backup-mydumper-path = "/bin/mydumper"
backup-myloader-path = "/bin/myloader"
backup-mysqlbinlog-path = "/bin/mysqlbinlog"
backup-mysqldump-path = "/bin/mysqldump"
backup-mysqldump-options = "--hex-blob --single-transaction --verbose --all-databases"

sysbench-binary-path = "/usr/bin/sysbench"
sysbench-threads = 4
sysbench-time = 100
sysbench-v1 = true

**Comment by svaroqui** [comment]
Hi,

I you look it's a RESOLVED state. This is because when restarting ,replication-manager rediscover the topology and will do nothing until a correct topology is found, so the state machine first open a state for each server where each node is in a SUSPECT status, the topology discovery will at some point mark the cluster as capable of failover while closing cluster state like 
STATE RESOLV ERR00085 : No replica found for routing reads
STATE RESOLV ERR00012 : Could not find a master in topology
STATE RESOLV ERR00010 : Could not find a slave in topology
STATE RESOLV ERR00032 : No candidates found in slaves list

This indeed have advantage that if replication-manager is restart or config reloaded and something change topology on his back,  it will do a correct job instead of restoring a persistent state  that may have change

**Comment by zhituanchen** [comment]
OK
