### ISSUE TITLE
Failover/Switchover scripts not executed in latest Version 2.2.22

### ISSUE THREAD

**Issue by Manoharan-NMS** [signal18/replication-manager#435]
RPM Download Link :   https://ci.signal18.io/mrm/builds/tags/v2.2.22/replication-manager-osc-2.2.22-1.x86_64.rpm

**Execution Steps:**
Path: /etc/replication-manager/cluster.d
Changed File: cluster1.toml

Below properties changed. 
failover-pre-script = "/tmp/pre.sh"
failover-post-script = "/tmp/post.sh"

**Expected Result as per Old version Tested.** 

(https://ci.signal18.io/mrm/builds/tags/v2.1.7/replication-manager-osc-2.1.7-1.x86_64.rpm)
During Switchover/Failover Pre & Post shell script or expect script will be executed.
NOTE: Script has read and execute permissions

**Actual Result:**

Without pre & post failover script entry in cluster1.toml file switchover is happening properly.
After introduced script entries in cluster1.toml file  its not moving after "Calling pre-failover script" log in GUI.

**NOTE**
I'm using Master Slave combination.
During this condition it shows both as Master in GUI.

**Comment by nyxneuf** [comment]
https://github.com/signal18/replication-manager/blob/develop/cluster/cluster_fail.go#L562-L574

[code]
out, err = exec.Command(cluster.Conf.PreScript, cluster.oldMaster.Host, cluster.**vmaster**.Host, cluster.oldMaster.Port, cluster.**vmaster**.Port, cluster.oldMaster.MxsServerName, cluster.**vmaster**.MxsServerName).CombinedOutput()

-----

vmaster -> master   - change code vmaster to master.

I modified it and it works normally. Need to check if this is the problem

**Comment by Manoharan-NMS** [comment]
> https://github.com/signal18/replication-manager/blob/develop/cluster/cluster_fail.go#L562-L574
> 
> [code] out, err = exec.Command(cluster.Conf.PreScript, cluster.oldMaster.Host, cluster.**vmaster**.Host, cluster.oldMaster.Port, cluster.**vmaster**.Port, cluster.oldMaster.MxsServerName, cluster.**vmaster**.MxsServerName).CombinedOutput()
> 
> vmaster -> master - change code vmaster to master.
> 
> I modified it and it works normally. Need to check if this is the problem

Multiple times I verified with MySQL DB Replication (MySQL 8.0.27) with GTID. WIthout referring pre & post failover script its working perfectly. Once I enabled script, its misbehaves.
In 2.1.7 the same working perfectly.

Please look into that issue. Any major changes happened in 2.2 versions.

**Comment by svaroqui** [comment]
Ok sorry for this regression i pushed a fix in 2.2.24 also make many MySQL8.0 GTID  backup and direct dump from leader work in 2.2.23 can you please test it and report back if it has fixed the issue

**Comment by Manoharan-NMS** [comment]
> Ok sorry for this regression i pushed a fix in 2.2.24 also make many MySQL8.0 GTID backup and direct dump from leader work in 2.2.23 can you please test it and report back if it has fixed the issue

@svaroqui 

Verified with latest tag build. Its working fine.
RPM Reference Link: https://ci.signal18.io/mrm/builds/tags/v2.2.24/replication-manager-osc-2.2.24-1.x86_64.rpm

Thanks for your quick fix
