### ISSUE TITLE
mysql8 gtid #434 test intermittent rejoin failure

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#436]
SRM - v2.2.24
MySQL8 - M-S

Test scenario

1. M - S  ->  master db stop and slave is new master!
2.  old master db start -> S - M 
3.  S - M  -> master db stop and slave is new master!
4. old master db start -> M - S

repeat the above process!
intermittent rejoin failure!

![20220705_105822](https://user-images.githubusercontent.com/33710188/177235860-8c580c2c-6105-4337-8b23-e117709e5516.png)

**Comment by nyxneuf** [comment]
Similarly, I use the code
there was no problem!

https://github.com/signal18/replication-manager/blob/932673c8f979bc8192d20c0e509c7eff2a8ab976/cluster/srv_rejoin.go#L675-L682

errss -> err   after modification

		ss, err := server.GetSlaveStatus(server.ReplicationSourceName)
		if err != nil {
			server.ClusterGroup.LogPrintf(LvlInfo, "Failed to check if server was using GTID %s", err)
			return false
		}
		server.ClusterGroup.LogPrintf(LvlInfo, "Rejoin server using GTID %s", ss.UsingGtid.String)

**Comment by nyxneuf** [comment]
I found it!

https://github.com/signal18/replication-manager/blob/develop/cluster/srv_rejoin.go#L675-L682

not the code above!

https://github.com/signal18/replication-manager/blob/develop/cluster/srv_rejoin.go#L684

[Before]
if crash.FailoverIOGtid == nil {  

[After]
if crash.FailoverIOGtid != nil {

=======================

I applied and tested it and there was no problem.

What does this code mean?

And 

https://github.com/signal18/replication-manager/blob/develop/cluster/srv_rejoin.go#L376

You need to check that the code is also correct!

**Comment by svaroqui** [comment]
Re, I think you are missing  one point here . There are time when you can not rejoin the old master , and replication-manager is detecting this scenario if it's not possible to rejoin  you need a full state transfert via mysqldump , restoring a backup or  a snapshot to put the old master back in time before the crash of the old leader. you need to install the same server package on the replication-manager server and provide the path to the tools needed for state transfert.


```
autorejoin-mysqldump = true
backup-mysqlbinlog-path = "/Users/apple/mysql/bin/mysqlbinlog"
backup-mysqldump-path = "/Users/apple/mysql/bin/mysqldump"
backup-mysqlclient-path = "/Users/apple/mysql/bin/mysql"

```

**Comment by nyxneuf** [comment]
Rejoin fails even if there is no change in DB data.
Do I have to use mysqldump for all DB data?

**Comment by svaroqui** [comment]
Ok i'll give it try you say multiple times failover rejoin

**Comment by svaroqui** [comment]
I'm testing always with 3 nodes may be it make a difference

**Comment by svaroqui** [comment]
To explain the code when the leader is crashed , replication-manager record the position of the crash by looking show slave status on the  candidate master that is still a replica at this time . It record gtid_executed and translate uuid to hash  to get similar to mariadb GTID an record it in property FailoverIOGtid that is the name of the MariaDB counter part .

**Comment by nyxneuf** [comment]
yes! multiple times failover rejoin.
I'm sorry to bother you.
Please check!

**Comment by svaroqui** [comment]
You don't bother me at all , you're help is very valuable, would prefer still to get issues without images but with log files it's more easy to dig into it

**Comment by nyxneuf** [comment]
Thank you.
I'm not a developer. I'm an infra engineer.
It's hard to understand Golang. It is difficult to use English. So I use a translator.
I think replication-manager is great.
I'm glad it helped. :)

**Comment by svaroqui** [comment]
Found it MySQL can print carriage return in GTID output of show slave status i 've pushed a fix and will make a new release soon , thanks again for founding this !
