### ISSUE TITLE
MariaDB - error message after srm switchover command

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#437]
SRM-v.2.2.24
MariaDB10.6 - M-S
![20220707_164534](https://user-images.githubusercontent.com/33710188/177720634-c2083fa3-0bac-4a40-9396-a26e32c0baf8.png)

-- Log --

time="2022-07-07 16:45:02" level=info msg="Inject fake transaction on new master 192.168.50.32:3307 " cluster=cluster_mariadb
time="2022-07-07 16:45:02" level=info msg="FLUSH TABLES" cluster=cluster_mariadb module=MasterFailover server="192.168.50.32:3307"
time="2022-07-07 16:45:02" level=info msg="Killing new connections on old master showing before update route" cluster=cluster_mariadb
time="2022-07-07 16:45:02" level=info msg="Switching old leader to slave" cluster=cluster_mariadb
time="2022-07-07 16:45:02" level=info msg="UNLOCK TABLES" cluster=cluster_mariadb module=MasterFailover server="192.168.50.31:3307"
time="2022-07-07 16:45:02" level=info msg="UNLOCK TABLES" cluster=cluster_mariadb module=MasterFailover server="192.168.50.31:3307"
time="2022-07-07 16:45:02" level=info msg="Doing MariaDB GTID switch of the old master" cluster=cluster_mariadb
time="2022-07-07 16:45:02" level=error msg="Change master failed on old master, reason:[Change master statement CHANGE MASTER  TO master_host='192.168.50.32', master_port=3307, master_user='XXX', master_password='XXX', master_connect_retry=5, master_heartbeat_period=3, MASTER_USE_GTID=CURRENT_POS failed, reason: Error 1198: This operation cannot be performed as you have a running slave ''; run STOP SLAVE '' first] " cluster=cluster_mariadb
time="2022-07-07 16:45:02" level=error msg="Change master failed on old master, reason:Change master statement CHANGE MASTER  TO master_host='192.168.50.32', master_port=3307, master_user='XXX', master_password='XXX', master_connect_retry=5, master_heartbeat_period=3, MASTER_USE_GTID=CURRENT_POS failed, reason: Error 1198: This operation cannot be performed as you have a running slave ''; run STOP SLAVE '' first " cluster=cluster_mariadb error="Change master statement CHANGE MASTER  TO master_host='192.168.50.32', master_port=3307, master_user='XXX', master_password='XXX', master_connect_retry=5, master_heartbeat_period=3, MASTER_USE_GTID=CURRENT_POS failed, reason: Error 1198: This operation cannot be performed as you have a running slave ''; run STOP SLAVE '' first" module=MasterFailover server="192.168.50.31:3307" sql="CHANGE MASTER  TO master_host='192.168.50.32', master_port=3307, master_user='XXX', master_password='XXX', master_connect_retry=5, master_heartbeat_period=3, MASTER_USE_GTID=CURRENT_POS"
time="2022-07-07 16:45:02" level=info msg="CHANGE MASTER  TO master_host='192.168.50.32', master_port=3307, master_user='XXX', master_password='XXX', master_connect_retry=5, master_heartbeat_period=3, MASTER_USE_GTID=CURRENT_POS" cluster=cluster_mariadb module=MasterFailover server="192.168.50.31:3307"
time="2022-07-07 16:45:02" level=info msg="START SLAVE" cluster=cluster_mariadb module=MasterFailover server="192.168.50.31:3307"
time="2022-07-07 16:45:02" level=info msg="SET GLOBAL read_only=1" cluster=cluster_mariadb module=MasterFailover server="192.168.50.31:3307"
time="2022-07-07 16:45:02" level=info msg="SET GLOBAL max_connections=2000" cluster=cluster_mariadb module=MasterFailover server="192.168.50.31:3307"
time="2022-07-07 16:45:02" level=info msg="Server 192.168.50.31:3307 state transition Master changed to: Slave" cluster=cluster_mariadb
time="2022-07-07 16:45:02" level=info msg="Switching other slaves to the new master" cluster=cluster_mariadb
time="2022-07-07 16:45:02" level=info msg="Master switch on 192.168.50.32:3307 complete" cluster=cluster_mariadb
time="2022-07-07 16:45:03" level=info msg="Server 192.168.50.31:3307 state transition Master changed to: SlaveLate" cluster=cluster_mariadb
time="2022-07-07 16:45:03" level=info msg="Server 192.168.50.31:3307 previous state changed to: SlaveLate" cluster=cluster_mariadb
time="2022-07-07 16:45:03" level=info msg="Server 192.168.50.32:3307 previous state changed to: Master" cluster=cluster_mariadb
time="2022-07-07 16:45:03" level=info msg="Election matrice maxseq >0: [\n\t{\n\t\t\"URL\": \"192.168.50.31:3307\",\n\t\t\"Indice\": 0,\n\t\t\"Pos\": 22000000000639,\n\t\t\"Seq\": 91,\n\t\t\"Prefered\": true,\n\t\t\"Ignoredconf\": false,\n\t\t\"Ignoredrelay\": false,\n\t\t\"Ignoredmultimaster\": false,\n\t\t\"Ignoredreplication\": true,\n\t\t\"Weight\": 0\n\t}\n] " cluster=cluster_mariadb

**Comment by svaroqui** [comment]
Hi i don't think this is an error , Why does the old master have a running replication it should have been free of any replication as it was the master, if you wan't to preserve a replication from an other cluster please use different source name for that specific leader the default source used by replication-manager is "" but could be change for a specific source as well

**Comment by nyxneuf** [comment]
I found. My mistake. sorry! 

The maxscale server was running.
