### ISSUE TITLE
Switchover misbehaves when more than one Cluster is enabled.

### ISSUE THREAD

**Issue by Manoharan-NMS** [signal18/replication-manager#439]
**Test Conditions**
File Path: /etc/replication-manager/cluster.d
File Name(Cluster1): cluster1.toml
File Name(Cluster2): cluster2.toml

**cluster1.toml**
[cluster1]
title = "cluster1"
prov-orchestrator = "onpremise"
prov-db-tags = "innodb,noquerycache,slow,pfs,pkg,linux,smallredolog,logtotable"
prov-db-memory = "256"
prov-db-memory-shared-pct = "threads:16,innodb:60,myisam:10,aria:10,rocksdb:1,tokudb:1,s3:1,archive:1,querycache:0"
prov-db-disk-size = "1"
prov-db-cpu-cores = "1"
prov-db-disk-iops = "300"

db-servers-hosts = "10.10.10.11:3307,10.10.10.12:3307"
db-servers-prefered-master = "10.10.10.11:3307"
db-servers-credential = "test:test"
db-servers-connect-timeout = 1
replication-credential = "testrepl:testrepl"

**cluster2.toml**
[cluster2]
title = "cluster2"
prov-orchestrator = "onpremise"
prov-db-tags = "innodb,noquerycache,slow,pfs,pkg,linux,smallredolog,logtotable"
prov-db-memory = "256"
prov-db-memory-shared-pct = "threads:16,innodb:60,myisam:10,aria:10,rocksdb:1,tokudb:1,s3:1,archive:1,querycache:0"
prov-db-disk-size = "1"
prov-db-cpu-cores = "1"
prov-db-disk-iops = "300"

db-servers-hosts = "10.10.10.2:3307,10.10.10.3:3307"
db-servers-prefered-master = "10.10.10.2:3307"
db-servers-credential = "test:test"
db-servers-connect-timeout = 1
replication-credential = "testrepl:testrepl"

**Execution Steps**
In Replication Manager, multiple clusters are enabled with Master Slave Topology.
Trying to perform switchover Cluster2 alone.

**Expected Result**
Cluster2 must be switched over from IP1 to IP2

**Actual Result**
Cluster2 switchover from IP1 to IP2 happened successfully.
Also Cluster1 switchover took place.

**NOTE:** 
Multiple times verified, able to reproduce the same. Kindly fix this

**Comment by nyxneuf** [comment]
What is your srm version?
mysql or mariadb ?
When I test it works fine. v2.2.25

**Comment by Manoharan-NMS** [comment]
> What is your srm version? mysql or mariadb ? When I test it works fine. v2.2.25

I tested in MariaDB 10.4.6 & 10.4.13

Switchover working correctly, when single cluster is enabled.

My observation is more than one cluster configured, it misbehaves.

I tested with below RPM
https://ci.signal18.io/mrm/builds/tags/v2.2.24/replication-manager-osc-2.2.24-1.x86_64.rpm

**Comment by nyxneuf** [comment]
show me the replication manager log

**Comment by Manoharan-NMS** [comment]
> show me the replication manager log
Logs attached.

[_replication-manager.log](https://github.com/signal18/replication-manager/files/9090210/_replication-manager.log)
