### ISSUE TITLE
Replication Manager 5.2.1 installation from source package issue

### ISSUE THREAD

**Issue by KalaiDurai** [signal18/replication-manager#449]
Hello, I am trying to install  repmgr-5.2.1.tar.gz on Postgres DB 13.x which is installed from Redhat repository. can you please help with this below issue while i try to install replication manager for DR setup

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC repmgr-client.o repmgr-action-primary.o repmgr-action-standby.o repmgr-action-witness.o repmgr-action-cluster.o repmgr-action-node.o repmgr-action-service.o repmgr-action-daemon.o configdata.o configfile.o configfile-scan.o log.o strutil.o controldata.o dirutil.o compat.o dbutils.o sysutils.o -L/usr/lib64 -lpgcommon -lpgport -lpq -L/usr/lib64  -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -Wl,--as-needed  -o repmgr
**/usr/bin/ld: cannot find -lpgcommon
/usr/bin/ld: cannot find -lpgport
**collect2: error: ld returned 1 exit status
make: *** [Makefile:82: repmgr] Error 1****

**Comment by svaroqui** [comment]
Sorry, we are replication-manager not repmgr project here
