### ISSUE TITLE
Does not support MySQL multi-source replication?

### ISSUE THREAD

**Issue by lenovore** [signal18/replication-manager#459]
Replication Manager : v2.2.31
MySQL: 5.7.40

MySQL replication topology
```
cluster 1:
192.168.90.170:7306 -> 192.168.90.171:7306
192.168.90.170:7306 -> 192.168.90.172:7306 (multi-source,channel_name:test_7306)
cluster 2:
192.168.90.170:8306 -> 192.168.90.171:8306
192.168.90.170:8306 -> 192.168.90.172:7306 (multi-source,channel_name:test_8306)
```
![image](https://user-images.githubusercontent.com/29646774/209785360-12d342fd-d5a7-4437-a132-a0d6e96fcb5e.png)

Replication Manager  config:
```
replication-source-name="test_7306"

db-servers-hosts = "192.168.90.170:7306,192.168.90.171:7306,192.168.90.172:7306"
db-servers-credential = "replmanager:replmanager"
db-servers-ignored-hosts = "192.168.90.172:7306"
replication-credential = "db_repl:db_repl"
```
Slave status is Suspect
![image](https://user-images.githubusercontent.com/29646774/209785698-49d01119-ab0c-4d49-97a5-080ccffe5550.png)

After the replication-source-name is commented out, it is normal
![image](https://user-images.githubusercontent.com/29646774/209787043-1412f807-839f-4f23-a4b7-efd83d6683af.png)

**Comment by svaroqui** [comment]
Hi thanks for reporting, i indeed never tested on MySQL and use it a lot on MariaDB will try to fixed, how  critical is this for you ?

**Comment by lenovore** [comment]
It's not too important for me, just to confirm. After failover, I can manually switch multi-source replication. Of course, it is best to support MySQL multi-source replication

**Comment by lenovore** [comment]
By the way, failover-superreadonly-state=true has no effect.
![image](https://user-images.githubusercontent.com/29646774/209895234-94e71c66-69ae-47f7-9485-eec997fa06f5.png)
After switchover,the variable value is still OFF.
![image](https://user-images.githubusercontent.com/29646774/209895559-f6cf7ac8-0d80-476e-a187-7180190f21f9.png)

**Comment by svaroqui** [comment]
Thanks, can you try 2.2.32 and reopen if both issues are not fixed

**Comment by lenovore** [comment]
Unfortunately, there are still problems with version 2.2.32
![image](https://user-images.githubusercontent.com/29646774/210032347-0f4e2bcc-97de-44d6-b6c4-9e42bc264ff8.png)

**Comment by svaroqui** [comment]
Hey this was not on the scope on topology but is fixable, at the same time i don't see why you don't put that standalone node in the same source if it get the same master or in a different cluster if it is from a different cluster or dit you come to such state after switchover or failover, starting from a correct topology ?

**Comment by svaroqui** [comment]
This topology  could be dangerous  because there is no guaranty of serialization between both sources.

**Comment by lenovore** [comment]
Thanks for your reply. The reason why the same source is not used is because of compatibility and purpose. 170 and 171 are used for business data, and 172 are used for other businesses.

Our existing business framework does not support multi-source replication. However, according to what you said, it is also possible to put it under the same source, which is to change the existing architecture. Thanks again, we plan to adjust the architecture to adapt.
