### ISSUE TITLE
MySQL Multi source rejoin got the wrong GITD seq 

### ISSUE THREAD

**Issue by lenovore** [signal18/replication-manager#462]
Replication Manager : v2.2.32
MySQL: 5.7.40

MySQL replication topology
```
192.168.90.170:7306 -> 192.168.90.171:7306(multi-source,channel_name:test_7306)
192.168.90.170:7306 -> 192.168.90.172:7306 (multi-source,channel_name:test_7306)
```
Replication Manager config:

```
replication-source-name="test_7306"

db-servers-hosts = "192.168.90.170:7306,192.168.90.171:7306,192.168.90.172:7306"
db-servers-credential = "replmanager:replmanager"
db-servers-ignored-hosts = "192.168.90.172:7306"
replication-credential = "db_repl:db_repl"
```
192.168.90.171:7306 Skipped a seq  57480 and GTID is 6B950603-82AE-11ED-8536-623C11E9A4C9:1-57479:57481-57483，when 192.168.90.170:7306 rejoined，got master seq 57479 instead of 57483 and cause rejoin failed.
![image](https://user-images.githubusercontent.com/29646774/210794954-e937fbcc-7933-43ec-8ec0-056895c2ba70.png)

**Comment by lenovore** [comment]
Another strange phenomenon is that the automatic failover is blocked. Note that 2023-01-05 21:26:21 is blocked all the time and HA switch button on the page status is 
![image](https://user-images.githubusercontent.com/29646774/210802984-1850f94a-9247-42c6-88ff-495d5b78c34b.png)
. It is only after manually clicking the HA switch button on the page (2023-01-05 21:30:40) that the failover is executed.

Here are some logs
```
time="2023-01-05 21:23:37" level=info msg="Server refresh failed but ping connect driver: bad connection" cluster=cluster_test1
time="2023-01-05 21:23:43" level=info msg="State changed, init failed server 192.168.90.170:7306 as unconnected" cluster=cluster_test1
time="2023-01-05 21:23:43" level=info msg="Server 192.168.90.170:7306 state transition Failed changed to: StandAlone" cluster=cluster_test1
time="2023-01-05 21:23:43" level=info msg="Calling alert script" cluster=cluster_test1
time="2023-01-05 21:23:43" level=info msg="Alert script complete:%!(EXTRA string=)" cluster=cluster_test1
time="2023-01-05 21:23:43" level=info msg="Server 192.168.90.170:7306 previous state changed to: StandAlone" cluster=cluster_test1
time="2023-01-05 21:23:43" level=info msg="Server 192.168.90.170:7306 state transition StandAlone changed to: Master" cluster=cluster_test1
time="2023-01-05 21:23:43" level=info msg="Can DB Connect creating cookie state:Master" cluster=cluster_test1
time="2023-01-05 21:23:46" level=info msg="Server 192.168.90.170:7306 previous state changed to: Master" cluster=cluster_test1
time="2023-01-05 21:25:53" level=info msg="Master Failure detected! Retry 1/10" cluster=cluster_test1
time="2023-01-05 21:25:53" level=info msg="Server 192.168.90.170:7306 state transition Master changed to: Suspect" cluster=cluster_test1
time="2023-01-05 21:25:53" level=info msg="Server 192.168.90.170:7306 previous state changed to: Suspect" cluster=cluster_test1
time="2023-01-05 21:25:53" level=info msg="Server 192.168.90.170:7306 state transition Suspect changed to: Master" cluster=cluster_test1
time="2023-01-05 21:25:56" level=info msg="Master Failure detected! Retry 2/10" cluster=cluster_test1
time="2023-01-05 21:25:56" level=info msg="Server 192.168.90.170:7306 state transition Suspect changed to: Master" cluster=cluster_test1
time="2023-01-05 21:25:59" level=info msg="Master Failure detected! Retry 3/10" cluster=cluster_test1
time="2023-01-05 21:25:59" level=info msg="Server 192.168.90.170:7306 state transition Suspect changed to: Master" cluster=cluster_test1
time="2023-01-05 21:26:02" level=info msg="Master Failure detected! Retry 4/10" cluster=cluster_test1
time="2023-01-05 21:26:02" level=info msg="Server 192.168.90.170:7306 state transition Suspect changed to: Master" cluster=cluster_test1
time="2023-01-05 21:26:05" level=info msg="Master Failure detected! Retry 5/10" cluster=cluster_test1
time="2023-01-05 21:26:05" level=info msg="Server 192.168.90.170:7306 state transition Suspect changed to: Master" cluster=cluster_test1
time="2023-01-05 21:26:08" level=info msg="Master Failure detected! Retry 6/10" cluster=cluster_test1
time="2023-01-05 21:26:08" level=info msg="Server 192.168.90.170:7306 state transition Suspect changed to: Master" cluster=cluster_test1
time="2023-01-05 21:26:12" level=info msg="Master Failure detected! Retry 7/10" cluster=cluster_test1
time="2023-01-05 21:26:12" level=info msg="Server 192.168.90.170:7306 state transition Suspect changed to: Master" cluster=cluster_test1
time="2023-01-05 21:26:15" level=info msg="Master Failure detected! Retry 8/10" cluster=cluster_test1
time="2023-01-05 21:26:15" level=info msg="Server 192.168.90.170:7306 state transition Suspect changed to: Master" cluster=cluster_test1
time="2023-01-05 21:26:18" level=info msg="Master Failure detected! Retry 9/10" cluster=cluster_test1
time="2023-01-05 21:26:18" level=info msg="Server 192.168.90.170:7306 state transition Suspect changed to: Master" cluster=cluster_test1
time="2023-01-05 21:26:21" level=info msg="Master Failure detected! Retry 10/10" cluster=cluster_test1
time="2023-01-05 21:26:21" level=info msg="Declaring db master as failed 192.168.90.170:7306" cluster=cluster_test1
time="2023-01-05 21:26:21" level=info msg="Server 192.168.90.170:7306 state transition Suspect changed to: Failed" cluster=cluster_test1
time="2023-01-05 21:26:21" level=warning msg="Server 192.168.90.170:7306 state changed from Suspect to Failed" cluster=cluster_test1 type=alert
time="2023-01-05 21:26:21" level=info msg="Calling alert script" cluster=cluster_test1
time="2023-01-05 21:26:21" level=info msg="Alert script complete:%!(EXTRA string=)" cluster=cluster_test1
time="2023-01-05 21:26:21" level=info msg="Server 192.168.90.170:7306 previous state changed to: Failed" cluster=cluster_test1

time="2023-01-05 21:30:40" level=info msg=------------------------ cluster=cluster_test1
time="2023-01-05 21:30:40" level=info msg="Starting master failover" cluster=cluster_test1
time="2023-01-05 21:30:40" level=info msg=------------------------ cluster=cluster_test1
time="2023-01-05 21:30:40" level=info msg="Electing a new master" cluster=cluster_test1

```

I have configured automatic failover in the following way:
**/a/apps/replication-manager/etc/config.toml**
```
[Default]
include = "/a/apps/replication-manager/etc/cluster.d"
failover-mode = "manual"
```
**/a/apps/replication-manager/etc/cluster.d/test1.toml**
```
[cluster_test1]
failover-mode = "automatic"
```

**Comment by svaroqui** [comment]
Hi, i was not able to reproduce the automatic failover issue from a fresh cluster where i do stop the master and from the log it appear that you also entering the failover after 10/10 the is probaly soething else blocking the failover after but the log is truncated do you have what follow in the log ?

**Comment by svaroqui** [comment]
From your first post this need more investigation why it report wrong rejoining sequence , may be this is caused by non valid wait for relay log apply after the election of the new master on this release of mysql , so far on 8.0.x i never encounter such case in testing , can you reproduce it every time on your side ?

**Comment by svaroqui** [comment]
Hooooo grrr MariaDB  is error 1617 MySQL is  error 3074 grrrfr 

	ss, _, errss := dbhelper.GetSlaveStatus(server.Conn, server.ClusterGroup.Conf.MasterConn, server.DBVersion)
	// We have no replicatieon can this be the old master
	//  1617 is no multi source channel found
	noChannel := false
	if errss != nil {
		if strings.Contains(errss.Error(), "1617") || strings.Contains(errss.Error(), "3074") {
			// This is a special case when using muti source there is a error instead of empty resultset when no replication is defined on channel
			//	server.ClusterGroup.LogPrintf(LvlInfo, " server: %s replication no channel err 1617 %s ", server.URL, errss)
			noChannel = true
		}
	}

**Comment by lenovore** [comment]
Hi,the log is not truncated.I left it blank just for observation.
![image](https://user-images.githubusercontent.com/29646774/210872972-908ca32f-1533-4cbc-932c-ec38f1db8a3c.png)

After failover, the old master has redundant data. I rolled back the redundant data and used mysqlbinlog -- exclude-gtids to regenerate the binlog file and replace the original file to exclude redundant binlog GTID(6B950603-82AE-11ED-8536-623C11E9A4C9:57480). When failover occurs again, the seq of the slave node becomes 1-57479:57481-57483.

By the way, no data is written to MySQL during failover

**Comment by svaroqui** [comment]
Clever solution, 

replication-manager does not yet support this procedure for flashback old master, but it can run a custom rejoin
script may be we could atomate such solution,  it has partial support of it when
rejoin flashback is enable but never tested it on  MySQL (only  MariaDB) and it only reverse
the data not the binlog file like you do.

Also MariaDB  fixed this binlog file issue when using semi-sync it rollback transactions not received by any
semisync slave  in  the storage engine and in binlog file on restart

**Comment by lenovore** [comment]
Mariadb is really better than MySQL in some features such as binlog.

**Comment by lenovore** [comment]
Hi,It is also the problem of automatic failover.

I don't know whether it is because I changed the binlog and deleted some gtids, or because I used multi-source replication,after I stopped the master, it can not  failover automatically. 
There is no problem with manual failover on the page when I click the HA button.
![image](https://user-images.githubusercontent.com/29646774/211272344-3a83d4fe-340d-461a-8444-ff06a11acd41.png)

debug log
[manager.txt](https://github.com/signal18/replication-manager/files/10371771/manager.txt)

**Comment by lenovore** [comment]
configuration file
[config.toml.txt](https://github.com/signal18/replication-manager/files/10371813/config.toml.txt)
[test1.toml.txt](https://github.com/signal18/replication-manager/files/10371814/test1.toml.txt)

**Comment by svaroqui** [comment]
Hi if using multi source please use 2.2.33 i building the repo now, but in case you should not mix multiple servers from different source inside the same cluster . You should configure one cluster for first source and an other cluster for second source, than replication-manager can do in such case is to manage the replications between the 2 leaders of each source and discover the replica on the other cluster

**Comment by lenovore** [comment]
I use the installation package replication manager osc downloaded from this address  https://repo.signal18.io/deb/incoming/2.2/,
there is no 2.2.33.

**Comment by svaroqui** [comment]
i'm buliding it now , if i understand you could have replicas that fetch data form 2 source correct , if it's the case i think it is wrong design because 2 different replicas does not have the same consistency in regards to GTID, that why i prefer to only link leader of 2 sources so that each replica than get a consist point in time in regards to it's leader

**Comment by lenovore** [comment]
Different clusters are distinguished by tags，for example：
[cluster_test1]
title = "cluster_test1"
db-servers-hosts = "192.168.90.170:7306,192.168.90.171:7306,192.168.90.172:7306"

[cluster_test2]
title = "cluster_test2"
db-servers-hosts = "192.168.90.170:8306,192.168.90.171:8306,192.168.90.172:7306"

**Comment by svaroqui** [comment]
Yes you have 2 times 192.168.90.172:7306

**Comment by lenovore** [comment]
yes

**Comment by svaroqui** [comment]
The way 2 do it with replication-manager is to have distinct clusters and build the extra link beetween both master

**Comment by svaroqui** [comment]
2.2.33 should be in repo now

**Comment by svaroqui** [comment]
This version is fixing MySQL multi source replication standalone(leader) detection as my previous comment about strings.Contains(errss.Error(), "3074" and not an empty resultset

**Comment by lenovore** [comment]
ok.thanks,i will be try it

**Comment by lenovore** [comment]
Hi,i upgraded to 2.2.23.
![image](https://user-images.githubusercontent.com/29646774/211445658-41abbd17-afce-440a-97f5-3e363c773b11.png)

I canceled multi-source replication and used semi-synchronous replication. It took more than 2 minutes to start automatic failover. I don't know where it will take so long.
![image](https://user-images.githubusercontent.com/29646774/211445362-43233d5b-fadb-4d2a-abf2-81532119916c.png)
