### ISSUE TITLE
Replication manager pro don't start if account.yaml not found

### ISSUE THREAD

**Issue by emmaloubersac** [signal18/replication-manager#470]
Add one parameter to specify the file path of account.yaml, containing opensvc user password of the collector.
Don't panic if not found.

**Comment by svaroqui** [comment]
opensvc-collector-account default /etc/replication-manager/account.yaml

**Comment by emmaloubersac** [comment]
when p12 certif not found for opensvc api cluster, exit

**Comment by emmaloubersac** [comment]
add http time out for get_node and out get_node in go routine
