### ISSUE TITLE
Get password from a vault

### ISSUE THREAD

**Issue by Thorsieger** [signal18/replication-manager#484]
Hello,

even though there are a [security function](https://docs.signal18.io/configuration/security) that use AES encryption.

I will find usefull to don't write my databases logins in the config file.

Is their, by any chance, a plan to implement a way to get secret from a password manager ( I was thinking of Hashicorp Vault) to be use in the replication-manager ?

**Comment by tanji** [comment]
Hi @Thorsieger I am a Hashicorp Vault user myself, how I do it is using Ansible to get the secret from Vault then write the file. You can also do this with Vault Agent.
We don't plan native implementation of Vault in the future but why not! Could be something to think of.

**Comment by svaroqui** [comment]
Hi i have quick question on the implementation , we could go and fetch the password from a vault path we would simply extend user:password to user:/vault_path is such implementation  just as key value store good for you in first place or do you plan to make replication-manager work in coordination with Database Secrets Engine  and replication-manager use temporary user/password account created by vault ?

**Comment by svaroqui** [comment]
Solution 1 using secret engine V2  
vault kv put secret/replication-manager/db-servers-credential="repman:my_secret_monitoring_pwd" 
vault kv put secret/replication-manager/replication-credential="replication:my_secret_replication_pwd"

would be instructed in replication-manager  
--replication-credential="secret/replication-manager/replication-credential"
--db-servers-credential="secret/replication-manager/db-servers-credential"

**Comment by Thorsieger** [comment]
Hi ! I think solution 1 is good

I was thinking of something like that for the config files: 

vault kv put secret/replication-manager/replication-credential/cluster1/repman="my_secret_monitoring_pwd"
vault kv put secret/replication-manager/replication-credential/cluster1/replication="my_secret_replication_pwd"

/etc/replication-manager/cluster.d/cluster1.toml : 
```
[cluster1]
title = "cluster1"
...
db-servers-credential = "repman:secret/replication-manager/replication-credential/cluster1/repman"
replication-credential = "replication:secret/replication-manager/replication-credential/cluster1/replication"
```

or just : 
```
db-servers-credential = "secret/replication-manager/replication-credential/cluster1/repman"
replication-credential = "secret/replication-manager/replication-credential/cluster1/replication"
```

that get translated into : name_of_secret=user & value_of_secret=password
but I'm not sure about this last one.

and for the replication manager, using approle for vault: 
--vault-server-addr="https://vault.url"
--vault-role-id=XXX
--vault-secret-id=XXX
