### ISSUE TITLE
develop source build error!

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#488]
[root@localhost replication-manager]# ll
total 264
-rw-r--r--  1 root root  28335 Apr 11 03:22 Gopkg.lock
-rw-r--r--  1 root root   2807 Apr 11 03:22 Gopkg.toml
-rw-r--r--  1 root root    801 Apr 11 03:22 Jenkinsfile
-rw-r--r--  1 root root  35147 Apr 11 03:22 LICENSE
-rwxr-xr-x  1 root root   5935 Apr 11 03:22 Makefile
-rw-r--r--  1 root root   1495 Apr 11 03:22 README.md
-rw-r--r--  1 root root   1539 Apr 11 03:22 agent.go
drwxr-xr-x  2 root root     52 Apr 11 03:22 arbitrator
drwxr-xr-x  6 root root     63 Apr 11 03:22 build
drwxr-xr-x  2 root root     21 Apr 11 03:22 cert
-rw-r--r--  1 root root   2042 Apr 11 03:22 certgen.go
drwxr-xr-x  2 root root    305 Apr 11 03:22 clients
drwxr-xr-x  4 root root   4096 Apr 11 03:22 cluster
drwxr-xr-x  2 root root     23 Apr 11 03:22 config
drwxr-xr-x  3 root root     30 Apr 11 03:22 contrib
drwxr-xr-x  2 root root    190 Apr 11 03:22 doc
drwxr-xr-x  2 root root     85 Apr 11 03:22 docker
drwxr-xr-x  6 root root    132 Apr 11 03:22 etc
-rw-r--r--  1 root root   7073 Apr 11 03:22 go.mod
-rw-r--r--  1 root root 117755 Apr 11 03:22 go.sum
drwxr-xr-x  4 root root     33 Apr 11 03:22 goofys
drwxr-xr-x 15 root root   4096 Apr 11 03:22 graphite
-rw-r--r--  1 root root    776 Apr 11 03:22 main_arbitrator.go
-rw-r--r--  1 root root    765 Apr 11 03:22 main_client.go
-rw-r--r--  1 root root    762 Apr 11 03:22 main_server.go
drwxr-xr-x  2 root root     50 Apr 11 03:22 opensvc
-rw-r--r--  1 root root    316 Apr 11 03:22 package-lock.json
-rwxr-xr-x  1 root root   6115 Apr 11 03:22 package_linux.sh
drwxr-xr-x  2 root root   4096 Apr 11 03:22 regtest
drwxr-xr-x  2 root root    181 Apr 11 03:22 repmanv3
drwxr-xr-x  7 root root     82 Apr 11 03:22 router
drwxr-xr-x  2 root root    274 Apr 11 03:22 server
drwxr-xr-x  2 root root   4096 Apr 11 03:22 service
drwxr-xr-x 12 root root    302 Apr 11 03:22 share
drwxr-xr-x  3 root root     33 Apr 11 03:22 signal18
-rw-r--r--  1 root root    332 Apr 11 03:22 tools.go
-rwxr-xr-x  1 root root   2300 Apr 11 03:22 updaterepo.sh
drwxr-xr-x 12 root root    139 Apr 11 03:22 utils

[root@localhost replication-manager]# ./package_linux.sh 
# Getting branch info
## develop...origin/develop
# Building for amd64
env GOOS=linux GOARCH=amd64 go build -v --tags "server" --ldflags "-extldflags '-static' -w -s -X github.com/signal18/replication-manager/server.Version=v2.3.3 -X github.com/signal18/replication-manager/server.FullVersion=v2.3.3-1-g13809c8b -X github.com/signal18/replication-manager/server.Build=2023-04-11T03:24:01+0900 -X github.com/signal18/replication-manager/server.WithProvisioning=OFF "   -o build/binaries/replication-manager-osc
etc/embed.go:8:12: pattern local/embed/config.toml: no matching files found
make: *** [Makefile:28: osc] Error 1
[root@localhost replication-manager]#

**Comment by svaroqui** [comment]
Thanks for the report
