### ISSUE TITLE
deb package for v2.3.3 not available for x86_64

### ISSUE THREAD

**Issue by Thorsieger** [signal18/replication-manager#489]
Hi ! 

I would like to upgrade my replication-manager to latest 2.3 version; i.e. 2.3.3 but the deb release for x86_64 is not available at http://repo.signal18.io .

Thx in advance

**Comment by svaroqui** [comment]
Hi thanks for reporting, it should be fixed now for 2.3.4

**Comment by svaroqui** [comment]
Please reopen if not fixed
