### ISSUE TITLE
Misleading Error Message: Error getting privileges for user root on server 127.0.0.1:3307: sql: no rows in result set. 

### ISSUE THREAD

**Issue by willcn** [signal18/replication-manager#50]
When running the monitor:

replication-manager monitor --hosts=127.0.0.1:3307,127.0.0.1:3308,127.0.0.1:3309 --user=root --rpluser=r --verbose

I got this error message:

ERROR:ERR00015 Error getting privileges for user root on server 127.0.0.1:3307: sql: no rows in result set. 

Turning on the general query log, I found out what queries this was after:

Execute SELECT Select_priv, Process_priv, Super_priv, Repl_slave_priv, Repl_client_priv, Reload_priv FROM mysql.user WHERE user = 'root' AND host = '127.0.0.1'
Execute SELECT Select_priv, Process_priv, Super_priv, Repl_slave_priv, Repl_client_priv, Reload_priv FROM mysql.user WHERE user = 'r' AND host = '127.0.0.1'
Execute SELECT Select_priv, Process_priv, Super_priv, Repl_slave_priv, Repl_client_priv, Reload_priv FROM mysql.user WHERE user = 'r' AND host = '%'

I had the first two users, but I did not have the r@% user. 

This was confusing because it wasn't the root user as the error message stated.

It would be great if the error message could show what query it ran, to make debugging these a bit easier.

Thanks!

**Comment by tanji** [comment]
Fixed in a19b63964ab464afad976a78453668ea49ddb905

**Comment by blackluck** [comment]
It's the same issue if rpl user is not allowed from a specific slave ip, but a subnet.
Originaly I have rpl user like replicator@192.168.0.0/255.255.255.0
After created rpl user with specific ip too the error message is gone, but this should handle subnets also.

**Comment by tanji** [comment]
Noted to add support for subnets.

**Comment by sysdljr** [comment]
Hi, @tanji 
    We run MRM 0.7 in host  10.1.0.121 or 10.1.0.123,  monitor is normal.
    repmgr monitor --gtidcheck --logfile=/tmp/repmonitor.log --user=mysqlcheck:xxx --rpluser=rep_user:xxx --hosts=10.1.0.121:3306,10.1.0.123:3306
   when run  in host 192.168.1.133 ,   both master and slave are normal,  but show some error message,    please help to confirm, thanks.

```
     Host   Port          Status   Failures   Using GTID         Current GTID           Slave GTID             Replication Health  Delay  RO$<2>                                                                                                                                                                                                                                    
 10.1.0.121   3306          Master          0                  0-121-2835392590$<2>                         Master OK      0 OFF$<2>                                       
 10.1.0.123   3306           Slave          0    Slave_Pos     0-121-2835392594     0-121-2835392594$<2>                 Running OK      0  ON                                           
```

 Ctrl-Q0to4quit,9Ctrl-SFto:switchovertarted in manual mode                                                                                                                                   

 2016-10-14 15:19:54 ERROR: ERR00015 Error getting privileges for user rep_user on server 10.1.0.121:3306: sql: no rows in result set  
 2016-10-14 15:19:54 ERROR: ERR00005 Error getting privileges for user mysqlcheck@test-133: sql: no rows in result set  

---

supplement：
192.168.1.133  hostname is test-133,   it own grants in 10.1.0.121 or 10.1.0.123:
--   mysqlcheck@192.168.1.133
GRANT SELECT, RELOAD, PROCESS, SUPER, REPLICATION CLIENT ON _._ TO 'mysqlcheck'@'192.168.1.133' IDENTIFIED BY PASSWORD 'xxxxxx'

--    rep_user@10.1.0.121
GRANT REPLICATION SLAVE ON _._ TO 'rep_user'@'10.1.0.121' IDENTIFIED BY PASSWORD 'xxxxx'

**Comment by svaroqui** [comment]
Hi, 

Looks like you need to setup grants on the 121 from the 123 
GRANT REPLICATION SLAVE ON . TO 'rep_user'@'10.1.0.123' IDENTIFIED BY PASSWORD 'xxxxx'

Looks like the grants are checked with ip address and not hostname  
test-133
adding mysqlcheck@test-133 grants should remove the issue 

Please let us know if it helps , i will check the code if hostname detection need to be added as a feature request .

**Comment by sysdljr** [comment]
@svaroqui ,thank you.

setup grants on the 10.1.0.121:
 GRANT REPLICATION SLAVE ON _._ TO 'rep_user'@'10.1.0.123' IDENTIFIED BY PASSWORD '_xxxx';
 GRANT REPLICATION SLAVE ON *._ TO 'rep_user'@'10.1.0.121' IDENTIFIED BY PASSWORD '*xxxx';

setup grants on the 10.1.0.123:
 GRANT REPLICATION SLAVE ON _._ TO 'rep_user'@'10.1.0.123' IDENTIFIED BY PASSWORD '_xxxx';
 GRANT REPLICATION SLAVE ON *._ TO 'rep_user'@'10.1.0.121' IDENTIFIED BY PASSWORD '*xxxx';

because  we add skip_name_resolve in my.cnf file,  can not  adding mysqlcheck@test-133.
we have not add  mysqlcheck@hostname  in  10.1.0.123 or 10.1.0.121 ,  when MRM run in 10.1.0.123 or 10.1.0.121 ,all normal.
if MRM run in 192.168._._ ,  all of privileges setup  too,  but have error on above.
