### ISSUE TITLE
Alert with error description

### ISSUE THREAD

**Issue by svaroqui** [signal18/replication-manager#500]
Email does not contains error description

**Comment by ahfa92** [comment]
This will be helpful if we can get more descriptive alert. And if we can add cluster name in the alert.

**Comment by svaroqui** [comment]
> This will be helpful if we can get more descriptive alert. And if we can add cluster name in the alert.

Can you provide an example of alert that you want to improved ? I see many place in the code where the cluster name is already specify

**Comment by ahfa92** [comment]
Sorry I mean the hostname or the IP where replication manager installed. I have some server installed with replication manager. When the service started, there is an email, but I don't know which replication manager server sent the email.

**Comment by svaroqui** [comment]
Hooo i get it now : make sens
