### ISSUE TITLE
replication-manager-cli command is Issues with API Credential Options

### ISSUE THREAD

**Issue by nyxneuf** [signal18/replication-manager#504]
https://github.com/signal18/replication-manager/issues/496

[config.toml]

api-credentials = "admin:repman" -> replication-manager-cli console command does not run. 

api-credential = "admin:repman" -> replication manager-cli console command executed without password.

api-credentials VS api-credential 

------

https://github.com/signal18/replication-manager/commit/939f5d51890008687e6de59f315511953a9356ea

Can you check if there is a problem with the source?

**Comment by svaroqui** [comment]
Hi ,

Not able to reproduce on last source code 

Please see my config.toml file 

```
[Default]
# log-heartbeat = true
include ="etc/opensvc/cluster-api/cluster-demo/stephane.d"
log-file="/var/log/replication-manager.log"
http-bind-address = "0.0.0.0"
api-credentials="admin:repman"

```

And in my include ="etc/opensvc/cluster-api/cluster-demo/stephane.d"

I get multiple config files like bench.toml mysql80.toml

cat "etc/opensvc/cluster-api/cluster-demo/stephane.d/bench.toml"
```
[bench]
title = "bench"
db-servers-hosts = "db1,db2,db3"
db-servers-prefered-master = "db1"

```

And as a extrat command line test , do 

`./replication-manager-pro --config=etc/opensvc/cluster-api/cluster-demo/stephane.toml monitor  --monitoring-save-config --api-credentials="admin:toto" `

and then indeed to rune the console i need to  run 

`./replication-manager-cli console --password=toto  `

This is expected  .
