### ISSUE TITLE
replication-manager crash with: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lukasdebaum** [signal18/replication-manager#505]
Hi

i have installed the latest package of the replication-manager on a debian 12 (bookworm). 
   (replication-manager-osc_2.3.11_amd64.deb)

Unfortunately the replication-manager-osc crashes immediately after startup with the following runtime error.
I use the "Minimal configuration" from the documentation. Also a self compiled replication-manager binary crashes with the same runtime error. 

 `/usr/bin/replication-manager-osc monitor --config /etc/replication-manager/config.toml`

````
WARN[2023-09-11T21:35:34+02:00] No include directory in default section      
WARN[2023-09-11T21:35:34+02:00] No monitoring-save-config variable in default section config change lost on restart 
INFO[2023-09-11T21:35:34+02:00] Replication-Manager started in daemon mode    version=v2.3.11
INFO[2023-09-11T21:35:34+02:00] repman.Conf.WorkingDir : /var/lib/replication-manager 
INFO[2023-09-11T21:35:34+02:00] repman.Conf.ShareDir : /usr/share/replication-manager 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1de8688]

goroutine 1 [running]:
github.com/signal18/replication-manager/server.(*ReplicationManager).StartCluster(0xc000218000, {0x22ef5c7, 0x7})
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/server/server.go:1105 +0x288
github.com/signal18/replication-manager/server.(*ReplicationManager).Run(0xc000218000)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/server/server.go:893 +0x23c8
github.com/signal18/replication-manager/server.glob..func5(0x3f6e300, {0x22eaf92, 0x2, 0x2})
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/server/server_monitor.go:718 +0x105
github.com/spf13/cobra.(*Command).execute(0x3f6e300, {0xc00011e600, 0x2, 0x2})
        /var/jenkins_home/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x3f6ddc0)
        /var/jenkins_home/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x38d
github.com/spf13/cobra.(*Command).Execute(...)
        /var/jenkins_home/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
github.com/signal18/replication-manager/server.Execute()
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/server/server_cmd.go:104 +0x25
main.main()
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/main_server.go:24 +0x19
````
   

`/etc/replication-manager/config.toml`
````
[Default]
title = "db-c1"
db-servers-hosts = "db2-c1:3306,db1-c1:3306"
db-servers-credential = "replmgr:xxx"
replication-credential = "repl:xxx"
failover-mode = "manual"
````

**Comment by svaroqui** [comment]
Hi,
Thanks for reporting can you try with following  config 

[Default]
failover-mode = "manual"

[TestCluster]
title = "TestCluster"
db-servers-hosts = "db2-c1:3306,db1-c1:3306"
db-servers-credential = "replmgr:xxx"
replication-credential = "repl:xxx"

**Comment by svaroqui** [comment]
I was able to reproduce the crash , indeed it should not crash , we have been doing work with  for --monitoring-save-config=true.  and probably lost such minimum setup  that only works with [Default] being a special section that apply to every other cluster section, i will change documentation and fix the crash

**Comment by lukasdebaum** [comment]
Thank you for the quick response.
With the config you suggested the replication manager starts without problems, thanks!

**Comment by svaroqui** [comment]
What routing solution do you plan to use , proxysql , haproxy ?

**Comment by lukasdebaum** [comment]
I need to replace an old replication manager 1.0.x setup. It changes the ip using failover-post-script and failover-pre-script but only manually before an update.

**Comment by svaroqui** [comment]
If you need help you can create account at git.signal18.io and then join our support chat on meet.signal18.io
