### ISSUE TITLE
authentication errors detection - how it detects authentication is faulty or ok

### ISSUE THREAD

**Issue by lukasdebaum** [signal18/replication-manager#506]
Hi

I have the problem that when I run the replication-manager-cli several times I get "blocked" for 3 minutes.

````
root@ha-c1:~# replication-manager-cli status --user root --password xxx
running
root@ha-c1:~# replication-manager-cli status --user root --password xxx
running
root@ha-c1:~# replication-manager-cli status --user root --password xxx
running
root@ha-c1:~# replication-manager-cli status --user root --password xxx
INFO[0000] ERROR in login unexpected end of JSON input  
````

replication-manager-osc monitor
`3 authentication errors for the user root, please try again in 3 minutes`

How does the following function (server/api.go) decide if the authentication is faulty or ok? and only count if the authentication is faulty.
[565e82b](https://github.com/signal18/replication-manager/commit/565e82bbcc94500d7dd6021fe93ab124352e89a1)

**Comment by svaroqui** [comment]
Hi thanks for reporting That's a new feature , are you sure that the authentification is valid this feature is anti brut force attack but the login counter should not increase on success

**Comment by lukasdebaum** [comment]
I think so I get data back ("running")

```
root@ha-c1:~# replication-manager-cli status --password xxx
running
root@ha-c1:~# replication-manager-cli status --password yyy
Cluster not found
```

Is my problem not reproducible if you check the "status" more than 3 times in a short time?
