### ISSUE TITLE
FR: Dashboard: Be able to specify preferred master when switching over

### ISSUE THREAD

**Issue by willcn** [signal18/replication-manager#53]
When using the dashboard, it would be great if I could specify which host to switchover to. A simple input box :)

**Comment by tanji** [comment]
Agreed. I think we can implement it for this version.

**Comment by ahfa92** [comment]
Hi, is there any progress on this feature?
This will be a great feature.

As current dashboard I think we can just put a button within the drop-down menu in slave.

**Comment by svaroqui** [comment]
HI many thanks for the reminder i will look at it this month

**Comment by ahfa92** [comment]
You're welcome.
I tried to code but it seems it's not my strength. 
Tried to help but only got few things changed today 
https://github.com/ahfa92/replication-manager/tree/develop

**Comment by svaroqui** [comment]
Well good try looks good to me .. i will review , if you wan't to try it yourself you need to compile go code with make pro  or make osc as the web code is now embedded or you can  run repman with --test=true  forcing it to use the file in monitoring-sharedir and --http-root string                                     Path to HTTP replication-monitor files (default "/opt/replication-manager/share/dashboard")
& Don't forget to clear you browser cache to get the new dashboard

**Comment by svaroqui** [comment]
From the review you  added code in the cluster_api.go where it should more go inside server_api as this is action done on a given db server , also there is already an existing grant to switchover  named cluster-switchover

**Comment by ahfa92** [comment]
> 

Yes, I didn't know which api triggered the switch. For the best duration I think it's better for you to solve this feature. I will try to learn this replication-manager code first and see if I can contribute later.

**Comment by svaroqui** [comment]
Could you reopen if not fixed in next release
