### ISSUE TITLE
SLA Uptime updates too frequently

### ISSUE THREAD

**Issue by willcn** [signal18/replication-manager#54]
On my completely idle system, the SLA Uptime updates too frequently, which makes the value bounce around from 99.94 to 99.99999. This is a bit distracting, and also less reliable.

I'm not sure what the purpose of this information is, so I'm not sure what to recommend as a fix. But it should at least take a longer sample. 

Thanks,
-will

**Comment by tanji** [comment]
Fixed in 7dc7193cdf461d35537a75205f248622a0834892
