### ISSUE TITLE
Vulnerability for JQUERY 2.1.1 with REP manager version 2.3.14 | Need to upgrade JQUERY

### ISSUE THREAD

**Issue by rupeshhandore** [signal18/replication-manager#543]
Team,

We are using rep manager 2.3.14 which is having some vulnerability related to JQUERY. 
Is there any impact for repmanager if we upgrade JQUERY?

the version of JQuery hosted on the remote web server is greater than or equal to 1.2 and prior to 3.5.0. It is, therefore, affected by multiple cross site scripting vulnerabilities.

https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

Installed version : 2.1.1
Fixed version     : 3.5.0

Upgrade to JQuery version 3.5.0 or later.

**Comment by svaroqui** [comment]
No Jquery is only used for graph , i guess we can rewrite this

**Comment by caffeinated92** [comment]
Let's see if we can use JQuery v3. Need to check if the old function is working properly.

**Comment by svaroqui** [comment]
Well replication manager does not really need graphs as it is already data source for grafana  , the idea was to use giraffe to display few graphs, it looks like giraffe now moved to react

**Comment by svaroqui** [comment]
https://square.github.io/cubism/ looks like we can move foward now with such library

**Comment by svaroqui** [comment]
If you need to test changing the dashboard be aware that the code is embed to use  the dashboard in share directory you need to use --debug flag

**Comment by svaroqui** [comment]
sorry it is test=true
