### ISSUE TITLE
dbhelper GetPrivileges fails to retrieve privileges for 127.0.0.1

### ISSUE THREAD

**Issue by fmbiete** [signal18/replication-manager#545]
Hi,

When testing replication manager against a local cluster (mysql shell sandbox instances, db/replica user "root"), GetPrivileges fails to identify the privileges of the user and an error appears in the UI.
The issue happens because the host is "127.0.0.1" and the user host is "localhost" in db.
There should be an special case for this:

```
if host == "127.0.0.1" {
  host = "localhost"
}
```

Adding this allows GetPrivileges to identify the correct user

![Screenshot_20240401_074100](https://github.com/signal18/replication-manager/assets/1531783/a39dfc92-7af4-4084-8387-98b720d172d3)

**Comment by ahfa92** [comment]
Do you have required privileges within DB? This is not replication manager problem, this is user access within DB. You have to understand that MariaDB / MySQL treat 127.0.0.1 (IP) and localhost (NS) differently.

**Comment by ahfa92** [comment]
You can just create a user for root in 127.0.0.1

**Comment by fmbiete** [comment]
Notice how I'm using "root" as the user and it obviously has the required privileges.

A user defined with
_user@hostname_
will be able to login as
_user@ip_

The existing check will never identify the user privileges for any user defined with hostname.
https://github.com/signal18/replication-manager/blob/4cf6fccf18f764cc7ec6662c5907f596a4722eee/cluster/srv_chk.go#L368

Should you not be passing also _myhost_ ?

**Comment by svaroqui** [comment]
Hello we do this already 	via repman.Hostname, err = os.Hostname() in func (repman *ReplicationManager) Run() error {}
from  cluster.repmgrHostname and stored  in cluster class  via func (cluster *Cluster) Init(  cluster.repmgrHostname = repmgrHostname

**Comment by fmbiete** [comment]
You have this:
```
myhost, logs, err := dbhelper.GetHostFromConnection(server.Conn, cluster.GetDbUser(), server.DBVersion)
myip, err := misc.GetIPSafe(misc.Unbracket(myhost))
...

priv, logs, err := dbhelper.GetPrivileges(server.Conn, cluster.GetDbUser(), cluster.repmgrHostname, myip, server.DBVersion)
```

If I don't understand this wrong, _myhost_ is the db user host. _myip_ is the IP resolution.
But in the function call to get the privileges for the user _myhost_ is not passed.

So if the user is defined in the database with the hostname (root@localhost) it won't be found. That function will check against the IPs, IP prefixes and the cluster.repmgrHostname. But not against the connection hostname _myhost_

Is that not an error?

**Comment by tanji** [comment]
Hi @fmbiete as @ahfa92 said, `localhost` does not equal to `127.0.0.1` because it has a special meaning in MySQL and MariaDB:

```
If the host is not specified or is localhost, a connection to the local host occurs:

On Windows, the client connects using shared memory, if the server was started with the [shared_memory](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_shared_memory) system variable enabled to support shared-memory connections.

On Unix, MySQL programs treat the host name localhost specially, in a way that is likely different from what you expect compared to other network-based programs: the client connects using a Unix socket file. The [--socket](https://dev.mysql.com/doc/refman/8.0/en/connection-options.html#option_general_socket) option or the MYSQL_UNIX_PORT environment variable may be used to specify the socket name.
```

Therefore it is not an error but a feature, replication-manager does not support socket connections.

**Comment by svaroqui** [comment]
May be documentation should mention this

**Comment by ahfa92** [comment]
Noted. I will update the document accordingly.

**Comment by ahfa92** [comment]
After checking the docs.signal18.io. The configuration already mentioned about usage of IP and Port:
![image](https://github.com/signal18/replication-manager/assets/35247436/ffd48dd3-06d0-40fa-aab3-4d2fe8908005)

I will add some notes for MySQL/MariaDB privileges for that

**Comment by tanji** [comment]
Yes it's mentioned @ahfa92 but maybe it should say that all the connections are TCP and there is no socket connection option

**Comment by ahfa92** [comment]
I already made a PR in docs.signal18.io.
