### ISSUE TITLE
[2.3.20] No file found /var/lib/replication-manager/clusterX/x.x.x.x/serverstate.json

### ISSUE THREAD

**Issue by firdibasri** [signal18/replication-manager#552]
I just install fresh a repman 2.3.20 (latest) with existing replication mariadb (1 master, 3 slaves), setup config (cluster1.toml), and then restart the service. Then I Login to http and see those all nodes are in status "suspect" (should Master or Slave). From the log file, I got this msg:

No file found /var/lib/replication-manager/cluster2/192.168.18.55_3307/serverstate.json: open /var/lib/replication-manager/cluster2/192.168.18.55_3307/serverstate.json: no such file or directory

[replication-manager.log](https://github.com/signal18/replication-manager/files/14895770/replication-manager.log)

and:
![image](https://github.com/signal18/replication-manager/assets/17285660/0e13706d-4357-456f-b805-736afee9461b)
 

But with previous version (2.3.18) its normal and recognizable the master & slaves nodes and the file "serverstate.json" exists in the directory

**Comment by ahfa92** [comment]
Is the replication running currently?

**Comment by firdibasri** [comment]
hi @ahfa92 , yes of course, 4 nodes/instance (1 master, 3 slaves) in a single server (virtual box), have the same GTID also, running properly. And here all configuration file I've prepared:

config.toml (nothing changed)
[config.toml.txt](https://github.com/signal18/replication-manager/files/14900172/config.toml.txt)

cluster2.toml
[cluster2.toml.txt](https://github.com/signal18/replication-manager/files/14900175/cluster2.toml.txt)

master & slave (.cnf)
[master-slaves.cnf.txt](https://github.com/signal18/replication-manager/files/14900182/master-slaves.cnf.txt)

OS: Ubuntu 20.04 (focal)
MariaDB: 10.11

**Comment by caffeinated92** [comment]
can you give me the result of ls -lah /var/lib/replication-manager/cluster2/192.168.18.55_3307

**Comment by firdibasri** [comment]
hi @caffeinated92 , here is:
![image](https://github.com/signal18/replication-manager/assets/17285660/a4948105-4fc1-45d3-b0a9-c36f0bd58c2c)

home:
![image](https://github.com/signal18/replication-manager/assets/17285660/92d0270b-08d9-4733-bbd2-3ffa05a270e4)

and inside:
![image](https://github.com/signal18/replication-manager/assets/17285660/92e4f50e-caee-40f8-aa9b-f4e608f942f5)

**Comment by firdibasri** [comment]
and also I add result from my existing replication:
![image](https://github.com/signal18/replication-manager/assets/17285660/b3be6921-f39e-4f2d-b8e3-4b2f5d848ee7)

the replication working properly

**Comment by caffeinated92** [comment]
Can you try to restart the replication manager?

**Comment by firdibasri** [comment]
@caffeinated92 , yes sure, but still get the same result. 
![image](https://github.com/signal18/replication-manager/assets/17285660/1d11890e-6834-4107-b042-48debf5e1618)

Here is the log:
[(2) replication-manager.log](https://github.com/signal18/replication-manager/files/14900912/2.replication-manager.log)

**Comment by caffeinated92** [comment]
can you show me:
`show slave hosts` 
from each instance?
time="2024-04-08 11:29:06" level=debug msg="Server 192.168.18.55:3307 has no slaves " cluster=cluster2
time="2024-04-08 11:29:06" level=debug msg="Server 192.168.18.55:3308 has no slaves " cluster=cluster2
time="2024-04-08 11:29:06" level=debug msg="Server 192.168.18.55:3309 has no slaves " cluster=cluster2
time="2024-04-08 11:29:06" level=debug msg="Server 192.168.18.55:3310 has no slaves " cluster=cluster2

**Comment by firdibasri** [comment]
Sure, here is:
![image](https://github.com/signal18/replication-manager/assets/17285660/b073e540-25e0-4c15-a947-619b76102261)

**Comment by firdibasri** [comment]
Just for comparison, here I add some capture from version: 2.3.18 (different VM):

home:
![image](https://github.com/signal18/replication-manager/assets/17285660/b420cc90-af86-456f-85ca-18b149173ac0)

inside:
![image](https://github.com/signal18/replication-manager/assets/17285660/62b87e05-56ba-45d3-a17f-14036fb84196)

exists for file: serverstate.json
![image](https://github.com/signal18/replication-manager/assets/17285660/ad46148f-1dac-46ac-b840-c7cdcc6646e5)

**Comment by caffeinated92** [comment]
can you try to `touch /var/lib/replication-manager/cluster2/192.168.18.55_3307/serverstate.json`

**Comment by caffeinated92** [comment]
Wait, if it's different VM, do you have the required privileges? db-servers-credential = "firdi:firdi123" are you using the correct username?
Please use `mariadb -h 192.168.18.55 -u firdi -pfirdi123 -P3307` to check

**Comment by firdibasri** [comment]
> can you try to `touch /var/lib/replication-manager/cluster2/192.168.18.55_3307/serverstate.json`

Sure, success:
![image](https://github.com/signal18/replication-manager/assets/17285660/4f0679c6-37bb-430b-8fe8-194791aef12a)


> Wait, if it's different VM, do you have the required privileges? db-servers-credential = "firdi:firdi123" are you using the correct username? Please use `mariadb -h 192.168.18.55 -u firdi -pfirdi123 -P3307` to check

here is the result:
![image](https://github.com/signal18/replication-manager/assets/17285660/8826ac6a-75a1-409a-a568-cc45e949982b)

**Comment by caffeinated92** [comment]
can you try to set the log to verbose let me know what it logs?

**Comment by firdibasri** [comment]
Sure from file cluster2.toml, I already set `verbose = true`

/var/log/replication-manager.log:
[(3) replication-manager.log](https://github.com/signal18/replication-manager/files/14901235/3.replication-manager.log)

**Comment by caffeinated92** [comment]
Okay. I'm on my way checking. Hope it will be solved soon

**Comment by firdibasri** [comment]
hi @caffeinated92 , I've been update to 2.3.21 and the result now:

current version:
![image](https://github.com/signal18/replication-manager/assets/17285660/a0e109d6-1f3a-46c3-b68c-46280b9b3d95)

file serverstate.json now is exists:
![image](https://github.com/signal18/replication-manager/assets/17285660/63ce9c0c-945a-4e10-a585-fb679fe488f5)

home:
![image](https://github.com/signal18/replication-manager/assets/17285660/d1f75301-b6cf-4a0a-a58c-0fda1fa1fd0f)
But for the Topology is still "**unknown**". For previous version (2.3.18) is able to autodetect and get result 'master-slave' (my capture image above)

inside:
![image](https://github.com/signal18/replication-manager/assets/17285660/ecfc8887-407d-405a-b081-8e0a5d29c19d)

replication-manager.log:
[(4) replication-manager.log](https://github.com/signal18/replication-manager/files/14907344/4.replication-manager.log)

And thank you for solving the problems, really good :)

**Comment by caffeinated92** [comment]
I will check on this again and make sure if everything works well

**Comment by svaroqui** [comment]
I don't get what is special about your setup i have played all day with 2.3.20 without behing able to make it deadlock can you send a show all slaves status from all nodes. Can you also please mv all datadir to something like backup and rm -rf /var/lib/replication-manager/* and see if it does recover the topology

**Comment by svaroqui** [comment]
Can you test the last push release without repo to see if it fixed your issue ?

**Comment by firdibasri** [comment]
> Can you test the last push release without repo to see if it fixed your issue ?

hi @svaroqui , yes sure:
![image](https://github.com/signal18/replication-manager/assets/17285660/f259022b-256c-4818-a410-1b2ada778d17)

and the result is: Topology = unknown and the light (Is Down) is still yellow:
![image](https://github.com/signal18/replication-manager/assets/17285660/a719ffd1-320f-498f-80d5-effe5c7a92fa)

inside:
![image](https://github.com/signal18/replication-manager/assets/17285660/b0d27b5e-3f47-46bb-b659-2ff9582d6254)

**Comment by tanji** [comment]
It seems that in 2.3.20 there were some changes related to topology discovery,
https://github.com/signal18/replication-manager/compare/v2.3.19...v2.3.20#diff-86cbfc045d9b3441a4f4c2235e276915275698f1e70a42e38e74a846cb9bdcc4L652
notably in `cluster/cluster.go` line 652, getTopology was removed and moved earlier in the process (I dont know for which reason) maybe that is causing the issue
since getTopology(fromConf) will only find a MasterServer conf if cluster.master is not nil
```
	} else {
		relay := cluster.GetRelayServer()
		if relay != nil && cluster.Conf.ReplicationNoRelay == false {
			cluster.Conf.Topology = topoMultiTierSlave
		} else if cluster.master != nil {
			cluster.Conf.Topology = topoMasterSlave
		}
	}
```
I would assume the condition is not working at this point.

@svaroqui maybe you can explain why you moved the topology on top of the cluster.Run function?

**Comment by firdibasri** [comment]
Hi, sorry I don't know do I have to raise a new issue again or able to raise here, that:

1. I can not label "Set as Preferred" after choose one or more node  to "FAILOVER CANDIDATE":
![image](https://github.com/signal18/replication-manager/assets/17285660/44d23fa6-184f-4889-966c-845c65cb9fde)

From cluster2.toml, I already set:
![image](https://github.com/signal18/replication-manager/assets/17285660/9109dcbd-dc00-441c-aaf9-3fe1186b1936)

but the symbol is still not visible, then I try manually choose "Set as Preferred" one of them but the symbol is still not visible

2. No cancel button from DELETE SHARD:
![image](https://github.com/signal18/replication-manager/assets/17285660/7302a9f8-1914-466e-82bd-c655f3b4bfce)

3. jquery-3.7.1.min.js not found
![image](https://github.com/signal18/replication-manager/assets/17285660/52ac18f5-660c-4ce1-84bf-5be6700acfcb)


version: 2.3.21
