### ISSUE TITLE
Cannot label set preferred

### ISSUE THREAD

**Issue by tanji** [signal18/replication-manager#555]
Hi, sorry I don't know do I have to raise a new issue again or able to raise here, that:

1. I can not label "Set as Preferred" after choose one or more node  to "FAILOVER CANDIDATE":
![image](https://github.com/signal18/replication-manager/assets/17285660/44d23fa6-184f-4889-966c-845c65cb9fde)

From cluster2.toml, I already set:
![image](https://github.com/signal18/replication-manager/assets/17285660/9109dcbd-dc00-441c-aaf9-3fe1186b1936)

but the symbol is still not visible, then I try manually choose "Set as Preferred" one of them but the symbol is still not visible

2. No cancel button from DELETE SHARD:
![image](https://github.com/signal18/replication-manager/assets/17285660/7302a9f8-1914-466e-82bd-c655f3b4bfce)

3. jquery-3.7.1.min.js not found
![image](https://github.com/signal18/replication-manager/assets/17285660/52ac18f5-660c-4ce1-84bf-5be6700acfcb)

Note:
Before it, I do this:
![image](https://github.com/signal18/replication-manager/assets/17285660/dd46c9d6-143a-449a-a09f-d098f89ce7e1)

version: 2.3.21

_Originally posted by @firdibasri in https://github.com/signal18/replication-manager/issues/552#issuecomment-2043830578_

**Comment by caffeinated92** [comment]
Patch already merged

**Comment by firdibasri** [comment]
Hi, for 2.3.22 (latest) is still not available when I try to upgrade (still 2.3.21), with following:

```
version="2.3"
echo "deb [arch=amd64] http://repo.signal18.io/deb $(lsb_release -sc) $version" > /etc/apt/sources.list.d/signal18.list
apt-key adv --recv-keys --keyserver keyserver.ubuntu.com FAE20E50
apt-get update
apt-get install replication-manager-osc
```
from: https://docs.signal18.io/installation/setup-instructions
Also I try to check from: http://repo.signal18.io/deb/pool/2.3/r/replication-manager-osc/, there is no file for 2.3.22
![image](https://github.com/signal18/replication-manager/assets/17285660/223d2e5a-d623-4e1c-a750-5277a4abbcd3)

My OS: Ubuntu 20.04 (focal)

And, a few days ago I install Ubuntu 23.10 server, but failed when try to install repman. Does repman support for ubuntu 23.10 yet? Or maybe there some missing configuration from me

thanks

**Comment by svaroqui** [comment]
Hi I can see the release in https://repo.signal18.io/deb/pool/2.3/r/replication-manager-osc/ now

**Comment by firdibasri** [comment]
> Hi I can see the release in https://repo.signal18.io/deb/pool/2.3/r/replication-manager-osc/ now

Thank you @svaroqui , I've updated to 2.3.22 now on my ubuntu 20.04 (focal)

FYI, for ubuntu 23.10 server (mantic):
![image](https://github.com/signal18/replication-manager/assets/17285660/1d089335-13ed-4883-8832-11c97f3bf2df)

**Comment by tanji** [comment]
We don't support packages for intermediary versions of Ubuntu, only LTS is supported.

If you want to use non-LTS I suggest compiling from source.

**Comment by firdibasri** [comment]
Oh ok, I understand. Thank you @tanji
