### ISSUE TITLE
improve binlog copy management

### ISSUE THREAD

**Issue by svaroqui** [signal18/replication-manager#558]
today we have 

--backup-binlogs                                       Archive binlogs
--backup-binlogs-keep int                              Number of master binlog to keep (default 10)
  

Would like to add ( today we only enable client) 

--backup-binlogs-method="client|ssh|gomysql|script"     
--backup-binlogs-script path to script (parameters: source_ssh_host ,source_ssh_port,source_path, dest_host ,dest_ssh_port, dest_ssh_path ) default empty

**Comment by caffeinated92** [comment]
options already added in #562 
added ssh method for backup binlogs
added status for show that master is backing up binlog (previously it will be purged by force-binlog-purge-on-restore)
