### ISSUE TITLE
Checking oldest binlog timestamp returned Err: Failed to parse binary log datetime string.

### ISSUE THREAD

**Issue by caffeinated92** [signal18/replication-manager#579]
Replication manager write error when datetime string from mysqlbinlog not found.

ERROR   Failed to parse binary log datetime string. . Str: . Host: 172.24.47.186:3306 - mysql-bin.000010

the reason is mysqlbinlog only parse until position 512 in order to prevent parsing many lines:
"--stop-position=512"

**Comment by peterpan104** [comment]
Thanks for opening a issue about this. If you need any information, please let me know .

**Comment by caffeinated92** [comment]
Hi @peterpan104,

Thanks for informing. Can you give me the result of:

`mysqlbinlog --stop-position=512 mysql-bin.000010`

If you get no timestamp, then can you try to change 512 to 1024?

I want to know if the timestamp will be seen there. 

here is the format of timestamp in binlog: # with 6 digits then space then time
`#[0-9]{6}[ ]{1,2}[0-9:]{8}`

**Comment by peterpan104** [comment]
hi @caffeinated92 

I got the following results, hope it helps you
```
#240508 17:50:46 server id 2447186  end_log_pos 256     Start: binlog v 4, server v 10.4.15-MariaDB-log created 240508 17:50:46 at startup
#240508 17:50:46 server id 2447186  end_log_pos 281     Gtid list []
#240508 17:50:46 server id 2447186  end_log_pos 320     Binlog checkpoint mysql-bin.000001
#240508 17:51:49 server id 2447186  end_log_pos 358     GTID 0-2447186-1 ddl
#240508 17:51:49 server id 2447186  end_log_pos 447     Query   thread_id=509022        exec_time=0     error_code=0
#240508 17:52:03 server id 2447186  end_log_pos 485     GTID 0-2447186-2 ddl
#240508 17:52:03 server id 2447186  end_log_pos 572     Query   thread_id=509022        exec_time=0     error_code=0
#240508 17:52:28 server id 2447186  end_log_pos 610     GTID 0-2447186-3 trans
#240508 17:52:28 server id 2447186  end_log_pos 678     Annotate_rows:
```

**Comment by caffeinated92** [comment]
Hi @peterpan104  thanks for the information. Actually the purpose of this function is to get the oldest timestamp in the binlog. I will try to resolve it this week. I will try to change the method of getting binlog timestamp using go-mysql instead of mysqlbinlog to remove dependencies
