### ISSUE TITLE
Doc Request: How it works and which is the next master

### ISSUE THREAD

**Issue by willcn** [signal18/replication-manager#58]
It would be great to get some general documentation on how MRM is designed to work. 

The most important part is, when doing a failover, what are the exact steps MRM uses to determine which host to fail over to.

Great respect to Mr. Matsunobu for the architecture documentation for MHA (https://code.google.com/p/mysql-master-ha/wiki/TableOfContents?tm=6)

**Comment by tanji** [comment]
now documented at https://docs.signal18.io
