### ISSUE TITLE
The PROXIES page on the Web is displaying abnormally.

### ISSUE THREAD

**Issue by peterpan104** [signal18/replication-manager#592]
I have confirmed that my proxysql is set up, and I can operate maintenance to control mysql_servers through repman. 

However, under different versions, the PROXIES page can't be displayed normally. It could be displayed before. What is the reason for this problem?

== v2.3.26 ==
![image](https://github.com/signal18/replication-manager/assets/140467680/053ec86c-0527-471d-b3fc-a01df5635639)

== v2.3.14 ==
![image](https://github.com/signal18/replication-manager/assets/140467680/0a815c6a-8e0e-44ba-a4cd-3919b17ef322)

**Comment by caffeinated92** [comment]
can you check the alert?
Have you check the proxysql mysql_servers?

And I see the image with two proxies is 2.3.26

**Comment by peterpan104** [comment]
My mysql_servers and runtime_mysql_servers are set up as follows, and no error messages from proxysql.

```
MySQL [(none)]> select * from mysql_servers;
+--------------+---------------+------+-----------+--------+--------+-------------+-----------------+---------------------+---------+----------------+---------+
| hostgroup_id | hostname      | port | gtid_port | status | weight | compression | max_connections | max_replication_lag | use_ssl | max_latency_ms | comment |
+--------------+---------------+------+-----------+--------+--------+-------------+-----------------+---------------------+---------+----------------+---------+
| 11           | 172.24.47.186 | 3306 | 0         | ONLINE | 1      | 0           | 1000            | 99999               | 0       | 0              |         |
| 11           | 172.24.47.187 | 3306 | 0         | ONLINE | 100    | 0           | 1000            | 99999               | 0       | 0              |         |
| 10           | 172.24.47.186 | 3306 | 0         | ONLINE | 1      | 0           | 1000            | 99999               | 0       | 0              |         |
+--------------+---------------+------+-----------+--------+--------+-------------+-----------------+---------------------+---------+----------------+---------+
3 rows in set (0.000 sec)

MySQL [(none)]> select * from runtime_mysql_servers;
+--------------+---------------+------+-----------+--------+--------+-------------+-----------------+---------------------+---------+----------------+---------+
| hostgroup_id | hostname      | port | gtid_port | status | weight | compression | max_connections | max_replication_lag | use_ssl | max_latency_ms | comment |
+--------------+---------------+------+-----------+--------+--------+-------------+-----------------+---------------------+---------+----------------+---------+
| 10           | 172.24.47.186 | 3306 | 0         | ONLINE | 1      | 0           | 1000            | 99999               | 0       | 0              |         |
| 11           | 172.24.47.186 | 3306 | 0         | ONLINE | 1      | 0           | 1000            | 99999               | 0       | 0              |         |
| 11           | 172.24.47.187 | 3306 | 0         | ONLINE | 100    | 0           | 1000            | 99999               | 0       | 0              |         |
+--------------+---------------+------+-----------+--------+--------+-------------+-----------------+---------------------+---------+----------------+---------+
3 rows in set (0.001 sec)

```

I've found the reason. Because I deleted mysql_replication_hostgroups, it caused the web to not display mysql_servers correctly. 

Mysql_replication_hostgroups must be set? I don't understand the necessity, and I don't want too many factors that could potentially cause proxysql to adjust mysql_servers.

**Comment by caffeinated92** [comment]
This is proxySQL feature which is not within signal18 focus. You need to
read more about ProxySQL in their documentation.

**Comment by peterpan104** [comment]
Hi @caffeinated92 
Thanks for your reply.

Why does repman web display abnormally? But I have to read proxysql documentation?

I used tcpdump to view proxysql queries from repman.

```
SELECT hostgroup, status, ConnUsed, Bytes_data_sent , Bytes_data_recv , Latency_us FROM stats.stats_mysql_connection_pool INNER JOIN mysql_replication_hostgroups ON mysql_replication_hostgroups.writer_hostgroup=hostgroup  WHERE srv_host='172.24.47.186' AND srv_port='3306';

SELECT hostgroup, status, ConnUsed, Bytes_data_sent , Bytes_data_recv , Latency_us FROM stats.stats_mysql_connection_pool INNER JOIN mysql_replication_hostgroups ON mysql_replication_hostgroups.reader_hostgroup=hostgroup  WHERE srv_host='172.24.47.186' AND srv_port='3306';

SELECT hostgroup, status, ConnUsed, Bytes_data_sent , Bytes_data_recv , Latency_us FROM stats.stats_mysql_connection_pool INNER JOIN mysql_replication_hostgroups ON mysql_replication_hostgroups.writer_hostgroup=hostgroup  WHERE srv_host='172.24.47.187' AND srv_port='3306';

SELECT hostgroup, status, ConnUsed, Bytes_data_sent , Bytes_data_recv , Latency_us FROM stats.stats_mysql_connection_pool INNER JOIN mysql_replication_hostgroups ON mysql_replication_hostgroups.reader_hostgroup=hostgroup  WHERE srv_host='172.24.47.187' AND srv_port='3306';
```

It's obvious that the queries are using mysql_replication_hostgroups, so when mysql_replication_hostgroups is not set up, the repman web can't display properly.

The following are the functions used by repman:
```
@replication-manager/router/proxysql/proxysql.go
## GetStatsForHostRead
	sql := fmt.Sprintf("SELECT hostgroup, status, ConnUsed, Bytes_data_sent , Bytes_data_recv , Latency_us FROM stats.stats_mysql_connection_pool INNER JOIN mysql_replication_hostgroups ON mysql_replication_hostgroups.reader_hostgroup=hostgroup  WHERE srv_host='%s' AND srv_port='%s'", host, port)


## GetStatsForHostWrite
	sql := fmt.Sprintf("SELECT hostgroup, status, ConnUsed, Bytes_data_sent , Bytes_data_recv , Latency_us FROM stats.stats_mysql_connection_pool INNER JOIN mysql_replication_hostgroups ON mysql_replication_hostgroups.writer_hostgroup=hostgroup  WHERE srv_host='%s' AND srv_port='%s'", host, port)
```

The config.toml can set proxysql-writer-hostgroup and proxysql-reader-hostgroup. I think the query can be modified to the following to get the information needed for this page?

```
SELECT XXX FROM stats.stats_mysql_connection_pool where hostgroup = 'proxysql-writer-hostgroup';

SELECT XXX FROM stats.stats_mysql_connection_pool where hostgroup = 'proxysql-reader-hostgroup';

```

Or is there any reason why mysql_replication_hostgroups must be used?

I hope you can open this issue again and listen to my questions, Thanks.

**Comment by caffeinated92** [comment]
Hi @peterpan104 
Replication hostgroup is a mandatory configuration within proxySQL because the reader and writer hostgroup need to be defined in pair. If you want signal18 to bootstrap, then you can use proxysql-bootstrap-hostgroups variable to true.

**Comment by peterpan104** [comment]
Hi @caffeinated92 

![image](https://github.com/signal18/replication-manager/assets/140467680/3cfc6c99-567f-4969-908c-17b6909ecff4)

Proxysql has mentioned that mysql_replication_hostgroups is optional. 
I don’t understand the purpose of repman using mysql_replication_hostgroups as query conditions? 
That's why I think repman needs to be adjusted.

Thanks.

**Comment by caffeinated92** [comment]
Hi @peterpan104 
We will confirm with ProxySQL about this. In the mean time, we will hold this off for a while until we get the answer from ProxySQL.

**Comment by svaroqui** [comment]
The raison is that you could have as many host group as you like multiple clusters  proxied from the same proxysql

**Comment by peterpan104** [comment]
Hi @svaroqui ,thanks for your reply.

I only need to use mysql_servers to allow multiple clusters to use the same proxysql.
And mysql_replication_hostgroups is just an additional way to control the W/R hostgroups of runtime_mysql_servers, but it depends on whether the user wants to use it or not.

Simply put, when I don't use mysql_replication_hostgroups, proxysql can function properly, but the repman web will display abnormally. This is very strange.

**Comment by svaroqui** [comment]
Agree
