### ISSUE TITLE
Failover failed caused by split brain restore manual is loosing topology

### ISSUE THREAD

**Issue by duguwo** [signal18/replication-manager#597]
After experiencing a failed replication-manager failover, where both nodes became read-only and lost the master-slave relationship, resulting in a split brain scenario, I proceeded by setting the original master as the new master to restore the replication relationship. However, upon checking the replication-manager interface, I observed that the original slave is mistakenly detected as the master, while the original master's status is marked as Suspect. Furthermore, the original slave has an additional transaction compared to the new master, causing replication-manager to be unable to rejoin the cluster. What steps should I take to resolve this issue?
rm status:
![企业微信截图_17162747533051](https://github.com/signal18/replication-manager/assets/48546875/d0781010-364f-4ac9-bfe7-f2c23fdbf7c5)

**Comment by caffeinated92** [comment]
hi @duguwo 
is there any logs why the old master set as suspect? It seems like replication manager can not connect to the old master

**Comment by svaroqui** [comment]
This thread can help you https://www.percona.com/blog/gtid-failover-with-mysqlslavetrx-fix-errant-transactions/, also i remember doing something about errant transaction but we may have to dig into the code to found what as this was log time ago . Is replication-manager run inside his own DC ? Note only MariaDB >10.6 in conjonction with semisync is advice to auto fixe errant transaction as they will be auto remove in binlogs when  old leader rejoin after a crash

**Comment by svaroqui** [comment]
If your database is not big you can enable rejoin with restore backup , backup should be enable from replication-manager they should end in /var/lib/replication-manager/backups/node_xxx that can be mounted for an NFS or form S3 bucket , if you wan't to restore direct dump from master you need to install mysql server and client packages in replication-manager host and configure the path to binaries  mysqlbinlog and mysqldump via replication-manager config

**Comment by svaroqui** [comment]
Having the log may be intersting to understand why new leader did not became read write

**Comment by duguwo** [comment]
> hi @duguwo is there any logs why the old master set as suspect? It seems like replication manager can not connect to the old master

This happened a few days ago, and there are too many logs to pinpoint the exact location. However, the replication between the master and slave is currently functioning properly.

**Comment by duguwo** [comment]
> If your database is not big you can enable rejoin with restore backup , backup should be enable from replication-manager they should end in /var/lib/replication-manager/backups/node_xxx that can be mounted for an NFS or form S3 bucket , if you wan't to restore direct dump from master you need to install mysql server and client packages in replication-manager host and configure the path to binaries mysqlbinlog and mysqldump via replication-manager config

My database is several terabytes in size and currently in use by our business operations. Performing a backup, restore, and reconfiguration of the master-slave setup may not be a practical solution. Is it possible to switch the roles of the master and slave, making the current new master the primary node? I also have another slave that is based on the current master. This way, I can maintain consistent GTID replication. Is this approach feasible?

**Comment by svaroqui** [comment]
> > If your database is not big you can enable rejoin with restore backup , backup should be enable from replication-manager they should end in /var/lib/replication-manager/backups/node_xxx that can be mounted for an NFS or form S3 bucket , if you wan't to restore direct dump from master you need to install mysql server and client packages in replication-manager host and configure the path to binaries mysqlbinlog and mysqldump via replication-manager config
> 
> My database is several terabytes in size and currently in use by our business operations. Performing a backup, restore, and reconfiguration of the master-slave setup may not be a practical solution. Is it possible to switch the roles of the master and slave, making the current new master the primary node? I also have another slave that is based on the current master. This way, I can maintain consistent GTID replication. Is this approach feasible?

Yes sure the product was design for this. You need to install a routing solution to  the master we support proxysql , haproxy or custom failover script that would enable any network root to be changed like VIP or router config. Than switchover do the work of performing the change so that you get a consistent state of the cluster   in all nodes with minimum impact

**Comment by svaroqui** [comment]
For multi terrabytes and failover ( crash of the leader) , a rejoin script can be created to restore a snapshot of the ex leader this would  put it back in time so that it could rejoin the cluster, i tend to like ZFS for that

**Comment by svaroqui** [comment]
From what i understand you did the job of restore the topology manually and not with replication-manager so from your screen paste we can see that the new master was still having replication , that need to be removed with reset slave all or something similaras this is may be the mariadb syntax and the read only was still on on the new master , in this state i'm not surprise about replication-manager status

**Comment by svaroqui** [comment]
When experimenting such issues there is an open bug when using monitoring-save-config=true if it's the case the best is to remove all  json files in the /var/lib/replication-manager/<cluster> directory after stop and before a start of the service
