### ISSUE TITLE
When a slave failed, repman can cause writer_hostgroup_id to be lost if bootstrap server off and wrong initial proxysql setup

### ISSUE THREAD

**Issue by peterpan104** [signal18/replication-manager#616]
I have a cluster configuration as follows:
```
## mysql_servers status of proxysql
## hostgroup_id		hostname	status 		weight
10      172.24.43.182   ONLINE (Master)    100
11      172.24.44.182   ONLINE (Slave)       100

## config.toml or repman
proxy-servers-read-on-master = true
proxy-servers-read-on-master-no-slave = true
```

When I stop the slave, I found that repman executed the following SQL statement on ProxySQL, causing my writer hostgroup_id to be lost.
```
## when slave crash
DELETE FROM mysql_servers WHERE hostgroup_id='10'  AND hostgroup_id in ('11','10');

REPLACE INTO mysql_servers (hostgroup_id, hostname, port, gtid_port, status, weight, compression, max_connections, max_replication_lag, use_ssl, max_latency_ms) SELECT '10', hostname, port, gtid_port, status, weight, compression, max_connections, max_replication_lag, use_ssl, max_latency_ms FROM mysql_servers WHERE  hostgroup_id = '11' AND hostname = '172.24.43.182' AND port = '3306';

LOAD MYSQL SERVERS TO RUNTIME;

## I call openstate_script set slave maintenance
UPDATE mysql_servers SET status='OFFLINE_SOFT' WHERE hostname='172.24.44.182' AND port='3306' AND hostgroup_id in ('11','10');

LOAD MYSQL SERVERS TO RUNTIME;


## mysql_servers status of proxysql
## hostgroup_id		hostname	status 		weight
11      172.24.44.182   OFFLINE_SOFT (Slave)     100

```

It seems to use the same functions as the failover :
```
func (psql *ProxySQL) CopyReaderToWriter(host string, port string) error {
	sql := fmt.Sprintf("REPLACE INTO mysql_servers (hostgroup_id, hostname, port, gtid_port, status, weight, compression, max_connections, max_replication_lag, use_ssl, max_latency_ms) SELECT '%s', hostname, port, gtid_port, status, weight, compression, max_connections, max_replication_lag, use_ssl, max_latency_ms FROM mysql_servers WHERE  hostgroup_id = '%s' AND hostname = '%s' AND port = '%s'", psql.WriterHG, psql.ReaderHG, host, port)
	_, err := psql.Connection.Exec(sql)
	return err
}

```

When a slave error occurs, it only needs to write the master to the reader hostgroup_id, but repman deletes the writer hostgroup_id. 
Can this be fixed?

**Comment by caffeinated92** [comment]
Are you sure you're stopping the slave?

**Comment by svaroqui** [comment]
Hi Can you give use a precise description of what stop slave means for you ? stop mysql process , stop sql thread stop io thread stop both , slave is late ? Also it looks like maintenance has something to do with that issue. Can you describe the exact procedure to trigger the issue you are reporting ?  Just keep in mind that  there is 2 path for maintenance. One is a master can never stay in maintenance as it transite to a replicate before cutting traffic to it . The goal of the product is to enable write service continuity . The other path that would be maintenance of the master to stop cluster traffic as never been a feature for us . Should we implement it ? may be if there is a demand for it ?

**Comment by peterpan104** [comment]
HI @svaroqui 
Thanks for your reply.

I simulated the situation where a slave crash by executing "stop slave" on the slave. In fact, whether executing "stop slave", "stop mariadb", or "set maintenance mode" on the slave, the situation would be the same.

I can't avoid the possibility of a slave crashing, so I performed this test and discovered the issue.

The reason why the previous test didn't reveal this problem was because my mysql_servers was configured as follows:
```
## mysql_servers status of proxysql
## hostgroup_id		hostname	status 		weight
10      172.24.43.182   ONLINE (Master)		100
10      172.24.43.182   ONLINE (Master)		1
11      172.24.44.182   ONLINE (Slave)		100

```
Therefore, even if the slave crashed, writes can still continue.

But I hope that when the slave exists, the master will never have any reads, So what I can try is to delete the master from "hostgroup_id=11", or set the weight of "hostgroup_id=11" to 0, when the slave crash, use openstate_script to make the master readable. Currently, when the slave crash or goes into maintenance mode, repman takes the CopyReaderToWriter action, which will cause a temporary write interruption.

```
## if delete the master from "hostgroup_id=11",when the slave crash ,mysql_servers as follows:

## mysql_servers status of proxysql
## hostgroup_id		hostname	status 		weight
11      172.24.44.182   OFFLINE_SOFT (Slave)


---
## if set master the weight of "hostgroup_id=11" to 0,when the slave crash ,mysql_servers as follows:

## mysql_servers status of proxysql
## hostgroup_id		hostname	status 		weight
10      172.24.43.182   ONLINE  0
11      172.24.43.182   ONLINE  0
11      172.24.44.182   OFFLINE_SOFT (Slave)

```

Do you have any thoughts or suggestions for this situation?

**Comment by caffeinated92** [comment]
hi @peterpan104 ,

why do you set `proxy-servers-read-on-master = true` if you dont want master to read?
If you don't want master to be reader hostgroup, then you can set it to false.
`proxy-servers-read-on-master-no-slave = true` will be sufficient if no slave exists

**Comment by caffeinated92** [comment]
`proxy-servers-read-on-master = true`
Means master will be added to reader HG in proxySQL. To have only master in writer HG set it to false

`proxy-servers-read-on-master-no-slave = true`
Add  leader in reader group if no slave found

However you need to set proxysql bootstrap to true in order to check
`proxysql-bootstrap = true` will make replication-manager monitor the proxysql and doing SAVE MYSQL SERVERS TO DISK
`proxysql-bootstrap = false` will prevent replication-manager from doing SAVE MYSQL SERVERS TO DISK

**Comment by peterpan104** [comment]
hi @caffeinated92 
Maybe I misunderstood the usage of the parameters, I will try it, maybe this will solve my problem, thanks for your reply.

**Comment by caffeinated92** [comment]
Hi @peterpan104,

No problem. Your questions will help us in making documentation too.

**Comment by peterpan104** [comment]
Hi @caffeinated92 

After adjusting the parameters and testing, I found that when I stop the slave, it triggers the openstate_script to set the slave to maintenance mode (OPENED ERR00047),after I recover the slave, I manually remove the maintenance mode (RESOLV ERR00047). 

However, when the slave crashes (stop mariadb), it also triggers the openstate_script to set the slave to maintenance mode (OPENED ERR00047), but it eventually RESOLV ERR00047, which will cause my ProxySQL to behave strangely. 
At this point, should ERR00047 be disabled? Because at this time, the slave is in a stopped state, and I didn't encounter this situation in my previous tests.

```
## mysql_servers
## hostgroup_id	   hostname	   status    weight    max_replication_lag

## when stop slave
10      172.24.43.182   ONLINE  100     99999
11      172.24.43.182   ONLINE  1       30
11      172.24.44.182   OFFLINE_SOFT    100     99999


## when stop mariadb on slave
10      172.24.43.182   ONLINE  100     99999
11      172.24.43.182   ONLINE  1       30
11      172.24.44.182   ONLINE  100     99999
```

when stop mariadb on slave,repman logs as follows:
```
time="2024-05-29 14:52:03" level=info msg="Server 172.24.44.182:3306 state transition from Slave changed to: S
uspect" cluster=l-ptest-lab
time="2024-05-29 14:52:03" level=info msg="Set state called from /var/jenkins_home/workspace/go/src/github.com
/signal18/replication-manager/cluster/srv.go#425\n" cluster=l-ptest-lab
time="2024-05-29 14:52:03" level=info msg="Server 172.24.44.182:3306 previous state set to: Suspect" cluster=l
-ptest-lab
time="2024-05-29 14:52:03" level=warning msg="Skip slave in election 172.24.44.182:3306 does not ping or has n
o binlogs" channel=StdOut cluster=l-ptest-lab code=ERR00040 status=OPENED type=state
time="2024-05-29 14:52:03" level=warning msg="No candidates found in slaves list" channel=StdOut cluster=l-pte
st-lab code=ERR00032 status=OPENED type=state
time="2024-05-29 14:52:03" level=info msg="Calling open state script" cluster=l-ptest-lab
time="2024-05-29 14:52:03" level=info msg="Open state script complete: " cluster=l-ptest-lab
time="2024-05-29 14:52:03" level=info msg="Calling open state script" cluster=l-ptest-lab
time="2024-05-29 14:52:06" level=info msg="Open state script complete: " cluster=l-ptest-lab
time="2024-05-29 14:52:08" level=warning msg="Skip slave in election 172.24.44.182:3306 - Maintenance mode" ch
annel=StdOut cluster=l-ptest-lab code=ERR00047 status=OPENED type=state
time="2024-05-29 14:52:08" level=warning msg="No replica found for routing reads" channel=StdOut cluster=l-pte
st-lab code=ERR00085 status=OPENED type=state
time="2024-05-29 14:52:08" level=info msg="Calling open state script" cluster=l-ptest-lab
time="2024-05-29 14:52:08" level=info msg="Open state script complete: " cluster=l-ptest-lab
time="2024-05-29 14:52:08" level=info msg="Calling open state script" cluster=l-ptest-lab
time="2024-05-29 14:52:09" level=info msg="Open state script complete: " cluster=l-ptest-lab
time="2024-05-29 14:52:15" level=info msg="Declaring replica 172.24.44.182:3306 as failed" cluster=l-ptest-lab
time="2024-05-29 14:52:15" level=info msg="Server 172.24.44.182:3306 state transition from Suspect changed to: Failed" cluster=l-ptest-lab
time="2024-05-29 14:52:15" level=info msg="Set state called from /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/srv.go#412\n" cluster=l-ptest-lab
time="2024-05-29 14:52:15" level=error msg="Server 172.24.44.182:3306 state changed from Suspect to Failed" channel=StdOut cluster=l-ptest-lab type=alert
time="2024-05-29 14:52:15" level=info msg="Server 172.24.44.182:3306 previous state set to: Failed" cluster=l-ptest-lab
time="2024-05-29 14:52:15" level=warning msg="Could not find a slave in topology" channel=StdOut cluster=l-ptest-lab code=ERR00010 status=OPENED type=state
time="2024-05-29 14:52:15" level=info msg="Calling open state script" cluster=l-ptest-lab
time="2024-05-29 14:52:16" level=info msg="Open state script complete: " cluster=l-ptest-lab
time="2024-05-29 14:52:18" level=info msg="Calling close state script" cluster=l-ptest-lab
time="2024-05-29 14:52:19" level=info msg="Close state script complete :" cluster=l-ptest-lab
time="2024-05-29 14:52:19" level=info msg="Calling close state script" cluster=l-ptest-lab
time="2024-05-29 14:52:20" level=info msg="Close state script complete :" cluster=l-ptest-lab
time="2024-05-29 14:52:20" level=info msg="Calling close state script" cluster=l-ptest-lab
time="2024-05-29 14:52:20" level=info msg="Close state script complete :" cluster=l-ptest-lab
time="2024-05-29 14:52:20" level=info msg="Calling close state script" cluster=l-ptest-lab
time="2024-05-29 14:52:21" level=info msg="Close state script complete :" cluster=l-ptest-lab
time="2024-05-29 14:52:21" level=info msg="Calling close state script" cluster=l-ptest-lab
time="2024-05-29 14:52:22" level=info msg="Close state script complete :" cluster=l-ptest-lab
time="2024-05-29 14:52:22" level=warning msg="No compression of binlog on slave 172.24.44.182:3306" channel=StdOut cluster=l-ptest-lab code=WARN0056 status=RESOLV type=state
time="2024-05-29 14:52:22" level=warning msg="No GTID strict mode on slave 172.24.44.182:3306" channel=StdOut cluster=l-ptest-lab code=WARN0058 status=RESOLV type=state
time="2024-05-29 14:52:22" level=warning msg="No semisync settings on slave 172.24.44.182:3306" channel=StdOut cluster=l-ptest-lab code=WARN0048 status=RESOLV type=state
time="2024-05-29 14:52:22" level=warning msg="Skip slave in election 172.24.44.182:3306 - Maintenance mode" channel=StdOut cluster=l-ptest-lab code=ERR00047 status=RESOLV type=state
time="2024-05-29 14:52:22" level=warning msg="Skip slave in election 172.24.44.182:3306 does not ping or has no binlogs" channel=StdOut cluster=l-ptest-lab code=ERR00040 status=RESOLV type=state
time="2024-05-29 14:52:35" level=info msg="Calling close state script" cluster=l-ptest-lab
time="2024-05-29 14:52:35" level=info msg="Close state script complete :" cluster=l-ptest-lab
time="2024-05-29 14:52:35" level=warning msg="Variable diff:\n [\n \t{\n \t\t\"variableName\": \"EVENT_SCHEDULER\",\n \t\t\"diffValues\": [\n \t\t\t{\n \t\t\t\t\"serverName\": \"172.24.43.182:3306\",\n \t\t\t\t\"variableValue\": \"ON\"\n \t\t\t},\n \t\t\t{\n \t\t\t\t\"serverName\": \"172.24.44.182:3306\",\n \t\t\t\t\"variableValue\": \"OFF\"\n \t\t\t}\n \t\t]\n \t}\n ]" channel=StdOut cluster=l-ptest-lab code=WARN0084 status=RESOLV type=state
```

![image](https://github.com/signal18/replication-manager/assets/140467680/9a99434e-d539-44ba-b9e6-dfc9bbea8eb8)

**Comment by caffeinated92** [comment]
Hi @peterpan104,

As per our open state script sample:
```
echo "Open state script args"
echo "Script:$0, Cluster:$1, Server:$2, Code:$3"   

```
In your script, you should check if the code is right. 

Add checking within your openstate script.
```
if "$3" == "ERRxxxxxx" 
  do things here
fi
````

What you wanted maybe `alert-script`:
```
AlertScript: $0, Cluster: $1, Host: $2, PrevState: $3, State: $4
```
Add checking within your alert script.
```
if  "$3" == "PREV" && "$4" == "STATE"
  do things here
fi
````

**Comment by peterpan104** [comment]
Hi @caffeinated92 
My process is that when the slave crashes, it will OPENED ERR00032.
My openstate_script is as follows:

```
if "$3" = "ERR00032" 
  slave set maintenance mode (OPENED ERR00047)
fi
```

When the slave is recovered, maintenance mode must be manually released. Only then will the ProxySQL status be set to online.

But from the above, we can see that the slave has not yet recovered, and the web status is also "is mnt", but the ProxySQL status has already been set to online.

**Comment by caffeinated92** [comment]
can you show both mysql_servers and runtime_mysql_servers?

**Comment by caffeinated92** [comment]
> Hi @caffeinated92 My process is that when the slave crashes, it will OPENED ERR00032. My openstate_script is as follows:
> 
> ```
> if "$3" = "ERR00032" 
>   slave set maintenance mode (OPENED ERR00047)
> fi
> ```
> 
> When the slave is recovered, maintenance mode must be manually released. Only then will the ProxySQL status be set to online.
> 
> But from the above, we can see that the slave has not yet recovered, and the web status is also "is mnt", but the ProxySQL status has already been set to online.

Can you explain further on this SET TO MAINTENANCE while failed?

**Comment by peterpan104** [comment]
Hi @caffeinated92 

Initial settings
```
## hostgroup_id	   hostname	   status    weight    max_replication_lag

## mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.44.182   ONLINE  100     99999

## runtime_mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.44.182   ONLINE  100     99999

```

---

when stop slave
```
## hostgroup_id	   hostname	   status    weight    max_replication_lag

## mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.43.182   ONLINE  1       30
11      172.24.44.182   OFFLINE_SOFT    100     99999

## runtime_mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.43.182   ONLINE  1       30
11      172.24.44.182   OFFLINE_SOFT    100     99999

```

when start slave 
```
## hostgroup_id	   hostname	   status    weight    max_replication_lag

## mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.43.182   ONLINE  1       30
11      172.24.44.182   OFFLINE_SOFT    100     99999

## runtime_mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.43.182   ONLINE  1       30
11      172.24.44.182   OFFLINE_SOFT    100     99999

```

slave manually released maintenance mode
```
## hostgroup_id	   hostname	   status    weight    max_replication_lag

## mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.44.182   ONLINE  100     99999

## runtime_mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.44.182   ONLINE  100     99999

and I will get error : Failover ProxySQL could not set server 172.24.43.182:3306 Master (Error 1045: ProxySQL Admin Error: UNIQUE constraint failed: mysql_servers.hostgroup_id, mysql_servers.hostname, mysql_servers.port)

```
---

when stop mariadb on slave
```
## hostgroup_id	   hostname	   status    weight    max_replication_lag

## mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.43.182   ONLINE  1       30
11      172.24.44.182   ONLINE  100     99999

## runtime_mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.43.182   ONLINE  1       30
11      172.24.44.182   SHUNNED/ONLINE 100     99999

runtime_mysql_servers status will switch back and forth between SHUNNED and ONLINE
```

when start mariadb on slave 
```
## hostgroup_id	   hostname	   status    weight    max_replication_lag

## mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.43.182   ONLINE  1       30
11      172.24.44.182   ONLINE  100     99999

## runtime_mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.43.182   ONLINE  1       30
11      172.24.44.182   SHUNNED 100     99999
```

when slave manually released maintenance mode
```
## hostgroup_id	   hostname	   status    weight    max_replication_lag

## mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.44.182   ONLINE  100     99999

## runtime_mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.44.182   ONLINE  100     99999

and I get error :Failover ProxySQL could not set server 172.24.43.182:3306 Master (Error 1045: ProxySQL Admin Error: UNIQUE constraint failed: mysql_servers.hostgroup_id, mysql_servers.hostname, mysql_servers.port)

```

---

The reason why slave is set to MAINTENANCE is because I want to ensure that after the slave is restored, the data will be fine and there will be no delay before providing services.

**Comment by caffeinated92** [comment]
Please set `proxy-servers-read-on-master = false` and try again

Check within settings -> proxies and find the switch below and make sure it turned off
![image](https://github.com/signal18/replication-manager/assets/155546371/2636dfa8-bf7d-4435-8c5c-07e50f97ce46)

**Comment by caffeinated92** [comment]
> Hi @caffeinated92
> 
> Initial settings
> 
> ```
> ## hostgroup_id	   hostname	   status    weight    max_replication_lag
> 
> ## mysql_servers
> 10      172.24.43.182   ONLINE  100     99999
> 11      172.24.44.182   ONLINE  100     99999
> 
> ## runtime_mysql_servers
> 10      172.24.43.182   ONLINE  100     99999
> 11      172.24.44.182   ONLINE  100     99999
> ```
> 
> when stop slave
> 
> ```
> ## hostgroup_id	   hostname	   status    weight    max_replication_lag
> 
> ## mysql_servers
> 10      172.24.43.182   ONLINE  100     99999
> 11      172.24.43.182   ONLINE  1       30
> 11      172.24.44.182   OFFLINE_SOFT    100     99999
> 
> ## runtime_mysql_servers
> 10      172.24.43.182   ONLINE  100     99999
> 11      172.24.43.182   ONLINE  1       30
> 11      172.24.44.182   OFFLINE_SOFT    100     99999
> ```
> 
> when start slave
> 
> ```
> ## hostgroup_id	   hostname	   status    weight    max_replication_lag
> 
> ## mysql_servers
> 10      172.24.43.182   ONLINE  100     99999
> 11      172.24.43.182   ONLINE  1       30
> 11      172.24.44.182   OFFLINE_SOFT    100     99999
> 
> ## runtime_mysql_servers
> 10      172.24.43.182   ONLINE  100     99999
> 11      172.24.43.182   ONLINE  1       30
> 11      172.24.44.182   OFFLINE_SOFT    100     99999
> ```
> 
> slave manually released maintenance mode
> 
> ```
> ## hostgroup_id	   hostname	   status    weight    max_replication_lag
> 
> ## mysql_servers
> 10      172.24.43.182   ONLINE  100     99999
> 11      172.24.44.182   ONLINE  100     99999
> 
> ## runtime_mysql_servers
> 10      172.24.43.182   ONLINE  100     99999
> 11      172.24.44.182   ONLINE  100     99999
> 
> and I will get error : Failover ProxySQL could not set server 172.24.43.182:3306 Master (Error 1045: ProxySQL Admin Error: UNIQUE constraint failed: mysql_servers.hostgroup_id, mysql_servers.hostname, mysql_servers.port)
> ```
> 
> when stop mariadb on slave
> 
> ```
> ## hostgroup_id	   hostname	   status    weight    max_replication_lag
> 
> ## mysql_servers
> 10      172.24.43.182   ONLINE  100     99999
> 11      172.24.43.182   ONLINE  1       30
> 11      172.24.44.182   ONLINE  100     99999
> 
> ## runtime_mysql_servers
> 10      172.24.43.182   ONLINE  100     99999
> 11      172.24.43.182   ONLINE  1       30
> 11      172.24.44.182   SHUNNED/ONLINE 100     99999
> 
> runtime_mysql_servers status will switch back and forth between SHUNNED and ONLINE
> ```
> 
> when start mariadb on slave
> 
> ```
> ## hostgroup_id	   hostname	   status    weight    max_replication_lag
> 
> ## mysql_servers
> 10      172.24.43.182   ONLINE  100     99999
> 11      172.24.43.182   ONLINE  1       30
> 11      172.24.44.182   ONLINE  100     99999
> 
> ## runtime_mysql_servers
> 10      172.24.43.182   ONLINE  100     99999
> 11      172.24.43.182   ONLINE  1       30
> 11      172.24.44.182   SHUNNED 100     99999
> ```
> 
> when slave manually released maintenance mode
> 
> ```
> ## hostgroup_id	   hostname	   status    weight    max_replication_lag
> 
> ## mysql_servers
> 10      172.24.43.182   ONLINE  100     99999
> 11      172.24.44.182   ONLINE  100     99999
> 
> ## runtime_mysql_servers
> 10      172.24.43.182   ONLINE  100     99999
> 11      172.24.44.182   ONLINE  100     99999
> 
> and I get error :Failover ProxySQL could not set server 172.24.43.182:3306 Master (Error 1045: ProxySQL Admin Error: UNIQUE constraint failed: mysql_servers.hostgroup_id, mysql_servers.hostname, mysql_servers.port)
> ```
> 
> The reason why slave is set to MAINTENANCE is because I want to ensure that after the slave is restored, the data will be fine and there will be no delay before providing services.

I can't reproduce your bug, it worked normally here.

I saw nothing strange within your proxysql servers table except when the slave start after failed, how did you set maintenance on failed server? by clicking maintenance mode?

**Comment by peterpan104** [comment]
I've made sure it's turned off, and the test results above were tested with this setting
![image](https://github.com/signal18/replication-manager/assets/140467680/517d6b7e-48a6-4e04-8bbc-4a6dbade4a2d)

I use openstate_script set slave to maintenance mode

```
## openstate_script
if "$3" = "ERR00032" 
  slave_status=$(replication-manager-cli topology --cluster="$CLUSTER" |egrep $S_IP |awk '{print $4}')
  if $slave_status != "Maintenance" 
  	S_ID=$(replication-manager-cli topology --cluster="$CLUSTER" |grep $S_IP |awk '{print $1}')
    replication-manager-cli server --cluster="$CLUSTER" --id=$S_ID --maintenance 
fi
```

**Comment by caffeinated92** [comment]
> replication-manager-cli server --cluster="$CLUSTER" --id=$S_ID --maintenance

Ah, I see.. I will need to check within the cli and see if I can find something from this.

**Comment by peterpan104** [comment]
Thanks, please let me know if you need more information.

**Comment by caffeinated92** [comment]
can you try changing the script from openstate to alert-script?

**Comment by peterpan104** [comment]
I used alert-script and the result is the same. What I can confirm is that repman has set the slave to maintenance first, but I can't see from the repman log that it has opened ERR00047 and closed ERR00047.

![image](https://github.com/signal18/replication-manager/assets/140467680/787e7ef1-87c7-477c-9439-38539a77c3a2)

when stop mariadb
```
## hostgroup_id    hostname    status    weight    max_replication_lag

## mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.43.182   ONLINE  1       30
11      172.24.44.182   ONLINE  100     99999

## runtime_mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.43.182   ONLINE  1       30
11      172.24.44.182   ONLINE/SHUNNED 100     99999
```

when start mariadb
```
## hostgroup_id    hostname    status    weight    max_replication_lag

## mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.43.182   ONLINE  1       30
11      172.24.44.182   ONLINE  100     99999

## runtime_mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.43.182   ONLINE  1       30
11      172.24.44.182   SHUNNED 100     99999
```

slave manually released maintenance mode
```
## hostgroup_id    hostname    status    weight    max_replication_lag

## mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.44.182   ONLINE  100     99999

## runtime_mysql_servers
10      172.24.43.182   ONLINE  100     99999
11      172.24.44.182   ONLINE  100     99999
```

But I didn’t see the proxysql error.

**Comment by caffeinated92** [comment]
What are you expecting of the output? As per logic, it's correct that failed slave retain the failed status, and is in maintenance. What is the problem?

**Comment by peterpan104** [comment]
Hi @caffeinated92 
I have added some information, slave status is maintenance,but proxysql status is online.

**Comment by caffeinated92** [comment]
I already identified your problem. The problem is you're using cli for getting the maintenance status. while the failed is stronger than maintenance status. I will add one column for Maintenance status at the last column

```
./replication-manager-cli topology --cluster=fr
####
                 Id            Host   Port          Status   Failures   Using GTID         Current GTID           Slave GTID             Replication Health  Delay  RO MAINT
db8333316815677374852      172.17.0.2   3306          Master          0           No                0-1-5                                                          0 OFF     N
db3425150372194902490      172.17.0.3   3306          Failed       2159           No                0-1-5                0-1-5                                     0  ON     Y
db2995596438658588357      172.17.0.4   3306          Failed       2255           No                                                                               0         N
```

The MAINT column is new and can be used for checking maintenance status, resulting in Y or N
