### ISSUE TITLE
Topology requires rpluser?

### ISSUE THREAD

**Issue by willfong** [signal18/replication-manager#63]
Why does the topology command require the replication user since it already has the root user?

I consider this a bug/issue because it would be best to require the least amount of commands to run. If I change the password for the replication user, I would have one less command to update.

Thanks,
-will

**Comment by tanji** [comment]
That's due to changes we made recently. Thanks for spotting this.

**Comment by tanji** [comment]
Actually, that matters no more because your replication user should now be in a configuration file, so I'm closing the issue.
