### ISSUE TITLE
Concurrent login lead to concurrent map writes as no protected by mutex

### ISSUE THREAD

**Issue by PeterJanRoes** [signal18/replication-manager#634]
When running _Replication Manager_ in a Kubernetes pod, the container crashes frequently. The following is logged to `stdout`:

```
fatal error: concurrent map writes

goroutine 2327265 [running]:
github.com/signal18/replication-manager/server.(*ReplicationManager).loginHandler(0xc00023b900, {0x2eb9ab0?, 0xc004c50380}, 0xc000195400)
	/go/src/github.com/signal18/replication-manager/server/api.go:323 +0x4e5
net/http.HandlerFunc.ServeHTTP(0xc000194f00?, {0x2eb9ab0?, 0xc004c50380?}, 0x800?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0027d0000, {0x2eb9ab0, 0xc004c50380}, 0xc000194900)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0x2eab288?}, {0x2eb9ab0, 0xc004c50380}, 0xc000194900)
	/usr/local/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc0012245a0, {0x2ebb070, 0xc0007e5a70})
	/usr/local/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3089 +0x5ed

goroutine 1 [sleep]:
time.Sleep(0x77359400)
	/usr/local/go/src/runtime/time.go:195 +0x135
github.com/signal18/replication-manager/server.(*ReplicationManager).Run(0xc00023b900)
	/go/src/github.com/signal18/replication-manager/server/server.go:1687 +0x22b3
github.com/signal18/replication-manager/server.glob..func6(0x3fe0080?, {0x2416cca?, 0x0?, 0x0?})
	/go/src/github.com/signal18/replication-manager/server/server_mo

nitor.go:85 +0x127
github.com/spf13/cobra.(*Command).execute(0x3fe0080, {0x4037f18, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x3fdf8a0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x37d
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
github.com/signal18/replication-manager/server.Execute()
	/go/src/github.com/signal18/replication-manager/server/server_cmd.go:103 +0x25
main.main()
	/go/src/github.com/signal18/replication-manager/main_server.go:24 +0x19

...
```
For the full error message in the log see [replication-manager.log](https://github.com/user-attachments/files/15765953/replication-manager.log).

When _Replication Manager_ is automatically restarted after the crash, it seems to need to rediscover the state of the clusters and generates warnings which disappear quickly. Because the container often crashes multiple times a day we receive quite a few false alarms on clusters being in the wrong state. Is this a bug?

**Comment by svaroqui** [comment]
It is a bug but we are also using it in docker for 4 years without such an issue  (we always use the pro release that is based on debian while  osc is may be alpine ). When looking at the trace it looks like the issue is trigger on api authentication that  increase the number of authentification request per user 
 ```
auth_try.Try += 1
repman.UserAuthTry[user.Username] = auth_try 
```

Do you have something constantly pulling the api ?

**Comment by svaroqui** [comment]
We will try to add a login mutex or sync.map to protect against concurrent login that may write to same struct

**Comment by PeterJanRoes** [comment]
> Do you have something constantly pulling the api ?

Yes, we use Zabbix to pull information from the API. I believe it is not possible to generate one long-lived bearer token for the replication-manager API and reuse that in each call. Or is that possible? I think it would be great to be able to do that. Now we just retrieve a fresh token from the `login` endpoint every time we need to do a request.

**Comment by svaroqui** [comment]
> > Do you have something constantly pulling the api ?
> 
> Yes, we use Zabbix to pull information from the API. I believe it is not possible to generate one long-lived bearer token for the replication-manager API and reuse that in each call. Or is that possible? I think it would be great to be able to do that. Now we just retrieve a fresh token from the `login` endpoint every time we need to do a request.

Ok that explain it all we will fixe this in next release for sure for the  token as constant timeout of 	claims["exp"] = time.Now().Add(time.Hour * 48).Unix()

**Comment by caffeinated92** [comment]
As per my experiences, as long as you don't restart the services, you can
use the same Bearer.

**Comment by svaroqui** [comment]
> As per my experiences, as long as you don't restart the services, you can use the same Bearer.

Please see #635

**Comment by PeterJanRoes** [comment]
> Ok that explain it all we will fixe this in next release for sure for the token as constant timeout of claims["exp"] = time.Now().Add(time.Hour * 48).Unix()

Great, thank you!

> As per my experiences, as long as you don't restart the services, you can
use the same Bearer.

Thank you. We do restart the services as we maintain `config.toml` in version control and mount it as a `ConfigMap` into the container. But it is good to know the expiration time of the token so I can try to somehow reuse tokens and reduce the `login` calls.

**Comment by PeterJanRoes** [comment]
> > As per my experiences, as long as you don't restart the services, you can use the same Bearer.
> 
> Please see #635

Great!

**Comment by svaroqui** [comment]
Peter do you know we can partly control K8S service using the pro release , it just need that you are deploying your service on a namespace that is the same name of the cluster name. Still we are lacking Config and Secret Map for configuration of services. Meaning we can stop start service made by you . But that this is not super ready for provisioning  unlike OpenSVC.

**Comment by svaroqui** [comment]
```
--kube-config string                                   path to ks8 config file
--prov-orchestrator string                          onpremise|opensvc|kube|slapos|local (default "opensvc")
--prov-net-cni-cluster
     
```
in such setup the db and proxy list in the config are just mon_service in mon-service.mon-namespace.svc.cluster.local.

so that  mon-service.mon-namespace.svc.cluster.local translate <db_name>.<cluster_name>.svc.<prov_net_cni_cluster>.local
