### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by krissfr** [signal18/replication-manager#66]
Hello,

I know this is a MariaDB tool, but can we use it we Oracle MySQL replication or Percona MySQL replication ?

could the interactive option be put in the config.toml ?

will you do a service for SystemD to start the replication-manager monitor ?

It's a great tool, merci beaucoup Guillaume et Stéphane ! :)

**Comment by tanji** [comment]
Hello @krissfr,

Thanks for the good words!

yes, interactive has been added to the configuration file in a recent commit. You should build from source if you want to have this feature, or I can drop you a RPM or DEB.

We will have a systemd service file shortly, I think Stéphane already wrote it.

Regarding Oracle GTID support, I think there are comparable tools that might fill the void but I am not sure if they have that much features. That's certainly something we can do in the future, however MariaDB is our first focus :)

**Comment by krissfr** [comment]
Thank you for your quick answer :)

don't bother you to build a new package, i can wait the next beta-release. Do you have an expected date for the 0.7 stable release ? Maybe a gift for my birthday (last week of August) ^^

**Comment by tanji** [comment]
Included in 1.1.0-preview2, sorry for being late for the birthday...
