### ISSUE TITLE
MRM monitor RESTful API

### ISSUE THREAD

**Issue by krissfr** [signal18/replication-manager#67]
Hello,

do you will implement a RESTful API to get server status or arbitrator status with JSON output ?

thanks,

Regards,

Krissfr

**Comment by krissfr** [comment]
Sorry, i'm looking in the code a found that's already exist !!

Thanks again for this wonderfull tool ! :)

**Comment by tanji** [comment]
No problem, httpserver.go implements this in some capacity :) Happy to help if you need more answers.
