### ISSUE TITLE
Force a failover

### ISSUE THREAD

**Issue by wrestle1** [signal18/replication-manager#68]
It would be nice if there was a command line option to force a failover.  In this situation there could be data loss, but in the case of a 2 system configuration when the master dies, it is the only alternative.  It can be done manually (set global gtid_slave_pos = "") and then start the slave, but in an fully automated environment, data loss may be acceptable to avoid unavailability.  This is a requirement in our environment.

**Comment by svaroqui** [comment]
Hello wrestle1, 

Thanks for trying out replication-manager!   

That's exactly the case , may be something should be fix with the documentation, that you   miss that point   , there are few cases where you can't failover they are rare
- you have no slaves at all 
- you have set a replication delay  <>0 
- you have already failover x times 

In interactive mode , replication is asking you to confirm failover  
in onleave (interactive=0) mode the failover is trigger silently under the predefined conditions

Hope it helps
/stephane

**Comment by wrestle1** [comment]
I tried interactive=0 and it didn't work.  I probably am not describing my scenario properly.  

Monitor believes a replication topology exists.  When I try a failover from the monitor is says no suitable candidates found.  If I do a show slave status on the slave, it show that there is an error condition (error 1236).  My hope was to be able to force the switchover/failover.  

Interactively I do not get a prompt and --interactive=0 doesn't work.

See screen shots attached.

![screen shot 2016-07-27 at 1 40 08 pm](https://cloud.githubusercontent.com/assets/20479683/17187691/ef5222ec-53ff-11e6-8071-cb82119ebcc0.png)
![screen shot 2016-07-27 at 1 40 29 pm](https://cloud.githubusercontent.com/assets/20479683/17187693/ef5736d8-53ff-11e6-8aef-2c8744474fc0.png)
![screen shot 2016-07-27 at 1 41 39 pm](https://cloud.githubusercontent.com/assets/20479683/17187694/ef60d774-53ff-11e6-856e-5d65def89eee.png)

**Comment by svaroqui** [comment]
Ok i see and will fixed it

**Comment by wrestle1** [comment]
Awesome.  Thanks for the quick response.

**Comment by 113rm0** [comment]
@svaroqui Is this issue fixed?

**Comment by tanji** [comment]
@svaroqui is this issue fixed?

**Comment by svaroqui** [comment]
fixed by turning off  rplchecks flag
