### ISSUE TITLE
Per database server state change script ?

### ISSUE THREAD

**Issue by peterpan104** [signal18/replication-manager#691]
My architecture is 1M2S,
When both slaves set to maintenance,the log shows that only one ERR00047 is enabled.

![image](https://github.com/signal18/replication-manager/assets/140467680/480edade-1cda-4ceb-b2b0-4e05274333d5)

When I set 172.22.44.182 to online, it does not close ERR00047,
therefore, I can't use ERR00047 to trigger closestate_script.

![image](https://github.com/signal18/replication-manager/assets/140467680/f452bbd9-faa7-4a79-a098-cb61ef6bf20d)

When I set 172.22.47.183 to online, it did close ERR00047,

![image](https://github.com/signal18/replication-manager/assets/140467680/33c6e801-44cd-4367-93f7-86ab0f4dd2ab)

Do you think this issue can be fixed?

**Comment by svaroqui** [comment]
It's not easy, the state machine track cluster state not server state , it would required an other machine for each server

**Comment by svaroqui** [comment]
```
./replication-manager-pro --config=etc/opensvc/cluster-api/cluster-demo/stephane.toml --db-servers-state-change-script=./share/scripts/databasechangestate.sh monitor`
```

```
INFO[2024-07-07T15:42:35+02:00] Database change state script Database state change script args
Script:./share/scripts/databasechangestate.sh, Cluster:bench, Host:db1.bench.svc.cloud18, Port:3306, State:Master, OldState:Suspect
```

**Comment by peterpan104** [comment]
hi @svaroqui 

How do I trigger the script?
I updated repman to the latest version and I set the parameters and tried change the server status, 
but it doesn't seem to work.

```
db-servers-state-change-script= "/data/repman/script/test.sh"
```

**Comment by svaroqui** [comment]
we provide a sample script in share with the parameters

**Comment by svaroqui** [comment]
oups sorry i forget to add the script in the release 

```
#!/bin/bash
# This script is given as sample and will be overwrite on upgrade
# db-servers-state-change-script
echo "Database state change script args"
echo "Script:$0, Cluster:$1, Host:$2, Port:$3, State:$4, OldState:$5"   
```

**Comment by peterpan104** [comment]
I'm looking forward to add script in the next release,
thanks for your reply.

**Comment by peterpan104** [comment]
I was successfully triggered the script. After checking the commit, I found that I used the wrong parameter name. 
Thanks again for your help.

![image](https://github.com/signal18/replication-manager/assets/140467680/0a19ad77-2e6e-4168-b5e6-9aec5e14e864)
