### ISSUE TITLE
 Could not find a slave in topology and Failover exception

### ISSUE THREAD

**Issue by dibrother** [signal18/replication-manager#696]
My architecture is 1M1S
<img width="1411" alt="image" src="https://github.com/signal18/replication-manager/assets/95730552/00acd8fd-4c9c-4087-817c-7e70049ec105">

### Q 1:
  There is no data written to the master ，When I stop the master, a failure occurs.
The results are as follows:
Excuse me, is it not supported for 1 master and 1 slave?
If supported, the main instance should still be able to provide service writing and display on the web interface instead of reporting an error:
<img width="1395" alt="image" src="https://github.com/signal18/replication-manager/assets/95730552/3207ccb3-6df3-4454-9ab6-6edfa18111a3">
<img width="1436" alt="image" src="https://github.com/signal18/replication-manager/assets/95730552/a71674fc-7f18-400e-9ca0-5e62e8549d09">

```shell
[root@test11 replication-manager]# replication-manager-cli topology
| Group: cluster1 |  Mode: Manual 
                 Id            Host   Port          Status   Failures   Using GTID         Current GTID           Slave GTID             Replication Health  Delay  RO MAINT
db14945847834543103650      10.10.2.10   3310          Failed         87          Yes 0-17432551081057813428-12947,0-9831016450675646889-1                                                          0 OFF     N
db10612492877609025276      10.10.2.11   3310          Master          0          Yes 0-17432551081057813428-12947,0-9831016450675646889-2                                                          0 OFF     N
```

### Q 2:
If there is data written to the master,then I execute the stop master.
Surprisingly, it would cause the inability to fail over.The reason is that the GTID of the slave is larger than that of the master.
The replication cannot obtain the GTID of the master in a timely manner, which should not affect the failure over. It is normal for the slave to be greater than or equal to the GTID of the master.
<img width="1398" alt="image" src="https://github.com/signal18/replication-manager/assets/95730552/25c730e6-5dcb-4db6-9df3-9d3c52aff0f0">

**Comment by dibrother** [comment]
version :
[root@test11 replication-manager]# replication-manager-osc version
init
Replication Manager v2.3.36 for MariaDB 10.x and MySQL 5.7 Series
Full Version:  v2.3.36
Build Time:  2024-07-05T16:17:49+0000

**Comment by dibrother** [comment]
Cluster Logs:
<img width="1247" alt="image" src="https://github.com/signal18/replication-manager/assets/95730552/977c468b-a5dd-4272-9471-9dba820d5388">

**Comment by caffeinated92** [comment]
have you set the failover-mode to auto?
are you using GTID strict mode?

**Comment by svaroqui** [comment]
Regarding you first question Yes it is supported but 2 nodes cluster is never advice as loosing a node would break the master-slave topology and ending up with a single node and no more slave for HA.  What proxy are you using to enable the traffic on node 2 ? The replication-manager is printing a valid error that there is no more slave 

For the second case you will see from the log that replication-manager notice errant transactions , while this is normal to have node 2 greater than node 1 after a failover this is not expected to have errant transactions . it means that no successfull rejoin took place at some point and that the dataset differ on both nodes

**Comment by svaroqui** [comment]
I would advice MariaDB for binlog cleanup with semisync  so that the node 1 can rejoin without backup reload , i don't think MySQL as such feature

**Comment by svaroqui** [comment]
Still what you image show is strange it does not look like there is an errant transaction in the binlog sequence

**Comment by svaroqui** [comment]
We will try to reproduce and report back

**Comment by svaroqui** [comment]
It'a. regression introduce in :) 
https://github.com/signal18/replication-manager/issues/540

We have been correct the purpose of this function was not to elect a slave that have missing transactions from the last know position of the master 
This fixe was  agressive by checking the opposite

**Comment by caffeinated92** [comment]
@dibrother can you set the log-failed-election to INFO in settings

**Comment by dibrother** [comment]
Thank you for your reply
I tested the first question, he will become an isolated node and continue to provide services

I changed the mode to 1M2S
However, it was found that there was still no fault transfer carried out.
I don't understand why 【level=warning msg="Server as error transaction 10.10.2.11:310"】 appears.Does this make it impossible to perform a failover.

The default configuration used for config.toml and the configuration of cluster1. toml is as follows.
I also tested 2.2.40 and it is working properly
<img width="1392" alt="image" src="https://github.com/signal18/replication-manager/assets/95730552/10f8f37c-2a1c-4f21-95f9-6dc727e6454f">
```shell
[root@test11 install]# cat  /etc/replication-manager/cluster.d/cluster1.toml
[cluster1]
title = "cluster1"
prov-orchestrator = "onpremise"

db-servers-hosts = "10.10.2.10:3310,10.10.2.11:3310,10.10.2.13:3310"
db-servers-prefered-master = "10.10.2.10:3310,10.10.2.11:3310"
db-servers-credential = "super_admin:123456"
db-servers-connect-timeout = 1
replication-credential = "repl:123456"

##############
## TOPOLOGY ##
##############

replication-multi-master = false
replication-multi-tier-slave = false

# backup-restic = true
backup-physical-type = "mariabackup"
backup-logical-type = "mysqldump"

##############
## FAILOVER ##
##############
failover-mode = "automatic"
failover-pre-script = "/etc/replication-manager/script/vip_down.sh"
failover-post-script = "/etc/replication-manager/script/vip_up.sh"

## Slaves will re enter with read-only

failover-readonly-state = true
failover-superreadonly-state = true
#failover-semisync-state = true
failover-event-scheduler = false
failover-event-status = false

failover-falsepositive-ping-counter = 5

failover-limit = 0
failover-time-limit = 0
failover-at-sync = false
failover-max-slave-delay = 30
failover-restart-unsafe = false

################
## SWITCHOVER ##
################

switchover-wait-kill = 5000
switchover-wait-trx = 10
switchover-wait-write-query = 10
switchover-at-equal-gtid = false
switchover-at-sync = false
switchover-max-slave-delay = 30

############
## REJOIN ##
############

autorejoin = true
autorejoin-script = ""
autorejoin-semisync = true
autorejoin-backup-binlog = true
autorejoin-flashback = false
autorejoin-mysqldump = false

####################
## CHECKS & FORCE ##
####################

check-replication-filters = true
check-binlog-filters = true
check-replication-state = true

force-slave-heartbeat= false
force-slave-heartbeat-retry = 5
force-slave-heartbeat-time = 3
force-slave-gtid-mode = false
force-slave-semisync = false
force-slave-failover-readonly-state = false
force-binlog-row = false
force-binlog-annotate = false
force-binlog-slowqueries = false
force-binlog-compress = false
force-binlog-checksum = false
force-inmemory-binlog-cache-size = false
force-disk-relaylog-size-limit = false
force-disk-relaylog-size-limit-size = 1000000000
force-sync-binlog = false
force-sync-innodb = false
```

**Comment by caffeinated92** [comment]
To disregard errant transaction, you can set check-replication-errant-trx = false

**Comment by dibrother** [comment]
> @caffeinated92 
I have set 
log-failed-election  = "INFO" or  log-failed-election  = true
log-level = 3， But the logs don't seem to contain much information

```shell
time="2024-07-09 10:16:02" level=warning msg="Cluster does not have backup" channel=StdOut cluster=cluster1 code=WARN0101 status=OPENED type=state
time="2024-07-09 10:16:02" level=info msg="Exit loop 10.10.2.11:3310. Start HB: 26, Stop HB: 30 " cluster=cluster1 module=general type=log
time="2024-07-09 10:16:04" level=warning msg="Server 10.10.2.11:3310 in capture mode" channel=StdOut cluster=cluster1 code=WARN0085 status=RESOLV type=state
time="2024-07-09 10:16:24" level=info msg="Master Failure detected! Retry 1/5" cluster=cluster1 module=general type=log
time="2024-07-09 10:16:24" level=info msg="Server 10.10.2.10:3310 state transition from Master changed to: Suspect" cluster=cluster1 module=general type=log
time="2024-07-09 10:16:24" level=info msg="Server 10.10.2.10:3310 previous state set to: Suspect" cluster=cluster1 module=general type=log
time="2024-07-09 10:16:24" level=warning msg="Server as errant transaction 10.10.2.11:3310" channel=StdOut cluster=cluster1 code=WARN0091 status=OPENED type=state
time="2024-07-09 10:16:26" level=info msg="Master Failure detected! Retry 2/5" cluster=cluster1 module=general type=log
time="2024-07-09 10:16:28" level=info msg="Master Failure detected! Retry 3/5" cluster=cluster1 module=general type=log
time="2024-07-09 10:16:30" level=info msg="Master Failure detected! Retry 4/5" cluster=cluster1 module=general type=log
time="2024-07-09 10:16:32" level=info msg="Master Failure detected! Retry 5/5" cluster=cluster1 module=general type=log
time="2024-07-09 10:16:32" level=info msg="Declaring db master as failed 10.10.2.10:3310" cluster=cluster1 module=general type=log
time="2024-07-09 10:16:32" level=info msg="Server 10.10.2.10:3310 state transition from Suspect changed to: Failed" cluster=cluster1 module=general type=log
time="2024-07-09 10:16:32" level=error msg="Server 10.10.2.10:3310 state changed from Suspect to Failed" channel=StdOut cluster=cluster1 module=general type=alert
time="2024-07-09 10:16:32" level=info msg="Server 10.10.2.10:3310 previous state set to: Failed" cluster=cluster1 module=general type=log
```

**Comment by dibrother** [comment]
@caffeinated92 
Thank you for your recovery. After setting the parameters [check-replication-errant-trx = false], it can proceed with the fault transfer.
If a ghost transaction occurs in the main database, will it also be re added if this parameter is set?

**Comment by caffeinated92** [comment]
can you set the general log level and failed election to debug level? Maybe we can get something from that

**Comment by dibrother** [comment]
I deleted the parameter check replication error trx=false and it is now in a failed fail over state. The current structure is 11 as master, and the log can be found in the attachment

[replicatopn-debug.log](https://github.com/user-attachments/files/16136812/replicatopn-debug.log)

**Comment by caffeinated92** [comment]
can you list all the states in alert page?

**Comment by dibrother** [comment]
Is this the information you need?


<img width="1401" alt="image" src="https://github.com/signal18/replication-manager/assets/95730552/9e4be65a-2a15-4436-9445-c6ebb9a92b42">

**Comment by caffeinated92** [comment]
Yes, thank you. This will help for checking all states.

**Comment by caffeinated92** [comment]
> @caffeinated92 Thank you for your recovery. After setting the parameters [check-replication-errant-trx = false], it can proceed with the fault transfer. If a ghost transaction occurs in the main database, will it also be re added if this parameter is set?

What do you mean by ghost transaction?

**Comment by caffeinated92** [comment]
We will check on this with the additional info and report back

**Comment by dibrother** [comment]
Ghost transaction refers to the data recovered from the binlog by the master during crash recovery after restarting, but this data has not yet been transferred to the slave database, resulting in an additional transaction for the original master.

Thank you very much for your prompt reply

**Comment by svaroqui** [comment]
HI dibrother we have an open ticket on the state of ghost transactions it's a regression on errant transactions , in the past we wanted to refuse automatic failover on a slave  having errent trx to preserve the capability to rejoin unfortunatly that check add false positive result when run on delayed slave producing to many warning , The way it was working have been change to check if the slave GTID is included in master GTID. This now detect errant transactions on day to day but discard failover when the master is shoot in the head ,stay tune for true gost trx detection that can work in both cases
