### ISSUE TITLE
FailoverTS reset when FailoverCtr is reset

### ISSUE THREAD

**Issue by krissfr** [signal18/replication-manager#70]
Hello,

Could you reset the FailoverTS when resetting FailoverCtr ?

Regards,

Krissfr

**Comment by tanji** [comment]
Hi Kriss, would that have any kind of use?

**Comment by krissfr** [comment]
Hi Guillaume,

I wrote a template monitoring for Zabbix and so monitor the FailoverTS (if thereis a failover during the last hour).  When a failover occur, if the operator that will check the MRM logs can reset the FailoverTS as he can do for the FailoverCtr, everybody will know somebody has checked this failover ( and the alarm in our dashboard will disappears).

**Comment by tanji** [comment]
I see! So, would it be OK if the reset failover button in the web app resets the Failover TS?

**Comment by krissfr** [comment]
Yes it will be ok
