### ISSUE TITLE
After changing the API credential, switchover failed

### ISSUE THREAD

**Issue by dibrother** [signal18/replication-manager#719]
VERSION:
```SHELL
[root@test11 bin]# replication-manager-cli version
Replication Manager v2.3.36 for MariaDB 10.x and MySQL 5.7 Series
Full Version:  v2.3.36
Build Time:  2024-07-05T16:19:08+0000
```

I have modified the API credentials in the config. xml file to:
```shell
api-port = "10005"
api-credentials = "repman:123456"
```

Then execute the switch,but it failed:
```shell
[root@test11 bin]# replication-manager-cli --user=repman --password=123456 --port=10005 switchover --db-servers-prefered-master 10.10.2.10:3310
| Group: cluster1 |  Mode: Manual 
                 Id            Host   Port          Status   Failures   Using GTID         Current GTID           Slave GTID             Replication Health  Delay  RO MAINT
db14945847834543103650      10.10.2.10   3310           Slave          0          Yes 0-3005298880600996705-302604,0-16489532285359875922-12557          0-0-0,0-0-0                                     0  ON     N
db10612492877609025276      10.10.2.11   3310          Master          0          Yes 0-3005298880600996705-302604,0-16489532285359875922-12557                                                          0 OFF     N
db3106860092439920192      10.10.2.13   3310           Slave          0          Yes 0-3005298880600996705-302604,0-16489532285359875922-12557          0-0-0,0-0-0                                     0  ON     N
INFO[0002] [cluster1] [general] INFO  - ACL check failed for user repman : /api/clusters/cluster1/actions/switchover  
INFO[0002] [cluster1] [general] INFO  - ACL check failed for user repman : /api/clusters/cluster1/actions/switchover  
INFO[0002] [cluster1] [general] STATE - RESOLV WARN0085 : Server 10.10.2.10:3310 in capture mode 
INFO[0002] [cluster1] [general] INFO  - Exit loop 10.10.2.10:3310. Start HB: 313, Stop HB: 317  
INFO[0002] [cluster1] [general] STATE - RESOLV ERR00041 : Skip slave in election 10.10.2.10:3310 has more than 30 seconds of replication delay (51) Sql:  
INFO[0002] [cluster1] [general] INFO  - Server 10.10.2.10:3310 previous state set to: Slave 
INFO[0002] [cluster1] [general] INFO  - Server 10.10.2.10:3310 state transition from SlaveLate changed to: Slave 
INFO[0002] [cluster1] [general] STATE - OPENED WARN0085 : Server 10.10.2.10:3310 in capture mode 
INFO[0002] [cluster1] [general] STATE - RESOLV ERR00032 : No candidates found in slaves list 
INFO[0002] [cluster1] [general] INFO  - Capture ERR00041 on server 10.10.2.10:3310 
INFO[0002] [cluster1] [general] STATE - OPENED ERR00032 : No candidates found in slaves list 
INFO[0002] [cluster1] [general] STATE - OPENED ERR00041 : Skip slave in election 10.10.2.10:3310 has more than 30 seconds of replication delay (444) Sql:  
INFO[0002] [cluster1] [general] STATE - RESOLV WARN0022 : Rejoining standalone server 10.10.2.10:3310 to master 10.10.2.11:3310 
INFO[0002] [cluster1] [general] INFO  - Server 10.10.2.10:3310 previous state set to: SlaveLate 
INFO[0002] [cluster1] [general] INFO  - Server 10.10.2.10:3310 state transition from StandAlone changed to: SlaveLate 
INFO[0002] [cluster1] [general] STATE - OPENED WARN0022 : Rejoining standalone server 10.10.2.10:3310 to master 10.10.2.11:3310 
INFO[0002] [cluster1] [general] INFO  - Server 10.10.2.10:3310 previous state set to: StandAlone 
INFO[0002] [cluster1] [general] INFO  - Rejoin old Master 10.10.2.10:3310 , backing up lost event to /var/lib/replication-manager/cluster1/crash-bin-20240712145914 
INFO[0002] [cluster1] [general] INFO  - Doing MySQL GTID switch of the old master 
INFO[0002] [cluster1] [general] INFO  - Found same or lower GTID 0-3005298880600996705-302604,0-16489532285359875922-415 and new elected master was 0-3005298880600996705-302604,0-16489532285359875922-415 
INFO[0002] [cluster1] [general] INFO  -  8B73D396-3FFF-11EF-80CA-000C29532D30 10.10.2.10:3310 
INFO[0002] [cluster1] [general] INFO  -  8B73D396-3FFF-11EF-80CA-000C29532D30 10.10.2.10:3310 
INFO[0002] [cluster1] [general] INFO  -  8B73D396-3FFF-11EF-80CA-000C29532D30 10.10.2.10:3310 
INFO[0002] [cluster1] [general] INFO  - Rejoin server found a crash GTID greater than 0  
INFO[0002] [cluster1] [general] INFO  - Crash Saved GTID sequence 302604 from server id 3005298880600996705 
INFO[0002] [cluster1] [general] INFO  -  8B73D396-3FFF-11EF-80CA-000C29532D30 10.10.2.10:3310 
INFO[0002] [cluster1] [general] INFO  -  8B73D396-3FFF-11EF-80CA-000C29532D30 10.10.2.10:3310 
INFO[0002] [cluster1] [general] INFO  - Rejoined GTID sequence  302604 from server id 3005298880600996705 
INFO[0002] [cluster1] [general] INFO  -  8B73D396-3FFF-11EF-80CA-000C29532D30 10.10.2.10:3310 
| Group: cluster1 |  Mode: Manual 
                 Id            Host   Port          Status   Failures   Using GTID         Current GTID           Slave GTID             Replication Health  Delay  RO MAINT
db14945847834543103650      10.10.2.10   3310           Slave          0          Yes 0-3005298880600996705-302604,0-16489532285359875922-12557          0-0-0,0-0-0                                     0  ON     N
db10612492877609025276      10.10.2.11   3310          Master          0          Yes 0-3005298880600996705-302604,0-16489532285359875922-12557                                                          0 OFF     N
db3106860092439920192      10.10.2.13   3310           Slave          0          Yes 0-3005298880600996705-302604,0-16489532285359875922-12557          0-0-0,0-0-0                                     0  ON     N
```

Change back：
```shell
api-port = "10005"
api-credentials = "admin:repman"
```
Then execute the switch,succeeded:
```shell
[root@test11 bin]# replication-manager-cli switchover --db-servers-prefered-master 10.10.2.10:3310
| Group: cluster1 |  Mode: Manual 
                 Id            Host   Port          Status   Failures   Using GTID         Current GTID           Slave GTID             Replication Health  Delay  RO MAINT
db14945847834543103650      10.10.2.10   3310           Slave          0          Yes 0-3005298880600996705-302604,0-16489532285359875922-15303          0-0-0,0-0-0                                     0  ON     N
db10612492877609025276      10.10.2.11   3310          Master          0          Yes 0-3005298880600996705-302604,0-16489532285359875922-15303                                                          0 OFF     N
db3106860092439920192      10.10.2.13   3310           Slave          0          Yes 0-3005298880600996705-302604,0-16489532285359875922-15303          0-0-0,0-0-0                                     0  ON     N
INFO[0007] [cluster1] [general] INFO  - Master switch on 10.10.2.10:3310 complete 
INFO[0007] [cluster1] [general] INFO  - Change master on slave 10.10.2.13:3310 
INFO[0007] [cluster1] [general] INFO  - Server:10.10.2.13:3310 Current GTID:0-3005298880600996705-302604,0-16489532285359875922-15360 Slave GTID:0-0-0,0-0-0 Binlog Pos:0-3005298880600996705-302604,0-16489532285359875922-15360 
INFO[0007] [cluster1] [general] INFO  - Waiting for slave 10.10.2.13:3310 to sync 
INFO[0007] [cluster1] [general] INFO  - Switching other slaves to the new master 
INFO[0007] [cluster1] [general] INFO  - Server 10.10.2.11:3310 state transition from Master changed to: Slave 
INFO[0007] [cluster1] [general] INFO  - Doing MySQL GTID switch of the old master 
INFO[0007] [cluster1] [general] INFO  - Switching old leader to slave 
INFO[0007] [cluster1] [general] INFO  - Killing new connections on old master showing before update route 
INFO[0007] [cluster1] [general] INFO  - Inject fake transaction on new master 10.10.2.10:3310  
INFO[0007] [cluster1] [general] INFO  - Post-failover script complete 2024-07-12 15:02:39 [Note] make vip up on new master...
ARPING 10.10.2.111 from 10.10.2.111 ens160
Sent 1 probes (1 broadcast(s))
Received 0 response(s)
Connection to 10.10.2.10 closed.
2024-07-12 15:02:41 [Note] 10.10.2.111 is moved to 10.10.2.10. 
INFO[0007] [cluster1] [general] INFO  - Calling post-failover script 
INFO[0007] [cluster1] [general] INFO  - Waiting 2s for unmanaged proxy to monitor route change 
INFO[0007] [cluster1] [general] INFO  - Failover proxies 
INFO[0007] [cluster1] [general] INFO  - Resetting slave on new master and set read/write mode on 
INFO[0007] [cluster1] [general] INFO  - Stopping slave threads on new master 
INFO[0007] [cluster1] [general] INFO  - MySQL GTID saving crash info for replication ExexecutedGtidSet 8b73d396-3fff-11ef-80ca-000c29532d30:1-302604,
a81c51e4-3fff-11ef-8ee2-000c293d1396:1-15323 
INFO[0007] [cluster1] [general] INFO  - Save replication status and crash infos before opening traffic 
INFO[0007] [cluster1] [general] INFO  - Waiting sync IO_Pos:{mysql-bin.000007 %!!(MISSING)s(bool=true)}/4, Slave_Pos:{mysql-bin.000007 %!!(MISSING)s(bool=true)} 4 
INFO[0007] [cluster1] [general] INFO  - Reading all relay logs on 10.10.2.10:3310 
INFO[0007] [cluster1] [general] INFO  - Waiting for candidate master 10.10.2.10:3310 to apply relay log 
INFO[0007] [cluster1] [general] INFO  - Freezing writes rejecting writes via FTWRL on 10.10.2.11:3310  
INFO[0007] [cluster1] [general] INFO  - Freezing writes killing all other remaining threads on  10.10.2.11:3310 
INFO[0007] [cluster1] [general] INFO  - Freezing writes decreasing max_connections to 1 on 10.10.2.11:3310  
INFO[0007] [cluster1] [general] INFO  - Freezing writes saving max_connections on 10.10.2.11:3310  
INFO[0007] [cluster1] [general] INFO  - Freezing writes set read only on 10.10.2.11:3310 
INFO[0007] [cluster1] [general] INFO  - Freezing writes stopping all slaves on 10.10.2.11:3310 
INFO[0007] [cluster1] [general] INFO  - Pre-failover script complete:%!!(MISSING)(EXTRA string=2024-07-12 15:02:36 [Note] Master is dead, failover
ARPING 10.10.2.111 from 10.10.2.111 ens160
Sent 1 probes (1 broadcast(s))
Received 0 response(s)
PING 10.10.2.111 (10.10.2.111) 56(84) bytes of data.
64 bytes from 10.10.2.111: icmp_seq=1 ttl=64 time=0.051 ms

--- 10.10.2.111 ping statistics ---
1 packets transmitted, 1 received, 0%!p(MISSING)acket loss, time 0ms
rtt min/avg/max/mdev = 0.051/0.051/0.051/0.000 ms
Connection to 10.10.2.11 closed.
2024-07-12 15:02:37 10.10.2.111 is removed from 10.10.2.11.
2024-07-12 15:02:37 [Note] 10.10.2.111 is removed from 10.10.2.11.
) 
INFO[0007] [cluster1] [general] INFO  - Calling pre-failover script 
| Group: cluster1 |  Mode: Manual 
                 Id            Host   Port          Status   Failures   Using GTID         Current GTID           Slave GTID             Replication Health  Delay  RO MAINT
db14945847834543103650      10.10.2.10   3310          Master          0          Yes 0-3005298880600996705-302604,0-16489532285359875922-15360                                                          0  ON     N
db10612492877609025276      10.10.2.11   3310           Slave          0          Yes 0-3005298880600996705-302604,0-16489532285359875922-15360                                                          0  ON     N
db3106860092439920192      10.10.2.13   3310           Slave          0          Yes 0-3005298880600996705-302604,0-16489532285359875922-15360          0-0-0,0-0-0                                     0  ON     N
```

**Comment by svaroqui** [comment]
have you try giving the password to the cli  ?

**Comment by dibrother** [comment]
replication-manager-cli --user=repman --password=123456 --port=10005 switchover --db-servers-prefered-master 10.10.2.10:3310

Yes, I provided it, but it cannot be switched on the web side either.

**Comment by svaroqui** [comment]
Ok you need to use admin as a user or give correct grant to switchover for the different user repman , we removed any ACL to extra user for security raisons

 --api-credentials-acl-allow string                     User acl allow (default "admin:cluster proxy db prov,dba:cluster proxy db,foo:")
For the list of ACL please visit config/config.go

**Comment by dibrother** [comment]
I haven't fully understood the parameter '--api-credentials-acl-allow' yet, but I have discovered a new issue and I'm not sure if this is due to my misunderstanding,this issue has been bothering me for a few days.

### Q1：Related to switching
  I have configured [switchover-at-equal-gtid = true ],but it didn't take effect.When the GTID of the slave is greater than that of the master and normal switching is still performed, I think this is incorrect.Application history transactions may lead to data confusion.
As follows：
<img width="1387" alt="image" src="https://github.com/user-attachments/assets/2aeaa4e0-c8f9-419b-b8a6-df43dd1cdd29">
<img width="1401" alt="image" src="https://github.com/user-attachments/assets/c1fcfaf8-2b6e-4190-9c2a-0ed77dc309af">
<img width="1390" alt="image" src="https://github.com/user-attachments/assets/137deb7d-ed83-47b2-90b4-4cd27fc498f2">

According to the HaveErantTransactions method, the statement is
```sql
query := "select gtid_subset('" + gtidSlave + "','" + gtidMaster + "') as slave_is_subset"
```
I opened the generality log and saw the following information,the replication-manager seems to have made a mistake in the direction of comparison
```sql
-- old master:0D221E32-433E-11EF-945F-000C293D1396:1-48058
-- new master:0D221E32-433E-11EF-945F-000C293D1396:1-48064
select gtid_subset('026465DA-433E-11EF-B658-000C29532D30:1-3913, 0D221E32-433E-11EF-945F-000C293D1396:1-48058','026465DA-433E-11EF-B658-000C29532D30:1-3913, 0D221E32-433E-11EF-945F-000C293D1396:1-48064') as slave_is_subset
```



### Q2：
It's still the same issue with the "check-replication-array-trx=true" parameter as before.As long as the detection is turned on, it cannot fail over normally.
It is easy to reproduce, just write a loop to the master and continue writing data, then stop the master. Due to the replication manager's failure to read the master's GTID information in a timely manner, the GTID on the slave will be greater than the GTID on the master, resulting in the termination of the switch.
In fact, the GTID of the master is greater than or equal to the GTID on the slave, as can be seen from restarting the master node.


I have uploaded the configuration file and logs, you can check them if you need them.Thank you.
[config-and-log.zip](https://github.com/user-attachments/files/16245402/config-and-log.zip)

**Comment by dibrother** [comment]
Q2 When performing a fault transfer, if the slave(new master) is greater than or equal to the old master GTID and the GTIDs of other uuids are consistent, the fault transfer can be performed correctly

<img width="1383" alt="image" src="https://github.com/user-attachments/assets/f0819908-1e21-4980-9b87-ff813e8a6517">

general log, return 0 , false
 :
```sql
-- to be new master:0D221E32-433E-11EF-945F-000C293D1396:1-49056
-- old master:0D221E32-433E-11EF-945F-000C293D1396:1-49014
select gtid_subset('026465DA-433E-11EF-B658-000C29532D30:1-3913, 0D221E32-433E-11EF-945F-000C293D1396:1-49056','026465DA-433E-11EF-B658-000C29532D30:1-3913, 0D221E32-433E-11EF-945F-000C293D1396:1-49014') as slave_is_subset
```

**Comment by svaroqui** [comment]
Thanks for the report what release are you using ?

**Comment by svaroqui** [comment]
Regarding the ACL it is a list of grant per user , if you change the user name you also need provide what grant this user can perform https://github.com/signal18/replication-manager/blob/develop/config/config.go#L831

**Comment by dibrother** [comment]
VERSION:
```
[root@test11 bin]# replication-manager-cli version
Replication Manager v2.3.36 for MariaDB 10.x and MySQL 5.7 Series
Full Version:  v2.3.36
Build Time:  2024-07-05T16:19:08+0000
```

I tested the ACL and it was successful. Thank you.

**Comment by svaroqui** [comment]
For MySQL GTID we will try to free some time to work on this .
- We wan't cancel switchover on a slave is having errant transaction  
- A slave having errant transaction should be overrated  on  check-replication-array-trx
- Equal GTID  is only valid for auto failover when slave as catch all events from master we can detect this from replication status

**Comment by dibrother** [comment]
Thank you for your reply.
Can we consider making this judgment：
1. Record the current master's [server_uuid] somewhere
2. When switching or failover occurs, compare whether the GTID of the server uuid on the new master is greater than or equal to the value on the old master. If it is, switch is allowed
3. Compare the other GTIDs to see if they are consistent. If they are not consistent, it indicates the presence of an anomaly

**Comment by svaroqui** [comment]
As previously discover the GTID of the master is unknowed the time we fetch it may have change , it looks you wan't to use semisync to make this happen.

**Comment by svaroqui** [comment]
2 - You perviously onpen a bug saying that the slave can be higher in case of failover because the slave may have catch more info from the master then what we last recorded before it died :)

**Comment by dibrother** [comment]
I used MySQL semi synchronization, and my confusion is that executing systemctl stop mysqld on the master stopped the master, while the GTID obtained by the replication manager due to the master rejecting the link will be smaller than the GTID played back by the slave in the future

Currently, due to the use of parameter [check replication array trx], it is not possible to perform failover. Is this a bug?

Because all replay transactions of a slave come from the value corresponding to the deceased master [server uuid], it should be allowed for the same [server uuid] value to be greater than the deceased master on the slave

It could also be that my understanding of the [check replication array trx] parameter is insufficient. 

Thank you for your patient reply.

**Comment by svaroqui** [comment]
I think i fixes this in 2 3.39 could you upgrade and report i did not
tested deep, so possible i miss something

**Comment by dibrother** [comment]
I tested version 2.3.40 and when the parameter [check replication array trx=true] is enabled, the problem still persists and cannot be failover
Operation steps:
1. Deploy master-slave and replication manager
2. Use a bash script to run a for loop to write data to the master
3.systemctl stop mysqld
4. Can reproduce the problem

Please refer to the attachment for log information.
[conf_and_log.zip](https://github.com/user-attachments/files/16280840/conf_and_log.zip)

**Comment by dibrother** [comment]
Is it due to my usage issue?

**Comment by caffeinated92** [comment]
May I know what do you want to achieve actually? We can disable the replication check if we want to do failover? I mean I'm not really clear about the goal.

**Comment by caffeinated92** [comment]
I'm going to split the thread based on the question. Please don't mix questions in one thread so we can focus. Cheers

**Comment by dibrother** [comment]
This is my problem,I didn't test it carefully.I tested it again on 2.3.40 and it can now achieve the desired function. Thank you again.

My goal is to:
1. Automatic fault transition can be performed in the event of a malfunction (such as a crash or power outage), and disabling the [check replication array trx] can achieve this
When switching over, if there are extra transactions on the slave node (someone has done some operations on the slave node), the switch will not be performed or another normal slave will be selected for switching, because switching to master may cause data confusion.
<img width="1404" alt="image" src="https://github.com/user-attachments/assets/131d5e1e-70e6-48ca-9cd1-0f4c0036fc05">

@svaroqui @caffeinated92 
The current question has been resolved. Thank you again and best wishes.

**Comment by svaroqui** [comment]
@dibrother @caffeinated92 during my internal testing i think that the fix in 2.3.39 , does allow to switchover on errant transaction so i would re qualify this thread as disable switchover when errant transaction but not when failover master is behind the slave

**Comment by svaroqui** [comment]
I thanks you for reporting area where we are not good in MySQL , MariaDB have slave_exec_mode strict  that limit such errent transactions as the slave would stop instantly and have Heuristic recovery to rollback using XA so that the old master can rejoin the cluster safe when semi sync status was ok during crash .

**Comment by dibrother** [comment]
I use MySQL more often and haven't used MariaDB much
Hello, There is still a small issue here. When the master does not write data and the slave data is incorrect, the replication manager does not detect the slave err and can still switch normally.

<img width="1414" alt="image" src="https://github.com/user-attachments/assets/8023d705-9393-4fab-b365-1ac5f2b9c3ad">

Then it can switch normally.
<img width="1388" alt="image" src="https://github.com/user-attachments/assets/d75e02fd-7b48-4d78-93ab-fdc4a851c304">
