### ISSUE TITLE
loading data causes metadata lock

### ISSUE THREAD

**Issue by ProGengi** [signal18/replication-manager#728]
Version:
I installed it using the source code, version V2.3.17

Question:
l load data into mysql with sql : mysql -uroot -p < xxxx.sql
It took a long time, then i check the processlist，the state of the load sql is 

> Waiting for table metadata lock

And I found lots of replication-manager threads，the state of these sql is

> Opening tables

and the Info of these sql is 

> /*replication-manager*/ SHOW CREATE TABLE xxxx

There are no other threads except replication-manager and load

Why replication-manager need opening tables？
I don't know how to solve the problem.

**Comment by caffeinated92** [comment]
Hi @ProGengi,

Can you try using our latest version and see if you have same problem?

**Comment by caffeinated92** [comment]
If you have same problem you can set monitoring-schema to OFF

**Comment by ProGengi** [comment]
> If you have same problem you can set monitoring-schema to OFF


It‘s troublesome for me to use the latest version, so i chose plan B.
It's ok after set monitoring-schema to OFF. 
Thank you @caffeinated92
