### ISSUE TITLE
Incorrect maxscale grant in doc 

### ISSUE THREAD

**Issue by svaroqui** [signal18/replication-manager#74]
GRANT SHOW DATABASES, REPLICATION CLIENT ON . TO 'maxadmin'@'%';

**Comment by svaroqui** [comment]
show be GRANT SHOW DATABASES, REPLICATION CLIENT ON _._ TO 'maxadmin'@'%';

**Comment by svaroqui** [comment]
star . star

**Comment by tanji** [comment]
That's exactly what is in the doc:

`GRANT SHOW DATABASES, REPLICATION CLIENT ON *.* TO 'maxadmin'@'%';`

what is the issue?

**Comment by svaroqui** [comment]
Sorry copy paste issue , the doc was good
