### ISSUE TITLE
Prevent multiple execution of replication manager

### ISSUE THREAD

**Issue by svaroqui** [signal18/replication-manager#75]
One can run replication manager monitor in console mode and in daemon  mode at the same time 
A solution would be to update a replication_monitor_heartbeat system table at every loop with unique process_id and  detect multiple instances   

Run in the master 

u, err := exec.Command("uuidgen").Output()
    if err != nil {
        log.Fatal(err)
        return err
    }
    r.run_uuid = fmt.Sprintf("%s", u)

At startup:

 CREATE OR REPLACE TABLE mysql.replication_monitor_heartbeat( pid BIGINT , lastping  DATA) ;

In the event loop: 

query = fmt.Sprintf("INSERT INTO mysql.replication_monitor_heartbeat SELECT    CONV(LEFT(MD5('%s'), 16), 16, 10) , NOW() ", u)

SELECT  count(*)  FROM mysql.replication_monitor_heartbeat WHERE lastping >   NOW() -  INTERVAL 3 SECOND ;

if resultset count  > 1 then

Output:

An other replication manager exists or  was just shutdown 3 second ago

**Comment by krissfr** [comment]
Hi Stephane,

a lock file ( ie /etc/replication-manager/mrm.lck) couldn't be a much simple and less intrusive solution ?

regards,

Krissfr

**Comment by tanji** [comment]
My personal choice is a pidfile as well, with systemd management.

@krissfr just curious to know what distributions you are using MRM with?

**Comment by krissfr** [comment]
@tanji :   pid file is  good enough for me too, although some application use both pid file and lock file .

Currently the only one server  we have with MRM is a Debian Jessie, but we use often CentOS too for this kind of things.

**Comment by tanji** [comment]
Fixed in 2.0 with introduction of server and CLI
