### ISSUE TITLE
Warning should be produce when lack sync_binlog=1 and innodb_flush_log_at_trx_commit <> 1  

### ISSUE THREAD

**Issue by svaroqui** [signal18/replication-manager#76]

**Comment by svaroqui** [comment]
Would be nice to check equality of such parameters in all possible slaves

**Comment by michaeldg** [comment]
Why does slave need sync_binlog = 1? The slave is crash safe with mysql.gtid_slave_pos table.

**Comment by tanji** [comment]
In order to make slave promotion consistent, all servers should have recommended parameters.
