### ISSUE TITLE
Seeing errors when building 

### ISSUE THREAD

**Issue by vipul-nextev** [signal18/replication-manager#83]
vagrant@db4 replication-manager]$ go build -v .
github.com/mariadb-corporation/replication-manager/vendor/github.com/go-sql-driver/mysql
github.com/mariadb-corporation/replication-manager/vendor/github.com/jmoiron/sqlx/reflectx
github.com/mariadb-corporation/replication-manager/vendor/github.com/jmoiron/sqlx
github.com/mariadb-corporation/replication-manager/vendor/github.com/mattn/go-runewidth
github.com/mariadb-corporation/replication-manager/vendor/github.com/nsf/termbox-go
github.com/mariadb-corporation/replication-manager/vendor/github.com/spf13/pflag
github.com/mariadb-corporation/replication-manager/vendor/github.com/spf13/cobra
github.com/mariadb-corporation/replication-manager/vendor/github.com/BurntSushi/toml
github.com/mariadb-corporation/replication-manager/vendor/golang.org/x/sys/unix
github.com/mariadb-corporation/replication-manager/vendor/github.com/fsnotify/fsnotify
github.com/mariadb-corporation/replication-manager/vendor/github.com/hashicorp/hcl/hcl/strconv
github.com/mariadb-corporation/replication-manager/vendor/github.com/hashicorp/hcl/hcl/token
github.com/mariadb-corporation/replication-manager/vendor/github.com/hashicorp/hcl/hcl/ast
github.com/mariadb-corporation/replication-manager/vendor/github.com/hashicorp/hcl/hcl/scanner
github.com/mariadb-corporation/replication-manager/vendor/github.com/hashicorp/hcl/hcl/parser
github.com/mariadb-corporation/replication-manager/vendor/github.com/hashicorp/hcl/json/token
github.com/mariadb-corporation/replication-manager/vendor/github.com/hashicorp/hcl/json/scanner
github.com/mariadb-corporation/replication-manager/vendor/github.com/hashicorp/hcl/json/parser
github.com/mariadb-corporation/replication-manager/vendor/github.com/hashicorp/hcl
github.com/mariadb-corporation/replication-manager/vendor/github.com/magiconair/properties
github.com/mariadb-corporation/replication-manager/vendor/github.com/mitchellh/mapstructure
github.com/mariadb-corporation/replication-manager/vendor/github.com/spf13/jwalterweatherman
github.com/mariadb-corporation/replication-manager/vendor/github.com/spf13/cast
github.com/mariadb-corporation/replication-manager/vendor/gopkg.in/yaml.v2
github.com/mariadb-corporation/replication-manager/vendor/github.com/spf13/viper
github.com/mariadb-corporation/replication-manager
# github.com/mariadb-corporation/replication-manager

./failover.go:27: cannot use master.Conn (type *"github.com/mariadb-corporation/replication-manager/vendor/github.com/jmoiron/sqlx".DB) as type *"github.com/tanji/replication-manager/vendor/github.com/jmoiron/sqlx".DB in argument to dbhelper.FlushTablesNoLog
./failover.go:32: cannot use master.Conn (type *"github.com/mariadb-corporation/replication-manager/vendor/github.com/jmoiron/sqlx".DB) as type *"github.com/tanji/replication-manager/vendor/github.com/jmoiron/sqlx".DB in argument to dbhelper.CheckLongRunningWrites
./failover.go:75: cannot use oldMaster.Conn (type *"github.com/mariadb-corporation/replication-manager/vendor/github.com/jmoiron/sqlx".DB) as type *"github.com/tanji/replication-manager/vendor/github.com/jmoiron/sqlx".DB in argument to dbhelper.FlushTablesWithReadLock
./failover.go:90: cannot use master.Conn (type *"github.com/mariadb-corporation/replication-manager/vendor/github.com/jmoiron/sqlx".DB) as type *"github.com/tanji/replication-manager/vendor/github.com/jmoiron/sqlx".DB in argument to dbhelper.MasterPosWait
./failover.go:104: cannot use master.Conn (type *"github.com/mariadb-corporation/replication-manager/vendor/github.com/jmoiron/sqlx".DB) as type *"github.com/tanji/replication-manager/vendor/github.com/jmoiron/sqlx".DB in argument to dbhelper.StopSlave
./failover.go:121: cannot use master.Conn (type *"github.com/mariadb-corporation/replication-manager/vendor/github.com/jmoiron/sqlx".DB) as type *"github.com/tanji/replication-manager/vendor/github.com/jmoiron/sqlx".DB in argument to dbhelper.ResetSlave
./failover.go:126: cannot use master.Conn (type *"github.com/mariadb-corporation/replication-manager/vendor/github.com/jmoiron/sqlx".DB) as type *"github.com/tanji/replication-manager/vendor/github.com/jmoiron/sqlx".DB in argument to dbhelper.SetReadOnly
./failover.go:135: cannot use master.Conn (type *"github.com/mariadb-corporation/replication-manager/vendor/github.com/jmoiron/sqlx".DB) as type *"github.com/tanji/replication-manager/vendor/github.com/jmoiron/sqlx".DB in argument to dbhelper.FlushTables
./failover.go:141: cannot use oldMaster.Conn (type *"github.com/mariadb-corporation/replication-manager/vendor/github.com/jmoiron/sqlx".DB) as type *"github.com/tanji/replication-manager/vendor/github.com/jmoiron/sqlx".DB in argument to dbhelper.UnlockTables
./failover.go:145: cannot use oldMaster.Conn (type *"github.com/mariadb-corporation/replication-manager/vendor/github.com/jmoiron/sqlx".DB) as type *"github.com/tanji/replication-manager/vendor/github.com/jmoiron/sqlx".DB in argument to dbhelper.StopSlave
./failover.go:145: too many errors

**Comment by tanji** [comment]
Seems you're using an older repo, please rm -rf this one and clone again. It should work fine.

**Comment by vipul-nextev** [comment]
Would you be kind enough to send me how to build and generate  replication-manager binary as I a not familiar with go . Thanks
