### ISSUE TITLE
Verbose output only goes to the log file

### ISSUE THREAD

**Issue by markus456** [signal18/replication-manager#89]
The verbose and debug output is only written to the log file, not to the standard output. When the replication manager is started with the following options, there's no additional output to stdout.

```
./replication-manager monitor --hosts 127.0.0.1:3000,127.0.0.1:3001,127.0.0.1:3002,127.0.0.1:3003 --user maxuser:maxpwd --rpluser maxuser:maxpwd --daemon --verbose --log-level 3
2016/10/01 14:59:13 INFO : No existing password encryption scheme: Key file does not exist
2016/10/01 14:59:13 INFO : replication-manager version 0.7 started in daemon mode
```

Adding the `--logfile mrm.log` fixes it and the file _mrm.log_ contains the DEBUG output.

Version: 0.7.0-rc2

**Comment by tanji** [comment]
Fixed in 62718a653df70e8fb86ced65d6b7e05c70d054ea
