### ISSUE TITLE
Monitor with --daemon option requires --interactive=false 

### ISSUE THREAD

**Issue by markus456** [signal18/replication-manager#90]
When starting the monitor with `--daemon`, `--interactive=false` is required to make automated failovers work. The daemon mode should implicitly start the replication manager in automatic mode.

Here's the output when the replication manager is started in manual daemon mode:

```
2016/10/01 15:15:08 INFO : Monitor started in manual mode
2016/10/01 15:15:24 WARN : Master Failure detected! Retry 1/5
2016/10/01 15:15:24 INFO : INF00001 Server 127.0.0.1:3000 is down
2016/10/01 15:15:26 WARN : Master Failure detected! Retry 2/5
2016/10/01 15:15:28 WARN : Master Failure detected! Retry 3/5
2016/10/01 15:15:30 WARN : Master Failure detected! Retry 4/5
2016/10/01 15:15:32 WARN : Master Failure detected! Retry 5/5
2016/10/01 15:15:32 WARN : Declaring master as failed
```

There's no way to initiate the failover as console commands are ignored with the daemon mode.

**Comment by markus456** [comment]
This seems to be by design and is a good safeguard to prevent unintentional master failovers.

**Comment by tanji** [comment]
By the way, the failover mode should be printed to the console when replication-manager starts, but because of #89 it did not happen.
