### ISSUE TITLE
centos 7 package for v2.3.52 not available for x86_64

### ISSUE THREAD

**Issue by duguwo** [signal18/replication-manager#917]
Hi !
I would like to upgrade my replication-manager to latest 2.3 version; i.e. 2.3.52 but the centos 7 release for x86_64 is not available at http://repo.signal18.io 

error:
http://repo.signal18.io/centos/7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.

**Comment by tanji** [comment]
It should be fixed by now, sorry for the inconvenience

**Comment by duguwo** [comment]
> It should be fixed by now, sorry for the inconvenience

It's OK now,Thank you very much!
