### ISSUE TITLE
Binary log off in slaves

### ISSUE THREAD

**Issue by Srijstha** [signal18/replication-manager#94]
It could probably be not an issue but I am facing a problem which might be naive as I am new to MariaDB and MaxScale!

I have a replication setup with one master and two slaves; binary log is on in the master and off in the slaves. Next,  I setup MaxScale with automatic failover script.  MaxScale+replication-manager tries to elect a master when the master failed but couldn't as binary logs are off in both the slaves. I tried by turning the binary logs on in both the master and slaves before setting up MaxScale, but replication stops working. I wonder when and how to turn the binary log on in the slave to be promoted as the master. Moreover, what happens when the original master is back again with binary logs on in both servers and what to do if I want to make the original master master again? Many thanks for the answers.

**Comment by tanji** [comment]
Hello,

Please read our documentation, it answers all those questions.
Binary log must be ON at all times on all servers.
It is recommended to run replication-manager as a standalone service if you want to have your old master autorejoin the topology. MaxScale can't do that by itself unfortunately.

**Comment by Srijstha** [comment]
Thanks tanji for the quick answer. I will have a good look in the documentation. 

Update: the binlog problem is solved!

MaxScale is a great tool. Hope to see autorejoin feature from MaxScale in the near future.

**Comment by tanji** [comment]
@Srijstha you can run MaxScale with Replication-manager, please check latest blog article.
