### ISSUE TITLE
Following package upgrade 3.0 old logs on /var/log/replication-manager are not chown to repman:repman

### ISSUE THREAD

**Issue by svaroqui** [signal18/replication-manager#943]
Action may chown to the user and rename old log  to *.old

**Comment by svaroqui** [comment]
journalctl -S today will have the logs  need proper documentation

**Comment by svaroqui** [comment]
journalctl -u replication-manager

**Comment by caffeinated92** [comment]
Already added in commit 68e85e0645998b6c3c3c6b1330ac8e566972cf2c and df2e80b7224e414019518daef510244192d045f1 4 days ago
